In [1]:
%load_ext autoreload
%autoreload 2

In [9]:
from sympy import Matrix, cos, sin, symbols, pi

# シンボルの定義
theta, dx, dy, sx, sy = symbols('theta dx dy sx sy')
x, y = symbols('x y')

# 1. 変換行列の定義 (3x3)
# 回転行列 (Rotation)
R = Matrix([
    [cos(theta), -sin(theta), 0],
    [sin(theta),  cos(theta), 0],
    [0,           0,          1]
])

# 平行移動行列 (Translation)
T = Matrix([
    [1, 0, dx],
    [0, 1, dy],
    [0, 0, 1]
])

# スケーリング行列 (Scaling)
S = Matrix([
    [sx, 0, 0],
    [0, sy, 0],
    [0, 0, 1]
])

# 2. 点の定義 (同次座標系: [x, y, 1])
point = Matrix([x, y, 1])

# 3. 変換の適用 (行列の積)
# 例：回転 -> 平行移動
transformed_point = T * R * point

print("変換後の点:")
print(transformed_point)

# 具体的な値を代入する場合
final_point = transformed_point.subs({theta: pi/4, dx: 1, dy: 2, x: 10, y: 0})
print("\n具体的な値(θ=45°, dx=1, dy=2, 10,0):")
print(final_point.evalf())

変換後の点:
Matrix([[dx + x*cos(theta) - y*sin(theta)], [dy + x*sin(theta) + y*cos(theta)], [1]])

具体的な値(θ=45°, dx=1, dy=2, 10,0):
Matrix([[8.07106781186548], [9.07106781186548], [1.00000000000000]])

## dual coding

In [2]:
import ggblab

In [3]:
%ggblab api getVersion()

[ggblab] created GeoGebra singleton and stored as 'ggb' in user namespace

'5.2.909.9'

In [32]:
%ggb Circle((0,0), 1)

['c']

In [42]:
%%ggb 
{theta} = Slider[0, 2 pi]
sx = Slider[0, 3]
sy = Slider[0, 3]
dx = Slider[0, 3]
dy = Slider[0, 3]
sx = 1
sy = 1
dx = 1
dy = 1

['θ', 'sx', 'sy', 'dx', 'dy', 'sx', 'sy', 'dx', 'dy']

In [35]:
%%ggb
m2 = {R}
m3 = {S}
m4 = {T}

['m2', 'm3', 'm4']

In [36]:
%%ggb
ApplyMatrix(m3, c)

["c'"]

In [40]:
%ggb ApplyMatrix(m2, c')

["c''"]

In [48]:
await ggb.function('getObjectType', [["c''"], ["a"]])

['ellipse', 'curvecartesian']

In [44]:
%%ggb
Curve(cos(u), sin(u), u, 0, 2 {pi})

['a']

In [47]:
%%ggb
ApplyMatrix(m3, a)

["a'"]

In [30]:
from ggblab_extra import ConstructionIO
from ggblab_extra import ConstructionTreeParser

In [50]:
df = await ConstructionIO.initialize_dataframe(ggb, use_applet=True)
df["Name", "Type", "Command", "Value"]

shape: (14, 4)
┌──────┬────────────────┬─────────────────────────────────┬─────────────────────────────────┐
│ Name ┆ Type           ┆ Command                         ┆ Value                           │
│ ---  ┆ ---            ┆ ---                             ┆ ---                             │
│ str  ┆ str            ┆ str                             ┆ str                             │
╞══════╪════════════════╪═════════════════════════════════╪═════════════════════════════════╡
│ c    ┆ circle         ┆ Circle((0, 0), 1)               ┆ c: x² + y² = 1                  │
│ θ    ┆ numeric        ┆ null                            ┆ θ = 3.6                         │
│ sx   ┆ numeric        ┆ null                            ┆ sx = 2                          │
│ sy   ┆ numeric        ┆ null                            ┆ sy = 1                          │
│ dx   ┆ numeric        ┆ 1                               ┆ dx = 1                          │
│ dy   ┆ numeric        ┆ null                            ┆ dy = 0                          │
│ m2   ┆ list           ┆ {{cos(θ), -sin(θ), 0}, {sin(θ)… ┆ m2 = {{-0.8967584163341, 0.442… │
│ m3   ┆ list           ┆ {{sx, 0, 0}, {0, sy, 0}, {0, 0… ┆ m3 = {{2, 0, 0}, {0, 1, 0}, {0… │
│ m4   ┆ list           ┆ {{1, 0, dx}, {0, 1, dy}, {0, 0… ┆ m4 = {{1, 0, 1}, {0, 1, 0}, {0… │
│ c'   ┆ ellipse        ┆ ApplyMatrix(m3, c)              ┆ c': x² / 4 + y² / 1 = 1         │
│ c''  ┆ ellipse        ┆ ApplyMatrix(m2, c')             ┆ c'': 1.5874730282016x² - 2.381… │
│ m4'  ┆ list           ┆ m4⁻¹                            ┆ m4' = {{1, 0, -1}, {0, 1, 0}, … │
│ a    ┆ curvecartesian ┆ Curve(cos(u), sin(u), u, 0, 2π… ┆ a:(cos(u), sin(u))              │
│ a'   ┆ curvecartesian ┆ ApplyMatrix(m3, a)              ┆ a':((2cos(u)) / 1, sin(u) / 1)  │
└──────┴────────────────┴─────────────────────────────────┴─────────────────────────────────┘

In [51]:
from ggblab_extra.sympy import Object2D, Object3D
from ggblab_extra.sympy import attach_object2d, attach_object3d, enumerate_plane_members

In [52]:
df2 = attach_object2d(df)

In [55]:
df2["Type", "object2d"]

shape: (14, 2)
┌────────────────┬─────────────────────────────────┐
│ Type           ┆ object2d                        │
│ ---            ┆ ---                             │
│ str            ┆ object                          │
╞════════════════╪═════════════════════════════════╡
│ circle         ┆ Object2D(kind='circle', obj=No… │
│ numeric        ┆ Object2D(kind=None, obj=None, … │
│ numeric        ┆ Object2D(kind='line', obj=Line… │
│ numeric        ┆ Object2D(kind='line', obj=Line… │
│ numeric        ┆ Object2D(kind='line', obj=Line… │
│ numeric        ┆ Object2D(kind='line', obj=Line… │
│ list           ┆ null                            │
│ list           ┆ null                            │
│ list           ┆ null                            │
│ ellipse        ┆ Object2D(kind=None, obj=None, … │
│ ellipse        ┆ Object2D(kind=None, obj=None, … │
│ list           ┆ null                            │
│ curvecartesian ┆ Object2D(kind='point', obj=Poi… │
│ curvecartesian ┆ Object2D(kind='point', obj=Poi… │
└────────────────┴─────────────────────────────────┘