In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from sympy import Matrix, cos, sin, symbols, pi

# シンボルの定義
theta, dx, dy, sx, sy = symbols('theta dx dy sx sy')
x, y = symbols('x y')

# 1. 変換行列の定義 (3x3)
# 回転行列 (Rotation)
R = Matrix([
    [cos(theta), -sin(theta), 0],
    [sin(theta),  cos(theta), 0],
    [0,           0,          1]
])

# 平行移動行列 (Translation)
T = Matrix([
    [1, 0, dx],
    [0, 1, dy],
    [0, 0, 1]
])

# スケーリング行列 (Scaling)
S = Matrix([
    [sx, 0, 0],
    [0, sy, 0],
    [0, 0, 1]
])

# 2. 点の定義 (同次座標系: [x, y, 1])
point = Matrix([x, y, 1])

# 3. 変換の適用 (行列の積)
# 例：回転 -> 平行移動
transformed_point = T * R * point

print("変換後の点:")
print(transformed_point)

# 具体的な値を代入する場合
final_point = transformed_point.subs({theta: pi/4, dx: 1, dy: 2, x: 10, y: 0})
print("\n具体的な値(θ=45°, dx=1, dy=2, 10,0):")
print(final_point.evalf())

変換後の点:
Matrix([[dx + x*cos(theta) - y*sin(theta)], [dy + x*sin(theta) + y*cos(theta)], [1]])

具体的な値(θ=45°, dx=1, dy=2, 10,0):
Matrix([[8.07106781186548], [9.07106781186548], [1.00000000000000]])

## dual coding

In [3]:
import ggblab

In [4]:
%ggblab api getVersion()

[ggblab] created GeoGebra singleton and stored as 'ggb' in user namespace

'5.2.909.9'

In [5]:
%ggb Circle((0,0), 1)

['c']

In [6]:
%%ggb 
{theta} = Slider[0, 2 pi]
sx = Slider[0, 3]
sy = Slider[0, 3]
dx = Slider[0, 3]
dy = Slider[0, 3]
sx = 1
sy = 1
dx = 1
dy = 1

['θ', 'sx', 'sy', 'dx', 'dy', 'sx', 'sy', 'dx', 'dy']

In [7]:
%%ggb
m2 = {R}
m3 = {S}
m4 = {T}

['m2', 'm3', 'm4']

In [8]:
%%ggb
ApplyMatrix(m3, c)

["c'"]

In [9]:
%ggb ApplyMatrix(m2, c')

["c''"]

In [10]:
await ggb.function('getObjectType', [["c''"], ["a"]])

['circle', None]

In [11]:
%%ggb
Curve(cos(u), sin(u), u, 0, 2 {pi})

['a']

In [12]:
%%ggb
ApplyMatrix(m3, a)

["a'"]

In [13]:
from ggblab_extra import ConstructionIO
from ggblab_extra import ConstructionTreeParser

In [49]:
df = await ConstructionIO.initialize_dataframe(ggb, use_applet=True)
df["Name", "Type", "Command", "Value"]

shape: (13, 4)
┌──────┬────────────────┬───────────────────────────────────────────────┬──────────────────────────────────────────────┐
│ Name ┆ Type           ┆ Command                                       ┆ Value                                        │
│ ---  ┆ ---            ┆ ---                                           ┆ ---                                          │
│ str  ┆ str            ┆ str                                           ┆ str                                          │
╞══════╪════════════════╪═══════════════════════════════════════════════╪══════════════════════════════════════════════╡
│ c    ┆ circle         ┆ Circle((0, 0), 1)                             ┆ c: x² + y² = 1                               │
│ θ    ┆ numeric        ┆ null                                          ┆ θ = 0.7                                      │
│ sx   ┆ numeric        ┆ null                                          ┆ sx = 1.5                                     │
│ sy   ┆ numeric        ┆ 1                                             ┆ sy = 1                                       │
│ dx   ┆ numeric        ┆ null                                          ┆ dx = 1                                       │
│ dy   ┆ numeric        ┆ 1                                             ┆ dy = 1                                       │
│ m2   ┆ list           ┆ {{cos(θ), -sin(θ), 0}, {sin(θ), cos(θ), 0},   ┆ m2 = {{0.7648421872845, -0.6442176872377,    │
│      ┆                ┆ {0, 0, 1}}                                    ┆ 0}, {0.6442176872377, 0.7648421872845, 0},   │
│      ┆                ┆                                               ┆ {0, 0, 1}}                                   │
│ m3   ┆ list           ┆ {{sx, 0, 0}, {0, sy, 0}, {0, 0, 1}}           ┆ m3 = {{1.5, 0, 0}, {0, 1, 0}, {0, 0, 1}}     │
│ m4   ┆ list           ┆ {{1, 0, dx}, {0, 1, dy}, {0, 0, 1}}           ┆ m4 = {{1, 0, 1}, {0, 1, 1}, {0, 0, 1}}       │
│ c'   ┆ ellipse        ┆ ApplyMatrix(m3, c)                            ┆ c': x² / 2.25 + y² / 1 = 1                   │
│ c''  ┆ ellipse        ┆ ApplyMatrix(m2, c')                           ┆ c'': 1.5187705356873x² - 1.2318121624856x y  │
│      ┆                ┆                                               ┆ + 1.7312294643127y² = 2.25                   │
│ a    ┆ curvecartesian ┆ Curve(cos(u), sin(u), u, 0, 2π)               ┆ a:(cos(u), sin(u))                           │
│ a'   ┆ curvecartesian ┆ ApplyMatrix(m3, a)                            ┆ a':((1.5cos(u)) / 1, sin(u) / 1)             │
└──────┴────────────────┴───────────────────────────────────────────────┴──────────────────────────────────────────────┘

In [50]:
from ggblab_extra.sympy import Object2D, Object3D
from ggblab_extra.sympy import attach_object2d, attach_object3d, enumerate_plane_members

In [51]:
df2 = attach_object2d(df)

In [52]:
df2["Type", "Command", "Value", "object2d"]

shape: (13, 4)
┌────────────────┬─────────────────────────────────┬─────────────────────────────────┬─────────────────────────────────┐
│ Type           ┆ Command                         ┆ Value                           ┆ object2d                        │
│ ---            ┆ ---                             ┆ ---                             ┆ ---                             │
│ str            ┆ str                             ┆ str                             ┆ object                          │
╞════════════════╪═════════════════════════════════╪═════════════════════════════════╪═════════════════════════════════╡
│ circle         ┆ Circle((0, 0), 1)               ┆ c: x² + y² = 1                  ┆ Object2D(kind='circle',         │
│                ┆                                 ┆                                 ┆ obj=Circle(Point2D(0, 0), 1),   │
│                ┆                                 ┆                                 ┆ value='c: x² + y² = 1',         │
│                ┆                                 ┆                                 ┆ command='Circle((0, 0), 1)')    │
│ numeric        ┆ null                            ┆ θ = 0.7                         ┆ null                            │
│ numeric        ┆ null                            ┆ sx = 1.5                        ┆ null                            │
│ numeric        ┆ 1                               ┆ sy = 1                          ┆ null                            │
│ numeric        ┆ null                            ┆ dx = 1                          ┆ null                            │
│ numeric        ┆ 1                               ┆ dy = 1                          ┆ null                            │
│ list           ┆ {{cos(θ), -sin(θ), 0}, {sin(θ), ┆ m2 = {{0.7648421872845,         ┆ null                            │
│                ┆ cos(θ), 0}, {0, 0, 1}}          ┆ -0.6442176872377, 0},           ┆                                 │
│                ┆                                 ┆ {0.6442176872377,               ┆                                 │
│                ┆                                 ┆ 0.7648421872845, 0}, {0, 0, 1}} ┆                                 │
│ list           ┆ {{sx, 0, 0}, {0, sy, 0}, {0, 0, ┆ m3 = {{1.5, 0, 0}, {0, 1, 0},   ┆ null                            │
│                ┆ 1}}                             ┆ {0, 0, 1}}                      ┆                                 │
│ list           ┆ {{1, 0, dx}, {0, 1, dy}, {0, 0, ┆ m4 = {{1, 0, 1}, {0, 1, 1}, {0, ┆ null                            │
│                ┆ 1}}                             ┆ 0, 1}}                          ┆                                 │
│ ellipse        ┆ ApplyMatrix(m3, c)              ┆ c': x² / 2.25 + y² / 1 = 1      ┆ Object2D(kind=None, obj=None,   │
│                ┆                                 ┆                                 ┆ value="c': x² / 2.25 + y² / 1 = │
│                ┆                                 ┆                                 ┆ 1", command='ApplyMatrix(m3,    │
│                ┆                                 ┆                                 ┆ c)')                            │
│ ellipse        ┆ ApplyMatrix(m2, c')             ┆ c'': 1.5187705356873x² -        ┆ Object2D(kind=None, obj=None,   │
│                ┆                                 ┆ 1.2318121624856x y +            ┆ value="c'': 1.5187705356873x² - │
│                ┆                                 ┆ 1.7312294643127y² = 2.25        ┆ 1.2318121624856x y +            │
│                ┆                                 ┆                                 ┆ 1.7312294643127y² = 2.25",      │
│                ┆                                 ┆                                 ┆ command="ApplyMatrix(m2, c')")  │
│ curvecartesian ┆ Curve(cos(u), sin(u), u, 0, 2π) ┆ a:(cos(u), sin(u))              ┆ Object2D(kind='curvecartesian', │
│                ┆                                 ┆                                 ┆ obj=Curve((cos(u), sin(u)), (u, │
│                ┆                                 ┆                                 ┆ 0, 2*π)), value='a:(cos(u),     │
│                ┆                                 ┆                                 ┆ sin(u))',                       │
│                ┆                                 ┆                                 ┆ command='Curve(cos(u), sin(u),  │
│                ┆                                 ┆                                 ┆ u, 0, 2π)')                     │
│ curvecartesian ┆ ApplyMatrix(m3, a)              ┆ a':((1.5cos(u)) / 1, sin(u) /   ┆ Object2D(kind='curvecartesian', │
│                ┆                                 ┆ 1)                              ┆ obj=None,                       │
│                ┆                                 ┆                                 ┆ value="a':((1.5cos(u)) / 1,     │
│                ┆                                 ┆                                 ┆ sin(u) / 1)",                   │
│                ┆                                 ┆                                 ┆ command='ApplyMatrix(m3, a)')   │
└────────────────┴─────────────────────────────────┴─────────────────────────────────┴─────────────────────────────────┘

In [44]:
import polars as pl
with pl.Config(fmt_str_lengths=80, tbl_width_chars=100):
    print(str(df2["Name", "Type", "Command", "Value", "object2d"]))

shape: (13, 5)
┌──────┬────────────────┬────────────────────────┬────────────────────────┬────────────────────────┐
│ Name ┆ Type           ┆ Command                ┆ Value                  ┆ object2d               │
│ ---  ┆ ---            ┆ ---                    ┆ ---                    ┆ ---                    │
│ str  ┆ str            ┆ str                    ┆ str                    ┆ object                 │
╞══════╪════════════════╪════════════════════════╪════════════════════════╪════════════════════════╡
│ c    ┆ circle         ┆ Circle((0, 0), 1)      ┆ c: x² + y² = 1         ┆ Object2D(kind='circle' │
│      ┆                ┆                        ┆                        ┆ ,                      │
│      ┆                ┆                        ┆                        ┆ obj=Circle(Point2D(0,  │
│      ┆                ┆                        ┆                        ┆ 0), 1), value='c: x² + │
│      ┆                ┆                        ┆                        ┆ y² = 1', co…           │
│ θ    ┆ numeric        ┆ null                   ┆ θ = 0                  ┆ null                   │
│ sx   ┆ numeric        ┆ 1                      ┆ sx = 1                 ┆ null                   │
│ sy   ┆ numeric        ┆ 1                      ┆ sy = 1                 ┆ null                   │
│ dx   ┆ numeric        ┆ 1                      ┆ dx = 1                 ┆ null                   │
│ dy   ┆ numeric        ┆ 1                      ┆ dy = 1                 ┆ null                   │
│ m2   ┆ list           ┆ {{cos(θ), -sin(θ), 0}, ┆ m2 = {{1, 0, 0}, {0,   ┆ null                   │
│      ┆                ┆ {sin(θ), cos(θ), 0},   ┆ 1, 0}, {0, 0, 1}}      ┆                        │
│      ┆                ┆ {0, 0, 1}}             ┆                        ┆                        │
│ m3   ┆ list           ┆ {{sx, 0, 0}, {0, sy,   ┆ m3 = {{1, 0, 0}, {0,   ┆ null                   │
│      ┆                ┆ 0}, {0, 0, 1}}         ┆ 1, 0}, {0, 0, 1}}      ┆                        │
│ m4   ┆ list           ┆ {{1, 0, dx}, {0, 1,    ┆ m4 = {{1, 0, 1}, {0,   ┆ null                   │
│      ┆                ┆ dy}, {0, 0, 1}}        ┆ 1, 1}, {0, 0, 1}}      ┆                        │
│ c'   ┆ circle         ┆ ApplyMatrix(m3, c)     ┆ c': x² + y² = 1        ┆ Object2D(kind='circle' │
│      ┆                ┆                        ┆                        ┆ ,                      │
│      ┆                ┆                        ┆                        ┆ obj=Circle(Point2D(0,  │
│      ┆                ┆                        ┆                        ┆ 0), 1), value="c': x²  │
│      ┆                ┆                        ┆                        ┆ + y² = 1", c…          │
│ c''  ┆ circle         ┆ ApplyMatrix(m2, c')    ┆ c'': x² + y² = 1       ┆ Object2D(kind='circle' │
│      ┆                ┆                        ┆                        ┆ ,                      │
│      ┆                ┆                        ┆                        ┆ obj=Circle(Point2D(0,  │
│      ┆                ┆                        ┆                        ┆ 0), 1), value="c'': x² │
│      ┆                ┆                        ┆                        ┆ + y² = 1", …           │
│ a    ┆ curvecartesian ┆ Curve(cos(u), sin(u),  ┆ a:(cos(u), sin(u))     ┆ Object2D(kind='curveca │
│      ┆                ┆ u, 0, 2π)              ┆                        ┆ rtesian',              │
│      ┆                ┆                        ┆                        ┆ obj=Curve((cos(u),     │
│      ┆                ┆                        ┆                        ┆ sin(u)), (u, 0, 2*π)), │
│      ┆                ┆                        ┆                        ┆ value=…                │
│ a'   ┆ curvecartesian ┆ ApplyMatrix(m3, a)     ┆ a':(cos(u) / 1, sin(u) ┆ Object2D(kind='curveca │
│      ┆                ┆                        ┆ / 1)                   ┆ rtesian', obj=None,    │
│      ┆                ┆                        ┆                        ┆ value="a':(cos(u) / 1, │
│      ┆                ┆                        ┆                        ┆ sin(u) / 1)", c…       │
└──────┴────────────────┴────────────────────────┴────────────────────────┴────────────────────────┘

In [45]:
curve = (df2.filter(pl.col('Name') == 'a')['object2d']).item().obj

In [46]:
type(curve)

sympy.geometry.curve.Curve