In [1]:
%load_ext autoreload
%autoreload 2

## dual coding

In [2]:
import ggblab

In [41]:
from ggblab.utils import flatten

In [3]:
%ggblab api getVersion()

[ggblab] created GeoGebra singleton and stored as 'ggb' in user namespace

'5.2.909.9'

In [137]:
%%ggb 
a = Slider[-3, 3]
b = Slider[-3, 3]
c = Slider[-3, 3]
d = Slider[-3, 3]
e = Slider[-3, 3]
f = Slider[-3, 3]
a = 1
c = 1
f = -1

['a', 'b', 'c', 'd', 'e', 'f', 'a', 'c', 'f']

In [71]:
%%ggb
a x^2 + b x y + c y^2 + d x + e y + f = 0

Parsed instance=None cmds=['a x^2 + b x y + c y^2 + d x + e y + f = 0']

['eq1']

In [72]:
from sympy import Matrix, cos, sin, symbols, pi

In [124]:
theta, dx, dy, sx, sy = symbols('theta dx dy sx sy')
a, b, c, d, e, f = symbols('a b c d e f')
x, y, z = symbols('x y z')

In [107]:
m1 = Matrix([[a, b/2, d/2], [b/2, c, e/2], [d/2, e/2, f]])
m1

Matrix([
[  a, b/2, d/2],
[b/2,   c, e/2],
[d/2, e/2,   f]])

In [125]:
m3 = Matrix([[x, y, 1]])

In [130]:
expr = (m3 * m1 * m3.T)
expr.expand()

Matrix([[a*x**2 + b*x*y + c*y**2 + d*x + e*y + f]])

In [108]:
m2 = m1[0:2, 0:2]
m2

Matrix([
[  a, b/2],
[b/2,   c]])

In [109]:
%%ggb
m1 = {m1}
m2 = {m2}

Parsed instance=None cmds=['m1 = {{a,b/2,d/2},{b/2,c,e/2},{d/2,e/2,f}}', 'm2 = {{a,b/2},{b/2,c}}']

['m1', 'm2']

In [115]:
rhs = -(m1.det()/m2.det()).simplify()

In [116]:
%%ggb
{rhs}

Parsed instance=None cmds=['-(4*a*c*f - a*e**2 - b**2*f + b*d*e - c*d**2)/(4*a*c - b**2)']

['k']

In [120]:
sma = (rhs / e1[0][0]).simplify()
smi = (rhs / e1[1][0]).simplify()

In [121]:
sma, smi

(2*(-4*a*c*f + a*e**2 + b**2*f - b*d*e + c*d**2)/((4*a*c - b**2)*(a + c - sqrt(a**2 - 2*a*c + b**2 + c**2))),
 2*(-4*a*c*f + a*e**2 + b**2*f - b*d*e + c*d**2)/((4*a*c - b**2)*(a + c + sqrt(a**2 - 2*a*c + b**2 + c**2))))

In [122]:
%%ggb
{sma}
{smi}

Parsed instance=None cmds=['2*(-4*a*c*f + a*e**2 + b**2*f - b*d*e + c*d**2)/((4*a*c - b**2)*(a + c - sqrt(a**2 - 2*a*c + b**2 + c**2)))', '2*(-4*a*c*f + a*e**2 + b**2*f - b*d*e + c*d**2)/((4*a*c - b**2)*(a + c + sqrt(a**2 - 2*a*c + b**2 + c**2)))']

['j', 'l']

In [76]:
m1.eigenvals()

{a/2 + c/2 - sqrt(a**2 - 2*a*c + b**2 + c**2)/2: 1,
 a/2 + c/2 + sqrt(a**2 - 2*a*c + b**2 + c**2)/2: 1}

In [77]:
e1 = m1.eigenvects()
e1

[(a/2 + c/2 - sqrt(a**2 - 2*a*c + b**2 + c**2)/2,
  1,
  [Matrix([
   [-2*c/b + 2*(a/2 + c/2 - sqrt(a**2 - 2*a*c + b**2 + c**2)/2)/b],
   [                                                            1]])]),
 (a/2 + c/2 + sqrt(a**2 - 2*a*c + b**2 + c**2)/2,
  1,
  [Matrix([
   [-2*c/b + 2*(a/2 + c/2 + sqrt(a**2 - 2*a*c + b**2 + c**2)/2)/b],
   [                                                            1]])])]

In [78]:
e11 = e1[0][2][0]

In [79]:
e12 = e1[1][2][0]

In [106]:
%%ggb
{e1[0][0]}
{e1[1][0]}

Parsed instance=None cmds=['a/2 + c/2 - sqrt(a**2 - 2*a*c + b**2 + c**2)/2', 'a/2 + c/2 + sqrt(a**2 - 2*a*c + b**2 + c**2)/2']

['h', 'i']

In [80]:
%%ggb
{e1[0][2][0]}
{e1[1][2][0]}

Parsed instance=None cmds=['Vector((-2*c/b + 2*(a/2 + c/2 - sqrt(a**2 - 2*a*c + b**2 + c**2)/2)/b,1))', 'Vector((-2*c/b + 2*(a/2 + c/2 + sqrt(a**2 - 2*a*c + b**2 + c**2)/2)/b,1))']

['u', 'v']

In [81]:
d = str(m1.det()).replace('**', '^')
d

'a*c - b^2/4'

In [82]:
%%ggb
{d}

Parsed instance=None cmds=['a*c - b^2/4']

['g']

In [45]:
e11 = list(flatten(e11.tolist()))

In [ ]:
 = 0

In [87]:
from sympy.parsing.sympy_parser import parse_expr, standard_transformations, function_exponentiation, implicit_multiplication_application, convert_xor
from sympy import pretty, init_printing

# 1. パースの設定 ( ^ -> ** への変換)
transformations = standard_transformations + (function_exponentiation, implicit_multiplication_application, convert_xor, )

# サンプル式: 2x^2 + 3y*z
expr_str = "a x^2 + b x y + c y^2 + d x + e y + f" 

# パースの実行 (implicit_multiplicationを有効にすると、2xが2*xと認識される)
# 注: transformations="all" を使うとさらに自動化が進む
expr = parse_expr(expr_str, transformations=transformations)

In [88]:
expr

a*x**2 + b*x*y + c*y**2 + d*x + e*y + f

In [90]:
from sympy import solve, nonlinsolve, linsolve, diff

In [102]:
c0 = next(iter(linsolve((diff(expr, x), diff(expr, y)), (x, y))))
c0

((b*e - 2*c*d)/(4*a*c - b**2), (-2*a*e + b*d)/(4*a*c - b**2))

In [103]:
%%ggb
{c0}

Parsed instance=None cmds=['((b*e - 2*c*d)/(4*a*c - b**2), (-2*a*e + b*d)/(4*a*c - b**2))']

['A']

In [132]:
from ggblab_extra import ConstructionIO
from ggblab_extra import ConstructionTreeParser

In [138]:
df = await ConstructionIO.initialize_dataframe(ggb, use_applet=True)
df["Name", "Type", "Command", "Value"]

shape: (21, 4)
┌──────┬─────────┬─────────────────────────────────┬─────────────────────────────────┐
│ Name ┆ Type    ┆ Command                         ┆ Value                           │
│ ---  ┆ ---     ┆ ---                             ┆ ---                             │
│ str  ┆ str     ┆ str                             ┆ str                             │
╞══════╪═════════╪═════════════════════════════════╪═════════════════════════════════╡
│ a    ┆ numeric ┆ 1                               ┆ a = 1                           │
│ b    ┆ numeric ┆ null                            ┆ b = 1                           │
│ c    ┆ numeric ┆ 1                               ┆ c = 1                           │
│ d    ┆ numeric ┆ null                            ┆ d = 1.2                         │
│ e    ┆ numeric ┆ null                            ┆ e = -1.2                        │
│ f    ┆ numeric ┆ null                            ┆ f = -1.3                        │
│ eq1  ┆ ellipse ┆ a x² + b x y + c y² + d x + e … ┆ eq1: 1 x² + 1 x y + 1 y² + 1.2… │
│ u    ┆ vector  ┆ Vector((-2 c / b + 2(a / 2 + c… ┆ u = (-1, 1)                     │
│ v    ┆ vector  ┆ Vector((-2 c / b + 2(a / 2 + c… ┆ v = (1, 1)                      │
│ g    ┆ numeric ┆ a c - b² / 4                    ┆ g = 0.75                        │
│ A    ┆ point   ┆ ((b e - 2c d) / (4a c - b²), (… ┆ A = (-1.2, 1.2)                 │
│ h    ┆ numeric ┆ a / 2 + c / 2 - sqrt(a² - 2a c… ┆ h = 0.5                         │
│ i    ┆ numeric ┆ a / 2 + c / 2 + sqrt(a² - 2a c… ┆ i = 1.5                         │
│ m1   ┆ list    ┆ {{a, b / 2, d / 2}, {b / 2, c,… ┆ m1 = {{1, 0.5, 0.6}, {0.5, 1, … │
│ m2   ┆ list    ┆ {{a, b / 2}, {b / 2, c}}        ┆ m2 = {{1, 0.5}, {0.5, 1}}       │
│ k    ┆ numeric ┆ (-(4a c f - a e² - b² f + b d … ┆ k = 2.74                        │
│ j    ┆ numeric ┆ 2(-4 a c f + a e² + b² f - b d… ┆ j = 5.48                        │
│ l    ┆ numeric ┆ 2(-4 a c f + a e² + b² f - b d… ┆ l = 1.8266666666667             │
│ eq3  ┆ ellipse ┆ x² / j + y² / l = 1             ┆ eq3: x² / 5.48 + y² / 1.826666… │
│ w    ┆ vector  ┆ Translate(u, A)                 ┆ w = (-1, 1)                     │
│ m    ┆ vector  ┆ Translate(v, A)                 ┆ m = (1, 1)                      │
└──────┴─────────┴─────────────────────────────────┴─────────────────────────────────┘

In [134]:
from ggblab_extra.sympy import Object2D, Object3D
from ggblab_extra.sympy import attach_object2d, attach_object3d, enumerate_plane_members

In [136]:
df2["Type", "object2d"]

shape: (20, 2)
┌─────────┬─────────────────────────────────┐
│ Type    ┆ object2d                        │
│ ---     ┆ ---                             │
│ str     ┆ object                          │
╞═════════╪═════════════════════════════════╡
│ numeric ┆ Object2D(kind=None, obj=None, … │
│ numeric ┆ Object2D(kind=None, obj=None, … │
│ numeric ┆ Object2D(kind=None, obj=None, … │
│ numeric ┆ Object2D(kind=None, obj=None, … │
│ numeric ┆ Object2D(kind=None, obj=None, … │
│ numeric ┆ Object2D(kind=None, obj=None, … │
│ ellipse ┆ Object2D(kind=None, obj=None, … │
│ vector  ┆ Object2D(kind='point', obj=Poi… │
│ vector  ┆ Object2D(kind='point', obj=Poi… │
│ numeric ┆ Object2D(kind=None, obj=None, … │
│ list    ┆ null                            │
│ point   ┆ Object2D(kind='point', obj=Poi… │
│ numeric ┆ Object2D(kind=None, obj=None, … │
│ numeric ┆ Object2D(kind=None, obj=None, … │
│ list    ┆ null                            │
│ list    ┆ null                            │
│ numeric ┆ Object2D(kind=None, obj=None, … │
│ numeric ┆ Object2D(kind=None, obj=None, … │
│ numeric ┆ Object2D(kind=None, obj=None, … │
│ ellipse ┆ Object2D(kind=None, obj=None, … │
└─────────┴─────────────────────────────────┘