In [119]:
import asyncio
import xmlschema
import networkx as nx
import polars as pl
from itertools import zip_longest

In [126]:
from ggblab import GeoGebra
ggb = await GeoGebra().init(use_vscode=True)

Using local cached file: xsd/common.xsd

In [127]:
%pwd

'/Users/manabu/work/ggblab/examples'

In [5]:
%cd examples/

/Users/manabu/work/ggblab/examples

In [128]:
# ggb.file.load('eg10_slider2.ggb')
ggb.file.load('2025_06_08.ggb')

In [129]:
r = await ggb.function("setBase64", [ggb.construction.base64_buffer.decode('utf-8')])

In [8]:
from ggblab_extra import ConstructionIO
from ggblab_extra import ConstructionTreeParser

In [84]:
r = await ggb.function('getXML', ['b'])
print(r)

<element type="numeric" label="b">
	<value val="7"/>
	<slider min="0" max="8" absoluteScreenLocation="true" width="200" x="51.630259376842744" y="180.23697406231565" fixed="false" horizontal="true" showAlgebra="true"/>
	<lineStyle thickness="10" type="0" typeHidden="1"/>
	<show object="true" label="true"/>
	<objColor r="0" g="0" b="0" alpha="0.10000000149011612"/>
	<layer val="9"/>
	<labelMode val="1"/>
	<animation step="1" type="0" playing="false"/>
</element>

In [89]:
r = await ggb.function('getXML', ['b'])
o = ggb.file.ggb_schema.decode(r)
o['value'][0]['@val'] = '0'
x = xmlschema.etree_tostring(ggb.file.ggb_schema.encode(o, 'element'))
r = await ggb.function('evalXML' , [x])
r

In [130]:

df = await ConstructionIO.initialize_dataframe(ggb, use_applet=True)
df

shape: (91, 10)
┌──────────┬───────┬──────────┬───────────────────┬───┬───────┬────────────┬───────────┬───────────┐
│ Sequence ┆ Name  ┆ Type     ┆ Command           ┆ … ┆ Layer ┆ ShowObject ┆ ShowLabel ┆ Auxiliary │
│ ---      ┆ ---   ┆ ---      ┆ ---               ┆   ┆ ---   ┆ ---        ┆ ---       ┆ ---       │
│ u32      ┆ str   ┆ str      ┆ str               ┆   ┆ u32   ┆ bool       ┆ bool      ┆ bool      │
╞══════════╪═══════╪══════════╪═══════════════════╪═══╪═══════╪════════════╪═══════════╪═══════════╡
│ 0        ┆ O_{2} ┆ point    ┆ null              ┆ … ┆ 9     ┆ true       ┆ true      ┆ false     │
│ 1        ┆ A     ┆ point    ┆ null              ┆ … ┆ 2     ┆ true       ┆ true      ┆ false     │
│ 2        ┆ B     ┆ point    ┆ Point(Line(O_{2}, ┆ … ┆ 9     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ A))               ┆   ┆       ┆            ┆           ┆           │
│ 3        ┆ c     ┆ circle   ┆ Circle(O_{2}, B)  ┆ … ┆ 9     ┆ true       ┆ false     ┆ false     │
│ 4        ┆ n     ┆ line     ┆ Line(O_{2}, A)    ┆ … ┆ 4     ┆ false      ┆ false     ┆ false     │
│ 5        ┆ O'    ┆ point    ┆ Midpoint(O_{2},   ┆ … ┆ 4     ┆ false      ┆ true      ┆ false     │
│          ┆       ┆          ┆ A)                ┆   ┆       ┆            ┆           ┆           │
│ 6        ┆ p     ┆ circle   ┆ Circle(O', A)     ┆ … ┆ 4     ┆ false      ┆ false     ┆ false     │
│ 7        ┆ j     ┆ line     ┆ Tangent(A, c)     ┆ … ┆ 2     ┆ true       ┆ false     ┆ false     │
│ 8        ┆ l     ┆ line     ┆ Tangent(A, c)     ┆ … ┆ 2     ┆ true       ┆ false     ┆ false     │
│ 9        ┆ q     ┆ line     ┆ AngleBisector(l,  ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ j)                ┆   ┆       ┆            ┆           ┆           │
│ 10       ┆ r     ┆ line     ┆ AngleBisector(l,  ┆ … ┆ 3     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ j)                ┆   ┆       ┆            ┆           ┆           │
│ 11       ┆ O_{1} ┆ point    ┆ Point(r)          ┆ … ┆ 9     ┆ true       ┆ true      ┆ false     │
│ 12       ┆ t     ┆ line     ┆ PerpendicularLine ┆ … ┆ 2     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ (O_{1}, l)        ┆   ┆       ┆            ┆           ┆           │
│ 13       ┆ F_{1} ┆ point    ┆ Intersect(t, l)   ┆ … ┆ 2     ┆ true       ┆ true      ┆ false     │
│ 14       ┆ h_1   ┆ circle   ┆ Circle(O_{1},     ┆ … ┆ 9     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ F_{1})            ┆   ┆       ┆            ┆           ┆           │
│ 15       ┆ p_2   ┆ circle   ┆ Circle(O_{2},     ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ Radius(c) + Radi… ┆   ┆       ┆            ┆           ┆           │
│ 16       ┆ q_2   ┆ line     ┆ Tangent(O_{1},    ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ p_2)              ┆   ┆       ┆            ┆           ┆           │
│ 17       ┆ r_2   ┆ line     ┆ Tangent(O_{1},    ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ p_2)              ┆   ┆       ┆            ┆           ┆           │
│ 18       ┆ M     ┆ point    ┆ Intersect(p_2,    ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ r_2)              ┆   ┆       ┆            ┆           ┆           │
│ 19       ┆ b_2   ┆ ray      ┆ Ray(O_{2}, M)     ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│ 20       ┆ F_{2} ┆ point    ┆ Intersect(c, b_2, ┆ … ┆ 2     ┆ true       ┆ true      ┆ false     │
│          ┆       ┆          ┆ 1)                ┆   ┆       ┆            ┆           ┆           │
│ 21       ┆ γ     ┆ angle    ┆ Angle(A, F_{2},   ┆ … ┆ 4     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{2})            ┆   ┆       ┆            ┆           ┆           │
│ 22       ┆ t2    ┆ triangle ┆ Polygon(A, F_{2}, ┆ … ┆ 4     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{2})            ┆   ┆       ┆            ┆           ┆           │
│ 23       ┆ a_1   ┆ segment  ┆ Segment(A, F_{2}, ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ t2)               ┆   ┆       ┆            ┆           ┆           │
│ 24       ┆ c_2   ┆ segment  ┆ Segment(F_{2},    ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ O_{2}, t2)        ┆   ┆       ┆            ┆           ┆           │
│ 25       ┆ i_1   ┆ segment  ┆ Segment(O_{2}, A, ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ t2)               ┆   ┆       ┆            ┆           ┆           │
│ 26       ┆ m     ┆ segment  ┆ Segment(A, F_{2}) ┆ … ┆ 4     ┆ false      ┆ false     ┆ false     │
│ 27       ┆ θ     ┆ angle    ┆ Angle(O_{2}, A,   ┆ … ┆ 6     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{1})            ┆   ┆       ┆            ┆           ┆           │
│ 28       ┆ b     ┆ line     ┆ Line(O_{2},       ┆ … ┆ 5     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{1})            ┆   ┆       ┆            ┆           ┆           │
│ 29       ┆ P'    ┆ point    ┆ Intersect(b, j)   ┆ … ┆ 0     ┆ true       ┆ true      ┆ false     │
│ 30       ┆ P     ┆ point    ┆ Intersect(b, l)   ┆ … ┆ 0     ┆ true       ┆ true      ┆ false     │
│ 31       ┆ j_1   ┆ line     ┆ Tangent(P', h_1)  ┆ … ┆ 0     ┆ true       ┆ false     ┆ false     │
│ 32       ┆ k_1   ┆ line     ┆ Tangent(P', h_1)  ┆ … ┆ 0     ┆ true       ┆ false     ┆ false     │
│ 33       ┆ l_1   ┆ line     ┆ Tangent(P, h_1)   ┆ … ┆ 0     ┆ true       ┆ false     ┆ false     │
│ 34       ┆ m_1   ┆ line     ┆ Tangent(P, h_1)   ┆ … ┆ 0     ┆ true       ┆ false     ┆ false     │
│ 35       ┆ O_3   ┆ point    ┆ Midpoint(O_{2},   ┆ … ┆ 5     ┆ false      ┆ true      ┆ false     │
│          ┆       ┆          ┆ O_{1})            ┆   ┆       ┆            ┆           ┆           │
│ 36       ┆ p_1   ┆ circle   ┆ Circle(O_3,       ┆ … ┆ 5     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{2})            ┆   ┆       ┆            ┆           ┆           │
│ 37       ┆ C     ┆ point    ┆ Intersect(p_1, l, ┆ … ┆ 2     ┆ true       ┆ true      ┆ false     │
│          ┆       ┆          ┆ 2)                ┆   ┆       ┆            ┆           ┆           │
│ 38       ┆ q_1   ┆ circle   ┆ Circle(A, F_{1})  ┆ … ┆ 2     ┆ true       ┆ false     ┆ false     │
│ 39       ┆ r_1   ┆ circle   ┆ Circle(A, F_{2})  ┆ … ┆ 4     ┆ false      ┆ false     ┆ false     │
│ 40       ┆ Q     ┆ point    ┆ Intersect(h_1,    ┆ … ┆ 2     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ j_1)              ┆   ┆       ┆            ┆           ┆           │
│ 41       ┆ R     ┆ point    ┆ Intersect(h_1,    ┆ … ┆ 2     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ k_1)              ┆   ┆       ┆            ┆           ┆           │
│ 42       ┆ D     ┆ point    ┆ Point(p_1)        ┆ … ┆ 6     ┆ false      ┆ false     ┆ false     │
│ 43       ┆ t3    ┆ triangle ┆ Polygon(O_{2},    ┆ … ┆ 6     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{1}, D)         ┆   ┆       ┆            ┆           ┆           │
│ 44       ┆ d     ┆ segment  ┆ Segment(O_{2},    ┆ … ┆ 6     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ O_{1}, t3)        ┆   ┆       ┆            ┆           ┆           │
│ 45       ┆ o     ┆ segment  ┆ Segment(O_{1}, D, ┆ … ┆ 6     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ t3)               ┆   ┆       ┆            ┆           ┆           │
│ 46       ┆ l_2   ┆ segment  ┆ Segment(D, O_{2}, ┆ … ┆ 6     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ t3)               ┆   ┆       ┆            ┆           ┆           │
│ 47       ┆ α     ┆ angle    ┆ Angle(O_{2}, D,   ┆ … ┆ 6     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{1})            ┆   ┆       ┆            ┆           ┆           │
│ 48       ┆ O     ┆ point    ┆ Midpoint(F_{1},   ┆ … ┆ 7     ┆ false      ┆ true      ┆ false     │
│          ┆       ┆          ┆ F_{2})            ┆   ┆       ┆            ┆           ┆           │
│ 49       ┆ f     ┆ line     ┆ PerpendicularLine ┆ … ┆ 7     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ (O, l)            ┆   ┆       ┆            ┆           ┆           │
│ 50       ┆ i     ┆ segment  ┆ Segment(F_{1},    ┆ … ┆ 7     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ F_{2})            ┆   ┆       ┆            ┆           ┆           │
│ 51       ┆ t4    ┆ triangle ┆ Polygon(O_3, A,   ┆ … ┆ 7     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ C)                ┆   ┆       ┆            ┆           ┆           │
│ 52       ┆ c_3   ┆ segment  ┆ Segment(O_3, A,   ┆ … ┆ 7     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ t4)               ┆   ┆       ┆            ┆           ┆           │
│ 53       ┆ i_2   ┆ segment  ┆ Segment(A, C, t4) ┆ … ┆ 7     ┆ false      ┆ false     ┆ true      │
│ 54       ┆ a_2   ┆ segment  ┆ Segment(C, O_3,   ┆ … ┆ 7     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ t4)               ┆   ┆       ┆            ┆           ┆           │
│ 55       ┆ h     ┆ circle   ┆ Circle(C, F_{2})  ┆ … ┆ 2     ┆ true       ┆ false     ┆ false     │
│ 56       ┆ g     ┆ segment  ┆ Segment(A, Q)     ┆ … ┆ 8     ┆ false      ┆ true      ┆ false     │
│ 57       ┆ s_1   ┆ segment  ┆ Segment(A, F_{2}) ┆ … ┆ 8     ┆ false      ┆ true      ┆ false     │
│ 58       ┆ d_1   ┆ segment  ┆ Segment(F_{2}, C) ┆ … ┆ 8     ┆ false      ┆ true      ┆ false     │
│ 59       ┆ e_1   ┆ line     ┆ PerpendicularLine ┆ … ┆ 2     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ (F_{2}, l)        ┆   ┆       ┆            ┆           ┆           │
│ 60       ┆ E     ┆ point    ┆ Intersect(p_1, t) ┆ … ┆ 6     ┆ false      ┆ true      ┆ false     │
│ 61       ┆ F     ┆ point    ┆ Intersect(p_1, t) ┆ … ┆ 6     ┆ false      ┆ false     ┆ true      │
│ 62       ┆ f_2   ┆ segment  ┆ Segment(E, O_{2}) ┆ … ┆ 7     ┆ false      ┆ false     ┆ false     │
│ 63       ┆ t5    ┆ triangle ┆ Polygon(O_3,      ┆ … ┆ 7     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{2}, E)         ┆   ┆       ┆            ┆           ┆           │
│ 64       ┆ e_2   ┆ segment  ┆ Segment(O_3,      ┆ … ┆ 7     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ O_{2}, t5)        ┆   ┆       ┆            ┆           ┆           │
│ 65       ┆ o_3   ┆ segment  ┆ Segment(O_{2}, E, ┆ … ┆ 7     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ t5)               ┆   ┆       ┆            ┆           ┆           │
│ 66       ┆ o_{2} ┆ segment  ┆ Segment(E, O_3,   ┆ … ┆ 7     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ t5)               ┆   ┆       ┆            ┆           ┆           │
│ 67       ┆ I     ┆ point    ┆ Intersect(c, k_1, ┆ … ┆ 2     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ 1)                ┆   ┆       ┆            ┆           ┆           │
│ 68       ┆ k_2   ┆ circle   ┆ Circle(O_{2},     ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ Radius(c) - Radi… ┆   ┆       ┆            ┆           ┆           │
│ 69       ┆ m_2   ┆ line     ┆ Tangent(O_{1},    ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ k_2)              ┆   ┆       ┆            ┆           ┆           │
│ 70       ┆ n_2   ┆ line     ┆ Tangent(O_{1},    ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ k_2)              ┆   ┆       ┆            ┆           ┆           │
│ 71       ┆ L     ┆ point    ┆ Intersect(k_2,    ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ m_2)              ┆   ┆       ┆            ┆           ┆           │
│ 72       ┆ N     ┆ point    ┆ Intersect(p_2,    ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ q_2)              ┆   ┆       ┆            ┆           ┆           │
│ 73       ┆ S     ┆ point    ┆ Intersect(k_2,    ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ n_2)              ┆   ┆       ┆            ┆           ┆           │
│ 74       ┆ s_2   ┆ ray      ┆ Ray(O_{2}, L)     ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│ 75       ┆ t_2   ┆ ray      ┆ Ray(O_{2}, S)     ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│ 76       ┆ d_2   ┆ ray      ┆ Ray(O_{2}, N)     ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│ 77       ┆ T     ┆ point    ┆ Intersect(c, d_2) ┆ … ┆ 2     ┆ true       ┆ false     ┆ false     │
│ 78       ┆ ι     ┆ angle    ┆ Angle(F_{2}, C,   ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{2})            ┆   ┆       ┆            ┆           ┆           │
│ 79       ┆ κ     ┆ angle    ┆ Angle(I, C,       ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{2})            ┆   ┆       ┆            ┆           ┆           │
│ 80       ┆ λ     ┆ angle    ┆ Angle(R, C,       ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{1})            ┆   ┆       ┆            ┆           ┆           │
│ 81       ┆ μ     ┆ angle    ┆ Angle(F_{2}, C,   ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{1})            ┆   ┆       ┆            ┆           ┆           │
│ 82       ┆ U     ┆ point    ┆ Intersect(h_1,    ┆ … ┆ 2     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ l_1)              ┆   ┆       ┆            ┆           ┆           │
│ 83       ┆ h_3   ┆ line     ┆ AngleBisector(k_1 ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ , m_1)            ┆   ┆       ┆            ┆           ┆           │
│ 84       ┆ i_3   ┆ line     ┆ AngleBisector(k_1 ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ , m_1)            ┆   ┆       ┆            ┆           ┆           │
│ 85       ┆ ν     ┆ angle    ┆ Angle(O_{1}, C,   ┆ … ┆ 6     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{2})            ┆   ┆       ┆            ┆           ┆           │
│ 86       ┆ η     ┆ angle    ┆ Angle(O_{1}, A,   ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ Q)                ┆   ┆       ┆            ┆           ┆           │
│ 87       ┆ ζ     ┆ angle    ┆ Angle(O_{1}, A,   ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ F_{1})            ┆   ┆       ┆            ┆           ┆           │
│ 88       ┆ ε     ┆ angle    ┆ Angle(O_{2}, A,   ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ F_{1})            ┆   ┆       ┆            ┆           ┆           │
│ 89       ┆ k     ┆ numeric  ┆ null              ┆ … ┆ 8     ┆ true       ┆ true      ┆ false     │
│ 90       ┆ n_1   ┆ numeric  ┆ null              ┆ … ┆ 8     ┆ true       ┆ true      ┆ false     │
└──────────┴───────┴──────────┴───────────────────┴───┴───────┴────────────┴───────────┴───────────┘

In [131]:
p = ConstructionTreeParser(df)
g1 = p.parse()
nx.write_network_text(g1)

╟── O_{2}
╎   ├─╼ B ╾ A
╎   │   └─╼ c ╾ O_{2}
╎   │       ├─╼ j ╾ A
╎   │       │   ├─╼ q ╾ l
╎   │       │   ├─╼ r ╾ l
╎   │       │   │   └─╼ O_{1}
╎   │       │   │       ├─╼ t ╾ l
╎   │       │   │       │   ├─╼ F_{1} ╾ l
╎   │       │   │       │   │   ├─╼ h_1 ╾ O_{1}
╎   │       │   │       │   │   │   ├─╼ p_2 ╾ O_{2}, c
╎   │       │   │       │   │   │   │   ├─╼ q_2 ╾ O_{1}
╎   │       │   │       │   │   │   │   │   └─╼ N ╾ p_2
╎   │       │   │       │   │   │   │   │       └─╼ d_2 ╾ O_{2}
╎   │       │   │       │   │   │   │   │           └─╼ T ╾ c
╎   │       │   │       │   │   │   │   ├─╼ r_2 ╾ O_{1}
╎   │       │   │       │   │   │   │   │   └─╼ M ╾ p_2
╎   │       │   │       │   │   │   │   │       └─╼ b_2 ╾ O_{2}
╎   │       │   │       │   │   │   │   │           └─╼ F_{2} ╾ c
╎   │       │   │       │   │   │   │   │               ├─╼ γ ╾ A, O_{2}
╎   │       │   │       │   │   │   │   │               ├─╼ t2 ╾ A, O_{2}
╎   │       │   │       │   │   │   │   │               │   ├─╼ a_1 ╾ A, F_{2}
╎   │       │   │       │   │   │   │   │               │   ├─╼ c_2 ╾ F_{2}, O_{2}
╎   │       │   │       │   │   │   │   │               │   └─╼ i_1 ╾ O_{2}, A
╎   │       │   │       │   │   │   │   │               ├─╼ m ╾ A
╎   │       │   │       │   │   │   │   │               ├─╼ r_1 ╾ A
╎   │       │   │       │   │   │   │   │               ├─╼ O ╾ F_{1}
╎   │       │   │       │   │   │   │   │               │   └─╼ f ╾ l
╎   │       │   │       │   │   │   │   │               ├─╼ i ╾ F_{1}
╎   │       │   │       │   │   │   │   │               ├─╼ h ╾ C
╎   │       │   │       │   │   │   │   │               ├─╼ s_1 ╾ A
╎   │       │   │       │   │   │   │   │               ├─╼ d_1 ╾ C
╎   │       │   │       │   │   │   │   │               ├─╼ e_1 ╾ l
╎   │       │   │       │   │   │   │   │               ├─╼ ι ╾ C, O_{2}
╎   │       │   │       │   │   │   │   │               ├─╼ μ ╾ C, O_{1}
╎   │       │   │       │   │   │   │   │               └─╼  ...
╎   │       │   │       │   │   │   │   └─╼  ...
╎   │       │   │       │   │   │   ├─╼ j_1 ╾ P'
╎   │       │   │       │   │   │   │   └─╼ Q ╾ h_1
╎   │       │   │       │   │   │   │       ├─╼ g ╾ A
╎   │       │   │       │   │   │   │       └─╼ η ╾ O_{1}, A
╎   │       │   │       │   │   │   ├─╼ k_1 ╾ P'
╎   │       │   │       │   │   │   │   ├─╼ R ╾ h_1
╎   │       │   │       │   │   │   │   │   └─╼ λ ╾ C, O_{1}
╎   │       │   │       │   │   │   │   ├─╼ I ╾ c
╎   │       │   │       │   │   │   │   │   └─╼ κ ╾ C, O_{2}
╎   │       │   │       │   │   │   │   ├─╼ h_3 ╾ m_1
╎   │       │   │       │   │   │   │   └─╼ i_3 ╾ m_1
╎   │       │   │       │   │   │   ├─╼ l_1 ╾ P
╎   │       │   │       │   │   │   │   └─╼ U ╾ h_1
╎   │       │   │       │   │   │   ├─╼ m_1 ╾ P
╎   │       │   │       │   │   │   │   └─╼  ...
╎   │       │   │       │   │   │   ├─╼ k_2 ╾ O_{2}, c
╎   │       │   │       │   │   │   │   ├─╼ m_2 ╾ O_{1}
╎   │       │   │       │   │   │   │   │   └─╼ L ╾ k_2
╎   │       │   │       │   │   │   │   │       └─╼ s_2 ╾ O_{2}
╎   │       │   │       │   │   │   │   ├─╼ n_2 ╾ O_{1}
╎   │       │   │       │   │   │   │   │   └─╼ S ╾ k_2
╎   │       │   │       │   │   │   │   │       └─╼ t_2 ╾ O_{2}
╎   │       │   │       │   │   │   │   └─╼  ...
╎   │       │   │       │   │   │   └─╼  ...
╎   │       │   │       │   │   ├─╼ q_1 ╾ A
╎   │       │   │       │   │   ├─╼ ζ ╾ O_{1}, A
╎   │       │   │       │   │   ├─╼ ε ╾ O_{2}, A
╎   │       │   │       │   │   └─╼  ...
╎   │       │   │       │   ├─╼ E ╾ p_1
╎   │       │   │       │   │   ├─╼ f_2 ╾ O_{2}
╎   │       │   │       │   │   ├─╼ t5 ╾ O_3, O_{2}
╎   │       │   │       │   │   │   ├─╼ e_2 ╾ O_3, O_{2}
╎   │       │   │       │   │   │   ├─╼ o_3 ╾ O_{2}, E
╎   │       │   │       │   │   │   └─╼ o_{2} ╾ E, O_3
╎   │       │   │       │   │   └─╼  ...
╎   │       │   │       │   └─╼ F ╾ p_1
╎   │       │   │       ├─╼ θ ╾ O_{2}, A
╎   │       │   │       ├─╼ b ╾ O_{2}
╎   │       │   │       │   ├─╼ P' ╾ j
╎   │       │   │       │   │   └─╼  ...
╎   │       │   │       │   └─╼ P ╾ l
╎   │       │   │       │       └─╼  ...
╎   │       │   │       ├─╼ O_3 ╾ O_{2}
╎   │       │   │       │   ├─╼ p_1 ╾ O_{2}
╎   │       │   │       │   │   ├─╼ C ╾ l
╎   │       │   │       │   │   │   ├─╼ t4 ╾ O_3, A
╎   │       │   │       │   │   │   │   ├─╼ c_3 ╾ O_3, A
╎   │       │   │       │   │   │   │   ├─╼ i_2 ╾ A, C
╎   │       │   │       │   │   │   │   └─╼ a_2 ╾ C, O_3
╎   │       │   │       │   │   │   ├─╼ ν ╾ O_{1}, O_{2}
╎   │       │   │       │   │   │   └─╼  ...
╎   │       │   │       │   │   ├─╼ D
╎   │       │   │       │   │   │   ├─╼ t3 ╾ O_{2}, O_{1}
╎   │       │   │       │   │   │   │   ├─╼ d ╾ O_{2}, O_{1}
╎   │       │   │       │   │   │   │   ├─╼ o ╾ O_{1}, D
╎   │       │   │       │   │   │   │   └─╼ l_2 ╾ D, O_{2}
╎   │       │   │       │   │   │   ├─╼ α ╾ O_{2}, O_{1}
╎   │       │   │       │   │   │   └─╼  ...
╎   │       │   │       │   │   └─╼  ...
╎   │       │   │       │   └─╼  ...
╎   │       │   │       └─╼  ...
╎   │       │   └─╼  ...
╎   │       ├─╼ l ╾ A
╎   │       │   └─╼  ...
╎   │       └─╼  ...
╎   ├─╼ n ╾ A
╎   ├─╼ O' ╾ A
╎   │   └─╼ p ╾ A
╎   └─╼  ...
╙── A
    └─╼  ...

In [132]:
p.df

shape: (91, 11)
┌──────────┬───────┬──────────┬─────────────┬───┬────────────┬───────────┬───────────┬─────────────┐
│ Sequence ┆ Name  ┆ Type     ┆ Command     ┆ … ┆ ShowObject ┆ ShowLabel ┆ Auxiliary ┆ DependsOn   │
│ ---      ┆ ---   ┆ ---      ┆ ---         ┆   ┆ ---        ┆ ---       ┆ ---       ┆ ---         │
│ u32      ┆ str   ┆ str      ┆ str         ┆   ┆ bool       ┆ bool      ┆ bool      ┆ list[str]   │
╞══════════╪═══════╪══════════╪═════════════╪═══╪════════════╪═══════════╪═══════════╪═════════════╡
│ 0        ┆ O_{2} ┆ point    ┆ null        ┆ … ┆ true       ┆ true      ┆ false     ┆ []          │
│ 1        ┆ A     ┆ point    ┆ null        ┆ … ┆ true       ┆ true      ┆ false     ┆ []          │
│ 2        ┆ B     ┆ point    ┆ Point(Line( ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A",       │
│          ┆       ┆          ┆ O_{2}, A))  ┆   ┆            ┆           ┆           ┆ "O_{2}"]    │
│ 3        ┆ c     ┆ circle   ┆ Circle(O_{2 ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ }, B)       ┆   ┆            ┆           ┆           ┆ "O_{2}"]    │
│ 4        ┆ n     ┆ line     ┆ Line(O_{2}, ┆ … ┆ false      ┆ false     ┆ false     ┆ ["A",       │
│          ┆       ┆          ┆ A)          ┆   ┆            ┆           ┆           ┆ "O_{2}"]    │
│ 5        ┆ O'    ┆ point    ┆ Midpoint(O_ ┆ … ┆ false      ┆ true      ┆ false     ┆ ["A",       │
│          ┆       ┆          ┆ {2}, A)     ┆   ┆            ┆           ┆           ┆ "O_{2}"]    │
│ 6        ┆ p     ┆ circle   ┆ Circle(O',  ┆ … ┆ false      ┆ false     ┆ false     ┆ ["A", "O'", │
│          ┆       ┆          ┆ A)          ┆   ┆            ┆           ┆           ┆ "O_{2}"]    │
│ 7        ┆ j     ┆ line     ┆ Tangent(A,  ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ c)          ┆   ┆            ┆           ┆           ┆ … "c"]      │
│ 8        ┆ l     ┆ line     ┆ Tangent(A,  ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ c)          ┆   ┆            ┆           ┆           ┆ … "c"]      │
│ 9        ┆ q     ┆ line     ┆ AngleBisect ┆ … ┆ false      ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ or(l, j)    ┆   ┆            ┆           ┆           ┆ … "l"]      │
│ 10       ┆ r     ┆ line     ┆ AngleBisect ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ or(l, j)    ┆   ┆            ┆           ┆           ┆ … "l"]      │
│ 11       ┆ O_{1} ┆ point    ┆ Point(r)    ┆ … ┆ true       ┆ true      ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆             ┆   ┆            ┆           ┆           ┆ … "r"]      │
│ 12       ┆ t     ┆ line     ┆ Perpendicul ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ arLine(O_{1 ┆   ┆            ┆           ┆           ┆ … "r"]      │
│          ┆       ┆          ┆ }, l)       ┆   ┆            ┆           ┆           ┆             │
│ 13       ┆ F_{1} ┆ point    ┆ Intersect(t ┆ … ┆ true       ┆ true      ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ , l)        ┆   ┆            ┆           ┆           ┆ … "t"]      │
│ 14       ┆ h_1   ┆ circle   ┆ Circle(O_{1 ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ }, F_{1})   ┆   ┆            ┆           ┆           ┆ … "t"]      │
│ 15       ┆ p_2   ┆ circle   ┆ Circle(O_{2 ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ },          ┆   ┆            ┆           ┆           ┆ … "t"]      │
│          ┆       ┆          ┆ Radius(c) + ┆   ┆            ┆           ┆           ┆             │
│          ┆       ┆          ┆ Radi…       ┆   ┆            ┆           ┆           ┆             │
│ 16       ┆ q_2   ┆ line     ┆ Tangent(O_{ ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ 1}, p_2)    ┆   ┆            ┆           ┆           ┆ … "t"]      │
│ 17       ┆ r_2   ┆ line     ┆ Tangent(O_{ ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ 1}, p_2)    ┆   ┆            ┆           ┆           ┆ … "t"]      │
│ 18       ┆ M     ┆ point    ┆ Intersect(p ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ _2, r_2)    ┆   ┆            ┆           ┆           ┆ … "t"]      │
│ 19       ┆ b_2   ┆ ray      ┆ Ray(O_{2},  ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ M)          ┆   ┆            ┆           ┆           ┆ … "t"]      │
│ 20       ┆ F_{2} ┆ point    ┆ Intersect(c ┆ … ┆ true       ┆ true      ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ , b_2, 1)   ┆   ┆            ┆           ┆           ┆ … "t"]      │
│ 21       ┆ γ     ┆ angle    ┆ Angle(A,    ┆ … ┆ false      ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ F_{2},      ┆   ┆            ┆           ┆           ┆ … "t"]      │
│          ┆       ┆          ┆ O_{2})      ┆   ┆            ┆           ┆           ┆             │
│ 22       ┆ t2    ┆ triangle ┆ Polygon(A,  ┆ … ┆ false      ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ F_{2},      ┆   ┆            ┆           ┆           ┆ … "t"]      │
│          ┆       ┆          ┆ O_{2})      ┆   ┆            ┆           ┆           ┆             │
│ 23       ┆ a_1   ┆ segment  ┆ Segment(A,  ┆ … ┆ false      ┆ false     ┆ true      ┆ ["A", "B",  │
│          ┆       ┆          ┆ F_{2}, t2)  ┆   ┆            ┆           ┆           ┆ … "t2"]     │
│ 24       ┆ c_2   ┆ segment  ┆ Segment(F_{ ┆ … ┆ false      ┆ false     ┆ true      ┆ ["A", "B",  │
│          ┆       ┆          ┆ 2}, O_{2},  ┆   ┆            ┆           ┆           ┆ … "t2"]     │
│          ┆       ┆          ┆ t2)         ┆   ┆            ┆           ┆           ┆             │
│ 25       ┆ i_1   ┆ segment  ┆ Segment(O_{ ┆ … ┆ false      ┆ false     ┆ true      ┆ ["A", "B",  │
│          ┆       ┆          ┆ 2}, A, t2)  ┆   ┆            ┆           ┆           ┆ … "t2"]     │
│ 26       ┆ m     ┆ segment  ┆ Segment(A,  ┆ … ┆ false      ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ F_{2})      ┆   ┆            ┆           ┆           ┆ … "t"]      │
│ 27       ┆ θ     ┆ angle    ┆ Angle(O_{2} ┆ … ┆ false      ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ , A, O_{1}) ┆   ┆            ┆           ┆           ┆ … "r"]      │
│ 28       ┆ b     ┆ line     ┆ Line(O_{2}, ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ O_{1})      ┆   ┆            ┆           ┆           ┆ … "r"]      │
│ 29       ┆ P'    ┆ point    ┆ Intersect(b ┆ … ┆ true       ┆ true      ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ , j)        ┆   ┆            ┆           ┆           ┆ … "r"]      │
│ 30       ┆ P     ┆ point    ┆ Intersect(b ┆ … ┆ true       ┆ true      ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ , l)        ┆   ┆            ┆           ┆           ┆ … "r"]      │
│ 31       ┆ j_1   ┆ line     ┆ Tangent(P', ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ h_1)        ┆   ┆            ┆           ┆           ┆ … "t"]      │
│ 32       ┆ k_1   ┆ line     ┆ Tangent(P', ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ h_1)        ┆   ┆            ┆           ┆           ┆ … "t"]      │
│ 33       ┆ l_1   ┆ line     ┆ Tangent(P,  ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ h_1)        ┆   ┆            ┆           ┆           ┆ … "t"]      │
│ 34       ┆ m_1   ┆ line     ┆ Tangent(P,  ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ h_1)        ┆   ┆            ┆           ┆           ┆ … "t"]      │
│ 35       ┆ O_3   ┆ point    ┆ Midpoint(O_ ┆ … ┆ false      ┆ true      ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ {2}, O_{1}) ┆   ┆            ┆           ┆           ┆ … "r"]      │
│ 36       ┆ p_1   ┆ circle   ┆ Circle(O_3, ┆ … ┆ false      ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ O_{2})      ┆   ┆            ┆           ┆           ┆ … "r"]      │
│ 37       ┆ C     ┆ point    ┆ Intersect(p ┆ … ┆ true       ┆ true      ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ _1, l, 2)   ┆   ┆            ┆           ┆           ┆ … "r"]      │
│ 38       ┆ q_1   ┆ circle   ┆ Circle(A,   ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ F_{1})      ┆   ┆            ┆           ┆           ┆ … "t"]      │
│ 39       ┆ r_1   ┆ circle   ┆ Circle(A,   ┆ … ┆ false      ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ F_{2})      ┆   ┆            ┆           ┆           ┆ … "t"]      │
│ 40       ┆ Q     ┆ point    ┆ Intersect(h ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ _1, j_1)    ┆   ┆            ┆           ┆           ┆ … "t"]      │
│ 41       ┆ R     ┆ point    ┆ Intersect(h ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ _1, k_1)    ┆   ┆            ┆           ┆           ┆ … "t"]      │
│ 42       ┆ D     ┆ point    ┆ Point(p_1)  ┆ … ┆ false      ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆             ┆   ┆            ┆           ┆           ┆ … "r"]      │
│ 43       ┆ t3    ┆ triangle ┆ Polygon(O_{ ┆ … ┆ false      ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ 2}, O_{1},  ┆   ┆            ┆           ┆           ┆ … "r"]      │
│          ┆       ┆          ┆ D)          ┆   ┆            ┆           ┆           ┆             │
│ 44       ┆ d     ┆ segment  ┆ Segment(O_{ ┆ … ┆ false      ┆ false     ┆ true      ┆ ["A", "B",  │
│          ┆       ┆          ┆ 2}, O_{1},  ┆   ┆            ┆           ┆           ┆ … "t3"]     │
│          ┆       ┆          ┆ t3)         ┆   ┆            ┆           ┆           ┆             │
│ 45       ┆ o     ┆ segment  ┆ Segment(O_{ ┆ … ┆ false      ┆ false     ┆ true      ┆ ["A", "B",  │
│          ┆       ┆          ┆ 1}, D, t3)  ┆   ┆            ┆           ┆           ┆ … "t3"]     │
│ 46       ┆ l_2   ┆ segment  ┆ Segment(D,  ┆ … ┆ false      ┆ false     ┆ true      ┆ ["A", "B",  │
│          ┆       ┆          ┆ O_{2}, t3)  ┆   ┆            ┆           ┆           ┆ … "t3"]     │
│ 47       ┆ α     ┆ angle    ┆ Angle(O_{2} ┆ … ┆ false      ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ , D, O_{1}) ┆   ┆            ┆           ┆           ┆ … "r"]      │
│ 48       ┆ O     ┆ point    ┆ Midpoint(F_ ┆ … ┆ false      ┆ true      ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ {1}, F_{2}) ┆   ┆            ┆           ┆           ┆ … "t"]      │
│ 49       ┆ f     ┆ line     ┆ Perpendicul ┆ … ┆ false      ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ arLine(O,   ┆   ┆            ┆           ┆           ┆ … "t"]      │
│          ┆       ┆          ┆ l)          ┆   ┆            ┆           ┆           ┆             │
│ 50       ┆ i     ┆ segment  ┆ Segment(F_{ ┆ … ┆ false      ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ 1}, F_{2})  ┆   ┆            ┆           ┆           ┆ … "t"]      │
│ 51       ┆ t4    ┆ triangle ┆ Polygon(O_3 ┆ … ┆ false      ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ , A, C)     ┆   ┆            ┆           ┆           ┆ … "r"]      │
│ 52       ┆ c_3   ┆ segment  ┆ Segment(O_3 ┆ … ┆ false      ┆ false     ┆ true      ┆ ["A", "B",  │
│          ┆       ┆          ┆ , A, t4)    ┆   ┆            ┆           ┆           ┆ … "t4"]     │
│ 53       ┆ i_2   ┆ segment  ┆ Segment(A,  ┆ … ┆ false      ┆ false     ┆ true      ┆ ["A", "B",  │
│          ┆       ┆          ┆ C, t4)      ┆   ┆            ┆           ┆           ┆ … "t4"]     │
│ 54       ┆ a_2   ┆ segment  ┆ Segment(C,  ┆ … ┆ false      ┆ false     ┆ true      ┆ ["A", "B",  │
│          ┆       ┆          ┆ O_3, t4)    ┆   ┆            ┆           ┆           ┆ … "t4"]     │
│ 55       ┆ h     ┆ circle   ┆ Circle(C,   ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ F_{2})      ┆   ┆            ┆           ┆           ┆ … "t"]      │
│ 56       ┆ g     ┆ segment  ┆ Segment(A,  ┆ … ┆ false      ┆ true      ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ Q)          ┆   ┆            ┆           ┆           ┆ … "t"]      │
│ 57       ┆ s_1   ┆ segment  ┆ Segment(A,  ┆ … ┆ false      ┆ true      ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ F_{2})      ┆   ┆            ┆           ┆           ┆ … "t"]      │
│ 58       ┆ d_1   ┆ segment  ┆ Segment(F_{ ┆ … ┆ false      ┆ true      ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ 2}, C)      ┆   ┆            ┆           ┆           ┆ … "t"]      │
│ 59       ┆ e_1   ┆ line     ┆ Perpendicul ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ arLine(F_{2 ┆   ┆            ┆           ┆           ┆ … "t"]      │
│          ┆       ┆          ┆ }, l)       ┆   ┆            ┆           ┆           ┆             │
│ 60       ┆ E     ┆ point    ┆ Intersect(p ┆ … ┆ false      ┆ true      ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ _1, t)      ┆   ┆            ┆           ┆           ┆ … "t"]      │
│ 61       ┆ F     ┆ point    ┆ Intersect(p ┆ … ┆ false      ┆ false     ┆ true      ┆ ["A", "B",  │
│          ┆       ┆          ┆ _1, t)      ┆   ┆            ┆           ┆           ┆ … "t"]      │
│ 62       ┆ f_2   ┆ segment  ┆ Segment(E,  ┆ … ┆ false      ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ O_{2})      ┆   ┆            ┆           ┆           ┆ … "t"]      │
│ 63       ┆ t5    ┆ triangle ┆ Polygon(O_3 ┆ … ┆ false      ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ , O_{2}, E) ┆   ┆            ┆           ┆           ┆ … "t"]      │
│ 64       ┆ e_2   ┆ segment  ┆ Segment(O_3 ┆ … ┆ false      ┆ false     ┆ true      ┆ ["A", "B",  │
│          ┆       ┆          ┆ , O_{2},    ┆   ┆            ┆           ┆           ┆ … "t5"]     │
│          ┆       ┆          ┆ t5)         ┆   ┆            ┆           ┆           ┆             │
│ 65       ┆ o_3   ┆ segment  ┆ Segment(O_{ ┆ … ┆ false      ┆ false     ┆ true      ┆ ["A", "B",  │
│          ┆       ┆          ┆ 2}, E, t5)  ┆   ┆            ┆           ┆           ┆ … "t5"]     │
│ 66       ┆ o_{2} ┆ segment  ┆ Segment(E,  ┆ … ┆ false      ┆ false     ┆ true      ┆ ["A", "B",  │
│          ┆       ┆          ┆ O_3, t5)    ┆   ┆            ┆           ┆           ┆ … "t5"]     │
│ 67       ┆ I     ┆ point    ┆ Intersect(c ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ , k_1, 1)   ┆   ┆            ┆           ┆           ┆ … "t"]      │
│ 68       ┆ k_2   ┆ circle   ┆ Circle(O_{2 ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ },          ┆   ┆            ┆           ┆           ┆ … "t"]      │
│          ┆       ┆          ┆ Radius(c) - ┆   ┆            ┆           ┆           ┆             │
│          ┆       ┆          ┆ Radi…       ┆   ┆            ┆           ┆           ┆             │
│ 69       ┆ m_2   ┆ line     ┆ Tangent(O_{ ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ 1}, k_2)    ┆   ┆            ┆           ┆           ┆ … "t"]      │
│ 70       ┆ n_2   ┆ line     ┆ Tangent(O_{ ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ 1}, k_2)    ┆   ┆            ┆           ┆           ┆ … "t"]      │
│ 71       ┆ L     ┆ point    ┆ Intersect(k ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ _2, m_2)    ┆   ┆            ┆           ┆           ┆ … "t"]      │
│ 72       ┆ N     ┆ point    ┆ Intersect(p ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ _2, q_2)    ┆   ┆            ┆           ┆           ┆ … "t"]      │
│ 73       ┆ S     ┆ point    ┆ Intersect(k ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ _2, n_2)    ┆   ┆            ┆           ┆           ┆ … "t"]      │
│ 74       ┆ s_2   ┆ ray      ┆ Ray(O_{2},  ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ L)          ┆   ┆            ┆           ┆           ┆ … "t"]      │
│ 75       ┆ t_2   ┆ ray      ┆ Ray(O_{2},  ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ S)          ┆   ┆            ┆           ┆           ┆ … "t"]      │
│ 76       ┆ d_2   ┆ ray      ┆ Ray(O_{2},  ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ N)          ┆   ┆            ┆           ┆           ┆ … "t"]      │
│ 77       ┆ T     ┆ point    ┆ Intersect(c ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ , d_2)      ┆   ┆            ┆           ┆           ┆ … "t"]      │
│ 78       ┆ ι     ┆ angle    ┆ Angle(F_{2} ┆ … ┆ false      ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ , C, O_{2}) ┆   ┆            ┆           ┆           ┆ … "t"]      │
│ 79       ┆ κ     ┆ angle    ┆ Angle(I, C, ┆ … ┆ false      ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ O_{2})      ┆   ┆            ┆           ┆           ┆ … "t"]      │
│ 80       ┆ λ     ┆ angle    ┆ Angle(R, C, ┆ … ┆ false      ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ O_{1})      ┆   ┆            ┆           ┆           ┆ … "t"]      │
│ 81       ┆ μ     ┆ angle    ┆ Angle(F_{2} ┆ … ┆ false      ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ , C, O_{1}) ┆   ┆            ┆           ┆           ┆ … "t"]      │
│ 82       ┆ U     ┆ point    ┆ Intersect(h ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ _1, l_1)    ┆   ┆            ┆           ┆           ┆ … "t"]      │
│ 83       ┆ h_3   ┆ line     ┆ AngleBisect ┆ … ┆ false      ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ or(k_1,     ┆   ┆            ┆           ┆           ┆ … "t"]      │
│          ┆       ┆          ┆ m_1)        ┆   ┆            ┆           ┆           ┆             │
│ 84       ┆ i_3   ┆ line     ┆ AngleBisect ┆ … ┆ false      ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ or(k_1,     ┆   ┆            ┆           ┆           ┆ … "t"]      │
│          ┆       ┆          ┆ m_1)        ┆   ┆            ┆           ┆           ┆             │
│ 85       ┆ ν     ┆ angle    ┆ Angle(O_{1} ┆ … ┆ false      ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ , C, O_{2}) ┆   ┆            ┆           ┆           ┆ … "r"]      │
│ 86       ┆ η     ┆ angle    ┆ Angle(O_{1} ┆ … ┆ false      ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ , A, Q)     ┆   ┆            ┆           ┆           ┆ … "t"]      │
│ 87       ┆ ζ     ┆ angle    ┆ Angle(O_{1} ┆ … ┆ false      ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ , A, F_{1}) ┆   ┆            ┆           ┆           ┆ … "t"]      │
│ 88       ┆ ε     ┆ angle    ┆ Angle(O_{2} ┆ … ┆ false      ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆       ┆          ┆ , A, F_{1}) ┆   ┆            ┆           ┆           ┆ … "t"]      │
│ 89       ┆ k     ┆ numeric  ┆ null        ┆ … ┆ true       ┆ true      ┆ false     ┆ []          │

In [166]:
await ggb.listen('k', True)
await ggb.listen('n_1', True)

{}

In [141]:
await ggb.listen('a', False)
await ggb.listen('b', False)

{}

In [167]:
ggb.comm.shared_objects

{}

In [162]:
await ggb.function("getVersion")

'5.2.909.9'

In [16]:
import ipywidgets as widgets
label1 = widgets.Label(value=ggb.comm.shared_objects['n'])
label2 = widgets.Label(value=ggb.comm.shared_objects['m'])
display(label1, label2)

Label(value='n = 6')

Label(value='m = 0')

In [146]:
async def on_shared_update1(changes):
    # await asyncio.sleep(0)
    # label1.value = changes['a']
    n = int(changes['k'].split()[2])
    # await asyncio.sleep(0)
    await ggb.function("setLayerVisible", list(zip_longest(range(9), [True]*n, fillvalue=False)))
    r = await ggb.function('getXML', ['n_1'])
    o = ggb.file.ggb_schema.decode(r)
    o['value'][0]['@val'] = '0'
    x = xmlschema.etree_tostring(ggb.file.ggb_schema.encode(o, 'element'))
    r = await ggb.function('evalXML' , [x])

In [147]:
ggb.comm.remove_shared_listener(on_shared_update1)
ggb.comm.add_shared_listener(on_shared_update1)

True

In [148]:
async def on_shared_update2(changes):
    # await asyncio.sleep(0)
    # label2.value = changes['b']
    m = int(changes['n_1'].split()[2])
    n = int(ggb.comm.shared_objects['k'].split()[2])
    l = df.filter(pl.col("Layer") == n)["Name"].to_list()
    # m = int(ggb.comm.shared_objects['m'].split()[2])
    # list(zip_longest(l, [True]*m, fillvalue=False))
    await ggb.function("setVisible", list(zip_longest(l, [True]*m, fillvalue=False)))

In [149]:
ggb.comm.remove_shared_listener(on_shared_update2)
ggb.comm.add_shared_listener(on_shared_update2)

True

In [104]:
ggb.comm.clear_shared_listeners()

2

In [103]:
await ggb.function("getVersion")

'5.2.909.9'

In [21]:
await ggb.command("Midpoint[D, E]")

'J'

In [22]:
await ggb.command("Circle(J, D)")

'e'

In [24]:
%pwd

'/Users/manabu/work/ggblab/examples'

In [116]:
# ggb.file.source_file = 'eg10_slider2.ggb'

In [168]:
ggb.file.base64_buffer = await ggb.function("getBase64")

In [169]:
ggb.file.save(overwrite=True)

* 原則（教育観）:
    - 目的化: 再現は「結果」ではなく「理解（なぜその操作か）」を目的にする。
    - 予測→検証: 次に何が起きるか予測させてから操作させる。
    - 説明要求: 手順ごとに短い理由説明（1文）を書かせる。
    - 変奏課題: パラメータを少し変えた課題で本質が移るか確認する。
    - 生成的課題: 「同じ発想で別の図形を作る」など転移を問う。
* ggblabで実装できる仕組み（短）:
    - 段階公開（layer slider）: 各レイヤーに「解説」「問い」「期待する操作」を紐付け、スライダーで段階的に提示。
    - 予測プロンプト: 各ステップの前に「次に何が起きる？」を表示し、回答を記録。
    - 説明入力欄: 学生が操作毎に短い説明を入力 → 教師や自動ルールでフィードバック。
    - 変化タスク自動化: DataFrame→コマンド生成を利用してパラメータをランダム化した派生課題を作る。
    - 操作ログ＋解析: 操作順・所要時間・試行回数をログ化して学習診断に使う。
    - 差分フィードバック: 学生構成と模範構成を比較して「次に直すべき一手」を提示。

In [29]:
await ggb.function("getVersion")

'5.2.909.9'