In [1]:
import asyncio
import xmlschema
import networkx as nx
import polars as pl
from itertools import zip_longest

In [2]:
from ggblab import GeoGebra
ggb = await GeoGebra().init(use_vscode=True)

Using local cached file: xsd/common.xsd

In [3]:
%pwd

'/Users/manabu/work/ggblab'

In [4]:
%cd examples/

/Users/manabu/work/ggblab/examples

In [5]:
ggb.file.load('eg10_slider3.ggb')
# ggb.file.load('2025_06_08.ggb')

In [6]:
r = await ggb.function("setBase64", [ggb.construction.base64_buffer.decode('utf-8')])

In [7]:
from ggblab_extra import ConstructionIO
from ggblab_extra import ConstructionTreeParser

In [51]:

df = await ConstructionIO.initialize_dataframe(ggb, use_applet=True)
df

shape: (51, 10)
┌──────────┬──────┬──────────┬────────────────────┬───┬───────┬────────────┬───────────┬───────────┐
│ Sequence ┆ Name ┆ Type     ┆ Command            ┆ … ┆ Layer ┆ ShowObject ┆ ShowLabel ┆ Auxiliary │
│ ---      ┆ ---  ┆ ---      ┆ ---                ┆   ┆ ---   ┆ ---        ┆ ---       ┆ ---       │
│ u32      ┆ str  ┆ str      ┆ str                ┆   ┆ u32   ┆ bool       ┆ bool      ┆ bool      │
╞══════════╪══════╪══════════╪════════════════════╪═══╪═══════╪════════════╪═══════════╪═══════════╡
│ 0        ┆ n    ┆ numeric  ┆ null               ┆ … ┆ 9     ┆ true       ┆ true      ┆ false     │
│ 1        ┆ i    ┆ numeric  ┆ null               ┆ … ┆ 9     ┆ true       ┆ true      ┆ false     │
│ 2        ┆ A    ┆ point    ┆ null               ┆ … ┆ 9     ┆ true       ┆ true      ┆ false     │
│ 3        ┆ B    ┆ point    ┆ null               ┆ … ┆ 9     ┆ true       ┆ true      ┆ false     │
│ 4        ┆ C    ┆ point    ┆ null               ┆ … ┆ 9     ┆ true       ┆ true      ┆ false     │
│ 5        ┆ f    ┆ line     ┆ Line(A, B)         ┆ … ┆ 0     ┆ true       ┆ false     ┆ false     │
│ 6        ┆ g    ┆ line     ┆ Line(A, C)         ┆ … ┆ 0     ┆ true       ┆ false     ┆ false     │
│ 7        ┆ h    ┆ line     ┆ AngleBisector(f,   ┆ … ┆ 0     ┆ true       ┆ false     ┆ false     │
│          ┆      ┆          ┆ g)                 ┆   ┆       ┆            ┆           ┆           │
│ 8        ┆ j    ┆ line     ┆ AngleBisector(f,   ┆ … ┆ 0     ┆ true       ┆ false     ┆ false     │
│          ┆      ┆          ┆ g)                 ┆   ┆       ┆            ┆           ┆           │
│ 9        ┆ H    ┆ point    ┆ null               ┆ … ┆ 9     ┆ true       ┆ true      ┆ false     │
│ 10       ┆ k    ┆ line     ┆ Line(C, H)         ┆ … ┆ 0     ┆ true       ┆ false     ┆ false     │
│ 11       ┆ D    ┆ point    ┆ Intersect(k, j)    ┆ … ┆ 0     ┆ true       ┆ true      ┆ false     │
│ 12       ┆ E    ┆ point    ┆ Intersect(k, h)    ┆ … ┆ 0     ┆ true       ┆ true      ┆ false     │
│ 13       ┆ l    ┆ line     ┆ PerpendicularLine( ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│          ┆      ┆          ┆ D, g)              ┆   ┆       ┆            ┆           ┆           │
│ 14       ┆ m    ┆ line     ┆ PerpendicularLine( ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│          ┆      ┆          ┆ E, g)              ┆   ┆       ┆            ┆           ┆           │
│ 15       ┆ F    ┆ point    ┆ Intersect(l, g)    ┆ … ┆ 1     ┆ true       ┆ true      ┆ false     │
│ 16       ┆ G    ┆ point    ┆ Intersect(m, g)    ┆ … ┆ 1     ┆ true       ┆ true      ┆ false     │
│ 17       ┆ c    ┆ circle   ┆ Circle(D, F)       ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│ 18       ┆ d    ┆ circle   ┆ Circle(E, G)       ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│ 19       ┆ J    ┆ point    ┆ Midpoint(F, G)     ┆ … ┆ 1     ┆ false      ┆ false     ┆ false     │
│ 20       ┆ g_1  ┆ line     ┆ Line(J, k)         ┆ … ┆ 5     ┆ false      ┆ false     ┆ false     │
│ 21       ┆ f_1  ┆ line     ┆ PerpendicularLine( ┆ … ┆ 4     ┆ true       ┆ false     ┆ false     │
│          ┆      ┆          ┆ J, k)              ┆   ┆       ┆            ┆           ┆           │
│ 22       ┆ K    ┆ point    ┆ Intersect(f, f_1)  ┆ … ┆ 4     ┆ true       ┆ true      ┆ false     │
│ 23       ┆ L    ┆ point    ┆ Intersect(k, f_1)  ┆ … ┆ 4     ┆ true       ┆ true      ┆ false     │
│ 24       ┆ d_1  ┆ circle   ┆ Circle(L, K)       ┆ … ┆ 4     ┆ true       ┆ false     ┆ false     │
│ 25       ┆ M    ┆ point    ┆ Intersect(d_1,     ┆ … ┆ 5     ┆ false      ┆ false     ┆ false     │
│          ┆      ┆          ┆ g_1)               ┆   ┆       ┆            ┆           ┆           │
│ 26       ┆ N    ┆ point    ┆ Intersect(d_1,     ┆ … ┆ 5     ┆ false      ┆ false     ┆ false     │
│          ┆      ┆          ┆ g_1)               ┆   ┆       ┆            ┆           ┆           │
│ 27       ┆ e_1  ┆ circle   ┆ Circle(J, M)       ┆ … ┆ 6     ┆ true       ┆ false     ┆ false     │
│ 28       ┆ S    ┆ point    ┆ Midpoint(A, J)     ┆ … ┆ 7     ┆ false      ┆ true      ┆ false     │
│ 29       ┆ k_1  ┆ circle   ┆ Circle(S, A)       ┆ … ┆ 7     ┆ false      ┆ false     ┆ false     │
│ 30       ┆ V    ┆ point    ┆ Intersect(e_1,     ┆ … ┆ 7     ┆ false      ┆ true      ┆ false     │
│          ┆      ┆          ┆ k_1)               ┆   ┆       ┆            ┆           ┆           │
│ 31       ┆ W    ┆ point    ┆ Intersect(e_1,     ┆ … ┆ 7     ┆ false      ┆ true      ┆ false     │
│          ┆      ┆          ┆ k_1)               ┆   ┆       ┆            ┆           ┆           │
│ 32       ┆ t1   ┆ triangle ┆ Polygon(J, A, W)   ┆ … ┆ 8     ┆ true       ┆ false     ┆ false     │
│ 33       ┆ q    ┆ segment  ┆ Segment(J, A, t1)  ┆ … ┆ 8     ┆ true       ┆ false     ┆ true      │
│ 34       ┆ r    ┆ segment  ┆ Segment(A, W, t1)  ┆ … ┆ 8     ┆ false      ┆ false     ┆ false     │
│ 35       ┆ s    ┆ segment  ┆ Segment(W, J, t1)  ┆ … ┆ 8     ┆ false      ┆ false     ┆ false     │
│ 36       ┆ c_1  ┆ circle   ┆ Circle(J, A)       ┆ … ┆ 2     ┆ true       ┆ false     ┆ false     │
│ 37       ┆ Q    ┆ point    ┆ Intersect(c_1, m)  ┆ … ┆ 7     ┆ false      ┆ true      ┆ false     │
│ 38       ┆ R    ┆ point    ┆ Intersect(c_1, m)  ┆ … ┆ 7     ┆ false      ┆ false     ┆ false     │
│ 39       ┆ t2   ┆ triangle ┆ Polygon(J, G, R)   ┆ … ┆ 8     ┆ true       ┆ false     ┆ false     │
│ 40       ┆ t    ┆ segment  ┆ Segment(J, G, t2)  ┆ … ┆ 8     ┆ true       ┆ false     ┆ true      │
│ 41       ┆ a    ┆ segment  ┆ Segment(G, R, t2)  ┆ … ┆ 8     ┆ true       ┆ false     ┆ true      │
│ 42       ┆ b    ┆ segment  ┆ Segment(R, J, t2)  ┆ … ┆ 8     ┆ false      ┆ false     ┆ false     │
│ 43       ┆ e    ┆ circle   ┆ Circle(J, F)       ┆ … ┆ 2     ┆ true       ┆ false     ┆ false     │
│ 44       ┆ h_1  ┆ ellipse  ┆ Ellipse(F, G, A)   ┆ … ┆ 6     ┆ true       ┆ false     ┆ false     │
│ 45       ┆ i_1  ┆ line     ┆ PerpendicularLine( ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│          ┆      ┆          ┆ J, g)              ┆   ┆       ┆            ┆           ┆           │
│ 46       ┆ T    ┆ point    ┆ Intersect(e_1,     ┆ … ┆ 6     ┆ true       ┆ true      ┆ false     │
│          ┆      ┆          ┆ h_1, 3)            ┆   ┆       ┆            ┆           ┆           │
│ 47       ┆ U    ┆ point    ┆ Intersect(k_1,     ┆ … ┆ 7     ┆ false      ┆ true      ┆ false     │
│          ┆      ┆          ┆ h_1, 1)            ┆   ┆       ┆            ┆           ┆           │
│ 48       ┆ Z    ┆ point    ┆ Midpoint(D, E)     ┆ … ┆ 3     ┆ true       ┆ true      ┆ false     │
│ 49       ┆ p_1  ┆ circle   ┆ Circle(Z, D)       ┆ … ┆ 3     ┆ true       ┆ false     ┆ false     │
│ 50       ┆ p    ┆ circle   ┆ Circle(T,          ┆ … ┆ 8     ┆ true       ┆ true      ┆ false     │
│          ┆      ┆          ┆ Distance(A, J))    ┆   ┆       ┆            ┆           ┆           │
└──────────┴──────┴──────────┴────────────────────┴───┴───────┴────────────┴───────────┴───────────┘

In [52]:
p = ConstructionTreeParser(df)
g1 = p.parse()
nx.write_network_text(g1)

╟── A
╎   ├─╼ f ╾ B
╎   │   ├─╼ h ╾ g
╎   │   │   └─╼ E ╾ k
╎   │   │       ├─╼ m ╾ g
╎   │   │       │   ├─╼ G ╾ g
╎   │   │       │   │   ├─╼ d ╾ E
╎   │   │       │   │   ├─╼ J ╾ F
╎   │   │       │   │   │   ├─╼ g_1 ╾ k
╎   │   │       │   │   │   │   ├─╼ M ╾ d_1
╎   │   │       │   │   │   │   │   └─╼ e_1 ╾ J
╎   │   │       │   │   │   │   │       ├─╼ V ╾ k_1
╎   │   │       │   │   │   │   │       ├─╼ W ╾ k_1
╎   │   │       │   │   │   │   │       │   ├─╼ t1 ╾ J, A
╎   │   │       │   │   │   │   │       │   │   ├─╼ q ╾ J, A
╎   │   │       │   │   │   │   │       │   │   ├─╼ r ╾ A, W
╎   │   │       │   │   │   │   │       │   │   └─╼ s ╾ W, J
╎   │   │       │   │   │   │   │       │   └─╼  ...
╎   │   │       │   │   │   │   │       └─╼ T ╾ h_1
╎   │   │       │   │   │   │   │           └─╼ p ╾ A, J
╎   │   │       │   │   │   │   └─╼ N ╾ d_1
╎   │   │       │   │   │   ├─╼ f_1 ╾ k
╎   │   │       │   │   │   │   ├─╼ K ╾ f
╎   │   │       │   │   │   │   │   └─╼ d_1 ╾ L
╎   │   │       │   │   │   │   │       └─╼  ...
╎   │   │       │   │   │   │   └─╼ L ╾ k
╎   │   │       │   │   │   │       └─╼  ...
╎   │   │       │   │   │   ├─╼ S ╾ A
╎   │   │       │   │   │   │   └─╼ k_1 ╾ A
╎   │   │       │   │   │   │       ├─╼ U ╾ h_1
╎   │   │       │   │   │   │       └─╼  ...
╎   │   │       │   │   │   ├─╼ c_1 ╾ A
╎   │   │       │   │   │   │   ├─╼ Q ╾ m
╎   │   │       │   │   │   │   └─╼ R ╾ m
╎   │   │       │   │   │   │       ├─╼ t2 ╾ J, G
╎   │   │       │   │   │   │       │   ├─╼ t ╾ J, G
╎   │   │       │   │   │   │       │   ├─╼ a ╾ G, R
╎   │   │       │   │   │   │       │   └─╼ b ╾ R, J
╎   │   │       │   │   │   │       └─╼  ...
╎   │   │       │   │   │   ├─╼ e ╾ F
╎   │   │       │   │   │   ├─╼ i_1 ╾ g
╎   │   │       │   │   │   └─╼  ...
╎   │   │       │   │   └─╼  ...
╎   │   │       │   └─╼  ...
╎   │   │       ├─╼ Z ╾ D
╎   │   │       │   └─╼ p_1 ╾ D
╎   │   │       └─╼  ...
╎   │   ├─╼ j ╾ g
╎   │   │   └─╼ D ╾ k
╎   │   │       ├─╼ l ╾ g
╎   │   │       │   └─╼ F ╾ g
╎   │   │       │       ├─╼ c ╾ D
╎   │   │       │       └─╼  ...
╎   │   │       └─╼  ...
╎   │   └─╼  ...
╎   ├─╼ g ╾ C
╎   │   └─╼  ...
╎   └─╼  ...
╟── B
╎   └─╼  ...
╟── C
╎   ├─╼ k ╾ H
╎   │   └─╼  ...
╎   └─╼  ...
╟── H
╎   └─╼  ...
╙── h_1
    └─╼  ...

In [56]:
g2 = p.parse_subgraph_legacy()
nx.write_network_text(g2)

╟── H
╎   └─╼ k ╾ C
╟── C
╎   ├─╼ g ╾ A
╎   │   ├─╼ h ╾ f
╎   │   │   └─╼ E
╎   │   │       └─╼ m
╎   │   │           └─╼ G
╎   │   │               └─╼ J ╾ F
╎   │   │                   ├─╼ f_1
╎   │   │                   │   ├─╼ K
╎   │   │                   │   │   └─╼ d_1 ╾ L
╎   │   │                   │   │       └─╼ M
╎   │   │                   │   │           └─╼ e_1
╎   │   │                   │   │               └─╼ W
╎   │   │                   │   └─╼ L
╎   │   │                   │       └─╼  ...
╎   │   │                   ├─╼ S
╎   │   │                   │   └─╼ k_1
╎   │   │                   ├─╼ c_1
╎   │   │                   │   └─╼ R
╎   │   │                   └─╼ g_1
╎   │   └─╼ j ╾ f
╎   │       └─╼ D
╎   │           └─╼ l
╎   │               └─╼ F
╎   │                   └─╼  ...
╎   └─╼  ...
╟── A
╎   ├─╼ f ╾ B
╎   │   └─╼  ...
╎   └─╼  ...
╙── B
    └─╼  ...

In [41]:
nx.descendants(g1, 'L')

{'M', 'N', 'T', 'V', 'W', 'd_1', 'e_1', 'q', 'r', 's', 't1'}

In [42]:
p.df

shape: (50, 11)
┌──────────┬──────┬──────────┬──────────────┬───┬────────────┬───────────┬───────────┬─────────────┐
│ Sequence ┆ Name ┆ Type     ┆ Command      ┆ … ┆ ShowObject ┆ ShowLabel ┆ Auxiliary ┆ DependsOn   │
│ ---      ┆ ---  ┆ ---      ┆ ---          ┆   ┆ ---        ┆ ---       ┆ ---       ┆ ---         │
│ u32      ┆ str  ┆ str      ┆ str          ┆   ┆ bool       ┆ bool      ┆ bool      ┆ list[str]   │
╞══════════╪══════╪══════════╪══════════════╪═══╪════════════╪═══════════╪═══════════╪═════════════╡
│ 0        ┆ n    ┆ numeric  ┆ null         ┆ … ┆ true       ┆ true      ┆ false     ┆ []          │
│ 1        ┆ i    ┆ numeric  ┆ null         ┆ … ┆ true       ┆ true      ┆ false     ┆ []          │
│ 2        ┆ A    ┆ point    ┆ null         ┆ … ┆ true       ┆ true      ┆ false     ┆ []          │
│ 3        ┆ B    ┆ point    ┆ null         ┆ … ┆ true       ┆ true      ┆ false     ┆ []          │
│ 4        ┆ C    ┆ point    ┆ null         ┆ … ┆ true       ┆ true      ┆ false     ┆ []          │
│ 5        ┆ f    ┆ line     ┆ Line(A, B)   ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B"]  │
│ 6        ┆ g    ┆ line     ┆ Line(A, C)   ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "C"]  │
│ 7        ┆ h    ┆ line     ┆ AngleBisecto ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆      ┆          ┆ r(f, g)      ┆   ┆            ┆           ┆           ┆ … "g"]      │
│ 8        ┆ j    ┆ line     ┆ AngleBisecto ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆      ┆          ┆ r(f, g)      ┆   ┆            ┆           ┆           ┆ … "g"]      │
│ 9        ┆ H    ┆ point    ┆ null         ┆ … ┆ true       ┆ true      ┆ false     ┆ []          │
│ 10       ┆ k    ┆ line     ┆ Line(C, H)   ┆ … ┆ true       ┆ false     ┆ false     ┆ ["C", "H"]  │
│ 11       ┆ D    ┆ point    ┆ Intersect(k, ┆ … ┆ true       ┆ true      ┆ false     ┆ ["A", "B",  │
│          ┆      ┆          ┆ j)           ┆   ┆            ┆           ┆           ┆ … "k"]      │
│ 12       ┆ E    ┆ point    ┆ Intersect(k, ┆ … ┆ true       ┆ true      ┆ false     ┆ ["A", "B",  │
│          ┆      ┆          ┆ h)           ┆   ┆            ┆           ┆           ┆ … "k"]      │
│ 13       ┆ l    ┆ line     ┆ Perpendicula ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆      ┆          ┆ rLine(D, g)  ┆   ┆            ┆           ┆           ┆ … "k"]      │
│ 14       ┆ m    ┆ line     ┆ Perpendicula ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆      ┆          ┆ rLine(E, g)  ┆   ┆            ┆           ┆           ┆ … "k"]      │
│ 15       ┆ F    ┆ point    ┆ Intersect(l, ┆ … ┆ true       ┆ true      ┆ false     ┆ ["A", "B",  │
│          ┆      ┆          ┆ g)           ┆   ┆            ┆           ┆           ┆ … "l"]      │
│ 16       ┆ G    ┆ point    ┆ Intersect(m, ┆ … ┆ true       ┆ true      ┆ false     ┆ ["A", "B",  │
│          ┆      ┆          ┆ g)           ┆   ┆            ┆           ┆           ┆ … "m"]      │
│ 17       ┆ c    ┆ circle   ┆ Circle(D, F) ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆      ┆          ┆              ┆   ┆            ┆           ┆           ┆ … "l"]      │
│ 18       ┆ d    ┆ circle   ┆ Circle(E, G) ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆      ┆          ┆              ┆   ┆            ┆           ┆           ┆ … "m"]      │
│ 19       ┆ J    ┆ point    ┆ Midpoint(F,  ┆ … ┆ true       ┆ true      ┆ false     ┆ ["A", "B",  │
│          ┆      ┆          ┆ G)           ┆   ┆            ┆           ┆           ┆ … "m"]      │
│ 20       ┆ g_1  ┆ line     ┆ Line(J, k)   ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆      ┆          ┆              ┆   ┆            ┆           ┆           ┆ … "m"]      │
│ 21       ┆ f_1  ┆ line     ┆ Perpendicula ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆      ┆          ┆ rLine(J, k)  ┆   ┆            ┆           ┆           ┆ … "m"]      │
│ 22       ┆ K    ┆ point    ┆ Intersect(f, ┆ … ┆ true       ┆ true      ┆ false     ┆ ["A", "B",  │
│          ┆      ┆          ┆ f_1)         ┆   ┆            ┆           ┆           ┆ … "m"]      │
│ 23       ┆ L    ┆ point    ┆ Intersect(k, ┆ … ┆ true       ┆ true      ┆ false     ┆ ["A", "B",  │
│          ┆      ┆          ┆ f_1)         ┆   ┆            ┆           ┆           ┆ … "m"]      │
│ 24       ┆ d_1  ┆ circle   ┆ Circle(L, K) ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆      ┆          ┆              ┆   ┆            ┆           ┆           ┆ … "m"]      │
│ 25       ┆ M    ┆ point    ┆ Intersect(d_ ┆ … ┆ true       ┆ true      ┆ false     ┆ ["A", "B",  │
│          ┆      ┆          ┆ 1, g_1)      ┆   ┆            ┆           ┆           ┆ … "m"]      │
│ 26       ┆ N    ┆ point    ┆ Intersect(d_ ┆ … ┆ true       ┆ true      ┆ false     ┆ ["A", "B",  │
│          ┆      ┆          ┆ 1, g_1)      ┆   ┆            ┆           ┆           ┆ … "m"]      │
│ 27       ┆ e_1  ┆ circle   ┆ Circle(J, M) ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆      ┆          ┆              ┆   ┆            ┆           ┆           ┆ … "m"]      │
│ 28       ┆ S    ┆ point    ┆ Midpoint(A,  ┆ … ┆ false      ┆ true      ┆ false     ┆ ["A", "B",  │
│          ┆      ┆          ┆ J)           ┆   ┆            ┆           ┆           ┆ … "m"]      │
│ 29       ┆ k_1  ┆ circle   ┆ Circle(S, A) ┆ … ┆ false      ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆      ┆          ┆              ┆   ┆            ┆           ┆           ┆ … "m"]      │
│ 30       ┆ V    ┆ point    ┆ Intersect(e_ ┆ … ┆ false      ┆ true      ┆ false     ┆ ["A", "B",  │
│          ┆      ┆          ┆ 1, k_1)      ┆   ┆            ┆           ┆           ┆ … "m"]      │
│ 31       ┆ W    ┆ point    ┆ Intersect(e_ ┆ … ┆ false      ┆ true      ┆ false     ┆ ["A", "B",  │
│          ┆      ┆          ┆ 1, k_1)      ┆   ┆            ┆           ┆           ┆ … "m"]      │
│ 32       ┆ t1   ┆ triangle ┆ Polygon(J,   ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆      ┆          ┆ A, W)        ┆   ┆            ┆           ┆           ┆ … "m"]      │
│ 33       ┆ q    ┆ segment  ┆ Segment(J,   ┆ … ┆ true       ┆ false     ┆ true      ┆ ["A", "B",  │
│          ┆      ┆          ┆ A, t1)       ┆   ┆            ┆           ┆           ┆ … "t1"]     │
│ 34       ┆ r    ┆ segment  ┆ Segment(A,   ┆ … ┆ true       ┆ false     ┆ true      ┆ ["A", "B",  │
│          ┆      ┆          ┆ W, t1)       ┆   ┆            ┆           ┆           ┆ … "t1"]     │
│ 35       ┆ s    ┆ segment  ┆ Segment(W,   ┆ … ┆ true       ┆ false     ┆ true      ┆ ["A", "B",  │
│          ┆      ┆          ┆ J, t1)       ┆   ┆            ┆           ┆           ┆ … "t1"]     │
│ 36       ┆ c_1  ┆ circle   ┆ Circle(J, A) ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆      ┆          ┆              ┆   ┆            ┆           ┆           ┆ … "m"]      │
│ 37       ┆ Q    ┆ point    ┆ Intersect(c_ ┆ … ┆ false      ┆ true      ┆ false     ┆ ["A", "B",  │
│          ┆      ┆          ┆ 1, m)        ┆   ┆            ┆           ┆           ┆ … "m"]      │
│ 38       ┆ R    ┆ point    ┆ Intersect(c_ ┆ … ┆ false      ┆ true      ┆ false     ┆ ["A", "B",  │
│          ┆      ┆          ┆ 1, m)        ┆   ┆            ┆           ┆           ┆ … "m"]      │
│ 39       ┆ t2   ┆ triangle ┆ Polygon(J,   ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆      ┆          ┆ G, R)        ┆   ┆            ┆           ┆           ┆ … "m"]      │
│ 40       ┆ t    ┆ segment  ┆ Segment(J,   ┆ … ┆ true       ┆ false     ┆ true      ┆ ["A", "B",  │
│          ┆      ┆          ┆ G, t2)       ┆   ┆            ┆           ┆           ┆ … "t2"]     │
│ 41       ┆ a    ┆ segment  ┆ Segment(G,   ┆ … ┆ true       ┆ false     ┆ true      ┆ ["A", "B",  │
│          ┆      ┆          ┆ R, t2)       ┆   ┆            ┆           ┆           ┆ … "t2"]     │
│ 42       ┆ b    ┆ segment  ┆ Segment(R,   ┆ … ┆ true       ┆ false     ┆ true      ┆ ["A", "B",  │
│          ┆      ┆          ┆ J, t2)       ┆   ┆            ┆           ┆           ┆ … "t2"]     │
│ 43       ┆ e    ┆ circle   ┆ Circle(J, F) ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆      ┆          ┆              ┆   ┆            ┆           ┆           ┆ … "m"]      │
│ 44       ┆ h_1  ┆ ellipse  ┆ Ellipse(F,   ┆ … ┆ true       ┆ false     ┆ false     ┆ []          │
│          ┆      ┆          ┆ G, A)        ┆   ┆            ┆           ┆           ┆             │
│ 45       ┆ i_1  ┆ line     ┆ Perpendicula ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆      ┆          ┆ rLine(J, g)  ┆   ┆            ┆           ┆           ┆ … "m"]      │
│ 46       ┆ T    ┆ point    ┆ Intersect(e_ ┆ … ┆ true       ┆ true      ┆ false     ┆ ["A", "B",  │
│          ┆      ┆          ┆ 1, h_1, 3)   ┆   ┆            ┆           ┆           ┆ … "m"]      │
│ 47       ┆ U    ┆ point    ┆ Intersect(k_ ┆ … ┆ false      ┆ true      ┆ false     ┆ ["A", "B",  │
│          ┆      ┆          ┆ 1, h_1, 1)   ┆   ┆            ┆           ┆           ┆ … "m"]      │
│ 48       ┆ Z    ┆ point    ┆ Midpoint(D,  ┆ … ┆ true       ┆ true      ┆ false     ┆ ["A", "B",  │
│          ┆      ┆          ┆ E)           ┆   ┆            ┆           ┆           ┆ … "k"]      │
│ 49       ┆ p_1  ┆ circle   ┆ Circle(Z, D) ┆ … ┆ true       ┆ false     ┆ false     ┆ ["A", "B",  │
│          ┆      ┆          ┆              ┆   ┆            ┆           ┆           ┆ … "k"]      │
└──────────┴──────┴──────────┴──────────────┴───┴────────────┴───────────┴───────────┴─────────────┘

In [12]:
l1 = 'n'
l2 = 'i'

In [13]:
await ggb.listen(l1, True)
await ggb.listen(l2, True)

{}

In [141]:
await ggb.listen('a', False)
await ggb.listen('b', False)

{}

In [14]:
ggb.comm.shared_objects

{'n': 'n = 0', 'i': 'i = 0'}

In [15]:
# import ipywidgets as widgets
# label1 = widgets.Label(value=ggb.comm.shared_objects['n'])
# label2 = widgets.Label(value=ggb.comm.shared_objects['m'])
# display(label1, label2)

In [16]:
async def on_shared_update1(changes):
    # await asyncio.sleep(0)
    # label1.value = changes['a']
    n = int(changes[l1].split()[2])
    # await asyncio.sleep(0)
    await ggb.function("setLayerVisible", list(zip_longest(range(9), [True]*n, fillvalue=False)))
    r = await ggb.function('getXML', [l2])
    o = ggb.file.ggb_schema.decode(r)
    o['value'][0]['@val'] = '0'
    x = xmlschema.etree_tostring(ggb.file.ggb_schema.encode(o, 'element'))
    r = await ggb.function('evalXML' , [x])

In [17]:
ggb.comm.remove_shared_listener(on_shared_update1)
ggb.comm.add_shared_listener(on_shared_update1)

True

In [18]:
async def on_shared_update2(changes):
    # await asyncio.sleep(0)
    # label2.value = changes['b']
    m = int(changes[l2].split()[2])
    n = int(ggb.comm.shared_objects[l1].split()[2])
    l = df.filter(pl.col("Layer") == n)["Name"].to_list()
    # m = int(ggb.comm.shared_objects['m'].split()[2])
    # list(zip_longest(l, [True]*m, fillvalue=False))
    await ggb.function("setVisible", list(zip_longest(l, [True]*m, fillvalue=False)))

In [19]:
ggb.comm.remove_shared_listener(on_shared_update2)
ggb.comm.add_shared_listener(on_shared_update2)

True

In [104]:
ggb.comm.clear_shared_listeners()

2

In [103]:
await ggb.function("getVersion")

'5.2.909.9'

In [48]:
await ggb.command("Circle[T,Distance[A,J]]")

'p'

In [17]:
await ggb.command("t1 = Polygon(J, A, W)")

't1,q,r,s'

In [44]:
%pwd

'/Users/manabu/work/ggblab/examples'

In [13]:
# ggb.file.source_file = 'eg10_slider3.ggb'

In [57]:
ggb.file.base64_buffer = await ggb.function("getBase64")

In [58]:
ggb.file.save(overwrite=True)

* 原則（教育観）:
    - 目的化: 再現は「結果」ではなく「理解（なぜその操作か）」を目的にする。
    - 予測→検証: 次に何が起きるか予測させてから操作させる。
    - 説明要求: 手順ごとに短い理由説明（1文）を書かせる。
    - 変奏課題: パラメータを少し変えた課題で本質が移るか確認する。
    - 生成的課題: 「同じ発想で別の図形を作る」など転移を問う。
* ggblabで実装できる仕組み（短）:
    - 段階公開（layer slider）: 各レイヤーに「解説」「問い」「期待する操作」を紐付け、スライダーで段階的に提示。
    - 予測プロンプト: 各ステップの前に「次に何が起きる？」を表示し、回答を記録。
    - 説明入力欄: 学生が操作毎に短い説明を入力 → 教師や自動ルールでフィードバック。
    - 変化タスク自動化: DataFrame→コマンド生成を利用してパラメータをランダム化した派生課題を作る。
    - 操作ログ＋解析: 操作順・所要時間・試行回数をログ化して学習診断に使う。
    - 差分フィードバック: 学生構成と模範構成を比較して「次に直すべき一手」を提示。

In [29]:
await ggb.function("getVersion")

'5.2.909.9'