# example of worksheet

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import xml.etree.ElementTree as ET
import xmlschema
import polars as pl
import networkx as nx
from itertools import zip_longest

In [3]:
import ggblab

In [4]:
# # open GeoGebra Widget on left-side
# from ggblab import GeoGebra
# ggb = await GeoGebra().init()

In [5]:
%ggblab api getVersion()

[ggblab] created GeoGebra singleton and stored as 'ggb' in user namespace

'5.2.909.9'

In [94]:
# ggb.file.load('2025_02_03_1.ggb')
# await ggb.function("setBase64", [ggb.construction.base64_buffer.decode('utf-8')])

## composition of primitives

switch calculator to `3d`

In [20]:
%ggb api newConstruction()

In [21]:
ls = {i: set() for i in range(10)}
ls

{0: set(),
 1: set(),
 2: set(),
 3: set(),
 4: set(),
 5: set(),
 6: set(),
 7: set(),
 8: set(),
 9: set()}

### cylinder

In [22]:
%%ggblab
C_{t} = Point(zAxis)
C_{b} = Point(zAxis)
SetCoords(C_{t}, 0, 0, 3)
SetCoords(C_{b}, 0, 0, -3)
Cylinder(_1, _2, 1)

['C_{t}', 'C_{b}', 'a', 'c', 'd', 'b']

In [23]:
ls[0] |= set(_)

In [24]:
i = 0
r = await ggb.function("setLayer", list(zip_longest(ls[i], [], fillvalue=i)))

### control points `Q` and `P`

In [25]:
%%ggblab
O = Intersect(yAxis, xAxis)
e = Circle(yAxis, C_{t})
Q = Point(_)
p = Plane(_, yAxis)
f = IntersectPath(_, a)
P = Point(_)

['O', 'e', 'Q', 'p', 'f', 'P']

In [26]:
ls[9] |= set(_)

In [27]:
i = 9
r = await ggb.function("setLayer", list(zip_longest(ls[i], [], fillvalue=i)))

In [99]:
# %%ggblab
# axis_{z} = Line(C_{t}, C_{b})
# axis_y = Line(O, yAxis)
# axis_x = Line(O, xAxis)

### horizontal

In [28]:
%%ggblab
p_{xy} = Plane(xAxis, yAxis)
k = IntersectPath(_, a)
# k = IntersectPath(xOyPlane, a)
l_1 = Line(P, zAxis)
P_{c} = Intersect(_, __)
h_2 = PerpendicularLine(P_{c}, yAxis)
h_1 = PerpendicularLine(P, yAxis, space)
P_{h} = Intersect(h_1, h_2)
h_3 = PerpendicularLine(P_{c}, xAxis)
P_{w} = Intersect(h_3, xAxis)
# #
i_2 = Segment(O, P_{c})
s_{cw} = Segment(P_{c}, P_{w})
s_{ch} = Segment(P_{c}, P_{h})

['p_{xy}',
 'k',
 'l_1',
 'P_{c}',
 'undefined',
 'h_2',
 'h_1',
 'P_{h}',
 'h_3',
 'P_{w}',
 'i_2',
 's_{cw}',
 's_{ch}']

In [29]:
ls[1] |= set(_)

In [30]:
i = 1
r = await ggb.function("setLayer", list(zip_longest(ls[i], [], fillvalue=i)))

In [31]:
%%ggb
l2 = {Intersect(xAxis, b)}
C' = l2(1)
A' = l2(2)

['l2', "C'", "A'"]

In [32]:
ls[2] |= set(_)

In [33]:
i = 2
r = await ggb.function("setLayer", list(zip_longest(ls[i], [], fillvalue=i)))

### ellipse

In [34]:
%%ggb
xzPlane = Plane(xAxis, zAxis)
l1 = {Intersect(_1, f)}
A = l1(1)
C = l1(2)
l3 = {Intersect(yAxis, f)}
B = l3(1)
D = l3(2)
a_1 = Line(O, Q)
c_1 = Circle(yAxis, A)

['xzPlane', 'l1', 'A', 'C', 'l3', 'B', 'D', 'a_1', 'c_1']

In [35]:
ls[2] |= set(_)

In [36]:
i = 2
r = await ggb.function("setLayer", list(zip_longest(ls[i], [], fillvalue=i)))

In [37]:
%%ggb
# Line(A, zAxis)
# Line(C, zAxis)
# {AngleBisector(a_1, _1)}
# Element(_3, 1)
# Element(_3, 2)
# {AngleBisector(a_1, _2)}
# Element(_6, 1)
# Element(_6, 2)
l_{10} = Line(A, zAxis)
l_{11} = Line(C, zAxis)
l10 = {AngleBisector(a_1, _1)}
l_{12} = Element(_3, 1)
l_{13} = Element(_3, 2)
l11 = {AngleBisector(a_1, _2)}
l_{14} = Element(_6, 1)
l_{15} = Element(_6, 2)

['l_{10}', 'l_{11}', 'l10', 'l_{12}', 'l_{13}', 'l11', 'l_{14}', 'l_{15}']

In [38]:
ls[3] |= set(_)

In [39]:
%%ggblab
# l4 = {Intersect(zAxis, c_1)}
# O'' = l4(1)
# O''' = l4(2)
O'' = Intersect(l_{13}, l_{14})
O''' = Intersect(l_{12}, l_{15})

["O''", "O'''"]

In [40]:
ls[3] |= set(_)

In [41]:
i = 3
r = await ggb.function("setLayer", list(zip_longest(ls[i], [], fillvalue=i)))

In [42]:
%%ggb 
f_2 = PerpendicularLine(O'', p)
f_1 = PerpendicularLine(O''', p)
F_2 = Intersect(f_2, p)
F_1 = Intersect(f_1, p)

['f_2', 'f_1', 'F_2', 'F_1']

In [43]:
ls[4] |= set(_)

In [44]:
%%ggb
g = Segment(O, A)
i = Segment(O, A')
j = Segment(B, O)
# s = Segment(P, P_{c})
h = Segment(A', A)
# r = Segment(P, P_{h})
# g_2 = Segment(O, P)
i_1 = Segment(O'', O)
j_1 = Segment(O'', F_2)
k_1 = Segment(F_2, O)

['g', 'i', 'j', 'h', 'i_1', 'j_1', 'k_1']

In [45]:
ls[4] |= set(_)

In [46]:
i = 4
r = await ggb.function("setLayer", list(zip_longest(ls[i], [], fillvalue=i)))

In [97]:
%%ggb
l_3 = Line(O, f_1)
c_4 = Circle(_1, B)
c_5 = Circle(_1, A)
c_6 = Circle(_1, F_1)

['l_3', 'c_4', 'c_5', 'c_6']

In [48]:
ls[5] |= set(_)

In [49]:
i = 5
r = await ggb.function("setLayer", list(zip_longest(ls[i], [], fillvalue=i)))

### post analysis

In [50]:
%%ggb
g_1 = Segment(B, F_1)
r_1 = Segment(O, F_1)
b_1 = Segment(B, F_2)

['g_1', 'r_1', 'b_1']

In [51]:
ls[6] |= set(_)

In [52]:
%%ggb
o = Sphere(O'', F_2)
u_{1} = Sphere(O''', F_1)
p_1 = Plane(O'', xOyPlane)
q_1 = Plane(O''', xOyPlane)
d_1 = IntersectPath(p_1, a)
e_1 = IntersectPath(q_1, a)
l7 = {Intersect(l_1, d_1)}
l8 = {Intersect(l_1, e_1)}
P'' = l7(1)
P''' = l8(1)
l = Segment(P'', P)
m = Segment(P, P''')

['o', 'u_{1}', 'p_1', 'q_1', 'd_1', 'e_1', 'l7', 'l8', "P''", "P'''", 'l', 'm']

In [53]:
ls[6] |= set(_)

In [54]:
%%ggb
n_2 = Segment(P, F_2)
n_1 = Segment(P, F_1)
u = Vector(P_{h}, P)
v = Vector(P_{h}, P_{c})
n = Translate(Vector((((u * v)) / ((v * v)) * v)), P_{h})
t = Line(O, P_{w})
t_1 = Segment(O, P_{h})
j_2 = Segment(P_{h}, P_{c})
l9 = {Intersect(yAxis, k)}
E = l9(1)
F = l9(2)
s_1 = Segment(E, F)

['n_2', 'n_1', 'u', 'v', 'n', 't', 't_1', 'j_2', 'l9', 'E', 'F', 's_1']

In [55]:
ls[6] |= set(_)

In [56]:
i = 5
r = await ggb.function("setLayer", list(zip_longest(ls[i], [], fillvalue=i)))

### area

In [57]:
%%ggb
t1 = Polygon(O, P_{c}, P_{h})
# p_{h} = Segment(O, P_{c}, t1)
# o_1 = Segment(P_{c}, P_{h}, t1)
# p_{c} = Segment(P_{h}, O, t1)
t2 = Polygon(O, P, P_{h})
# k_2 = Segment(O, P, t2)
# o_2 = Segment(P, P_{h}, t2)
# p_2 = Segment(P_{h}, O, t2)

['t1', 'p_{h}', 'o_1', 'p_{c}', 't2', 'q', 'o_2', 'p_2']

## 3d on or not

In [58]:
from ggblab_extra import ConstructionIO
from ggblab_extra import ConstructionTreeParser

In [59]:
df = await ConstructionIO.initialize_dataframe(ggb, use_applet=True)
# df = pl.read_parquet('2025_02_03.parquet')

In [60]:
p = ConstructionTreeParser(df)
g1 = p.parse()

In [61]:
# lc = {}
# for i in range(10):
#     _df = df.filter(pl.col("Layer") == i)
#     ls[i] = set(_df["Name"].to_list())
#     lc[i] = ConstructionIO.commands_for_magic(_df, use_name_equals=True)

## on plane

In [62]:
from ggblab_extra.sympy_utils import Object3D
from ggblab_extra.sympy_utils import attach_object3d, enumerate_plane_members

In [63]:
from ggblab_extra.sympy_utils import point_on_plane, segment_on_plane, line_on_plane, circle_on_plane, point_from_value

In [64]:
for r in df.filter(pl.col("Type").is_in(["plane"]))["Name","Type","Command","Value"].iter_rows():
    print(r)
    print(Object3D.from_value_command(command=r[2], value=r[3]))

('p', 'plane', 'Plane(Q, yAxis)', 'p: 1.91x + 2.32z = 0')
Object3D(kind='plane', obj=Plane(Point3D(0, 0, 0), (191/100, 0, 58/25)), value='p: 1.91x + 2.32z = 0', command='Plane(Q, yAxis)')
('p_{xy}', 'plane', 'Plane(xAxis, yAxis)', 'p_{xy}: z = 0')
Object3D(kind='plane', obj=Plane(Point3D(0, 0, 0), (0, 0, 1)), value='p_{xy}: z = 0', command='Plane(xAxis, yAxis)')
('xzPlane', 'plane', 'Plane(xAxis, zAxis)', 'xzPlane: y = 0')
Object3D(kind='plane', obj=Plane(Point3D(0, 0, 0), (0, 1, 0)), value='xzPlane: y = 0', command='Plane(xAxis, zAxis)')
('p_1', 'plane', "Plane(O'', xOyPlane)", 'p_1: z = 1.29')
Object3D(kind='plane', obj=Plane(Point3D(0, 0, 129/100), (0, 0, 1)), value='p_1: z = 1.29', command="Plane(O'', xOyPlane)")
('q_1', 'plane', "Plane(O''', xOyPlane)", 'q_1: z = -1.29')
Object3D(kind='plane', obj=Plane(Point3D(0, 0, -129/100), (0, 0, 1)), value='q_1: z = -1.29', command="Plane(O''', xOyPlane)")

In [65]:
df2 = attach_object3d(df)

In [82]:
import pickle
df2_serialized = df2.with_columns(pl.col("object3d").map_elements(pickle.dumps, return_dtype=pl.Object))

In [83]:
df2_serialized["object3d"][0]

b'\x80\x05\x95\xd9\x00\x00\x00\x00\x00\x00\x00\x8c\x18ggblab_extra.sympy_utils\x94\x8c\x08Object3D\x94\x93\x94)\x81\x94}\x94(\x8c\x04kind\x94\x8c\x05point\x94\x8c\x03obj\x94\x8c\x14sympy.geometry.point\x94\x8c\x07Point3D\x94\x93\x94\x8c\x12sympy.core.numbers\x94\x8c\x04Zero\x94\x93\x94)\x81\x94h\x0eh\x0b\x8c\x07Integer\x94\x93\x94K\x03\x85\x94\x81\x94\x87\x94\x81\x94\x8c\x05value\x94\x8c\x11C_{t} = (0, 0, 3)\x94\x8c\x07command\x94\x8c\x0cPoint(zAxis)\x94ub.'

In [85]:
df2_serialized.with_columns(pl.col("object3d").map_elements(pickle.loads, return_dtype=pl.Object))["object3d"]

shape: (96,)
Series: 'object3d' [o][object]
[
	Object3D(kind='point', obj=Point3D(0, 0, 3), value='C_{t} = (0, 0, 3)', command='Point(zAxis)')
	Object3D(kind='point', obj=Point3D(0, 0, -3), value='C_{b} = (0, 0, -3)', command='Point(zAxis)')
	Object3D(kind='expr', obj=18.8500000000000, value='a: 18.85', command='Cylinder(C_{t}, C_{b}, 1)')
	Object3D(kind='expr', obj=37.7000000000000, value='b: 37.7', command='Cylinder(C_{t}, C_{b}, 1)')
	Object3D(kind='circle', obj=Circle3D(center=Point3D(0, 0, 3), radius=1, normal=(0, 0, 1)), value='c: X = (0, 0, 3) + (cos(t), sin(t), 0)', command='Cylinder(C_{t}, C_{b}, 1)')
	Object3D(kind='circle', obj=Circle3D(center=Point3D(0, 0, -3), radius=1, normal=(0, 0, -1)), value='d: X = (0, 0, -3) + (cos(t), - sin(t), 0)', command='Cylinder(C_{t}, C_{b}, 1)')
	Object3D(kind='point', obj=Point3D(0, 0, 0), value='O = (0, 0)', command='Intersect(yAxis, xAxis)')
	Object3D(kind='circle', obj=Circle3D(center=Point3D(0, 0, 0), radius=3, normal=(0, 9, 0)), value='e: X = (0, 0, 0) + (3 sin(t), 0, 3 cos(t))', command='Circle(yAxis, C_{t})')
	Object3D(kind='point', obj=Point3D(-58/25, 0, 191/100), value='Q = (-2.32, 0, 1.91)', command='Point(e)')
	Object3D(kind='plane', obj=Plane(Point3D(0, 0, 0), (191/100, 0, 58/25)), value='p: 1.91x + 2.32z = 0', command='Plane(Q, yAxis)')
]

In [66]:
df3 = enumerate_plane_members(df2).filter(pl.col("Type") == "plane")

In [67]:
for r in df3.iter_rows():
    print(r[10])

Object3D(kind='plane', obj=Plane(Point3D(0, 0, 0), (191/100, 0, 58/25)), value='p: 1.91x + 2.32z = 0', command='Plane(Q, yAxis)')
Object3D(kind='plane', obj=Plane(Point3D(0, 0, 0), (0, 0, 1)), value='p_{xy}: z = 0', command='Plane(xAxis, yAxis)')
Object3D(kind='plane', obj=Plane(Point3D(0, 0, 0), (0, 1, 0)), value='xzPlane: y = 0', command='Plane(xAxis, zAxis)')
Object3D(kind='plane', obj=Plane(Point3D(0, 0, 129/100), (0, 0, 1)), value='p_1: z = 1.29', command="Plane(O'', xOyPlane)")
Object3D(kind='plane', obj=Plane(Point3D(0, 0, -129/100), (0, 0, 1)), value='q_1: z = -1.29', command="Plane(O''', xOyPlane)")

In [72]:
df3[0]["object3d"]

shape: (1,)
Series: 'object3d' [o][object]
[
	Object3D(kind='plane', obj=Plane(Point3D(0, 0, 0), (191/100, 0, 58/25)), value='p: 1.91x + 2.32z = 0', command='Plane(Q, yAxis)')
]

In [90]:
for r in df3.iter_rows():
    print(r[11])

['O', 'Q', 'f', 'P', 'h_1', 'P_{h}', 'l1', 'A', 'C', 'l3', 'B', 'D', 'a_1', 'F_2', 'F_1', 'g', 'j', 'k_1', 'c_4', 'c_5', 'c_6', 'g_1', 'r_1', 'b_1', 'n_2', 'n_1', 'u', 't_1', 'l9', 'E', 'F', 's_1', 'p_{c}', 'q', 'o_2', 'p_2']
['O', 'k', 'P_{c}', 'h_2', 'P_{h}', 'h_3', 'P_{w}', 'i_2', 's_{cw}', 's_{ch}', 'l2', "C'", "A'", 'l3', 'B', 'D', 'i', 'j', 'v', 'n', 't', 't_1', 'j_2', 'l9', 'E', 'F', 's_1', 'p_{h}', 'o_1', 'p_{c}', 'p_2']
['C_{t}', 'C_{b}', 'O', 'e', 'Q', 'P_{w}', 'l2', "C'", "A'", 'l1', 'A', 'C', 'a_1', 'c_1', 'l_{10}', 'l_{11}', 'l10', 'l_{12}', 'l_{13}', 'l11', 'l_{14}', 'l_{15}', "O''", "O'''", 'f_2', 'f_1', 'F_2', 'F_1', 'g', 'i', 'h', 'i_1', 'j_1', 'k_1', 'l_3', 'r_1', 'u', 'v', 'n', 't']
["O''", 'd_1', 'l7', "P''"]
["O'''", 'e_1', 'l8', "P'''"]

In [143]:
# set(df3[0]['plane_members'].item()) & set(df3[]['plane_members'].item())

In [95]:
r = await ggb.function('setLayerVisible', list(zip_longest(range(10), [], fillvalue=False)))

In [96]:
r = await ggb.function('setVisible', list(zip_longest(df3[0]['plane_members'].item(), [], fillvalue=True)))

## attributs

In [86]:
c = ggb.file.load('2025_02_03.ggb')

In [87]:
o = c.ggb_schema.decode(c.geogebra_xml)

In [88]:
r = await ggb.function("getAllObjectNames")
for _n in r:# set(r) - {'xOyPlane', 'l7', 'l8', 'l9', 'l3', 'l2', 'l1', 'l0', 'l6', 'l4', 'l5'}:
    # print(_n)
    try:
        _i = [e['@label'] for e in o['element']].index(_n)
        _e = o['element'][_i]
        for _k in ['animation', 'pointSize', 'pointStyle', 'coords', 'eigenvectors', 'eqnStyle', 'matrix', 'show']:
            _e.pop(_k, None)
        _x = xmlschema.etree_tostring(c.ggb_schema.encode(_e, 'element'))
        # print(_x)
        await ggb.function("evalXML", [_x])
    except ValueError as e:
        print(e)
        pass

list.index(x): x not in list
list.index(x): x not in list
list.index(x): x not in list
list.index(x): x not in list
list.index(x): x not in list
list.index(x): x not in list
list.index(x): x not in list
list.index(x): x not in list
list.index(x): x not in list
list.index(x): x not in list
list.index(x): x not in list
list.index(x): x not in list
list.index(x): x not in list
list.index(x): x not in list
list.index(x): x not in list
list.index(x): x not in list
list.index(x): x not in list
list.index(x): x not in list
list.index(x): x not in list

In [98]:
ggb.file.source_file = '2025_02_03_1.ggb'

In [99]:
ggb.file.save(overwrite=True)