# Parsing GeoGebra Construction Protocolto Polars DataFrame

In [ ]:
# this magic for develop only
%load_ext autoreload
%autoreload 2

In [1]:
from ggblab import GeoGebra

In [2]:
# initialize base class, not open GeoGebra Widget
ggb = GeoGebra()

Using local cached file: xsd/common.xsd

In [3]:
from ggblab_extra.construction_io import ConstructionIO

In [4]:
await ggb.init()

In [5]:
c = ggb.file.load('2025_13_01.ggb')

In [6]:
r = await ggb.function("setBase64", [ggb.construction.base64_buffer.decode('utf-8')])

In [7]:
# df1 from a file df2 from a applet
df1 = await ConstructionIO.initialize_dataframe(ggb, file='2025_13_01.ggb')
df2 = await ConstructionIO.initialize_dataframe(ggb, use_applet=True)

In [8]:
df1

shape: (170, 9)
┌───────────┬─────────┬─────────────┬─────────────┬───┬───────┬────────────┬───────────┬───────────┐
│ Name      ┆ Type    ┆ Command     ┆ Value       ┆ … ┆ Layer ┆ ShowObject ┆ ShowLabel ┆ Auxiliary │
│ ---       ┆ ---     ┆ ---         ┆ ---         ┆   ┆ ---   ┆ ---        ┆ ---       ┆ ---       │
│ str       ┆ str     ┆ str         ┆ str         ┆   ┆ i64   ┆ bool       ┆ bool      ┆ bool      │
╞═══════════╪═════════╪═════════════╪═════════════╪═══╪═══════╪════════════╪═══════════╪═══════════╡
│ C         ┆ point   ┆ null        ┆ null        ┆ … ┆ 9     ┆ true       ┆ true      ┆ false     │
│ A         ┆ point   ┆ null        ┆ null        ┆ … ┆ 9     ┆ true       ┆ true      ┆ false     │
│ poly1     ┆ polygon ┆ Polygon(C,  ┆ null        ┆ … ┆ 3     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ A, 4)       ┆             ┆   ┆       ┆            ┆           ┆           │
│ f         ┆ segment ┆ Segment(C,  ┆ null        ┆ … ┆ 2     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ A, poly1)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ g         ┆ segment ┆ Segment(A,  ┆ null        ┆ … ┆ 2     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ E, poly1)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ …         ┆ …       ┆ …           ┆ …           ┆ … ┆ …     ┆ …          ┆ …         ┆ …         │
│ b_3       ┆ segment ┆ Segment(P,  ┆ null        ┆ … ┆ 2     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ B_1, t8)    ┆             ┆   ┆       ┆            ┆           ┆           │
│ p_6       ┆ segment ┆ Segment(B_1 ┆ null        ┆ … ┆ 2     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ , A_1, t8)  ┆             ┆   ┆       ┆            ┆           ┆           │
│ e_3       ┆ segment ┆ Segment(A_1 ┆ null        ┆ … ┆ 2     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ , P, t8)    ┆             ┆   ┆       ┆            ┆           ┆           │
│ text5_{3} ┆ text    ┆ "$proj_{\ve ┆ "$proj_{\ve ┆ … ┆ 9     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ c{a}}\      ┆ c{a}}\      ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ \vec{b} =   ┆ \vec{b} =   ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ \f…         ┆ \f…         ┆   ┆       ┆            ┆           ┆           │
│ η         ┆ angle   ┆ Angle(C, A, ┆ null        ┆ … ┆ 6     ┆ false      ┆ true      ┆ false     │
│           ┆         ┆ B)          ┆             ┆   ┆       ┆            ┆           ┆           │
└───────────┴─────────┴─────────────┴─────────────┴───┴───────┴────────────┴───────────┴───────────┘

In [9]:
df2

shape: (170, 9)
┌───────────┬─────────┬─────────────┬─────────────┬───┬───────┬────────────┬───────────┬───────────┐
│ Name      ┆ Type    ┆ Command     ┆ Value       ┆ … ┆ Layer ┆ ShowObject ┆ ShowLabel ┆ Auxiliary │
│ ---       ┆ ---     ┆ ---         ┆ ---         ┆   ┆ ---   ┆ ---        ┆ ---       ┆ ---       │
│ str       ┆ str     ┆ str         ┆ str         ┆   ┆ i64   ┆ bool       ┆ bool      ┆ bool      │
╞═══════════╪═════════╪═════════════╪═════════════╪═══╪═══════╪════════════╪═══════════╪═══════════╡
│ C         ┆ point   ┆ null        ┆ C = (0, 0)  ┆ … ┆ 9     ┆ true       ┆ true      ┆ false     │
│ A         ┆ point   ┆ null        ┆ A = (2.2,   ┆ … ┆ 9     ┆ true       ┆ true      ┆ false     │
│           ┆         ┆             ┆ 0)          ┆   ┆       ┆            ┆           ┆           │
│ poly1     ┆ polygon ┆ Polygon(C,  ┆ poly1 = 4.6 ┆ … ┆ 3     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ A, 4)       ┆             ┆   ┆       ┆            ┆           ┆           │
│ f         ┆ segment ┆ Segment(C,  ┆ f = 2.2     ┆ … ┆ 2     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ A, poly1)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ g         ┆ segment ┆ Segment(A,  ┆ g = 2.2     ┆ … ┆ 2     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ E, poly1)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ …         ┆ …       ┆ …           ┆ …           ┆ … ┆ …     ┆ …          ┆ …         ┆ …         │
│ b_3       ┆ segment ┆ Segment(P,  ┆ b_3 = 3     ┆ … ┆ 2     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ B_1, t8)    ┆             ┆   ┆       ┆            ┆           ┆           │
│ p_6       ┆ segment ┆ Segment(B_1 ┆ p_6 = 2.4   ┆ … ┆ 2     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ , A_1, t8)  ┆             ┆   ┆       ┆            ┆           ┆           │
│ e_3       ┆ segment ┆ Segment(A_1 ┆ e_3 = 1.8   ┆ … ┆ 2     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ , P, t8)    ┆             ┆   ┆       ┆            ┆           ┆           │
│ text5_{3} ┆ text    ┆ null        ┆ $proj_{\vec ┆ … ┆ 9     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆             ┆ {a}}\       ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆             ┆ \vec{b} =   ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆             ┆ \fr…        ┆   ┆       ┆            ┆           ┆           │
│ η         ┆ angle   ┆ Angle(C, A, ┆ η = 59.2°   ┆ … ┆ 6     ┆ false      ┆ true      ┆ false     │
│           ┆         ┆ B)          ┆             ┆   ┆       ┆            ┆           ┆           │
└───────────┴─────────┴─────────────┴─────────────┴───┴───────┴────────────┴───────────┴───────────┘

In [10]:
set(df1["Type"].unique()) - set(df2["Type"].unique())

{'conic'}

In [11]:
set(df2["Type"].unique()) - set(df1["Type"].unique())

{'circle', 'quadrilateral', 'triangle'}

In [12]:
# df1 and df2 have different order...
# df1["Command"] == df2["Command"]
mask = df1['Command'].eq_missing(df2['Command']).not_()
# df1.filter(mask)
df2.filter(mask)

shape: (51, 9)
┌───────────┬─────────┬─────────────┬─────────────┬───┬───────┬────────────┬───────────┬───────────┐
│ Name      ┆ Type    ┆ Command     ┆ Value       ┆ … ┆ Layer ┆ ShowObject ┆ ShowLabel ┆ Auxiliary │
│ ---       ┆ ---     ┆ ---         ┆ ---         ┆   ┆ ---   ┆ ---        ┆ ---       ┆ ---       │
│ str       ┆ str     ┆ str         ┆ str         ┆   ┆ i64   ┆ bool       ┆ bool      ┆ bool      │
╞═══════════╪═════════╪═════════════╪═════════════╪═══╪═══════╪════════════╪═══════════╪═══════════╡
│ E         ┆ point   ┆ Polygon(C,  ┆ E = (2.1,   ┆ … ┆ 2     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ A, 4)       ┆ 2.2)        ┆   ┆       ┆            ┆           ┆           │
│ D         ┆ point   ┆ Polygon(C,  ┆ D = (0,     ┆ … ┆ 2     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ A, 4)       ┆ 2.2)        ┆   ┆       ┆            ┆           ┆           │
│ h         ┆ segment ┆ Segment(E,  ┆ h = 2.2     ┆ … ┆ 2     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ D, poly1)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ i         ┆ segment ┆ Segment(D,  ┆ i = 2.2     ┆ … ┆ 2     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ C, poly1)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ G         ┆ point   ┆ Polygon(A,  ┆ G = (0,     ┆ … ┆ 4     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ C, 4)       ┆ -2.2)       ┆   ┆       ┆            ┆           ┆           │
│ …         ┆ …       ┆ …           ┆ …           ┆ … ┆ …     ┆ …          ┆ …         ┆ …         │
│ H_1       ┆ point   ┆ Polygon(O', ┆ H_1 =       ┆ … ┆ 2     ┆ false      ┆ true      ┆ true      │
│           ┆         ┆ P, 4)       ┆ (-0.3, 1)   ┆   ┆       ┆            ┆           ┆           │
│ I_1       ┆ point   ┆ Polygon(O', ┆ I_1 =       ┆ … ┆ 2     ┆ false      ┆ true      ┆ true      │
│           ┆         ┆ P, 4)       ┆ (-0.3, 0)   ┆   ┆       ┆            ┆           ┆           │
│ f_4       ┆ segment ┆ Segment(H_1 ┆ f_4 = 1     ┆ … ┆ 2     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ , I_1,      ┆             ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ poly8)      ┆             ┆   ┆       ┆            ┆           ┆           │
│ h_4       ┆ segment ┆ Segment(I_1 ┆ h_4 = 1     ┆ … ┆ 2     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ , O',       ┆             ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ poly8)      ┆             ┆   ┆       ┆            ┆           ┆           │
│ text5_{3} ┆ text    ┆ null        ┆ $proj_{\vec ┆ … ┆ 9     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆             ┆ {a}}\       ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆             ┆ \vec{b} =   ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆             ┆ \fr…        ┆   ┆       ┆            ┆           ┆           │
└───────────┴─────────┴─────────────┴─────────────┴───┴───────┴────────────┴───────────┴───────────┘

## IR files

In [ ]:
import os
os.path.splitext(ggb.file.source_file)[0]+'.json'

In [ ]:
df1.write_json(os.path.splitext(ggb.file.source_file)[0]+'.json')

In [ ]:
import xml.etree.ElementTree as ET
import xmltodict

In [ ]:
root = ET.Element(c.geogebra_xml)
tree = ET.ElementTree(root)
tree.write(os.path.splitext(ggb.file.source_file)[0]+'.xml', encoding='utf-8', xml_declaration=True)

## handle no root returens from the applet

In [13]:
r = await ggb.function("getXML", ["text1"])

In [14]:
print(r)

<expression label="text1" exp="&quot;1.  Thales&apos;s  theorem: right  triangle  inscribed  in  a  circle&quot;"/>
<element type="text" label="text1">
	<show object="true" label="false" ev="40"/>
	<objColor r="0" g="0" b="0" alpha="0"/>
	<layer val="9"/>
	<labelMode val="0"/>
	<isLaTeX val="true"/>
	<font serif="false" sizeM="1" size="0" style="0"/>
	<absoluteScreenLocation x="50" y="50"/>
</element>

In [15]:
import xml.etree.ElementTree as ET
from itertools import chain

try:
    o3 = ggb.file.ggb_schema.decode(r)
except ET.ParseError:
    vr = ET.fromstringlist(chain(['<construction>'], r, ['</construction>']))
    o3 = ggb.file.ggb_schema.decode(ET.tostring(vr).decode('utf-8'))
o3

{'expression': [{'@label': 'text1',
   '@exp': '"1. \xa0Thales\'s \xa0theorem: right \xa0triangle \xa0inscribed \xa0in \xa0a \xa0circle"'}],
 'element': [{'@type': 'text',
   '@label': 'text1',
   'show': [{'@object': True, '@label': False, '@ev': 40}],
   'objColor': [{'@r': 0, '@g': 0, '@b': 0, '@alpha': 0.0}],
   'layer': [{'@val': 9}],
   'labelMode': [{'@val': 0}],
   'isLaTeX': [{'@val': True}],
   'font': [{'@serif': False, '@sizeM': 1.0, '@size': 0, '@style': 0}],
   'absoluteScreenLocation': [{'@x': 50.0, '@y': 50.0}]}]}

In [16]:
o3['element'][0].get('show')

[{'@object': True, '@label': False, '@ev': 40}]