# Parsing GeoGebra Construction Protocolto Polars DataFrame

In [ ]:
# this magic for develop only
%load_ext autoreload
%autoreload 2

In [1]:
from ggblab import GeoGebra

In [2]:
# initialize base class, not open GeoGebra Widget
ggb = GeoGebra()

Using local cached file: xsd/common.xsd

In [3]:
from ggblab_extra.construction_io import ConstructionIO

In [4]:
c = ggb.file.load('2025_13_01.ggb')

In [5]:
# df1 from a file df2 from a applet
df1 = await ConstructionIO.initialize_dataframe(ggb, file='2025_13_01.ggb')

In [6]:
df1

shape: (170, 9)
┌───────────┬─────────┬─────────────┬─────────────┬───┬───────┬────────────┬───────────┬───────────┐
│ Name      ┆ Type    ┆ Command     ┆ Value       ┆ … ┆ Layer ┆ ShowObject ┆ ShowLabel ┆ Auxiliary │
│ ---       ┆ ---     ┆ ---         ┆ ---         ┆   ┆ ---   ┆ ---        ┆ ---       ┆ ---       │
│ str       ┆ str     ┆ str         ┆ str         ┆   ┆ i64   ┆ bool       ┆ bool      ┆ bool      │
╞═══════════╪═════════╪═════════════╪═════════════╪═══╪═══════╪════════════╪═══════════╪═══════════╡
│ C         ┆ point   ┆ null        ┆ null        ┆ … ┆ 9     ┆ true       ┆ true      ┆ false     │
│ A         ┆ point   ┆ null        ┆ null        ┆ … ┆ 9     ┆ true       ┆ true      ┆ false     │
│ poly1     ┆ polygon ┆ Polygon(C,  ┆ null        ┆ … ┆ 3     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ A, 4)       ┆             ┆   ┆       ┆            ┆           ┆           │
│ f         ┆ segment ┆ Segment(C,  ┆ null        ┆ … ┆ 2     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ A, poly1)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ g         ┆ segment ┆ Segment(A,  ┆ null        ┆ … ┆ 2     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ E, poly1)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ h         ┆ segment ┆ Segment(E,  ┆ null        ┆ … ┆ 2     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ D, poly1)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ i         ┆ segment ┆ Segment(D,  ┆ null        ┆ … ┆ 2     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ C, poly1)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ E         ┆ point   ┆ Polygon(C,  ┆ null        ┆ … ┆ 2     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ A, 4)       ┆             ┆   ┆       ┆            ┆           ┆           │
│ D         ┆ point   ┆ Polygon(C,  ┆ null        ┆ … ┆ 2     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ A, 4)       ┆             ┆   ┆       ┆            ┆           ┆           │
│ O         ┆ point   ┆ Midpoint(C, ┆ null        ┆ … ┆ 1     ┆ false      ┆ true      ┆ false     │
│           ┆         ┆ A)          ┆             ┆   ┆       ┆            ┆           ┆           │
│ c_1       ┆ conic   ┆ Circle(O,   ┆ null        ┆ … ┆ 0     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ C)          ┆             ┆   ┆       ┆            ┆           ┆           │
│ P         ┆ point   ┆ Point(c_1)  ┆ null        ┆ … ┆ 9     ┆ true       ┆ true      ┆ false     │
│ j         ┆ ray     ┆ Ray(C, P)   ┆ null        ┆ … ┆ 0     ┆ true       ┆ false     ┆ false     │
│ k         ┆ ray     ┆ Ray(A, P)   ┆ null        ┆ … ┆ 0     ┆ true       ┆ false     ┆ false     │
│ l         ┆ line    ┆ Perpendicul ┆ null        ┆ … ┆ 3     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ arLine(E,   ┆             ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ k)          ┆             ┆   ┆       ┆            ┆           ┆           │
│ m         ┆ line    ┆ Perpendicul ┆ null        ┆ … ┆ 3     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ arLine(D,   ┆             ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ j)          ┆             ┆   ┆       ┆            ┆           ┆           │
│ n         ┆ line    ┆ Line(D, j)  ┆ null        ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│ p         ┆ line    ┆ Line(E, m)  ┆ null        ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│ q         ┆ line    ┆ Line(A, l)  ┆ null        ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│ r         ┆ line    ┆ Line(C, k)  ┆ null        ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│ poly2     ┆ polygon ┆ Polygon(A,  ┆ null        ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ C, 4)       ┆             ┆   ┆       ┆            ┆           ┆           │
│ s         ┆ segment ┆ Segment(A,  ┆ null        ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ C, poly2)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ t         ┆ segment ┆ Segment(C,  ┆ null        ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ G, poly2)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ a_{3}     ┆ segment ┆ Segment(G,  ┆ null        ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ H, poly2)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ b_1       ┆ segment ┆ Segment(H,  ┆ null        ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ A, poly2)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ G         ┆ point   ┆ Polygon(A,  ┆ null        ┆ … ┆ 4     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ C, 4)       ┆             ┆   ┆       ┆            ┆           ┆           │
│ H         ┆ point   ┆ Polygon(A,  ┆ null        ┆ … ┆ 4     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ C, 4)       ┆             ┆   ┆       ┆            ┆           ┆           │
│ e         ┆ ray     ┆ Ray(C, A)   ┆ null        ┆ … ┆ 0     ┆ true       ┆ false     ┆ false     │
│ P'        ┆ point   ┆ Point(c_1)  ┆ null        ┆ … ┆ 9     ┆ true       ┆ true      ┆ false     │
│ d         ┆ ray     ┆ Ray(A, P')  ┆ null        ┆ … ┆ 4     ┆ false      ┆ false     ┆ false     │
│ B         ┆ point   ┆ Intersect(d ┆ null        ┆ … ┆ 4     ┆ false      ┆ true      ┆ false     │
│           ┆         ┆ , j)        ┆             ┆   ┆       ┆            ┆           ┆           │
│ f_1       ┆ line    ┆ Line(C, d)  ┆ null        ┆ … ┆ 6     ┆ false      ┆ false     ┆ false     │
│ g_{4}     ┆ line    ┆ Perpendicul ┆ null        ┆ … ┆ 4     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ arLine(C,   ┆             ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ d)          ┆             ┆   ┆       ┆            ┆           ┆           │
│ w         ┆ vector  ┆ Vector(C,   ┆ null        ┆ … ┆ 7     ┆ false      ┆ true      ┆ false     │
│           ┆         ┆ B)          ┆             ┆   ┆       ┆            ┆           ┆           │
│ c_{5}     ┆ conic   ┆ Circle(C,   ┆ null        ┆ … ┆ 6     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ 1)          ┆             ┆   ┆       ┆            ┆           ┆           │
│ I         ┆ point   ┆ Intersect(c ┆ null        ┆ … ┆ 6     ┆ false      ┆ true      ┆ false     │
│           ┆         ┆ _{5}, e)    ┆             ┆   ┆       ┆            ┆           ┆           │
│ J         ┆ point   ┆ Intersect(c ┆ null        ┆ … ┆ 7     ┆ false      ┆ true      ┆ true      │
│           ┆         ┆ _{5}, f_1)  ┆             ┆   ┆       ┆            ┆           ┆           │
│ K         ┆ point   ┆ Intersect(c ┆ null        ┆ … ┆ 6     ┆ false      ┆ true      ┆ false     │
│           ┆         ┆ _{5}, f_1)  ┆             ┆   ┆       ┆            ┆           ┆           │
│ u         ┆ vector  ┆ Vector(C,   ┆ null        ┆ … ┆ 6     ┆ false      ┆ true      ┆ false     │
│           ┆         ┆ I)          ┆             ┆   ┆       ┆            ┆           ┆           │
│ v         ┆ vector  ┆ Vector(C,   ┆ null        ┆ … ┆ 6     ┆ false      ┆ true      ┆ false     │
│           ┆         ┆ K)          ┆             ┆   ┆       ┆            ┆           ┆           │
│ h_1       ┆ line    ┆ Perpendicul ┆ null        ┆ … ┆ 4     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ arLine(B,   ┆             ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ e)          ┆             ┆   ┆       ┆            ┆           ┆           │
│ L         ┆ point   ┆ Intersect(h ┆ null        ┆ … ┆ 4     ┆ false      ┆ true      ┆ false     │
│           ┆         ┆ _1, e)      ┆             ┆   ┆       ┆            ┆           ┆           │
│ proj_{u}w ┆ numeric ┆ ((w * u)) / ┆ ((w * u)) / ┆ … ┆ 0     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ ((u * u))   ┆ ((u * u))   ┆   ┆       ┆            ┆           ┆           │
│ proj_{v}w ┆ numeric ┆ ((w * v)) / ┆ ((w * v)) / ┆ … ┆ 0     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ ((v * v))   ┆ ((v * v))   ┆   ┆       ┆            ┆           ┆           │
│ γ         ┆ angle   ┆ Angle(A, C, ┆ null        ┆ … ┆ 5     ┆ false      ┆ true      ┆ false     │
│           ┆         ┆ B)          ┆             ┆   ┆       ┆            ┆           ┆           │
│ β         ┆ angle   ┆ Angle(A, B, ┆ null        ┆ … ┆ 5     ┆ false      ┆ true      ┆ false     │
│           ┆         ┆ C)          ┆             ┆   ┆       ┆            ┆           ┆           │
│ α         ┆ angle   ┆ Angle(C, A, ┆ null        ┆ … ┆ 5     ┆ false      ┆ true      ┆ false     │
│           ┆         ┆ B)          ┆             ┆   ┆       ┆            ┆           ┆           │
│ θ         ┆ angle   ┆ Angle(Vecto ┆ null        ┆ … ┆ 6     ┆ false      ┆ true      ┆ false     │
│           ┆         ┆ r(C, A),    ┆             ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ Vector(A, … ┆             ┆   ┆       ┆            ┆           ┆           │
│ b         ┆ numeric ┆ Distance(C, ┆ null        ┆ … ┆ 0     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ A)          ┆             ┆   ┆       ┆            ┆           ┆           │
│ c         ┆ numeric ┆ Distance(A, ┆ null        ┆ … ┆ 0     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ B)          ┆             ┆   ┆       ┆            ┆           ┆           │
│ Γ'_{uu}   ┆ numeric ┆ (-(((proj_{ ┆ (-(((proj_{ ┆ … ┆ 0     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ u}w *       ┆ u}w *       ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ cos(θ)) -   ┆ cos(θ)) -   ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ pro…        ┆ pro…        ┆   ┆       ┆            ┆           ┆           │
│ Γ_{uu}    ┆ numeric ┆ (proj_{u}w  ┆ (proj_{u}w  ┆ … ┆ 0     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ -           ┆ -           ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ (proj_{v}w  ┆ (proj_{v}w  ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ * cos(…     ┆ * cos(…     ┆   ┆       ┆            ┆           ┆           │
│ u_1       ┆ vector  ┆ Translate(V ┆ null        ┆ … ┆ 7     ┆ false      ┆ true      ┆ false     │
│           ┆         ┆ ector((((u  ┆             ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ * w)) / …   ┆             ┆   ┆       ┆            ┆           ┆           │
│ v_1       ┆ vector  ┆ Translate(V ┆ null        ┆ … ┆ 7     ┆ false      ┆ true      ┆ false     │
│           ┆         ┆ ector((((w  ┆             ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ * v)) / …   ┆             ┆   ┆       ┆            ┆           ┆           │
│ δ         ┆ angle   ┆ Angle(C, P, ┆ null        ┆ … ┆ 0     ┆ true       ┆ false     ┆ false     │
│           ┆         ┆ A)          ┆             ┆   ┆       ┆            ┆           ┆           │
│ ε         ┆ angle   ┆ Angle(C,    ┆ null        ┆ … ┆ 4     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ P', A)      ┆             ┆   ┆       ┆            ┆           ┆           │
│ text1     ┆ text    ┆ "1.         ┆ "1.         ┆ … ┆ 9     ┆ true       ┆ false     ┆ false     │
│           ┆         ┆  Thales's   ┆  Thales's   ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆  theorem:   ┆  theorem:   ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ right …     ┆ right …     ┆   ┆       ┆            ┆           ┆           │
│ text3     ┆ text    ┆ "3.  Pythag ┆ "3.  Pythag ┆ … ┆ 9     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ orean       ┆ orean       ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆  theorem"   ┆  theorem"   ┆   ┆       ┆            ┆           ┆           │
│ text3_{1} ┆ text    ┆ "$\|a\| =   ┆ "$\|a\| =   ┆ … ┆ 9     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ \|b\| \cos( ┆ \|b\| \cos( ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ \gamma)+ …  ┆ \gamma)+ …  ┆   ┆       ┆            ┆           ┆           │
│ text5     ┆ text    ┆ "5.  Projec ┆ "5.  Projec ┆ … ┆ 9     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ tion"       ┆ tion"       ┆   ┆       ┆            ┆           ┆           │
│ i_1       ┆ segment ┆ Segment(P,  ┆ null        ┆ … ┆ 1     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ O)          ┆             ┆   ┆       ┆            ┆           ┆           │
│ t1        ┆ polygon ┆ Polygon(O,  ┆ null        ┆ … ┆ 1     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ C, P)       ┆             ┆   ┆       ┆            ┆           ┆           │
│ p_1       ┆ segment ┆ Segment(O,  ┆ null        ┆ … ┆ 1     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ C, t1)      ┆             ┆   ┆       ┆            ┆           ┆           │
│ o         ┆ segment ┆ Segment(C,  ┆ null        ┆ … ┆ 1     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ P, t1)      ┆             ┆   ┆       ┆            ┆           ┆           │
│ c_3       ┆ segment ┆ Segment(P,  ┆ null        ┆ … ┆ 1     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ O, t1)      ┆             ┆   ┆       ┆            ┆           ┆           │
│ t2        ┆ polygon ┆ Polygon(O,  ┆ null        ┆ … ┆ 1     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ A, P)       ┆             ┆   ┆       ┆            ┆           ┆           │
│ p_2       ┆ segment ┆ Segment(O,  ┆ null        ┆ … ┆ 1     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ A, t2)      ┆             ┆   ┆       ┆            ┆           ┆           │
│ o_1       ┆ segment ┆ Segment(A,  ┆ null        ┆ … ┆ 1     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ P, t2)      ┆             ┆   ┆       ┆            ┆           ┆           │
│ a_1       ┆ segment ┆ Segment(P,  ┆ null        ┆ … ┆ 1     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ O, t2)      ┆             ┆   ┆       ┆            ┆           ┆           │
│ t3        ┆ polygon ┆ Polygon(A,  ┆ null        ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ C, P)       ┆             ┆   ┆       ┆            ┆           ┆           │
│ p_3       ┆ segment ┆ Segment(A,  ┆ null        ┆ … ┆ 3     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ C, t3)      ┆             ┆   ┆       ┆            ┆           ┆           │
│ a_2       ┆ segment ┆ Segment(C,  ┆ null        ┆ … ┆ 3     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ P, t3)      ┆             ┆   ┆       ┆            ┆           ┆           │
│ c_4       ┆ segment ┆ Segment(P,  ┆ null        ┆ … ┆ 3     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ A, t3)      ┆             ┆   ┆       ┆            ┆           ┆           │
│ poly3     ┆ polygon ┆ Polygon(C,  ┆ null        ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ P, 4)       ┆             ┆   ┆       ┆            ┆           ┆           │
│ j_1       ┆ segment ┆ Segment(C,  ┆ null        ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ P, poly3)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ k_1       ┆ segment ┆ Segment(P,  ┆ null        ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ F, poly3)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ l_1       ┆ segment ┆ Segment(F,  ┆ null        ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ M, poly3)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ m_1       ┆ segment ┆ Segment(M,  ┆ null        ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ C, poly3)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ F         ┆ point   ┆ Polygon(C,  ┆ null        ┆ … ┆ 4     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ P, 4)       ┆             ┆   ┆       ┆            ┆           ┆           │
│ M         ┆ point   ┆ Polygon(C,  ┆ null        ┆ … ┆ 4     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ P, 4)       ┆             ┆   ┆       ┆            ┆           ┆           │
│ poly4     ┆ polygon ┆ Polygon(P,  ┆ null        ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ A, 4)       ┆             ┆   ┆       ┆            ┆           ┆           │
│ n_1       ┆ segment ┆ Segment(P,  ┆ null        ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ A, poly4)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ q_1       ┆ segment ┆ Segment(A,  ┆ null        ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ N, poly4)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ r_1       ┆ segment ┆ Segment(N,  ┆ null        ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ Q, poly4)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ s_1       ┆ segment ┆ Segment(Q,  ┆ null        ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ P, poly4)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ N         ┆ point   ┆ Polygon(P,  ┆ null        ┆ … ┆ 4     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ A, 4)       ┆             ┆   ┆       ┆            ┆           ┆           │
│ Q         ┆ point   ┆ Polygon(P,  ┆ null        ┆ … ┆ 4     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ A, 4)       ┆             ┆   ┆       ┆            ┆           ┆           │
│ t_1       ┆ segment ┆ Segment(C,  ┆ null        ┆ … ┆ 5     ┆ false      ┆ true      ┆ false     │
│           ┆         ┆ L)          ┆             ┆   ┆       ┆            ┆           ┆           │
│ d_1       ┆ segment ┆ Segment(A,  ┆ null        ┆ … ┆ 5     ┆ false      ┆ true      ┆ false     │
│           ┆         ┆ L)          ┆             ┆   ┆       ┆            ┆           ┆           │
│ e_1       ┆ segment ┆ Segment(C,  ┆ null        ┆ … ┆ 5     ┆ false      ┆ true      ┆ false     │
│           ┆         ┆ P)          ┆             ┆   ┆       ┆            ┆           ┆           │
│ f_2       ┆ segment ┆ Segment(B,  ┆ null        ┆ … ┆ 5     ┆ false      ┆ true      ┆ false     │
│           ┆         ┆ P)          ┆             ┆   ┆       ┆            ┆           ┆           │
│ g_{5}     ┆ segment ┆ Segment(B,  ┆ null        ┆ … ┆ 5     ┆ false      ┆ true      ┆ false     │
│           ┆         ┆ P')         ┆             ┆   ┆       ┆            ┆           ┆           │
│ h_2       ┆ segment ┆ Segment(A,  ┆ null        ┆ … ┆ 5     ┆ false      ┆ true      ┆ false     │
│           ┆         ┆ P')         ┆             ┆   ┆       ┆            ┆           ┆           │
│ a         ┆ numeric ┆ Distance(B, ┆ null        ┆ … ┆ 0     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ C)          ┆             ┆   ┆       ┆            ┆           ┆           │
│ poly5     ┆ polygon ┆ Polygon(C,  ┆ null        ┆ … ┆ 5     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ B, 4)       ┆             ┆   ┆       ┆            ┆           ┆           │

In [7]:
await ggb.init()

In [8]:
r = await ggb.function("setBase64", [ggb.construction.base64_buffer.decode('utf-8')])

In [9]:
# df1 from a file df2 from a applet
df2 = await ConstructionIO.initialize_dataframe(ggb, use_applet=True)

In [10]:
ggb.file.source_file

'2025_13_01.ggb'

In [11]:
ConstructionIO.save_dataframe(df2, ggb=ggb, fmt='json')

'2025_13_01_2.json'

In [12]:
df2

shape: (170, 9)
┌───────────┬────────────┬────────────┬────────────┬───┬───────┬───────────┬───────────┬───────────┐
│ Name      ┆ Type       ┆ Command    ┆ Value      ┆ … ┆ Layer ┆ ShowObjec ┆ ShowLabel ┆ Auxiliary │
│ ---       ┆ ---        ┆ ---        ┆ ---        ┆   ┆ ---   ┆ t         ┆ ---       ┆ ---       │
│ str       ┆ str        ┆ str        ┆ str        ┆   ┆ i64   ┆ ---       ┆ bool      ┆ bool      │
│           ┆            ┆            ┆            ┆   ┆       ┆ bool      ┆           ┆           │
╞═══════════╪════════════╪════════════╪════════════╪═══╪═══════╪═══════════╪═══════════╪═══════════╡
│ C         ┆ point      ┆ null       ┆ C = (0, 0) ┆ … ┆ 9     ┆ true      ┆ true      ┆ false     │
│ A         ┆ point      ┆ null       ┆ A = (2.2,  ┆ … ┆ 9     ┆ true      ┆ true      ┆ false     │
│           ┆            ┆            ┆ 0)         ┆   ┆       ┆           ┆           ┆           │
│ poly1     ┆ polygon    ┆ Polygon(C, ┆ poly1 =    ┆ … ┆ 3     ┆ false     ┆ false     ┆ true      │
│           ┆            ┆ A, 4)      ┆ 4.6        ┆   ┆       ┆           ┆           ┆           │
│ f         ┆ segment    ┆ Segment(C, ┆ f = 2.2    ┆ … ┆ 2     ┆ false     ┆ false     ┆ true      │
│           ┆            ┆ A, poly1)  ┆            ┆   ┆       ┆           ┆           ┆           │
│ g         ┆ segment    ┆ Segment(A, ┆ g = 2.2    ┆ … ┆ 2     ┆ false     ┆ false     ┆ true      │
│           ┆            ┆ E, poly1)  ┆            ┆   ┆       ┆           ┆           ┆           │
│ E         ┆ point      ┆ Polygon(C, ┆ E = (2.1,  ┆ … ┆ 2     ┆ true      ┆ false     ┆ true      │
│           ┆            ┆ A, 4)      ┆ 2.2)       ┆   ┆       ┆           ┆           ┆           │
│ D         ┆ point      ┆ Polygon(C, ┆ D = (0,    ┆ … ┆ 2     ┆ true      ┆ false     ┆ true      │
│           ┆            ┆ A, 4)      ┆ 2.2)       ┆   ┆       ┆           ┆           ┆           │
│ h         ┆ segment    ┆ Segment(E, ┆ h = 2.2    ┆ … ┆ 2     ┆ false     ┆ false     ┆ true      │
│           ┆            ┆ D, poly1)  ┆            ┆   ┆       ┆           ┆           ┆           │
│ i         ┆ segment    ┆ Segment(D, ┆ i = 2.2    ┆ … ┆ 2     ┆ false     ┆ false     ┆ true      │
│           ┆            ┆ C, poly1)  ┆            ┆   ┆       ┆           ┆           ┆           │
│ O         ┆ point      ┆ Midpoint(C ┆ O = (1.1,  ┆ … ┆ 1     ┆ false     ┆ true      ┆ false     │
│           ┆            ┆ , A)       ┆ 0)         ┆   ┆       ┆           ┆           ┆           │
│ c_1       ┆ circle     ┆ Circle(O,  ┆ c_1: (x -  ┆ … ┆ 0     ┆ true      ┆ false     ┆ true      │
│           ┆            ┆ C)         ┆ 1.1)² + (y ┆   ┆       ┆           ┆           ┆           │
│           ┆            ┆            ┆ - 0)² = 1… ┆   ┆       ┆           ┆           ┆           │
│ P         ┆ point      ┆ Point(c_1) ┆ P = (0.7,  ┆ … ┆ 9     ┆ true      ┆ true      ┆ false     │
│           ┆            ┆            ┆ 1)         ┆   ┆       ┆           ┆           ┆           │
│ j         ┆ ray        ┆ Ray(C, P)  ┆ j: y =     ┆ … ┆ 0     ┆ true      ┆ false     ┆ false     │
│           ┆            ┆            ┆ 1.4x       ┆   ┆       ┆           ┆           ┆           │
│ k         ┆ ray        ┆ Ray(A, P)  ┆ k: y =     ┆ … ┆ 0     ┆ true      ┆ false     ┆ false     │
│           ┆            ┆            ┆ -0.7x +    ┆   ┆       ┆           ┆           ┆           │
│           ┆            ┆            ┆ 1.5        ┆   ┆       ┆           ┆           ┆           │
│ l         ┆ line       ┆ Perpendicu ┆ l: 1.4x -  ┆ … ┆ 3     ┆ false     ┆ false     ┆ true      │
│           ┆            ┆ larLine(E, ┆ 1y = 0.8   ┆   ┆       ┆           ┆           ┆           │
│           ┆            ┆ k)         ┆            ┆   ┆       ┆           ┆           ┆           │
│ m         ┆ line       ┆ Perpendicu ┆ m: -0.7x - ┆ … ┆ 3     ┆ false     ┆ false     ┆ true      │
│           ┆            ┆ larLine(D, ┆ 1y = -2.2  ┆   ┆       ┆           ┆           ┆           │
│           ┆            ┆ j)         ┆            ┆   ┆       ┆           ┆           ┆           │
│ n         ┆ line       ┆ Line(D, j) ┆ n: y =     ┆ … ┆ 3     ┆ false     ┆ false     ┆ false     │
│           ┆            ┆            ┆ 1.4x + 2.2 ┆   ┆       ┆           ┆           ┆           │
│ p         ┆ line       ┆ Line(E, m) ┆ p: y =     ┆ … ┆ 3     ┆ false     ┆ false     ┆ false     │
│           ┆            ┆            ┆ -0.7x +    ┆   ┆       ┆           ┆           ┆           │
│           ┆            ┆            ┆ 3.7        ┆   ┆       ┆           ┆           ┆           │
│ q         ┆ line       ┆ Line(A, l) ┆ q: y =     ┆ … ┆ 3     ┆ false     ┆ false     ┆ false     │
│           ┆            ┆            ┆ 1.4x - 3   ┆   ┆       ┆           ┆           ┆           │
│ r         ┆ line       ┆ Line(C, k) ┆ r: y =     ┆ … ┆ 3     ┆ false     ┆ false     ┆ false     │
│           ┆            ┆            ┆ -0.7x      ┆   ┆       ┆           ┆           ┆           │
│ poly2     ┆ polygon    ┆ Polygon(A, ┆ poly2 =    ┆ … ┆ 3     ┆ false     ┆ false     ┆ false     │
│           ┆            ┆ C, 4)      ┆ 4.6        ┆   ┆       ┆           ┆           ┆           │
│ s         ┆ segment    ┆ Segment(A, ┆ s = 2.2    ┆ … ┆ 4     ┆ false     ┆ false     ┆ true      │
│           ┆            ┆ C, poly2)  ┆            ┆   ┆       ┆           ┆           ┆           │
│ t         ┆ segment    ┆ Segment(C, ┆ t = 2.2    ┆ … ┆ 4     ┆ false     ┆ false     ┆ true      │
│           ┆            ┆ G, poly2)  ┆            ┆   ┆       ┆           ┆           ┆           │
│ G         ┆ point      ┆ Polygon(A, ┆ G = (0,    ┆ … ┆ 4     ┆ true      ┆ false     ┆ true      │
│           ┆            ┆ C, 4)      ┆ -2.2)      ┆   ┆       ┆           ┆           ┆           │
│ H         ┆ point      ┆ Polygon(A, ┆ H = (2.2,  ┆ … ┆ 4     ┆ true      ┆ false     ┆ true      │
│           ┆            ┆ C, 4)      ┆ -2.1)      ┆   ┆       ┆           ┆           ┆           │
│ a_{3}     ┆ segment    ┆ Segment(G, ┆ a_{3} =    ┆ … ┆ 4     ┆ false     ┆ false     ┆ true      │
│           ┆            ┆ H, poly2)  ┆ 2.2        ┆   ┆       ┆           ┆           ┆           │
│ b_1       ┆ segment    ┆ Segment(H, ┆ b_1 = 2.2  ┆ … ┆ 4     ┆ false     ┆ false     ┆ true      │
│           ┆            ┆ A, poly2)  ┆            ┆   ┆       ┆           ┆           ┆           │
│ e         ┆ ray        ┆ Ray(C, A)  ┆ e: y = 0   ┆ … ┆ 0     ┆ true      ┆ false     ┆ false     │
│ P'        ┆ point      ┆ Point(c_1) ┆ P' = (1.6, ┆ … ┆ 9     ┆ true      ┆ true      ┆ false     │
│           ┆            ┆            ┆ 1)         ┆   ┆       ┆           ┆           ┆           │
│ d         ┆ ray        ┆ Ray(A, P') ┆ d: y =     ┆ … ┆ 4     ┆ false     ┆ false     ┆ false     │
│           ┆            ┆            ┆ -1.6x +    ┆   ┆       ┆           ┆           ┆           │
│           ┆            ┆            ┆ 3.5        ┆   ┆       ┆           ┆           ┆           │
│ B         ┆ point      ┆ Intersect( ┆ B = (1.2,  ┆ … ┆ 4     ┆ false     ┆ true      ┆ false     │
│           ┆            ┆ d, j)      ┆ 1.6)       ┆   ┆       ┆           ┆           ┆           │
│ f_1       ┆ line       ┆ Line(C, d) ┆ f_1: y =   ┆ … ┆ 6     ┆ false     ┆ false     ┆ false     │
│           ┆            ┆            ┆ -1.6x      ┆   ┆       ┆           ┆           ┆           │
│ g_{4}     ┆ line       ┆ Perpendicu ┆ g_{4}:     ┆ … ┆ 4     ┆ false     ┆ false     ┆ false     │
│           ┆            ┆ larLine(C, ┆ 0.6x -     ┆   ┆       ┆           ┆           ┆           │
│           ┆            ┆ d)         ┆ 0.9y = 0   ┆   ┆       ┆           ┆           ┆           │
│ w         ┆ vector     ┆ Vector(C,  ┆ w = (1.2,  ┆ … ┆ 7     ┆ false     ┆ true      ┆ false     │
│           ┆            ┆ B)         ┆ 1.6)       ┆   ┆       ┆           ┆           ┆           │
│ c_{5}     ┆ circle     ┆ Circle(C,  ┆ c_{5}: x²  ┆ … ┆ 6     ┆ false     ┆ false     ┆ false     │
│           ┆            ┆ 1)         ┆ + y² = 1   ┆   ┆       ┆           ┆           ┆           │
│ I         ┆ point      ┆ Intersect( ┆ I = (1, 0) ┆ … ┆ 6     ┆ false     ┆ true      ┆ false     │
│           ┆            ┆ c_{5}, e)  ┆            ┆   ┆       ┆           ┆           ┆           │
│ J         ┆ point      ┆ Intersect( ┆ J = (0.5,  ┆ … ┆ 7     ┆ false     ┆ true      ┆ true      │
│           ┆            ┆ c_{5},     ┆ -0.9)      ┆   ┆       ┆           ┆           ┆           │
│           ┆            ┆ f_1)       ┆            ┆   ┆       ┆           ┆           ┆           │
│ K         ┆ point      ┆ Intersect( ┆ K = (-0.5, ┆ … ┆ 6     ┆ false     ┆ true      ┆ false     │
│           ┆            ┆ c_{5},     ┆ 0.9)       ┆   ┆       ┆           ┆           ┆           │
│           ┆            ┆ f_1)       ┆            ┆   ┆       ┆           ┆           ┆           │
│ u         ┆ vector     ┆ Vector(C,  ┆ u = (1, 0) ┆ … ┆ 6     ┆ false     ┆ true      ┆ false     │
│           ┆            ┆ I)         ┆            ┆   ┆       ┆           ┆           ┆           │
│ v         ┆ vector     ┆ Vector(C,  ┆ v = (-0.5, ┆ … ┆ 6     ┆ false     ┆ true      ┆ false     │
│           ┆            ┆ K)         ┆ 0.9)       ┆   ┆       ┆           ┆           ┆           │
│ h_1       ┆ line       ┆ Perpendicu ┆ h_1: -2.8x ┆ … ┆ 4     ┆ false     ┆ false     ┆ false     │
│           ┆            ┆ larLine(B, ┆ = -3.3     ┆   ┆       ┆           ┆           ┆           │
│           ┆            ┆ e)         ┆            ┆   ┆       ┆           ┆           ┆           │
│ L         ┆ point      ┆ Intersect( ┆ L = (1.2,  ┆ … ┆ 4     ┆ false     ┆ true      ┆ false     │
│           ┆            ┆ h_1, e)    ┆ 0)         ┆   ┆       ┆           ┆           ┆           │
│ proj_{u}w ┆ numeric    ┆ (w u) / (u ┆ proj_{u}w  ┆ … ┆ 8     ┆ false     ┆ false     ┆ false     │
│           ┆            ┆ u)         ┆ = 1.2      ┆   ┆       ┆           ┆           ┆           │
│ proj_{v}w ┆ numeric    ┆ (w v) / (v ┆ proj_{v}w  ┆ … ┆ 8     ┆ false     ┆ false     ┆ false     │
│           ┆            ┆ v)         ┆ = 0.8      ┆   ┆       ┆           ┆           ┆           │
│ γ         ┆ angle      ┆ Angle(A,   ┆ γ = 54.1°  ┆ … ┆ 5     ┆ false     ┆ true      ┆ false     │
│           ┆            ┆ C, B)      ┆            ┆   ┆       ┆           ┆           ┆           │
│ β         ┆ angle      ┆ Angle(A,   ┆ β = 66.8°  ┆ … ┆ 5     ┆ false     ┆ true      ┆ false     │
│           ┆            ┆ B, C)      ┆            ┆   ┆       ┆           ┆           ┆           │
│ α         ┆ angle      ┆ Angle(C,   ┆ α = 59.2°  ┆ … ┆ 5     ┆ false     ┆ true      ┆ false     │
│           ┆            ┆ A, B)      ┆            ┆   ┆       ┆           ┆           ┆           │
│ θ         ┆ angle      ┆ Angle(Vect ┆ θ = 120.8° ┆ … ┆ 6     ┆ false     ┆ true      ┆ false     │
│           ┆            ┆ or(C, A),  ┆            ┆   ┆       ┆           ┆           ┆           │
│           ┆            ┆ Vector(A,  ┆            ┆   ┆       ┆           ┆           ┆           │
│           ┆            ┆ …          ┆            ┆   ┆       ┆           ┆           ┆           │
│ b         ┆ numeric    ┆ Distance(C ┆ b = 2.2    ┆ … ┆ 8     ┆ false     ┆ false     ┆ false     │
│           ┆            ┆ , A)       ┆            ┆   ┆       ┆           ┆           ┆           │
│ c         ┆ numeric    ┆ Distance(A ┆ c = 1.9    ┆ … ┆ 8     ┆ false     ┆ false     ┆ false     │
│           ┆            ┆ , B)       ┆            ┆   ┆       ┆           ┆           ┆           │
│ Γ'_{uu}   ┆ numeric    ┆ -((proj_{u ┆ Γ'_{uu} =  ┆ … ┆ 8     ┆ false     ┆ false     ┆ false     │
│           ┆            ┆ }w cos(θ)  ┆ 1.9        ┆   ┆       ┆           ┆           ┆           │
│           ┆            ┆ -          ┆            ┆   ┆       ┆           ┆           ┆           │
│           ┆            ┆ proj_{v}…  ┆            ┆   ┆       ┆           ┆           ┆           │
│ Γ_{uu}    ┆ numeric    ┆ (proj_{u}w ┆ Γ_{uu} =   ┆ … ┆ 8     ┆ false     ┆ false     ┆ false     │
│           ┆            ┆ -          ┆ 2.2        ┆   ┆       ┆           ┆           ┆           │
│           ┆            ┆ proj_{v}w  ┆            ┆   ┆       ┆           ┆           ┆           │
│           ┆            ┆ cos(θ))…   ┆            ┆   ┆       ┆           ┆           ┆           │
│ u_1       ┆ vector     ┆ Translate( ┆ u_1 =      ┆ … ┆ 7     ┆ false     ┆ true      ┆ false     │
│           ┆            ┆ (u w) / (u ┆ (1.2, 0)   ┆   ┆       ┆           ┆           ┆           │
│           ┆            ┆ u) u, C)   ┆            ┆   ┆       ┆           ┆           ┆           │
│ v_1       ┆ vector     ┆ Translate( ┆ v_1 =      ┆ … ┆ 7     ┆ false     ┆ true      ┆ false     │
│           ┆            ┆ (w v) / (v ┆ (-0.4,     ┆   ┆       ┆           ┆           ┆           │
│           ┆            ┆ v) v, P')  ┆ 0.7)       ┆   ┆       ┆           ┆           ┆           │
│ δ         ┆ angle      ┆ Angle(C,   ┆ δ = 90°    ┆ … ┆ 0     ┆ true      ┆ false     ┆ false     │
│           ┆            ┆ P, A)      ┆            ┆   ┆       ┆           ┆           ┆           │
│ ε         ┆ angle      ┆ Angle(C,   ┆ ε = 90°    ┆ … ┆ 4     ┆ false     ┆ false     ┆ false     │
│           ┆            ┆ P', A)     ┆            ┆   ┆       ┆           ┆           ┆           │
│ text1     ┆ text       ┆ null       ┆ 1.         ┆ … ┆ 9     ┆ false     ┆ false     ┆ false     │
│           ┆            ┆            ┆  Thales's  ┆   ┆       ┆           ┆           ┆           │
│           ┆            ┆            ┆  theorem:  ┆   ┆       ┆           ┆           ┆           │
│           ┆            ┆            ┆ right  …   ┆   ┆       ┆           ┆           ┆           │
│ text3     ┆ text       ┆ null       ┆ 3.  Pythag ┆ … ┆ 9     ┆ false     ┆ false     ┆ false     │
│           ┆            ┆            ┆ orean      ┆   ┆       ┆           ┆           ┆           │
│           ┆            ┆            ┆  theorem   ┆   ┆       ┆           ┆           ┆           │
│ text3_{1} ┆ text       ┆ null       ┆ $\|a\| =   ┆ … ┆ 9     ┆ false     ┆ false     ┆ false     │
│           ┆            ┆            ┆ \|b\| \cos ┆   ┆       ┆           ┆           ┆           │
│           ┆            ┆            ┆ (\gamma)+  ┆   ┆       ┆           ┆           ┆           │
│           ┆            ┆            ┆ \…         ┆   ┆       ┆           ┆           ┆           │
│ text5     ┆ text       ┆ null       ┆ 5.  Projec ┆ … ┆ 9     ┆ false     ┆ false     ┆ false     │
│           ┆            ┆            ┆ tion       ┆   ┆       ┆           ┆           ┆           │
│ i_1       ┆ segment    ┆ Segment(P, ┆ i_1 = 1.1  ┆ … ┆ 1     ┆ false     ┆ false     ┆ false     │
│           ┆            ┆ O)         ┆            ┆   ┆       ┆           ┆           ┆           │
│ t1        ┆ triangle   ┆ Polygon(O, ┆ t1 = 0.6   ┆ … ┆ 1     ┆ false     ┆ false     ┆ false     │
│           ┆            ┆ C, P)      ┆            ┆   ┆       ┆           ┆           ┆           │
│ p_1       ┆ segment    ┆ Segment(O, ┆ p_1 = 1.1  ┆ … ┆ 1     ┆ false     ┆ false     ┆ true      │
│           ┆            ┆ C, t1)     ┆            ┆   ┆       ┆           ┆           ┆           │
│ o         ┆ segment    ┆ Segment(C, ┆ o = 1.3    ┆ … ┆ 1     ┆ false     ┆ false     ┆ true      │
│           ┆            ┆ P, t1)     ┆            ┆   ┆       ┆           ┆           ┆           │
│ c_3       ┆ segment    ┆ Segment(P, ┆ c_3 = 1.1  ┆ … ┆ 1     ┆ false     ┆ false     ┆ true      │
│           ┆            ┆ O, t1)     ┆            ┆   ┆       ┆           ┆           ┆           │
│ t2        ┆ triangle   ┆ Polygon(O, ┆ t2 = 0.6   ┆ … ┆ 1     ┆ false     ┆ false     ┆ false     │
│           ┆            ┆ A, P)      ┆            ┆   ┆       ┆           ┆           ┆           │
│ p_2       ┆ segment    ┆ Segment(O, ┆ p_2 = 1.1  ┆ … ┆ 1     ┆ false     ┆ false     ┆ true      │
│           ┆            ┆ A, t2)     ┆            ┆   ┆       ┆           ┆           ┆           │
│ o_1       ┆ segment    ┆ Segment(A, ┆ o_1 = 1.7  ┆ … ┆ 1     ┆ false     ┆ false     ┆ true      │
│           ┆            ┆ P, t2)     ┆            ┆   ┆       ┆           ┆           ┆           │
│ a_1       ┆ segment    ┆ Segment(P, ┆ a_1 = 1.1  ┆ … ┆ 1     ┆ false     ┆ false     ┆ true      │
│           ┆            ┆ O, t2)     ┆            ┆   ┆       ┆           ┆           ┆           │
│ t3        ┆ triangle   ┆ Polygon(A, ┆ t3 = 1.1   ┆ … ┆ 3     ┆ false     ┆ false     ┆ false     │
│           ┆            ┆ C, P)      ┆            ┆   ┆       ┆           ┆           ┆           │
│ p_3       ┆ segment    ┆ Segment(A, ┆ p_3 = 2.2  ┆ … ┆ 3     ┆ false     ┆ false     ┆ true      │
│           ┆            ┆ C, t3)     ┆            ┆   ┆       ┆           ┆           ┆           │
│ a_2       ┆ segment    ┆ Segment(C, ┆ a_2 = 1.3  ┆ … ┆ 3     ┆ false     ┆ false     ┆ true      │
│           ┆            ┆ P, t3)     ┆            ┆   ┆       ┆           ┆           ┆           │
│ c_4       ┆ segment    ┆ Segment(P, ┆ c_4 = 1.7  ┆ … ┆ 3     ┆ false     ┆ false     ┆ true      │
│           ┆            ┆ A, t3)     ┆            ┆   ┆       ┆           ┆           ┆           │
│ poly3     ┆ polygon    ┆ Polygon(C, ┆ poly3 =    ┆ … ┆ 3     ┆ false     ┆ false     ┆ false     │
│           ┆            ┆ P, 4)      ┆ 1.6        ┆   ┆       ┆           ┆           ┆           │
│ j_1       ┆ segment    ┆ Segment(C, ┆ j_1 = 1.3  ┆ … ┆ 4     ┆ false     ┆ false     ┆ true      │
│           ┆            ┆ P, poly3)  ┆            ┆   ┆       ┆           ┆           ┆           │
│ k_1       ┆ segment    ┆ Segment(P, ┆ k_1 = 1.3  ┆ … ┆ 4     ┆ false     ┆ false     ┆ true      │
│           ┆            ┆ F, poly3)  ┆            ┆   ┆       ┆           ┆           ┆           │
│ F         ┆ point      ┆ Polygon(C, ┆ F = (-0.3, ┆ … ┆ 4     ┆ true      ┆ false     ┆ true      │
│           ┆            ┆ P, 4)      ┆ 1.8)       ┆   ┆       ┆           ┆           ┆           │
│ M         ┆ point      ┆ Polygon(C, ┆ M = (-1,   ┆ … ┆ 4     ┆ true      ┆ false     ┆ true      │
│           ┆            ┆ P, 4)      ┆ 0.7)       ┆   ┆       ┆           ┆           ┆           │
│ l_1       ┆ segment    ┆ Segment(F, ┆ l_1 = 1.3  ┆ … ┆ 4     ┆ false     ┆ false     ┆ true      │
│           ┆            ┆ M, poly3)  ┆            ┆   ┆       ┆           ┆           ┆           │
│ m_1       ┆ segment    ┆ Segment(M, ┆ m_1 = 1.3  ┆ … ┆ 4     ┆ false     ┆ false     ┆ true      │
│           ┆            ┆ C, poly3)  ┆            ┆   ┆       ┆           ┆           ┆           │
│ poly4     ┆ polygon    ┆ Polygon(P, ┆ poly4 = 3  ┆ … ┆ 3     ┆ false     ┆ false     ┆ false     │
│           ┆            ┆ A, 4)      ┆            ┆   ┆       ┆           ┆           ┆           │
│ n_1       ┆ segment    ┆ Segment(P, ┆ n_1 = 1.7  ┆ … ┆ 4     ┆ false     ┆ false     ┆ true      │
│           ┆            ┆ A, poly4)  ┆            ┆   ┆       ┆           ┆           ┆           │
│ q_1       ┆ segment    ┆ Segment(A, ┆ q_1 = 1.7  ┆ … ┆ 4     ┆ false     ┆ false     ┆ true      │
│           ┆            ┆ N, poly4)  ┆            ┆   ┆       ┆           ┆           ┆           │
│ N         ┆ point      ┆ Polygon(P, ┆ N = (3.2,  ┆ … ┆ 4     ┆ true      ┆ false     ┆ true      │
│           ┆            ┆ A, 4)      ┆ 1.5)       ┆   ┆       ┆           ┆           ┆           │
│ Q         ┆ point      ┆ Polygon(P, ┆ Q = (1.7,  ┆ … ┆ 4     ┆ true      ┆ false     ┆ true      │
│           ┆            ┆ A, 4)      ┆ 2.5)       ┆   ┆       ┆           ┆           ┆           │

In [13]:
set(df1["Type"].unique()) - set(df2["Type"].unique())

{'conic'}

In [14]:
set(df2["Type"].unique()) - set(df1["Type"].unique())

{'circle', 'quadrilateral', 'triangle'}

In [15]:
# df1 and df2 have different order...
# df1["Command"] == df2["Command"]
mask = df1['Command'].eq_missing(df2['Command']).not_()
# df1.filter(mask)
df2.filter(mask)

shape: (51, 9)
┌───────────┬─────────┬─────────────┬─────────────┬───┬───────┬────────────┬───────────┬───────────┐
│ Name      ┆ Type    ┆ Command     ┆ Value       ┆ … ┆ Layer ┆ ShowObject ┆ ShowLabel ┆ Auxiliary │
│ ---       ┆ ---     ┆ ---         ┆ ---         ┆   ┆ ---   ┆ ---        ┆ ---       ┆ ---       │
│ str       ┆ str     ┆ str         ┆ str         ┆   ┆ i64   ┆ bool       ┆ bool      ┆ bool      │
╞═══════════╪═════════╪═════════════╪═════════════╪═══╪═══════╪════════════╪═══════════╪═══════════╡
│ E         ┆ point   ┆ Polygon(C,  ┆ E = (2.1,   ┆ … ┆ 2     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ A, 4)       ┆ 2.2)        ┆   ┆       ┆            ┆           ┆           │
│ D         ┆ point   ┆ Polygon(C,  ┆ D = (0,     ┆ … ┆ 2     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ A, 4)       ┆ 2.2)        ┆   ┆       ┆            ┆           ┆           │
│ h         ┆ segment ┆ Segment(E,  ┆ h = 2.2     ┆ … ┆ 2     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ D, poly1)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ i         ┆ segment ┆ Segment(D,  ┆ i = 2.2     ┆ … ┆ 2     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ C, poly1)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ G         ┆ point   ┆ Polygon(A,  ┆ G = (0,     ┆ … ┆ 4     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ C, 4)       ┆ -2.2)       ┆   ┆       ┆            ┆           ┆           │
│ H         ┆ point   ┆ Polygon(A,  ┆ H = (2.2,   ┆ … ┆ 4     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ C, 4)       ┆ -2.1)       ┆   ┆       ┆            ┆           ┆           │
│ a_{3}     ┆ segment ┆ Segment(G,  ┆ a_{3} = 2.2 ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ H, poly2)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ b_1       ┆ segment ┆ Segment(H,  ┆ b_1 = 2.2   ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ A, poly2)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ proj_{u}w ┆ numeric ┆ (w u) / (u  ┆ proj_{u}w = ┆ … ┆ 8     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ u)          ┆ 1.2         ┆   ┆       ┆            ┆           ┆           │
│ proj_{v}w ┆ numeric ┆ (w v) / (v  ┆ proj_{v}w = ┆ … ┆ 8     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ v)          ┆ 0.8         ┆   ┆       ┆            ┆           ┆           │
│ Γ'_{uu}   ┆ numeric ┆ -((proj_{u} ┆ Γ'_{uu} =   ┆ … ┆ 8     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ w cos(θ) -  ┆ 1.9         ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ proj_{v}…   ┆             ┆   ┆       ┆            ┆           ┆           │
│ Γ_{uu}    ┆ numeric ┆ (proj_{u}w  ┆ Γ_{uu} =    ┆ … ┆ 8     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ - proj_{v}w ┆ 2.2         ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ cos(θ))…    ┆             ┆   ┆       ┆            ┆           ┆           │
│ u_1       ┆ vector  ┆ Translate(( ┆ u_1 = (1.2, ┆ … ┆ 7     ┆ false      ┆ true      ┆ false     │
│           ┆         ┆ u w) / (u   ┆ 0)          ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ u) u, C)    ┆             ┆   ┆       ┆            ┆           ┆           │
│ v_1       ┆ vector  ┆ Translate(( ┆ v_1 =       ┆ … ┆ 7     ┆ false      ┆ true      ┆ false     │
│           ┆         ┆ w v) / (v   ┆ (-0.4, 0.7) ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ v) v, P')   ┆             ┆   ┆       ┆            ┆           ┆           │
│ text1     ┆ text    ┆ null        ┆ 1.          ┆ … ┆ 9     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆             ┆  Thales's   ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆             ┆  theorem:   ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆             ┆ right  …    ┆   ┆       ┆            ┆           ┆           │
│ text3     ┆ text    ┆ null        ┆ 3.  Pythago ┆ … ┆ 9     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆             ┆ rean        ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆             ┆  theorem    ┆   ┆       ┆            ┆           ┆           │
│ text3_{1} ┆ text    ┆ null        ┆ $\|a\| =    ┆ … ┆ 9     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆             ┆ \|b\| \cos( ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆             ┆ \gamma)+ \… ┆   ┆       ┆            ┆           ┆           │
│ text5     ┆ text    ┆ null        ┆ 5.          ┆ … ┆ 9     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆             ┆  Projection ┆   ┆       ┆            ┆           ┆           │
│ F         ┆ point   ┆ Polygon(C,  ┆ F = (-0.3,  ┆ … ┆ 4     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ P, 4)       ┆ 1.8)        ┆   ┆       ┆            ┆           ┆           │
│ M         ┆ point   ┆ Polygon(C,  ┆ M = (-1,    ┆ … ┆ 4     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ P, 4)       ┆ 0.7)        ┆   ┆       ┆            ┆           ┆           │
│ l_1       ┆ segment ┆ Segment(F,  ┆ l_1 = 1.3   ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ M, poly3)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ m_1       ┆ segment ┆ Segment(M,  ┆ m_1 = 1.3   ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ C, poly3)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ N         ┆ point   ┆ Polygon(P,  ┆ N = (3.2,   ┆ … ┆ 4     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ A, 4)       ┆ 1.5)        ┆   ┆       ┆            ┆           ┆           │
│ Q         ┆ point   ┆ Polygon(P,  ┆ Q = (1.7,   ┆ … ┆ 4     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ A, 4)       ┆ 2.5)        ┆   ┆       ┆            ┆           ┆           │
│ r_1       ┆ segment ┆ Segment(N,  ┆ r_1 = 1.7   ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ Q, poly4)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ s_1       ┆ segment ┆ Segment(Q,  ┆ s_1 = 1.7   ┆ … ┆ 4     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ P, poly4)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ R         ┆ point   ┆ Polygon(C,  ┆ R = (-0.5,  ┆ … ┆ 4     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ B, 4)       ┆ 2.8)        ┆   ┆       ┆            ┆           ┆           │
│ S         ┆ point   ┆ Polygon(C,  ┆ S = (-1.6,  ┆ … ┆ 4     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ B, 4)       ┆ 1.2)        ┆   ┆       ┆            ┆           ┆           │
│ k_2       ┆ segment ┆ Segment(R,  ┆ k_2 = 2     ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ S, poly5)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ l_2       ┆ segment ┆ Segment(S,  ┆ l_2 = 2     ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ C, poly5)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ T         ┆ point   ┆ Polygon(B,  ┆ T = (3.8,   ┆ … ┆ 4     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ A, 4)       ┆ 1)          ┆   ┆       ┆            ┆           ┆           │
│ U         ┆ point   ┆ Polygon(B,  ┆ U = (2.8,   ┆ … ┆ 4     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ A, 4)       ┆ 2.6)        ┆   ┆       ┆            ┆           ┆           │
│ q_2       ┆ segment ┆ Segment(T,  ┆ q_2 = 1.9   ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ U, poly6)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ r_2       ┆ segment ┆ Segment(U,  ┆ r_2 = 1.9   ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ B, poly6)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ w'        ┆ vector  ┆ Translate(Γ ┆ w' = (1.2,  ┆ … ┆ 7     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ _{uu} u +   ┆ 1.6)        ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ Γ'_{uu} v…  ┆             ┆   ┆       ┆            ┆           ┆           │
│ text4     ┆ text    ┆ null        ┆ 4.  Orthoce ┆ … ┆ 9     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆             ┆ nter  and   ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆             ┆  Law  of …  ┆   ┆       ┆            ┆           ┆           │
│ W         ┆ point   ┆ Polygon(V,  ┆ W = (1.4,   ┆ … ┆ 4     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ M, 4)       ┆ -1)         ┆   ┆       ┆            ┆           ┆           │
│ Z         ┆ point   ┆ Polygon(V,  ┆ Z = (3.2,   ┆ … ┆ 4     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ M, 4)       ┆ 1.5)        ┆   ┆       ┆            ┆           ┆           │
│ f_3       ┆ segment ┆ Segment(W,  ┆ f_3 = 3     ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ Z, poly7)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ g_{6}     ┆ segment ┆ Segment(Z,  ┆ g_{6} = 3   ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ V, poly7)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ text3_{2} ┆ text    ┆ null        ┆ $\|a\|^2 =  ┆ … ┆ 9     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆             ┆ \|b\|^2 +   ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆             ┆ \|c\|^2 -…  ┆   ┆       ┆            ┆           ┆           │
│ text5_{1} ┆ text    ┆ null        ┆ $\|b\| \cos ┆ … ┆ 9     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆             ┆ (\theta) =  ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆             ┆ \frac{\v…   ┆   ┆       ┆            ┆           ┆           │
│ g_2       ┆ numeric ┆ Distance(P, ┆ g_2 = 1.4   ┆ … ┆ 8     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ O') /       ┆             ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ Distance(C, ┆             ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ …           ┆             ┆   ┆       ┆            ┆           ┆           │
│ g_1       ┆ numeric ┆ Distance(A, ┆ g_1 = 1.4   ┆ … ┆ 8     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ O') /       ┆             ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ Distance(P, ┆             ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ …           ┆             ┆   ┆       ┆            ┆           ┆           │
│ g_3       ┆ numeric ┆ Area(t5)    ┆ g_3 = 0.7   ┆ … ┆ 8     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ g_2 g_2     ┆             ┆   ┆       ┆            ┆           ┆           │
│ text2     ┆ text    ┆ null        ┆ 2.          ┆ … ┆ 9     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆             ┆  Geometric  ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆             ┆  mean       ┆   ┆       ┆            ┆           ┆           │
│ H_1       ┆ point   ┆ Polygon(O', ┆ H_1 =       ┆ … ┆ 2     ┆ false      ┆ true      ┆ true      │
│           ┆         ┆ P, 4)       ┆ (-0.3, 1)   ┆   ┆       ┆            ┆           ┆           │
│ I_1       ┆ point   ┆ Polygon(O', ┆ I_1 =       ┆ … ┆ 2     ┆ false      ┆ true      ┆ true      │
│           ┆         ┆ P, 4)       ┆ (-0.3, 0)   ┆   ┆       ┆            ┆           ┆           │
│ f_4       ┆ segment ┆ Segment(H_1 ┆ f_4 = 1     ┆ … ┆ 2     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ , I_1,      ┆             ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ poly8)      ┆             ┆   ┆       ┆            ┆           ┆           │
│ h_4       ┆ segment ┆ Segment(I_1 ┆ h_4 = 1     ┆ … ┆ 2     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ , O',       ┆             ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ poly8)      ┆             ┆   ┆       ┆            ┆           ┆           │
│ text5_{3} ┆ text    ┆ null        ┆ $proj_{\vec ┆ … ┆ 9     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆             ┆ {a}}\       ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆             ┆ \vec{b} =   ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆             ┆ \fr…        ┆   ┆       ┆            ┆           ┆           │
└───────────┴─────────┴─────────────┴─────────────┴───┴───────┴────────────┴───────────┴───────────┘

## IR files

In [ ]:
import os
os.path.splitext(ggb.file.source_file)[0]+'.json'

In [ ]:
df1.write_json(os.path.splitext(ggb.file.source_file)[0]+'.json')

In [ ]:
import xml.etree.ElementTree as ET
import xmltodict

In [ ]:
root = ET.Element(c.geogebra_xml)
tree = ET.ElementTree(root)
tree.write(os.path.splitext(ggb.file.source_file)[0]+'.xml', encoding='utf-8', xml_declaration=True)

## handle no root returens from the applet

In [16]:
r = await ggb.function("getXML", ["text1"])

In [17]:
print(r)

<expression label="text1" exp="&quot;1.  Thales&apos;s  theorem: right  triangle  inscribed  in  a  circle&quot;"/>
<element type="text" label="text1">
	<show object="true" label="false" ev="40"/>
	<objColor r="0" g="0" b="0" alpha="0"/>
	<layer val="9"/>
	<labelMode val="0"/>
	<isLaTeX val="true"/>
	<font serif="false" sizeM="1" size="0" style="0"/>
	<absoluteScreenLocation x="50" y="50"/>
</element>

In [18]:
import xml.etree.ElementTree as ET
from itertools import chain

try:
    o3 = ggb.file.ggb_schema.decode(r)
except ET.ParseError:
    vr = ET.fromstringlist(chain(['<construction>'], r, ['</construction>']))
    o3 = ggb.file.ggb_schema.decode(ET.tostring(vr).decode('utf-8'))
o3

{'expression': [{'@label': 'text1',
   '@exp': '"1. \xa0Thales\'s \xa0theorem: right \xa0triangle \xa0inscribed \xa0in \xa0a \xa0circle"'}],
 'element': [{'@type': 'text',
   '@label': 'text1',
   'show': [{'@object': True, '@label': False, '@ev': 40}],
   'objColor': [{'@r': 0, '@g': 0, '@b': 0, '@alpha': 0.0}],
   'layer': [{'@val': 9}],
   'labelMode': [{'@val': 0}],
   'isLaTeX': [{'@val': True}],
   'font': [{'@serif': False, '@sizeM': 1.0, '@size': 0, '@style': 0}],
   'absoluteScreenLocation': [{'@x': 50.0, '@y': 50.0}]}]}

In [19]:
o3['element'][0].get('show')

[{'@object': True, '@label': False, '@ev': 40}]