# Parsing GeoGebra Construction Protocolto Polars DataFrame

In [1]:
# this magic for develop only
%load_ext autoreload
%autoreload 2

In [2]:
from ggblab import GeoGebra

In [3]:
# initialize base class, not open GeoGebra Widget
ggb = GeoGebra()

Using local cached file: xsd/common.xsd

In [8]:
from ggblab.construction_io import ConstructionIO

In [5]:
await ggb.init()

In [6]:
c = ggb.construction.load('2025_13_01.ggb')

In [7]:
r = await ggb.function("setBase64", [ggb.construction.base64_buffer.decode('utf-8')])

In [10]:
# df1 from a file df2 from a applet
df1 = await ConstructionIO.initialize_dataframe(ggb, file='2025_13_01.ggb', _columns=ConstructionIO.COLUMNS + ["ShowObject", "ShowLabel", "Auxiliary"])
df2 = await ConstructionIO.initialize_dataframe(ggb, use_applet=True)

In [ ]:
ConstructionIO.COLUMNS

In [11]:
df1

shape: (170, 9)
┌───────────┬─────────┬─────────────┬─────────────┬───┬───────┬────────────┬───────────┬───────────┐
│ Name      ┆ Type    ┆ Command     ┆ Value       ┆ … ┆ Layer ┆ ShowObject ┆ ShowLabel ┆ Auxiliary │
│ ---       ┆ ---     ┆ ---         ┆ ---         ┆   ┆ ---   ┆ ---        ┆ ---       ┆ ---       │
│ str       ┆ str     ┆ str         ┆ str         ┆   ┆ i64   ┆ bool       ┆ bool      ┆ bool      │
╞═══════════╪═════════╪═════════════╪═════════════╪═══╪═══════╪════════════╪═══════════╪═══════════╡
│ C         ┆ point   ┆ null        ┆ null        ┆ … ┆ 9     ┆ true       ┆ true      ┆ false     │
│ A         ┆ point   ┆ null        ┆ null        ┆ … ┆ 9     ┆ true       ┆ true      ┆ false     │
│ poly1     ┆ polygon ┆ Polygon(C,  ┆ null        ┆ … ┆ 3     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ A, 4)       ┆             ┆   ┆       ┆            ┆           ┆           │
│ f         ┆ segment ┆ Segment(C,  ┆ null        ┆ … ┆ 2     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ A, poly1)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ g         ┆ segment ┆ Segment(A,  ┆ null        ┆ … ┆ 2     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ E, poly1)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ h         ┆ segment ┆ Segment(E,  ┆ null        ┆ … ┆ 2     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ D, poly1)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ i         ┆ segment ┆ Segment(D,  ┆ null        ┆ … ┆ 2     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ C, poly1)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ E         ┆ point   ┆ Polygon(C,  ┆ null        ┆ … ┆ 2     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ A, 4)       ┆             ┆   ┆       ┆            ┆           ┆           │
│ D         ┆ point   ┆ Polygon(C,  ┆ null        ┆ … ┆ 2     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ A, 4)       ┆             ┆   ┆       ┆            ┆           ┆           │
│ O         ┆ point   ┆ Midpoint(C, ┆ null        ┆ … ┆ 1     ┆ false      ┆ true      ┆ false     │
│           ┆         ┆ A)          ┆             ┆   ┆       ┆            ┆           ┆           │
│ c_1       ┆ conic   ┆ Circle(O,   ┆ null        ┆ … ┆ 0     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ C)          ┆             ┆   ┆       ┆            ┆           ┆           │
│ P         ┆ point   ┆ Point(c_1)  ┆ null        ┆ … ┆ 9     ┆ true       ┆ true      ┆ false     │
│ j         ┆ ray     ┆ Ray(C, P)   ┆ null        ┆ … ┆ 0     ┆ true       ┆ false     ┆ false     │
│ k         ┆ ray     ┆ Ray(A, P)   ┆ null        ┆ … ┆ 0     ┆ true       ┆ false     ┆ false     │
│ l         ┆ line    ┆ Perpendicul ┆ null        ┆ … ┆ 3     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ arLine(E,   ┆             ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ k)          ┆             ┆   ┆       ┆            ┆           ┆           │
│ m         ┆ line    ┆ Perpendicul ┆ null        ┆ … ┆ 3     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ arLine(D,   ┆             ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ j)          ┆             ┆   ┆       ┆            ┆           ┆           │
│ n         ┆ line    ┆ Line(D, j)  ┆ null        ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│ p         ┆ line    ┆ Line(E, m)  ┆ null        ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│ q         ┆ line    ┆ Line(A, l)  ┆ null        ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│ r         ┆ line    ┆ Line(C, k)  ┆ null        ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│ poly2     ┆ polygon ┆ Polygon(A,  ┆ null        ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ C, 4)       ┆             ┆   ┆       ┆            ┆           ┆           │
│ s         ┆ segment ┆ Segment(A,  ┆ null        ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ C, poly2)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ t         ┆ segment ┆ Segment(C,  ┆ null        ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ G, poly2)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ a_{3}     ┆ segment ┆ Segment(G,  ┆ null        ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ H, poly2)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ b_1       ┆ segment ┆ Segment(H,  ┆ null        ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ A, poly2)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ G         ┆ point   ┆ Polygon(A,  ┆ null        ┆ … ┆ 4     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ C, 4)       ┆             ┆   ┆       ┆            ┆           ┆           │
│ H         ┆ point   ┆ Polygon(A,  ┆ null        ┆ … ┆ 4     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ C, 4)       ┆             ┆   ┆       ┆            ┆           ┆           │
│ e         ┆ ray     ┆ Ray(C, A)   ┆ null        ┆ … ┆ 0     ┆ true       ┆ false     ┆ false     │
│ P'        ┆ point   ┆ Point(c_1)  ┆ null        ┆ … ┆ 9     ┆ true       ┆ true      ┆ false     │
│ d         ┆ ray     ┆ Ray(A, P')  ┆ null        ┆ … ┆ 4     ┆ false      ┆ false     ┆ false     │
│ B         ┆ point   ┆ Intersect(d ┆ null        ┆ … ┆ 4     ┆ false      ┆ true      ┆ false     │
│           ┆         ┆ , j)        ┆             ┆   ┆       ┆            ┆           ┆           │
│ f_1       ┆ line    ┆ Line(C, d)  ┆ null        ┆ … ┆ 6     ┆ false      ┆ false     ┆ false     │
│ g_{4}     ┆ line    ┆ Perpendicul ┆ null        ┆ … ┆ 4     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ arLine(C,   ┆             ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ d)          ┆             ┆   ┆       ┆            ┆           ┆           │
│ w         ┆ vector  ┆ Vector(C,   ┆ null        ┆ … ┆ 7     ┆ false      ┆ true      ┆ false     │
│           ┆         ┆ B)          ┆             ┆   ┆       ┆            ┆           ┆           │
│ c_{5}     ┆ conic   ┆ Circle(C,   ┆ null        ┆ … ┆ 6     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ 1)          ┆             ┆   ┆       ┆            ┆           ┆           │
│ I         ┆ point   ┆ Intersect(c ┆ null        ┆ … ┆ 6     ┆ false      ┆ true      ┆ false     │
│           ┆         ┆ _{5}, e)    ┆             ┆   ┆       ┆            ┆           ┆           │
│ J         ┆ point   ┆ Intersect(c ┆ null        ┆ … ┆ 7     ┆ false      ┆ true      ┆ true      │
│           ┆         ┆ _{5}, f_1)  ┆             ┆   ┆       ┆            ┆           ┆           │
│ K         ┆ point   ┆ Intersect(c ┆ null        ┆ … ┆ 6     ┆ false      ┆ true      ┆ false     │
│           ┆         ┆ _{5}, f_1)  ┆             ┆   ┆       ┆            ┆           ┆           │
│ u         ┆ vector  ┆ Vector(C,   ┆ null        ┆ … ┆ 6     ┆ false      ┆ true      ┆ false     │
│           ┆         ┆ I)          ┆             ┆   ┆       ┆            ┆           ┆           │
│ v         ┆ vector  ┆ Vector(C,   ┆ null        ┆ … ┆ 6     ┆ false      ┆ true      ┆ false     │
│           ┆         ┆ K)          ┆             ┆   ┆       ┆            ┆           ┆           │
│ h_1       ┆ line    ┆ Perpendicul ┆ null        ┆ … ┆ 4     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ arLine(B,   ┆             ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ e)          ┆             ┆   ┆       ┆            ┆           ┆           │
│ L         ┆ point   ┆ Intersect(h ┆ null        ┆ … ┆ 4     ┆ false      ┆ true      ┆ false     │
│           ┆         ┆ _1, e)      ┆             ┆   ┆       ┆            ┆           ┆           │
│ proj_{u}w ┆ numeric ┆ ((w * u)) / ┆ ((w * u)) / ┆ … ┆ 0     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ ((u * u))   ┆ ((u * u))   ┆   ┆       ┆            ┆           ┆           │
│ proj_{v}w ┆ numeric ┆ ((w * v)) / ┆ ((w * v)) / ┆ … ┆ 0     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ ((v * v))   ┆ ((v * v))   ┆   ┆       ┆            ┆           ┆           │
│ γ         ┆ angle   ┆ Angle(A, C, ┆ null        ┆ … ┆ 5     ┆ false      ┆ true      ┆ false     │
│           ┆         ┆ B)          ┆             ┆   ┆       ┆            ┆           ┆           │
│ β         ┆ angle   ┆ Angle(A, B, ┆ null        ┆ … ┆ 5     ┆ false      ┆ true      ┆ false     │
│           ┆         ┆ C)          ┆             ┆   ┆       ┆            ┆           ┆           │
│ α         ┆ angle   ┆ Angle(C, A, ┆ null        ┆ … ┆ 5     ┆ false      ┆ true      ┆ false     │
│           ┆         ┆ B)          ┆             ┆   ┆       ┆            ┆           ┆           │
│ θ         ┆ angle   ┆ Angle(Vecto ┆ null        ┆ … ┆ 6     ┆ false      ┆ true      ┆ false     │
│           ┆         ┆ r(C, A),    ┆             ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ Vector(A, … ┆             ┆   ┆       ┆            ┆           ┆           │
│ b         ┆ numeric ┆ Distance(C, ┆ null        ┆ … ┆ 0     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ A)          ┆             ┆   ┆       ┆            ┆           ┆           │
│ c         ┆ numeric ┆ Distance(A, ┆ null        ┆ … ┆ 0     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ B)          ┆             ┆   ┆       ┆            ┆           ┆           │
│ Γ'_{uu}   ┆ numeric ┆ (-(((proj_{ ┆ (-(((proj_{ ┆ … ┆ 0     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ u}w *       ┆ u}w *       ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ cos(θ)) -   ┆ cos(θ)) -   ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ pro…        ┆ pro…        ┆   ┆       ┆            ┆           ┆           │
│ Γ_{uu}    ┆ numeric ┆ (proj_{u}w  ┆ (proj_{u}w  ┆ … ┆ 0     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ -           ┆ -           ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ (proj_{v}w  ┆ (proj_{v}w  ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ * cos(…     ┆ * cos(…     ┆   ┆       ┆            ┆           ┆           │
│ u_1       ┆ vector  ┆ Translate(V ┆ null        ┆ … ┆ 7     ┆ false      ┆ true      ┆ false     │
│           ┆         ┆ ector((((u  ┆             ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ * w)) / …   ┆             ┆   ┆       ┆            ┆           ┆           │
│ v_1       ┆ vector  ┆ Translate(V ┆ null        ┆ … ┆ 7     ┆ false      ┆ true      ┆ false     │
│           ┆         ┆ ector((((w  ┆             ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ * v)) / …   ┆             ┆   ┆       ┆            ┆           ┆           │
│ δ         ┆ angle   ┆ Angle(C, P, ┆ null        ┆ … ┆ 0     ┆ true       ┆ false     ┆ false     │
│           ┆         ┆ A)          ┆             ┆   ┆       ┆            ┆           ┆           │
│ ε         ┆ angle   ┆ Angle(C,    ┆ null        ┆ … ┆ 4     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ P', A)      ┆             ┆   ┆       ┆            ┆           ┆           │
│ text1     ┆ text    ┆ "1.         ┆ "1.         ┆ … ┆ 9     ┆ true       ┆ false     ┆ false     │
│           ┆         ┆  Thales's   ┆  Thales's   ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆  theorem:   ┆  theorem:   ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ right …     ┆ right …     ┆   ┆       ┆            ┆           ┆           │
│ text3     ┆ text    ┆ "3.  Pythag ┆ "3.  Pythag ┆ … ┆ 9     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ orean       ┆ orean       ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆  theorem"   ┆  theorem"   ┆   ┆       ┆            ┆           ┆           │
│ text3_{1} ┆ text    ┆ "$\|a\| =   ┆ "$\|a\| =   ┆ … ┆ 9     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ \|b\| \cos( ┆ \|b\| \cos( ┆   ┆       ┆            ┆           ┆           │
│           ┆         ┆ \gamma)+ …  ┆ \gamma)+ …  ┆   ┆       ┆            ┆           ┆           │
│ text5     ┆ text    ┆ "5.  Projec ┆ "5.  Projec ┆ … ┆ 9     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ tion"       ┆ tion"       ┆   ┆       ┆            ┆           ┆           │
│ i_1       ┆ segment ┆ Segment(P,  ┆ null        ┆ … ┆ 1     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ O)          ┆             ┆   ┆       ┆            ┆           ┆           │
│ t1        ┆ polygon ┆ Polygon(O,  ┆ null        ┆ … ┆ 1     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ C, P)       ┆             ┆   ┆       ┆            ┆           ┆           │
│ p_1       ┆ segment ┆ Segment(O,  ┆ null        ┆ … ┆ 1     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ C, t1)      ┆             ┆   ┆       ┆            ┆           ┆           │
│ o         ┆ segment ┆ Segment(C,  ┆ null        ┆ … ┆ 1     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ P, t1)      ┆             ┆   ┆       ┆            ┆           ┆           │
│ c_3       ┆ segment ┆ Segment(P,  ┆ null        ┆ … ┆ 1     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ O, t1)      ┆             ┆   ┆       ┆            ┆           ┆           │
│ t2        ┆ polygon ┆ Polygon(O,  ┆ null        ┆ … ┆ 1     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ A, P)       ┆             ┆   ┆       ┆            ┆           ┆           │
│ p_2       ┆ segment ┆ Segment(O,  ┆ null        ┆ … ┆ 1     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ A, t2)      ┆             ┆   ┆       ┆            ┆           ┆           │
│ o_1       ┆ segment ┆ Segment(A,  ┆ null        ┆ … ┆ 1     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ P, t2)      ┆             ┆   ┆       ┆            ┆           ┆           │
│ a_1       ┆ segment ┆ Segment(P,  ┆ null        ┆ … ┆ 1     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ O, t2)      ┆             ┆   ┆       ┆            ┆           ┆           │
│ t3        ┆ polygon ┆ Polygon(A,  ┆ null        ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ C, P)       ┆             ┆   ┆       ┆            ┆           ┆           │
│ p_3       ┆ segment ┆ Segment(A,  ┆ null        ┆ … ┆ 3     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ C, t3)      ┆             ┆   ┆       ┆            ┆           ┆           │
│ a_2       ┆ segment ┆ Segment(C,  ┆ null        ┆ … ┆ 3     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ P, t3)      ┆             ┆   ┆       ┆            ┆           ┆           │
│ c_4       ┆ segment ┆ Segment(P,  ┆ null        ┆ … ┆ 3     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ A, t3)      ┆             ┆   ┆       ┆            ┆           ┆           │
│ poly3     ┆ polygon ┆ Polygon(C,  ┆ null        ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ P, 4)       ┆             ┆   ┆       ┆            ┆           ┆           │
│ j_1       ┆ segment ┆ Segment(C,  ┆ null        ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ P, poly3)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ k_1       ┆ segment ┆ Segment(P,  ┆ null        ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ F, poly3)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ l_1       ┆ segment ┆ Segment(F,  ┆ null        ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ M, poly3)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ m_1       ┆ segment ┆ Segment(M,  ┆ null        ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ C, poly3)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ F         ┆ point   ┆ Polygon(C,  ┆ null        ┆ … ┆ 4     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ P, 4)       ┆             ┆   ┆       ┆            ┆           ┆           │
│ M         ┆ point   ┆ Polygon(C,  ┆ null        ┆ … ┆ 4     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ P, 4)       ┆             ┆   ┆       ┆            ┆           ┆           │
│ poly4     ┆ polygon ┆ Polygon(P,  ┆ null        ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ A, 4)       ┆             ┆   ┆       ┆            ┆           ┆           │
│ n_1       ┆ segment ┆ Segment(P,  ┆ null        ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ A, poly4)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ q_1       ┆ segment ┆ Segment(A,  ┆ null        ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ N, poly4)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ r_1       ┆ segment ┆ Segment(N,  ┆ null        ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ Q, poly4)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ s_1       ┆ segment ┆ Segment(Q,  ┆ null        ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│           ┆         ┆ P, poly4)   ┆             ┆   ┆       ┆            ┆           ┆           │
│ N         ┆ point   ┆ Polygon(P,  ┆ null        ┆ … ┆ 4     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ A, 4)       ┆             ┆   ┆       ┆            ┆           ┆           │
│ Q         ┆ point   ┆ Polygon(P,  ┆ null        ┆ … ┆ 4     ┆ true       ┆ false     ┆ true      │
│           ┆         ┆ A, 4)       ┆             ┆   ┆       ┆            ┆           ┆           │
│ t_1       ┆ segment ┆ Segment(C,  ┆ null        ┆ … ┆ 5     ┆ false      ┆ true      ┆ false     │
│           ┆         ┆ L)          ┆             ┆   ┆       ┆            ┆           ┆           │
│ d_1       ┆ segment ┆ Segment(A,  ┆ null        ┆ … ┆ 5     ┆ false      ┆ true      ┆ false     │
│           ┆         ┆ L)          ┆             ┆   ┆       ┆            ┆           ┆           │
│ e_1       ┆ segment ┆ Segment(C,  ┆ null        ┆ … ┆ 5     ┆ false      ┆ true      ┆ false     │
│           ┆         ┆ P)          ┆             ┆   ┆       ┆            ┆           ┆           │
│ f_2       ┆ segment ┆ Segment(B,  ┆ null        ┆ … ┆ 5     ┆ false      ┆ true      ┆ false     │
│           ┆         ┆ P)          ┆             ┆   ┆       ┆            ┆           ┆           │
│ g_{5}     ┆ segment ┆ Segment(B,  ┆ null        ┆ … ┆ 5     ┆ false      ┆ true      ┆ false     │
│           ┆         ┆ P')         ┆             ┆   ┆       ┆            ┆           ┆           │
│ h_2       ┆ segment ┆ Segment(A,  ┆ null        ┆ … ┆ 5     ┆ false      ┆ true      ┆ false     │
│           ┆         ┆ P')         ┆             ┆   ┆       ┆            ┆           ┆           │
│ a         ┆ numeric ┆ Distance(B, ┆ null        ┆ … ┆ 0     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ C)          ┆             ┆   ┆       ┆            ┆           ┆           │
│ poly5     ┆ polygon ┆ Polygon(C,  ┆ null        ┆ … ┆ 5     ┆ false      ┆ false     ┆ false     │
│           ┆         ┆ B, 4)       ┆             ┆   ┆       ┆            ┆           ┆           │

In [12]:
df2

shape: (170, 6)
┌───────────┬───────────────┬────────────────────┬────────────────────┬────────────────────┬───────┐
│ Name      ┆ Type          ┆ Command            ┆ Value              ┆ Caption            ┆ Layer │
│ ---       ┆ ---           ┆ ---                ┆ ---                ┆ ---                ┆ ---   │
│ str       ┆ str           ┆ str                ┆ str                ┆ str                ┆ i64   │
╞═══════════╪═══════════════╪════════════════════╪════════════════════╪════════════════════╪═══════╡
│ C         ┆ point         ┆ null               ┆ C = (0, 0)         ┆ null               ┆ 9     │
│ A         ┆ point         ┆ null               ┆ A = (2.2, 0)       ┆ null               ┆ 9     │
│ poly1     ┆ polygon       ┆ Polygon(C, A, 4)   ┆ poly1 = 4.6        ┆ null               ┆ 3     │
│ f         ┆ segment       ┆ Segment(C, A,      ┆ f = 2.2            ┆ null               ┆ 2     │
│           ┆               ┆ poly1)             ┆                    ┆                    ┆       │
│ g         ┆ segment       ┆ Segment(A, E,      ┆ g = 2.2            ┆ null               ┆ 2     │
│           ┆               ┆ poly1)             ┆                    ┆                    ┆       │
│ E         ┆ point         ┆ Polygon(C, A, 4)   ┆ E = (2.1, 2.2)     ┆ null               ┆ 2     │
│ D         ┆ point         ┆ Polygon(C, A, 4)   ┆ D = (0, 2.2)       ┆ null               ┆ 2     │
│ h         ┆ segment       ┆ Segment(E, D,      ┆ h = 2.2            ┆ null               ┆ 2     │
│           ┆               ┆ poly1)             ┆                    ┆                    ┆       │
│ i         ┆ segment       ┆ Segment(D, C,      ┆ i = 2.2            ┆ null               ┆ 2     │
│           ┆               ┆ poly1)             ┆                    ┆                    ┆       │
│ O         ┆ point         ┆ Midpoint(C, A)     ┆ O = (1.1, 0)       ┆ null               ┆ 1     │
│ c_1       ┆ circle        ┆ Circle(O, C)       ┆ c_1: (x - 1.1)² +  ┆ null               ┆ 0     │
│           ┆               ┆                    ┆ (y - 0)² = 1…      ┆                    ┆       │
│ P         ┆ point         ┆ Point(c_1)         ┆ P = (0.7, 1)       ┆ null               ┆ 9     │
│ j         ┆ ray           ┆ Ray(C, P)          ┆ j: y = 1.4x        ┆ null               ┆ 0     │
│ k         ┆ ray           ┆ Ray(A, P)          ┆ k: y = -0.7x + 1.5 ┆ null               ┆ 0     │
│ l         ┆ line          ┆ PerpendicularLine( ┆ l: 1.4x - 1y = 0.8 ┆ null               ┆ 3     │
│           ┆               ┆ E, k)              ┆                    ┆                    ┆       │
│ m         ┆ line          ┆ PerpendicularLine( ┆ m: -0.7x - 1y =    ┆ null               ┆ 3     │
│           ┆               ┆ D, j)              ┆ -2.2               ┆                    ┆       │
│ n         ┆ line          ┆ Line(D, j)         ┆ n: y = 1.4x + 2.2  ┆ null               ┆ 3     │
│ p         ┆ line          ┆ Line(E, m)         ┆ p: y = -0.7x + 3.7 ┆ null               ┆ 3     │
│ q         ┆ line          ┆ Line(A, l)         ┆ q: y = 1.4x - 3    ┆ null               ┆ 3     │
│ r         ┆ line          ┆ Line(C, k)         ┆ r: y = -0.7x       ┆ null               ┆ 3     │
│ poly2     ┆ polygon       ┆ Polygon(A, C, 4)   ┆ poly2 = 4.6        ┆ null               ┆ 3     │
│ s         ┆ segment       ┆ Segment(A, C,      ┆ s = 2.2            ┆ null               ┆ 4     │
│           ┆               ┆ poly2)             ┆                    ┆                    ┆       │
│ t         ┆ segment       ┆ Segment(C, G,      ┆ t = 2.2            ┆ null               ┆ 4     │
│           ┆               ┆ poly2)             ┆                    ┆                    ┆       │
│ G         ┆ point         ┆ Polygon(A, C, 4)   ┆ G = (0, -2.2)      ┆ null               ┆ 4     │
│ H         ┆ point         ┆ Polygon(A, C, 4)   ┆ H = (2.2, -2.1)    ┆ null               ┆ 4     │
│ a_{3}     ┆ segment       ┆ Segment(G, H,      ┆ a_{3} = 2.2        ┆ null               ┆ 4     │
│           ┆               ┆ poly2)             ┆                    ┆                    ┆       │
│ b_1       ┆ segment       ┆ Segment(H, A,      ┆ b_1 = 2.2          ┆ null               ┆ 4     │
│           ┆               ┆ poly2)             ┆                    ┆                    ┆       │
│ e         ┆ ray           ┆ Ray(C, A)          ┆ e: y = 0           ┆ null               ┆ 0     │
│ P'        ┆ point         ┆ Point(c_1)         ┆ P' = (1.6, 1)      ┆ null               ┆ 9     │
│ d         ┆ ray           ┆ Ray(A, P')         ┆ d: y = -1.6x + 3.5 ┆ null               ┆ 4     │
│ B         ┆ point         ┆ Intersect(d, j)    ┆ B = (1.2, 1.6)     ┆ null               ┆ 4     │
│ f_1       ┆ line          ┆ Line(C, d)         ┆ f_1: y = -1.6x     ┆ null               ┆ 6     │
│ g_{4}     ┆ line          ┆ PerpendicularLine( ┆ g_{4}: 0.6x - 0.9y ┆ null               ┆ 4     │
│           ┆               ┆ C, d)              ┆ = 0                ┆                    ┆       │
│ w         ┆ vector        ┆ Vector(C, B)       ┆ w = (1.2, 1.6)     ┆ $w$                ┆ 7     │
│ c_{5}     ┆ circle        ┆ Circle(C, 1)       ┆ c_{5}: x² + y² = 1 ┆ null               ┆ 6     │
│ I         ┆ point         ┆ Intersect(c_{5},   ┆ I = (1, 0)         ┆ null               ┆ 6     │
│           ┆               ┆ e)                 ┆                    ┆                    ┆       │
│ J         ┆ point         ┆ Intersect(c_{5},   ┆ J = (0.5, -0.9)    ┆ null               ┆ 7     │
│           ┆               ┆ f_1)               ┆                    ┆                    ┆       │
│ K         ┆ point         ┆ Intersect(c_{5},   ┆ K = (-0.5, 0.9)    ┆ null               ┆ 6     │
│           ┆               ┆ f_1)               ┆                    ┆                    ┆       │
│ u         ┆ vector        ┆ Vector(C, I)       ┆ u = (1, 0)         ┆ $u$                ┆ 6     │
│ v         ┆ vector        ┆ Vector(C, K)       ┆ v = (-0.5, 0.9)    ┆ $v$                ┆ 6     │
│ h_1       ┆ line          ┆ PerpendicularLine( ┆ h_1: -2.8x = -3.3  ┆ null               ┆ 4     │
│           ┆               ┆ B, e)              ┆                    ┆                    ┆       │
│ L         ┆ point         ┆ Intersect(h_1, e)  ┆ L = (1.2, 0)       ┆ null               ┆ 4     │
│ proj_{u}w ┆ numeric       ┆ (w u) / (u u)      ┆ proj_{u}w = 1.2    ┆ null               ┆ 8     │
│ proj_{v}w ┆ numeric       ┆ (w v) / (v v)      ┆ proj_{v}w = 0.8    ┆ null               ┆ 8     │
│ γ         ┆ angle         ┆ Angle(A, C, B)     ┆ γ = 54.1°          ┆ null               ┆ 5     │
│ β         ┆ angle         ┆ Angle(A, B, C)     ┆ β = 66.8°          ┆ null               ┆ 5     │
│ α         ┆ angle         ┆ Angle(C, A, B)     ┆ α = 59.2°          ┆ null               ┆ 5     │
│ θ         ┆ angle         ┆ Angle(Vector(C,    ┆ θ = 120.8°         ┆ $\theta$           ┆ 6     │
│           ┆               ┆ A), Vector(A, …    ┆                    ┆                    ┆       │
│ b         ┆ numeric       ┆ Distance(C, A)     ┆ b = 2.2            ┆ null               ┆ 8     │
│ c         ┆ numeric       ┆ Distance(A, B)     ┆ c = 1.9            ┆ null               ┆ 8     │
│ Γ'_{uu}   ┆ numeric       ┆ -((proj_{u}w       ┆ Γ'_{uu} = 1.9      ┆ null               ┆ 8     │
│           ┆               ┆ cos(θ) - proj_{v}… ┆                    ┆                    ┆       │
│ Γ_{uu}    ┆ numeric       ┆ (proj_{u}w -       ┆ Γ_{uu} = 2.2       ┆ null               ┆ 8     │
│           ┆               ┆ proj_{v}w cos(θ))… ┆                    ┆                    ┆       │
│ u_1       ┆ vector        ┆ Translate((u w) /  ┆ u_1 = (1.2, 0)     ┆ $proj_{u} w$       ┆ 7     │
│           ┆               ┆ (u u) u, C)        ┆                    ┆                    ┆       │
│ v_1       ┆ vector        ┆ Translate((w v) /  ┆ v_1 = (-0.4, 0.7)  ┆ $proj_{v} w$       ┆ 7     │
│           ┆               ┆ (v v) v, P')       ┆                    ┆                    ┆       │
│ δ         ┆ angle         ┆ Angle(C, P, A)     ┆ δ = 90°            ┆ null               ┆ 0     │
│ ε         ┆ angle         ┆ Angle(C, P', A)    ┆ ε = 90°            ┆ null               ┆ 4     │
│ text1     ┆ text          ┆ null               ┆ 1.  Thales's       ┆ null               ┆ 9     │
│           ┆               ┆                    ┆  theorem: right  … ┆                    ┆       │
│ text3     ┆ text          ┆ null               ┆ 3.  Pythagorean    ┆ null               ┆ 9     │
│           ┆               ┆                    ┆  theorem           ┆                    ┆       │
│ text3_{1} ┆ text          ┆ null               ┆ $\|a\| = \|b\|     ┆ null               ┆ 9     │
│           ┆               ┆                    ┆ \cos(\gamma)+ \…   ┆                    ┆       │
│ text5     ┆ text          ┆ null               ┆ 5.  Projection     ┆ null               ┆ 9     │
│ i_1       ┆ segment       ┆ Segment(P, O)      ┆ i_1 = 1.1          ┆ null               ┆ 1     │
│ t1        ┆ triangle      ┆ Polygon(O, C, P)   ┆ t1 = 0.6           ┆ null               ┆ 1     │
│ p_1       ┆ segment       ┆ Segment(O, C, t1)  ┆ p_1 = 1.1          ┆ null               ┆ 1     │
│ o         ┆ segment       ┆ Segment(C, P, t1)  ┆ o = 1.3            ┆ null               ┆ 1     │
│ c_3       ┆ segment       ┆ Segment(P, O, t1)  ┆ c_3 = 1.1          ┆ null               ┆ 1     │
│ t2        ┆ triangle      ┆ Polygon(O, A, P)   ┆ t2 = 0.6           ┆ null               ┆ 1     │
│ p_2       ┆ segment       ┆ Segment(O, A, t2)  ┆ p_2 = 1.1          ┆ null               ┆ 1     │
│ o_1       ┆ segment       ┆ Segment(A, P, t2)  ┆ o_1 = 1.7          ┆ null               ┆ 1     │
│ a_1       ┆ segment       ┆ Segment(P, O, t2)  ┆ a_1 = 1.1          ┆ null               ┆ 1     │
│ t3        ┆ triangle      ┆ Polygon(A, C, P)   ┆ t3 = 1.1           ┆ null               ┆ 3     │
│ p_3       ┆ segment       ┆ Segment(A, C, t3)  ┆ p_3 = 2.2          ┆ null               ┆ 3     │
│ a_2       ┆ segment       ┆ Segment(C, P, t3)  ┆ a_2 = 1.3          ┆ null               ┆ 3     │
│ c_4       ┆ segment       ┆ Segment(P, A, t3)  ┆ c_4 = 1.7          ┆ null               ┆ 3     │
│ poly3     ┆ polygon       ┆ Polygon(C, P, 4)   ┆ poly3 = 1.6        ┆ null               ┆ 3     │
│ j_1       ┆ segment       ┆ Segment(C, P,      ┆ j_1 = 1.3          ┆ null               ┆ 4     │
│           ┆               ┆ poly3)             ┆                    ┆                    ┆       │
│ k_1       ┆ segment       ┆ Segment(P, F,      ┆ k_1 = 1.3          ┆ null               ┆ 4     │
│           ┆               ┆ poly3)             ┆                    ┆                    ┆       │
│ F         ┆ point         ┆ Polygon(C, P, 4)   ┆ F = (-0.3, 1.8)    ┆ null               ┆ 4     │
│ M         ┆ point         ┆ Polygon(C, P, 4)   ┆ M = (-1, 0.7)      ┆ null               ┆ 4     │
│ l_1       ┆ segment       ┆ Segment(F, M,      ┆ l_1 = 1.3          ┆ null               ┆ 4     │
│           ┆               ┆ poly3)             ┆                    ┆                    ┆       │
│ m_1       ┆ segment       ┆ Segment(M, C,      ┆ m_1 = 1.3          ┆ null               ┆ 4     │
│           ┆               ┆ poly3)             ┆                    ┆                    ┆       │
│ poly4     ┆ polygon       ┆ Polygon(P, A, 4)   ┆ poly4 = 3          ┆ null               ┆ 3     │
│ n_1       ┆ segment       ┆ Segment(P, A,      ┆ n_1 = 1.7          ┆ null               ┆ 4     │
│           ┆               ┆ poly4)             ┆                    ┆                    ┆       │
│ q_1       ┆ segment       ┆ Segment(A, N,      ┆ q_1 = 1.7          ┆ null               ┆ 4     │
│           ┆               ┆ poly4)             ┆                    ┆                    ┆       │
│ N         ┆ point         ┆ Polygon(P, A, 4)   ┆ N = (3.2, 1.5)     ┆ null               ┆ 4     │
│ Q         ┆ point         ┆ Polygon(P, A, 4)   ┆ Q = (1.7, 2.5)     ┆ null               ┆ 4     │
│ r_1       ┆ segment       ┆ Segment(N, Q,      ┆ r_1 = 1.7          ┆ null               ┆ 4     │
│           ┆               ┆ poly4)             ┆                    ┆                    ┆       │
│ s_1       ┆ segment       ┆ Segment(Q, P,      ┆ s_1 = 1.7          ┆ null               ┆ 4     │
│           ┆               ┆ poly4)             ┆                    ┆                    ┆       │
│ t_1       ┆ segment       ┆ Segment(C, L)      ┆ t_1 = 1.2          ┆ $\|a\|             ┆ 5     │
│           ┆               ┆                    ┆                    ┆ cos(\gamma)$       ┆       │
│ d_1       ┆ segment       ┆ Segment(A, L)      ┆ d_1 = 1            ┆ $\|c\|             ┆ 5     │
│           ┆               ┆                    ┆                    ┆ \cos(\alpha)$      ┆       │
│ e_1       ┆ segment       ┆ Segment(C, P)      ┆ e_1 = 1.3          ┆ $\|b\|             ┆ 5     │
│           ┆               ┆                    ┆                    ┆ cos(\gamma)$       ┆       │
│ f_2       ┆ segment       ┆ Segment(B, P)      ┆ f_2 = 0.7          ┆ $\|c\| cos(\beta)$ ┆ 5     │
│ g_{5}     ┆ segment       ┆ Segment(B, P')     ┆ g_{5} = 0.8        ┆ $\|a\| cos(\beta)$ ┆ 5     │
│ h_2       ┆ segment       ┆ Segment(A, P')     ┆ h_2 = 1.1          ┆ $\|b\|             ┆ 5     │
│           ┆               ┆                    ┆                    ┆ cos(\alpha)$       ┆       │
│ a         ┆ numeric       ┆ Distance(B, C)     ┆ a = 2              ┆ null               ┆ 8     │
│ poly5     ┆ polygon       ┆ Polygon(C, B, 4)   ┆ poly5 = 4.1        ┆ null               ┆ 5     │
│ i_2       ┆ segment       ┆ Segment(C, B,      ┆ i_2 = 2            ┆ null               ┆ 4     │
│           ┆               ┆ poly5)             ┆                    ┆                    ┆       │
│ j_2       ┆ segment       ┆ Segment(B, R,      ┆ j_2 = 2            ┆ null               ┆ 4     │
│           ┆               ┆ poly5)             ┆                    ┆                    ┆       │
│ R         ┆ point         ┆ Polygon(C, B, 4)   ┆ R = (-0.5, 2.8)    ┆ null               ┆ 4     │
│ S         ┆ point         ┆ Polygon(C, B, 4)   ┆ S = (-1.6, 1.2)    ┆ null               ┆ 4     │
│ k_2       ┆ segment       ┆ Segment(R, S,      ┆ k_2 = 2            ┆ null               ┆ 4     │
│           ┆               ┆ poly5)             ┆                    ┆                    ┆       │
│ l_2       ┆ segment       ┆ Segment(S, C,      ┆ l_2 = 2            ┆ null               ┆ 4     │
│           ┆               ┆ poly5)             ┆                    ┆                    ┆       │
│ poly6     ┆ polygon       ┆ Polygon(B, A, 4)   ┆ poly6 = 3.6        ┆ null               ┆ 5     │
│ m_2       ┆ segment       ┆ Segment(B, A,      ┆ m_2 = 1.9          ┆ null               ┆ 4     │
│           ┆               ┆ poly6)             ┆                    ┆                    ┆       │
│ n_2       ┆ segment       ┆ Segment(A, T,      ┆ n_2 = 1.9          ┆ null               ┆ 4     │
│           ┆               ┆ poly6)             ┆                    ┆                    ┆       │
│ T         ┆ point         ┆ Polygon(B, A, 4)   ┆ T = (3.8, 1)       ┆ null               ┆ 4     │
│ U         ┆ point         ┆ Polygon(B, A, 4)   ┆ U = (2.8, 2.6)     ┆ null               ┆ 4     │
│ q_2       ┆ segment       ┆ Segment(T, U,      ┆ q_2 = 1.9          ┆ null               ┆ 4     │
│           ┆               ┆ poly6)             ┆                    ┆                    ┆       │
│ r_2       ┆ segment       ┆ Segment(U, B,      ┆ r_2 = 1.9          ┆ null               ┆ 4     │
│           ┆               ┆ poly6)             ┆                    ┆                    ┆       │
│ w'        ┆ vector        ┆ Translate(Γ_{uu} u ┆ w' = (1.2, 1.6)    ┆ null               ┆ 7     │
│           ┆               ┆ + Γ'_{uu} v…       ┆                    ┆                    ┆       │
│ t4        ┆ triangle      ┆ Polygon(A, B, C)   ┆ t4 = 1.8           ┆ null               ┆ 4     │
│ c_2       ┆ segment       ┆ Segment(A, B, t4)  ┆ c_2 = 1.9          ┆ null               ┆ 4     │
│ a_4       ┆ segment       ┆ Segment(B, C, t4)  ┆ a_4 = 2            ┆ null               ┆ 4     │
│ b_2       ┆ segment       ┆ Segment(C, A, t4)  ┆ b_2 = 2.2          ┆ null               ┆ 4     │
│ text4     ┆ text          ┆ null               ┆ 4.  Orthocenter    ┆ null               ┆ 9     │
│           ┆               ┆                    ┆  and  Law  of …    ┆                    ┆       │
│ s_2       ┆ segment       ┆ Segment(O, C)      ┆ s_2 = 1.1          ┆ null               ┆ 1     │
│ t_2       ┆ segment       ┆ Segment(O, A)      ┆ t_2 = 1.1          ┆ null               ┆ 1     │
│ V         ┆ point         ┆ Intersect(n, p)    ┆ V = (0.7, 3.2)     ┆ null               ┆ 4     │
│ poly7     ┆ polygon       ┆ Polygon(V, M, 4)   ┆ poly7 = 9.1        ┆ null               ┆ 3     │
│ d_2       ┆ segment       ┆ Segment(V, M,      ┆ d_2 = 3            ┆ null               ┆ 4     │
│           ┆               ┆ poly7)             ┆                    ┆                    ┆       │
│ e_2       ┆ segment       ┆ Segment(M, W,      ┆ e_2 = 3            ┆ null               ┆ 4     │
│           ┆               ┆ poly7)             ┆                    ┆                    ┆       │
│ W         ┆ point         ┆ Polygon(V, M, 4)   ┆ W = (1.4, -1)      ┆ null               ┆ 4     │
│ Z         ┆ point         ┆ Polygon(V, M, 4)   ┆ Z = (3.2, 1.5)     ┆ null               ┆ 4     │
│ f_3       ┆ segment       ┆ Segment(W, Z,      ┆ f_3 = 3            ┆ null               ┆ 4     │
│           ┆               ┆ poly7)             ┆                    ┆                    ┆       │
│ g_{6}     ┆ segment       ┆ Segment(Z, V,      ┆ g_{6} = 3          ┆ null               ┆ 4     │
│           ┆               ┆ poly7)             ┆                    ┆                    ┆       │
│ text3_{2} ┆ text          ┆ null               ┆ $\|a\|^2 = \|b\|^2 ┆ null               ┆ 9     │
│           ┆               ┆                    ┆ + \|c\|^2 -…       ┆                    ┆       │
│ text5_{1} ┆ text          ┆ null               ┆ $\|b\|             ┆ null               ┆ 9     │
│           ┆               ┆                    ┆ \cos(\theta) =     ┆                    ┆       │
│           ┆               ┆                    ┆ \frac{\v…          ┆                    ┆       │
│ h_3       ┆ line          ┆ PerpendicularLine( ┆ h_3: -2.2x = -1.6  ┆ null               ┆ 2     │
│           ┆               ┆ P, e)              ┆                    ┆                    ┆       │
│ O'        ┆ point         ┆ Intersect(h_3, e)  ┆ O' = (0.7, 0)      ┆ null               ┆ 2     │
│ g_2       ┆ numeric       ┆ Distance(P, O') /  ┆ g_2 = 1.4          ┆ null               ┆ 8     │
│           ┆               ┆ Distance(C, …      ┆                    ┆                    ┆       │
│ g_1       ┆ numeric       ┆ Distance(A, O') /  ┆ g_1 = 1.4          ┆ null               ┆ 8     │
│           ┆               ┆ Distance(P, …      ┆                    ┆                    ┆       │
│ t5        ┆ triangle      ┆ Polygon(P, C, O')  ┆ t5 = 0.4           ┆ null               ┆ 2     │
│ i_3       ┆ segment       ┆ Segment(P, C, t5)  ┆ i_3 = 1.3          ┆ null               ┆ 2     │
│ p_4       ┆ segment       ┆ Segment(C, O', t5) ┆ p_4 = 0.7          ┆ $a$                ┆ 2     │
│ c_6       ┆ segment       ┆ Segment(O', P, t5) ┆ c_6 = 1            ┆ $b$                ┆ 2     │
│ t6        ┆ triangle      ┆ Polygon(A, P, O')  ┆ t6 = 0.7           ┆ null               ┆ 2     │
│ j_3       ┆ segment       ┆ Segment(A, P, t6)  ┆ j_3 = 1.7          ┆ null               ┆ 2     │

In [13]:
set(df1["Type"].unique()) - set(df2["Type"].unique())

{'conic'}

In [14]:
set(df2["Type"].unique()) - set(df1["Type"].unique())

{'circle', 'quadrilateral', 'triangle'}

In [15]:
# df1 and df2 have different order...
# df1["Command"] == df2["Command"]
mask = df1['Command'].eq_missing(df2['Command']).not_()
# df1.filter(mask)
df2.filter(mask)

shape: (51, 6)
┌───────────┬─────────┬──────────────────────────┬──────────────────────────┬──────────────┬───────┐
│ Name      ┆ Type    ┆ Command                  ┆ Value                    ┆ Caption      ┆ Layer │
│ ---       ┆ ---     ┆ ---                      ┆ ---                      ┆ ---          ┆ ---   │
│ str       ┆ str     ┆ str                      ┆ str                      ┆ str          ┆ i64   │
╞═══════════╪═════════╪══════════════════════════╪══════════════════════════╪══════════════╪═══════╡
│ E         ┆ point   ┆ Polygon(C, A, 4)         ┆ E = (2.1, 2.2)           ┆ null         ┆ 2     │
│ D         ┆ point   ┆ Polygon(C, A, 4)         ┆ D = (0, 2.2)             ┆ null         ┆ 2     │
│ h         ┆ segment ┆ Segment(E, D, poly1)     ┆ h = 2.2                  ┆ null         ┆ 2     │
│ i         ┆ segment ┆ Segment(D, C, poly1)     ┆ i = 2.2                  ┆ null         ┆ 2     │
│ G         ┆ point   ┆ Polygon(A, C, 4)         ┆ G = (0, -2.2)            ┆ null         ┆ 4     │
│ H         ┆ point   ┆ Polygon(A, C, 4)         ┆ H = (2.2, -2.1)          ┆ null         ┆ 4     │
│ a_{3}     ┆ segment ┆ Segment(G, H, poly2)     ┆ a_{3} = 2.2              ┆ null         ┆ 4     │
│ b_1       ┆ segment ┆ Segment(H, A, poly2)     ┆ b_1 = 2.2                ┆ null         ┆ 4     │
│ proj_{u}w ┆ numeric ┆ (w u) / (u u)            ┆ proj_{u}w = 1.2          ┆ null         ┆ 8     │
│ proj_{v}w ┆ numeric ┆ (w v) / (v v)            ┆ proj_{v}w = 0.8          ┆ null         ┆ 8     │
│ Γ'_{uu}   ┆ numeric ┆ -((proj_{u}w cos(θ) -    ┆ Γ'_{uu} = 1.9            ┆ null         ┆ 8     │
│           ┆         ┆ proj_{v}…                ┆                          ┆              ┆       │
│ Γ_{uu}    ┆ numeric ┆ (proj_{u}w - proj_{v}w   ┆ Γ_{uu} = 2.2             ┆ null         ┆ 8     │
│           ┆         ┆ cos(θ))…                 ┆                          ┆              ┆       │
│ u_1       ┆ vector  ┆ Translate((u w) / (u u)  ┆ u_1 = (1.2, 0)           ┆ $proj_{u} w$ ┆ 7     │
│           ┆         ┆ u, C)                    ┆                          ┆              ┆       │
│ v_1       ┆ vector  ┆ Translate((w v) / (v v)  ┆ v_1 = (-0.4, 0.7)        ┆ $proj_{v} w$ ┆ 7     │
│           ┆         ┆ v, P')                   ┆                          ┆              ┆       │
│ text1     ┆ text    ┆ null                     ┆ 1.  Thales's  theorem:   ┆ null         ┆ 9     │
│           ┆         ┆                          ┆ right  …                 ┆              ┆       │
│ text3     ┆ text    ┆ null                     ┆ 3.  Pythagorean  theorem ┆ null         ┆ 9     │
│ text3_{1} ┆ text    ┆ null                     ┆ $\|a\| = \|b\|           ┆ null         ┆ 9     │
│           ┆         ┆                          ┆ \cos(\gamma)+ \…         ┆              ┆       │
│ text5     ┆ text    ┆ null                     ┆ 5.  Projection           ┆ null         ┆ 9     │
│ F         ┆ point   ┆ Polygon(C, P, 4)         ┆ F = (-0.3, 1.8)          ┆ null         ┆ 4     │
│ M         ┆ point   ┆ Polygon(C, P, 4)         ┆ M = (-1, 0.7)            ┆ null         ┆ 4     │
│ l_1       ┆ segment ┆ Segment(F, M, poly3)     ┆ l_1 = 1.3                ┆ null         ┆ 4     │
│ m_1       ┆ segment ┆ Segment(M, C, poly3)     ┆ m_1 = 1.3                ┆ null         ┆ 4     │
│ N         ┆ point   ┆ Polygon(P, A, 4)         ┆ N = (3.2, 1.5)           ┆ null         ┆ 4     │
│ Q         ┆ point   ┆ Polygon(P, A, 4)         ┆ Q = (1.7, 2.5)           ┆ null         ┆ 4     │
│ r_1       ┆ segment ┆ Segment(N, Q, poly4)     ┆ r_1 = 1.7                ┆ null         ┆ 4     │
│ s_1       ┆ segment ┆ Segment(Q, P, poly4)     ┆ s_1 = 1.7                ┆ null         ┆ 4     │
│ R         ┆ point   ┆ Polygon(C, B, 4)         ┆ R = (-0.5, 2.8)          ┆ null         ┆ 4     │
│ S         ┆ point   ┆ Polygon(C, B, 4)         ┆ S = (-1.6, 1.2)          ┆ null         ┆ 4     │
│ k_2       ┆ segment ┆ Segment(R, S, poly5)     ┆ k_2 = 2                  ┆ null         ┆ 4     │
│ l_2       ┆ segment ┆ Segment(S, C, poly5)     ┆ l_2 = 2                  ┆ null         ┆ 4     │
│ T         ┆ point   ┆ Polygon(B, A, 4)         ┆ T = (3.8, 1)             ┆ null         ┆ 4     │
│ U         ┆ point   ┆ Polygon(B, A, 4)         ┆ U = (2.8, 2.6)           ┆ null         ┆ 4     │
│ q_2       ┆ segment ┆ Segment(T, U, poly6)     ┆ q_2 = 1.9                ┆ null         ┆ 4     │
│ r_2       ┆ segment ┆ Segment(U, B, poly6)     ┆ r_2 = 1.9                ┆ null         ┆ 4     │
│ w'        ┆ vector  ┆ Translate(Γ_{uu} u +     ┆ w' = (1.2, 1.6)          ┆ null         ┆ 7     │
│           ┆         ┆ Γ'_{uu} v…               ┆                          ┆              ┆       │
│ text4     ┆ text    ┆ null                     ┆ 4.  Orthocenter  and     ┆ null         ┆ 9     │
│           ┆         ┆                          ┆  Law  of …               ┆              ┆       │
│ W         ┆ point   ┆ Polygon(V, M, 4)         ┆ W = (1.4, -1)            ┆ null         ┆ 4     │
│ Z         ┆ point   ┆ Polygon(V, M, 4)         ┆ Z = (3.2, 1.5)           ┆ null         ┆ 4     │
│ f_3       ┆ segment ┆ Segment(W, Z, poly7)     ┆ f_3 = 3                  ┆ null         ┆ 4     │
│ g_{6}     ┆ segment ┆ Segment(Z, V, poly7)     ┆ g_{6} = 3                ┆ null         ┆ 4     │
│ text3_{2} ┆ text    ┆ null                     ┆ $\|a\|^2 = \|b\|^2 +     ┆ null         ┆ 9     │
│           ┆         ┆                          ┆ \|c\|^2 -…               ┆              ┆       │
│ text5_{1} ┆ text    ┆ null                     ┆ $\|b\| \cos(\theta) =    ┆ null         ┆ 9     │
│           ┆         ┆                          ┆ \frac{\v…                ┆              ┆       │
│ g_2       ┆ numeric ┆ Distance(P, O') /        ┆ g_2 = 1.4                ┆ null         ┆ 8     │
│           ┆         ┆ Distance(C, …            ┆                          ┆              ┆       │
│ g_1       ┆ numeric ┆ Distance(A, O') /        ┆ g_1 = 1.4                ┆ null         ┆ 8     │
│           ┆         ┆ Distance(P, …            ┆                          ┆              ┆       │
│ g_3       ┆ numeric ┆ Area(t5) g_2 g_2         ┆ g_3 = 0.7                ┆ null         ┆ 8     │
│ text2     ┆ text    ┆ null                     ┆ 2.  Geometric  mean      ┆ null         ┆ 9     │
│ H_1       ┆ point   ┆ Polygon(O', P, 4)        ┆ H_1 = (-0.3, 1)          ┆ null         ┆ 2     │
│ I_1       ┆ point   ┆ Polygon(O', P, 4)        ┆ I_1 = (-0.3, 0)          ┆ null         ┆ 2     │
│ f_4       ┆ segment ┆ Segment(H_1, I_1, poly8) ┆ f_4 = 1                  ┆ null         ┆ 2     │
│ h_4       ┆ segment ┆ Segment(I_1, O', poly8)  ┆ h_4 = 1                  ┆ null         ┆ 2     │
│ text5_{3} ┆ text    ┆ null                     ┆ $proj_{\vec{a}}\ \vec{b} ┆ null         ┆ 9     │
│           ┆         ┆                          ┆ = \fr…                   ┆              ┆       │
└───────────┴─────────┴──────────────────────────┴──────────────────────────┴──────────────┴───────┘

## IR files

In [16]:
import os
os.path.splitext(ggb.file.source_file)[0]+'.json'

'2025_13_01.json'

In [19]:
df1.write_json(os.path.splitext(ggb.file.source_file)[0]+'.json')

In [17]:
import xml.etree.ElementTree as ET
root = ET.Element(c.geogebra_xml)
tree = ET.ElementTree(root)
tree.write(os.path.splitext(ggb.file.source_file)[0]+'.xml', encoding='utf-8', xml_declaration=True)