# ggblab Examples

This notebook demonstrates basic usage of `ggblab`. It walks through loading a `.ggb` file, displaying it in the GeoGebra widget, and parsing the construction for inspection and manipulation.

Key points:

- Large constructions are handled using `getBase64` / `setBase64` (zip + base64).
- Run cells from top to bottom for the examples to work as intended.
- Cells that produce output (e.g., version checks, object lists) will display their results directly below the code cell.

In [1]:
# this magic for develop only
%load_ext autoreload
%autoreload 2

## Create and initialize GeoGebra

The next two cells import the `GeoGebra` controller and initialize the widget. The import cell does not print output; the initialization cell may open the widget and produce transient console output in the notebook UI.

## Create GeoGebra controller

Import and construct the `GeoGebra` controller; the next cell initializes the widget in the JupyterLab UI.

In [2]:
from ggblab import GeoGebra

## Initialize the GeoGebra widget

This cell runs `await GeoGebra().init()` to open the GeoGebra widget attached to the current kernel. Expect the widget to appear in the JupyterLab UI; the cell may print status messages or the kernel may emit frontend messages (these appear in the notebook output area).

In [136]:
# open GeoGebra Widget on left-side
ggb = await GeoGebra().init()

Using local cached file: xsd/common.xsd

## Version checks (package)

This cell prints the installed `ggblab` package version. Expect a short version string as the cell output.

In [137]:
# ggblab version
import ggblab
ggblab.__version__

'1.1.0'

## Version checks (applet)

This cell queries the GeoGebra applet with `getVersion()` and prints the applet version string. The output helps verify compatibility.

In [138]:
# GeoGebra Applet version
r = await ggb.function("getVersion")
r

'5.2.909.9'

## Load a .ggb file

Load a `.ggb` file from disk into the local `ggb.construction` object for inspection and sending to the applet.

In [139]:
# load from .ggb (zipped, and base64 encoded)
c = ggb.file.load('2025_06_08.ggb')

## Send construction to the applet

Use `setBase64` to send the loaded .ggb (zip+base64) to the GeoGebra view so it is rendered in the widget.

In [140]:
# sending loaded construction to GeoGebra view and draw
r = await ggb.function("setBase64", [ggb.construction.base64_buffer.decode('utf-8')])

## Parse the construction XML

Decode the construction XML into Python structures (dicts/lists) so you can inspect and modify element attributes programmatically.

In [8]:
# parse loaded xml as python dict
o = c.ggb_schema.decode(c.geogebra_xml)

In [9]:
# list of all object names
[e['@label'] for e in o['element']]

['O_{2}',
 'A',
 'B',
 'c',
 'n',
 "O'",
 'p',
 'G',
 'F_{2}',
 'j',
 'l',
 'β',
 'γ',
 't1',
 'a',
 'c_1',
 'g_1',
 't2',
 'a_1',
 'c_2',
 'i_1',
 'k',
 'm',
 'δ',
 'ε',
 'q',
 'r',
 'e',
 'A_{1}',
 'C_{1}',
 'H',
 'J',
 'K',
 'ζ',
 'η',
 'O_{1}',
 'θ',
 's',
 'b',
 "P'",
 'P',
 't',
 'F_{1}',
 'h_1',
 'j_1',
 'k_1',
 'l_1',
 'm_1',
 'O_3',
 'p_1',
 'n_1',
 'C',
 'q_1',
 'r_1',
 'Q',
 'R',
 'D',
 't3',
 'd',
 'o',
 'l_2',
 'α',
 'O',
 'f',
 'i',
 't4',
 'c_3',
 'i_2',
 'a_2',
 'h',
 'g',
 'f_1',
 's_1',
 'd_1',
 'e_1',
 'E',
 'F',
 'f_2',
 'd_2',
 'L']

In [10]:
[e['@label'] for e in o['element']].index('A')

1

In [11]:
o['element'][1]

{'@type': 'point',
 '@label': 'A',
 'show': [{'@object': True, '@label': True, '@ev': 4}],
 'objColor': [{'@r': 176, '@g': 0, '@b': 32, '@alpha': 0.0}],
 'layer': [{'@val': 9}],
 'labelMode': [{'@val': 0}],
 'animation': [{'@step': '0.1', '@type': 1, '@playing': False}],
 'pointSize': [{'@val': 5.0}],
 'pointStyle': [{'@val': 0}],
 'coords': [{'@x': '10', '@y': '0', '@z': '1'}]}

In [12]:
# change visible state of object 'A'
o['element'][1]['show'][0]['@object'] = False

In [13]:
import xmlschema

In [14]:
# construct attributes from dict
x = xmlschema.etree_tostring(c.ggb_schema.encode(o['element'][1], 'element'))
print(x)

<element type="point" label="A">
    <show object="false" label="true" ev="4" />
    <objColor r="176" g="0" b="32" alpha="0.0" />
    <layer val="9" />
    <labelMode val="0" />
    <animation step="0.1" type="1" playing="false" />
    <pointSize val="5.0" />
    <pointStyle val="0" />
    <coords x="10" y="0" z="1" />
</element>

## Temporary updates with `preserve()`

The `preserve()` context manager snapshots the applet state (using a zip+base64 snapshot) and restores it automatically when the block exits.

Usage notes:

- The snapshot is taken with `getBase64` and restored with `setBase64` when available.
- The yielded `snap` object includes `base64_zip`, `xml` (optional), `timestamp`, `size_bytes`, and `sha1`.
- Call `await snap.restore()` to restore immediately; call `snap.release()` to drop the stored snapshot from memory.

In [15]:
import asyncio

In [16]:
# update the applet
async with ggb.preserve() as snap:
    r = await ggb.function("evalXML", [x])
    await asyncio.sleep(3)

## Advanced inspection

The following examples show how to decode the base64 snapshot, open the embedded zip, and inspect internal files (including the main construction XML). Expected outputs include a list of filenames inside the `.ggb` zip and the decoded XML string(s).

## Inspect base64 snapshot

Decode the base64 snapshot and inspect the zipped content (files inside the .ggb). This is useful when debugging or extracting the main construction XML.

In [17]:
import base64
import zipfile
import io

In [18]:
type(snap.base64_zip)

str

In [19]:
with zipfile.ZipFile(io.BytesIO(base64.b64decode(snap.base64_zip))) as zf:
    for info in zf.infolist():
        if info.filename == 'geogebra.xml':
            with zf.open(info) as f:
                xml = f.read()

In [20]:
type(xml.decode())

str

In [21]:
# r = await ggb.function("setXML", [xml.decode()])

In [22]:
await ggb.function("setBase64", [snap.base64_zip])

## draw step-by-step from new construction

In [135]:
# draw step-by-step from new construction
r = await ggb.function("newConstruction")

names = [e['@label'] for e in o['element']]
for n in names:
    cmd = None
    ci, co = None, None
    for _c in o['command']:
        _ci = tuple(zip(*_c['input'].items()))[1]
        _co = tuple(zip(*_c['output'].items()))[1]
        if n in _co:
            cmd = _c
            ci = _ci
            co = _co
            break

    match names.index(n):
        case int(i):
            ei = o['element'][i]
            if cmd:
                if co.index(n) == 0:
                    x = xmlschema.etree_tostring(c.ggb_schema.encode(cmd, 'construction/command'))
                    r = await ggb.function("evalXML", [x])
                    # print(f"command: {n}")
            x = xmlschema.etree_tostring(c.ggb_schema.encode(ei, 'element'))
            r = await ggb.function("evalXML", [x])
            # print(f"element:{n}")

In [23]:
ggb.comm.logs

['register_target_cb: <ipykernel.comm.comm.Comm object at 0x11a854910>',
 'Clients connected: 1 (connects+=1, disconnects+=0)',
 'Clients connected: 1 (connects+=2, disconnects+=2)',
 'Clients connected: 1 (connects+=84, disconnects+=84)',
 'Clients connected: 1 (connects+=35, disconnects+=35)',
 'Clients connected: 1 (connects+=72, disconnects+=72)',
 'Clients connected: 1 (connects+=88, disconnects+=88)',
 'Clients connected: 1 (connects+=83, disconnects+=83)',
 'Clients connected: 1 (connects+=81, disconnects+=81)']

In [24]:
ggb.comm.recv_msgs

{}

In [25]:
ggb.comm.pending_futures

{}

In [26]:
ggb.comm.recv_events.queue

deque([{'type': 'start', 'payload': {}},
       {'type': 'add', 'payload': 'O_{2}'},
       {'type': 'add', 'payload': 'A'},
       {'type': 'add', 'payload': 'B'},
       {'type': 'add', 'payload': 'c'},
       {'type': 'add', 'payload': 'n'},
       {'type': 'add', 'payload': "O'"},
       {'type': 'add', 'payload': 'p'},
       {'type': 'add', 'payload': 'G'},
       {'type': 'add', 'payload': 'F_{2}'},
       {'type': 'add', 'payload': 'j'},
       {'type': 'add', 'payload': 'l'},
       {'type': 'add', 'payload': 'β'},
       {'type': 'add', 'payload': 'γ'},
       {'type': 'add', 'payload': 't1'},
       {'type': 'add', 'payload': 'a'},
       {'type': 'add', 'payload': 'c_1'},
       {'type': 'add', 'payload': 'g_1'},
       {'type': 'add', 'payload': 't2'},
       {'type': 'add', 'payload': 'a_1'},
       {'type': 'add', 'payload': 'c_2'},
       {'type': 'add', 'payload': 'i_1'},
       {'type': 'add', 'payload': 'k'},
       {'type': 'add', 'payload': 'm'},
       {'type': 'add', 'payload': 'δ'},
       {'type': 'add', 'payload': 'ε'},
       {'type': 'add', 'payload': 'q'},
       {'type': 'add', 'payload': 'r'},
       {'type': 'add', 'payload': 'e'},
       {'type': 'add', 'payload': 'A_{1}'},
       {'type': 'add', 'payload': 'C_{1}'},
       {'type': 'add', 'payload': 'H'},
       {'type': 'add', 'payload': 'J'},
       {'type': 'add', 'payload': 'K'},
       {'type': 'add', 'payload': 'ζ'},
       {'type': 'add', 'payload': 'η'},
       {'type': 'add', 'payload': 'O_{1}'},
       {'type': 'add', 'payload': 'θ'},
       {'type': 'add', 'payload': 's'},
       {'type': 'add', 'payload': 'b'},
       {'type': 'add', 'payload': 'N'},
       {'type': 'add', 'payload': 'P'},
       {'type': 'add', 'payload': 't'},
       {'type': 'add', 'payload': 'F_{1}'},
       {'type': 'add', 'payload': 'h_1'},
       {'type': 'add', 'payload': 'j_1'},
       {'type': 'add', 'payload': 'k_1'},
       {'type': 'add', 'payload': 'l_1'},
       {'type': 'add', 'payload': 'm_1'},
       {'type': 'add', 'payload': 'I'},
       {'type': 'add', 'payload': 'p_1'},
       {'type': 'add', 'payload': 'n_1'},
       {'type': 'add', 'payload': 'C'},
       {'type': 'add', 'payload': 'q_1'},
       {'type': 'add', 'payload': 'r_1'},
       {'type': 'add', 'payload': 'Q'},
       {'type': 'add', 'payload': 'R'},
       {'type': 'add', 'payload': 'S'},
       {'type': 'add', 'payload': 'T'},
       {'type': 'add', 'payload': 't_1'},
       {'type': 'add', 'payload': 'b_1'},
       {'type': 'add', 'payload': 'D'},
       {'type': 'add', 'payload': 't3'},
       {'type': 'add', 'payload': 'd'},
       {'type': 'add', 'payload': 'o'},
       {'type': 'add', 'payload': 'l_2'},
       {'type': 'add', 'payload': 'α'},
       {'type': 'add', 'payload': 'O'},
       {'type': 'add', 'payload': 'f'},
       {'type': 'add', 'payload': 'i'},
       {'type': 'add', 'payload': 't4'},
       {'type': 'add', 'payload': 'c_3'},
       {'type': 'add', 'payload': 'i_2'},
       {'type': 'add', 'payload': 'a_2'},
       {'type': 'add', 'payload': 'h'},
       {'type': 'add', 'payload': 'g'},
       {'type': 'add', 'payload': 'f_1'},
       {'type': 'add', 'payload': 's_1'},
       {'type': 'add', 'payload': 'd_1'},
       {'type': 'add', 'payload': 'e_1'},
       {'type': 'add', 'payload': 'E'},
       {'type': 'add', 'payload': 'F'},
       {'type': 'add', 'payload': 'f_2'},
       {'type': 'add', 'payload': 'd_2'},
       {'type': 'add', 'payload': 'O_{2}'},
       {'type': 'add', 'payload': 'A'},
       {'type': 'add', 'payload': 'B'},
       {'type': 'add', 'payload': 'c'},
       {'type': 'add', 'payload': 'n'},
       {'type': 'add', 'payload': "O'"},
       {'type': 'add', 'payload': 'p'},
       {'type': 'add', 'payload': 'G'},
       {'type': 'add', 'payload': 'F_{2}'},
       {'type': 'add', 'payload': 'j'},
       {'type': 'add', 'payload': 'l'},
       {'type': 'add', 'payload': 'β'},
       {'type': 'add', 'payload': 'γ'},
       {'type': 'add', 'payload': 't1'},
       {'type': 'add', 'payload': 'a'},
       {'type': 'add', 'payload': 'c_1'},
       {'type': 'add', 'payload': 'g_1'},
       {'type': 'add', 'payload': 't2'},
       {'type': 'add', 'payload': 'a_1'},
       {'type': 'add', 'payload': 'c_2'},
       {'type': 'add', 'payload': 'i_1'},
       {'type': 'add', 'payload': 'k'},
       {'type': 'add', 'payload': 'm'},
       {'type': 'add', 'payload': 'δ'},
       {'type': 'add', 'payload': 'ε'},
       {'type': 'add', 'payload': 'q'},
       {'type': 'add', 'payload': 'r'},
       {'type': 'add', 'payload': 'e'},
       {'type': 'add', 'payload': 'A_{1}'},
       {'type': 'add', 'payload': 'C_{1}'},
       {'type': 'add', 'payload': 'H'},
       {'type': 'add', 'payload': 'J'},
       {'type': 'add', 'payload': 'K'},
       {'type': 'add', 'payload': 'ζ'},
       {'type': 'add', 'payload': 'η'},
       {'type': 'add', 'payload': 'O_{1}'},
       {'type': 'add', 'payload': 'θ'},
       {'type': 'add', 'payload': 's'},
       {'type': 'add', 'payload': 'b'},
       {'type': 'add', 'payload': 'N'},
       {'type': 'add', 'payload': 'P'},
       {'type': 'add', 'payload': 't'},
       {'type': 'add', 'payload': 'F_{1}'},
       {'type': 'add', 'payload': 'h_1'},
       {'type': 'add', 'payload': 'j_1'},
       {'type': 'add', 'payload': 'k_1'},
       {'type': 'add', 'payload': 'l_1'},
       {'type': 'add', 'payload': 'm_1'},
       {'type': 'add', 'payload': 'I'},
       {'type': 'add', 'payload': 'p_1'},
       {'type': 'add', 'payload': 'n_1'},
       {'type': 'add', 'payload': 'C'},
       {'type': 'add', 'payload': 'q_1'},
       {'type': 'add', 'payload': 'r_1'},
       {'type': 'add', 'payload': 'Q'},
       {'type': 'add', 'payload': 'R'},
       {'type': 'add', 'payload': 'S'},
       {'type': 'add', 'payload': 'T'},
       {'type': 'add', 'payload': 't_1'},
       {'type': 'add', 'payload': 'b_1'},
       {'type': 'add', 'payload': 'D'},
       {'type': 'add', 'payload': 't3'},
       {'type': 'add', 'payload': 'd'},
       {'type': 'add', 'payload': 'o'},
       {'type': 'add', 'payload': 'l_2'},
       {'type': 'add', 'payload': 'α'},
       {'type': 'add', 'payload': 'O'},
       {'type': 'add', 'payload': 'f'},
       {'type': 'add', 'payload': 'i'},
       {'type': 'add', 'payload': 't4'},
       {'type': 'add', 'payload': 'c_3'},
       {'type': 'add', 'payload': 'i_2'},
       {'type': 'add', 'payload': 'a_2'},
       {'type': 'add', 'payload': 'h'},
       {'type': 'add', 'payload': 'g'},
       {'type': 'add', 'payload': 'f_1'},
       {'type': 'add', 'payload': 's_1'},
       {'type': 'add', 'payload': 'd_1'},
       {'type': 'add', 'payload': 'e_1'},
       {'type': 'add', 'payload': 'E'},
       {'type': 'add', 'payload': 'F'},
       {'type': 'add', 'payload': 'f_2'},
       {'type': 'add', 'payload': 'd_2'},
       {'type': 'add', 'payload': 'O_{2}'},
       {'type': 'add', 'payload': 'A'},
       {'type': 'add', 'payload': 'B'},
       {'type': 'add', 'payload': 'c'},
       {'type': 'add', 'payload': 'n'},
       {'type': 'add', 'payload': "O'"},
       {'type': 'add', 'payload': 'p'},
       {'type': 'add', 'payload': 'G'},
       {'type': 'add', 'payload': 'F_{2}'},
       {'type': 'add', 'payload': 'j'},
       {'type': 'add', 'payload': 'l'},
       {'type': 'add', 'payload': 'β'},
       {'type': 'add', 'payload': 'γ'},
       {'type': 'add', 'payload': 't1'},
       {'type': 'add', 'payload': 'a'},
       {'type': 'add', 'payload': 'c_1'},
       {'type': 'add', 'payload': 'g_1'},
       {'type': 'add', 'payload': 't2'},
       {'type': 'add', 'payload': 'a_1'},
       {'type': 'add', 'payload': 'c_2'},
       {'type': 'add', 'payload': 'i_1'},
       {'type': 'add', 'payload': 'k'},
       {'type': 'add', 'payload': 'm'},
       {'type': 'add', 'payload': 'δ'},
       {'type': 'add', 'payload': 'ε'},
       {'type': 'add', 'payload': 'q'},
       {'type': 'add', 'payload': 'r'},
       {'type': 'add', 'payload': 'e'},
       {'type': 'add', 'payload': 'A_{1}'},
       {'type': 'add', 'payload': 'C_{1}'},
       {'type': 'add', 'payload': 'H'},
       {'type': 'add', 'payload': 'J'},
       {'type': 'add', 'payload': 'K'},
       {'type': 'add', 'payload': 'ζ'},
       {'type': 'add', 'payload': 'η'},
       {'type': 'add', 'payload': 'O_{1}'},
       {'type': 'add', 'payload': 'θ'},
       {'type': 'add', 'payload': 's'},
       {'type': 'add', 'payload': 'b'},
       {'type': 'add', 'payload': 'N'},
       {'type': 'add', 'payload': 'P'},
       {'type': 'add', 'payload': 't'},
       {'type': 'add', 'payload': 'F_{1}'},
       {'type': 'add', 'payload': 'h_1'},
       {'type': 'add', 'payload': 'j_1'},
       {'type': 'add', 'payload': 'k_1'},
       {'type': 'add', 'payload': 'l_1'},
       {'type': 'add', 'payload': 'm_1'},
       {'type': 'add', 'payload': 'I'},
       {'type': 'add', 'payload': 'p_1'},
       {'type': 'add', 'payload': 'n_1'},
       {'type': 'add', 'payload': 'C'},
       {'type': 'add', 'payload': 'q_1'},
       {'type': 'add', 'payload': 'r_1'},
       {'type': 'add', 'payload': 'Q'},
       {'type': 'add', 'payload': 'R'},
       {'type': 'add', 'payload': 'S'},
       {'type': 'add', 'payload': 'T'},
       {'type': 'add', 'payload': 't_1'},
       {'type': 'add', 'payload': 'b_1'},
       {'type': 'add', 'payload': 'D'},
       {'type': 'add', 'payload': 't3'},
       {'type': 'add', 'payload': 'd'},
       {'type': 'add', 'payload': 'o'},
       {'type': 'add', 'payload': 'l_2'},
       {'type': 'add', 'payload': 'α'},
       {'type': 'add', 'payload': 'O'},
       {'type': 'add', 'payload': 'f'},
       {'type': 'add', 'payload': 'i'},
       {'type': 'add', 'payload': 't4'},
       {'type': 'add', 'payload': 'c_3'},
       {'type': 'add', 'payload': 'i_2'},
       {'type': 'add', 'payload': 'a_2'},
       {'type': 'add', 'payload': 'h'},
       {'type': 'add', 'payload': 'g'},
       {'type': 'add', 'payload': 'f_1'},
       {'type': 'add', 'payload': 's_1'},
       {'type': 'add', 'payload': 'd_1'},
       {'type': 'add', 'payload': 'e_1'},
       {'type': 'add', 'payload': 'E'},
       {'type': 'add', 'payload': 'F'},
       {'type': 'add', 'payload': 'f_2'},
       {'type': 'add', 'payload': 'd_2'},
       {'type': 'add', 'payload': 'O_{2}'},
       {'type': 'add', 'payload': 'A'},
       {'type': 'add', 'payload': 'B'},
       {'type': 'add', 'payload': 'c'},
       {'type': 'add', 'payload': 'n'},
       {'type': 'add', 'payload': "O'"},
       {'type': 'add', 'payload': 'p'},
       {'type': 'add', 'payload': 'G'},
       {'type': 'add', 'payload': 'F_{2}'},
       {'type': 'add', 'payload': 'j'},
       {'type': 'add', 'payload': 'l'},
       {'type': 'add', 'payload': 'β'},
       {'type': 'add', 'payload': 'γ'},
       {'type': 'add', 'payload': 't1'},
       {'type': 'add', 'payload': 'a'},
       {'type': 'add', 'payload': 'c_1'},
       {'type': 'add', 'payload': 'g_1'},
       {'type': 'add', 'payload': 't2'},
       {'type': 'add', 'payload': 'a_1'},
       {'type': 'add', 'payload': 'c_2'},
       {'type': 'add', 'payload': 'i_1'},
       {'type': 'add', 'payload': 'k'},
       {'type': 'add', 'payload': 'm'},
       {'type': 'add', 'payload': 'δ'},
       {'type': 'add', 'payload': 'ε'},
       {'type': 'add', 'payload': 'q'},
       {'type': 'add', 'payload': 'r'},
       {'type': 'add', 'payload': 'e'},
       {'type': 'add', 'payload': 'A_{1}'},
       {'type': 'add', 'payload': 'C_{1}'},
       {'type': 'add', 'payload': 'H'},
       {'type': 'add', 'payload': 'J'},
       {'type': 'add', 'payload': 'K'},
       {'type': 'add', 'payload': 'ζ'},
       {'type': 'add', 'payload': 'η'},
       {'type': 'add', 'payload': 'O_{1}'},
       {'type': 'add', 'payload': 'θ'},
       {'type': 'add', 'payload': 's'},
       {'type': 'add', 'payload': 'b'},
       {'type': 'add', 'payload': 'N'},
       {'type': 'add', 'payload': 'P'},
       {'type': 'add', 'payload': 't'},
       {'type': 'add', 'payload': 'F_{1}'},
       {'type': 'add', 'payload': 'h_1'},
       {'type': 'add', 'payload': 'j_1'},
       {'type': 'add', 'payload': 'k_1'},
       {'type': 'add', 'payload': 'l_1'},
       {'type': 'add', 'payload': 'm_1'},
       {'type': 'add', 'payload': 'I'},
       {'type': 'add', 'payload': 'p_1'},
       {'type': 'add', 'payload': 'n_1'},
       {'type': 'add', 'payload': 'C'},
       {'type': 'add', 'payload': 'q_1'},
       {'type': 'add', 'payload': 'r_1'},
       {'type': 'add', 'payload': 'Q'},
       {'type': 'add', 'payload': 'R'},
       {'type': 'add', 'payload': 'S'},
       {'type': 'add', 'payload': 'T'},
       {'type': 'add', 'payload': 't_1'},
       {'type': 'add', 'payload': 'b_1'},
       {'type': 'add', 'payload': 'D'},
       {'type': 'add', 'payload': 't3'},
       {'type': 'add', 'payload': 'd'},
       {'type': 'add', 'payload': 'o'},
       {'type': 'add', 'payload': 'l_2'},
       {'type': 'add', 'payload': 'α'},
       {'type': 'add', 'payload': 'O'},
       {'type': 'add', 'payload': 'f'},
       {'type': 'add', 'payload': 'i'},
       {'type': 'add', 'payload': 't4'},
       {'type': 'add', 'payload': 'c_3'},
       {'type': 'add', 'payload': 'i_2'},
       {'type': 'add', 'payload': 'a_2'},
       {'type': 'add', 'payload': 'h'},
       {'type': 'add', 'payload': 'g'},
       {'type': 'add', 'payload': 'f_1'},
       {'type': 'add', 'payload': 's_1'},
       {'type': 'add', 'payload': 'd_1'},
       {'type': 'add', 'payload': 'e_1'},
       {'type': 'add', 'payload': 'E'},
       {'type': 'add', 'payload': 'F'},
       {'type': 'add', 'payload': 'f_2'},
       {'type': 'add', 'payload': 'd_2'}])

## ggblab_extra — construction protocol from the applet

These cells demonstrate how to extract a construction protocol (objects, commands, and dependency metadata) from a running GeoGebra applet using `ggblab_extra`.

They show how to initialize a structured `DataFrame` from the applet (`ConstructionIO.initialize_dataframe(ggb, use_applet=True)`) so you can analyze element attributes, sequences, and dependencies programmatically. These are analysis helpers and do not alter the stored applet state unless you explicitly call functions that modify the applet.

In [54]:
import polars as pl
import networkx as nx

In [55]:
from ggblab_extra.construction_io import ConstructionIO
df = await ConstructionIO.initialize_dataframe(ggb, use_applet=True)

In [56]:
df

shape: (111, 10)
┌──────────┬───────┬──────────┬───────────────────┬───┬───────┬────────────┬───────────┬───────────┐
│ Sequence ┆ Name  ┆ Type     ┆ Command           ┆ … ┆ Layer ┆ ShowObject ┆ ShowLabel ┆ Auxiliary │
│ ---      ┆ ---   ┆ ---      ┆ ---               ┆   ┆ ---   ┆ ---        ┆ ---       ┆ ---       │
│ u32      ┆ str   ┆ str      ┆ str               ┆   ┆ u32   ┆ bool       ┆ bool      ┆ bool      │
╞══════════╪═══════╪══════════╪═══════════════════╪═══╪═══════╪════════════╪═══════════╪═══════════╡
│ 0        ┆ O_{2} ┆ point    ┆ null              ┆ … ┆ 9     ┆ true       ┆ true      ┆ false     │
│ 1        ┆ A     ┆ point    ┆ null              ┆ … ┆ 2     ┆ true       ┆ true      ┆ false     │
│ 2        ┆ B     ┆ point    ┆ Point(Line(O_{2}, ┆ … ┆ 9     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ A))               ┆   ┆       ┆            ┆           ┆           │
│ 3        ┆ c     ┆ circle   ┆ Circle(O_{2}, B)  ┆ … ┆ 9     ┆ true       ┆ false     ┆ false     │
│ 4        ┆ n     ┆ line     ┆ Line(O_{2}, A)    ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│ 5        ┆ O'    ┆ point    ┆ Midpoint(O_{2},   ┆ … ┆ 3     ┆ false      ┆ true      ┆ false     │
│          ┆       ┆          ┆ A)                ┆   ┆       ┆            ┆           ┆           │
│ 6        ┆ p     ┆ circle   ┆ Circle(O', A)     ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│ 7        ┆ G     ┆ point    ┆ Intersect(c, p)   ┆ … ┆ 1     ┆ false      ┆ false     ┆ false     │
│ 8        ┆ F_{2} ┆ point    ┆ Intersect(c, p)   ┆ … ┆ 1     ┆ true       ┆ true      ┆ false     │
│ 9        ┆ j     ┆ line     ┆ Tangent(A, c)     ┆ … ┆ 2     ┆ true       ┆ false     ┆ false     │
│ 10       ┆ l     ┆ line     ┆ Tangent(A, c)     ┆ … ┆ 2     ┆ true       ┆ false     ┆ false     │
│ 11       ┆ β     ┆ angle    ┆ Angle(A, G,       ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{2})            ┆   ┆       ┆            ┆           ┆           │
│ 12       ┆ γ     ┆ angle    ┆ Angle(A, F_{2},   ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{2})            ┆   ┆       ┆            ┆           ┆           │
│ 13       ┆ t1    ┆ triangle ┆ Polygon(A, G,     ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{2})            ┆   ┆       ┆            ┆           ┆           │
│ 14       ┆ a     ┆ segment  ┆ Segment(A, G, t1) ┆ … ┆ 1     ┆ false      ┆ false     ┆ true      │
│ 15       ┆ c_1   ┆ segment  ┆ Segment(G, O_{2}, ┆ … ┆ 1     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ t1)               ┆   ┆       ┆            ┆           ┆           │
│ 16       ┆ g_1   ┆ segment  ┆ Segment(O_{2}, A, ┆ … ┆ 1     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ t1)               ┆   ┆       ┆            ┆           ┆           │
│ 17       ┆ t2    ┆ triangle ┆ Polygon(A, F_{2}, ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{2})            ┆   ┆       ┆            ┆           ┆           │
│ 18       ┆ a_1   ┆ segment  ┆ Segment(A, F_{2}, ┆ … ┆ 1     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ t2)               ┆   ┆       ┆            ┆           ┆           │
│ 19       ┆ c_2   ┆ segment  ┆ Segment(F_{2},    ┆ … ┆ 1     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ O_{2}, t2)        ┆   ┆       ┆            ┆           ┆           │
│ 20       ┆ i_1   ┆ segment  ┆ Segment(O_{2}, A, ┆ … ┆ 1     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ t2)               ┆   ┆       ┆            ┆           ┆           │
│ 21       ┆ k     ┆ segment  ┆ Segment(A, G)     ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│ 22       ┆ m     ┆ segment  ┆ Segment(A, F_{2}) ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│ 23       ┆ δ     ┆ angle    ┆ Angle(O_{2}, A,   ┆ … ┆ 2     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ G)                ┆   ┆       ┆            ┆           ┆           │
│ 24       ┆ ε     ┆ angle    ┆ Angle(O_{2}, A,   ┆ … ┆ 2     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ F_{2})            ┆   ┆       ┆            ┆           ┆           │
│ 25       ┆ q     ┆ line     ┆ AngleBisector(l,  ┆ … ┆ 2     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ j)                ┆   ┆       ┆            ┆           ┆           │
│ 26       ┆ r     ┆ line     ┆ AngleBisector(l,  ┆ … ┆ 2     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ j)                ┆   ┆       ┆            ┆           ┆           │
│ 27       ┆ e     ┆ circle   ┆ Circle(A, B)      ┆ … ┆ 3     ┆ false      ┆ false     ┆ true      │
│ 28       ┆ A_{1} ┆ point    ┆ Intersect(e, r,   ┆ … ┆ 3     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ 2)                ┆   ┆       ┆            ┆           ┆           │
│ 29       ┆ C_{1} ┆ point    ┆ Intersect(e, j)   ┆ … ┆ 3     ┆ false      ┆ false     ┆ true      │
│ 30       ┆ H     ┆ point    ┆ Intersect(e, j)   ┆ … ┆ 3     ┆ false      ┆ false     ┆ true      │
│ 31       ┆ J     ┆ point    ┆ Intersect(e, l)   ┆ … ┆ 3     ┆ false      ┆ false     ┆ true      │
│ 32       ┆ K     ┆ point    ┆ Intersect(e, l)   ┆ … ┆ 3     ┆ false      ┆ false     ┆ true      │
│ 33       ┆ ζ     ┆ angle    ┆ Angle(A_{1}, A,   ┆ … ┆ 2     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ K)                ┆   ┆       ┆            ┆           ┆           │
│ 34       ┆ η     ┆ angle    ┆ Angle(A_{1}, A,   ┆ … ┆ 2     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ C_{1})            ┆   ┆       ┆            ┆           ┆           │
│ 35       ┆ O_{1} ┆ point    ┆ Point(r)          ┆ … ┆ 9     ┆ true       ┆ true      ┆ false     │
│ 36       ┆ θ     ┆ angle    ┆ Angle(O_{2}, A,   ┆ … ┆ 2     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{1})            ┆   ┆       ┆            ┆           ┆           │
│ 37       ┆ s     ┆ line     ┆ PerpendicularLine ┆ … ┆ 7     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ (O_{1}, j)        ┆   ┆       ┆            ┆           ┆           │
│ 38       ┆ b     ┆ line     ┆ Line(O_{2},       ┆ … ┆ 4     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{1})            ┆   ┆       ┆            ┆           ┆           │
│ 39       ┆ P'    ┆ point    ┆ Intersect(b, j)   ┆ … ┆ 0     ┆ true       ┆ true      ┆ false     │
│ 40       ┆ P     ┆ point    ┆ Intersect(b, l)   ┆ … ┆ 0     ┆ true       ┆ true      ┆ false     │
│ 41       ┆ t     ┆ line     ┆ PerpendicularLine ┆ … ┆ 2     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ (O_{1}, l)        ┆   ┆       ┆            ┆           ┆           │
│ 42       ┆ F_{1} ┆ point    ┆ Intersect(t, l)   ┆ … ┆ 2     ┆ true       ┆ true      ┆ false     │
│ 43       ┆ h_1   ┆ circle   ┆ Circle(O_{1},     ┆ … ┆ 9     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ F_{1})            ┆   ┆       ┆            ┆           ┆           │
│ 44       ┆ j_1   ┆ line     ┆ Tangent(P', h_1)  ┆ … ┆ 0     ┆ true       ┆ false     ┆ false     │
│ 45       ┆ k_1   ┆ line     ┆ Tangent(P', h_1)  ┆ … ┆ 0     ┆ true       ┆ false     ┆ false     │
│ 46       ┆ l_1   ┆ line     ┆ Tangent(P, h_1)   ┆ … ┆ 0     ┆ true       ┆ false     ┆ false     │
│ 47       ┆ m_1   ┆ line     ┆ Tangent(P, h_1)   ┆ … ┆ 0     ┆ true       ┆ false     ┆ false     │
│ 48       ┆ O_3   ┆ point    ┆ Midpoint(O_{2},   ┆ … ┆ 4     ┆ true       ┆ true      ┆ false     │
│          ┆       ┆          ┆ O_{1})            ┆   ┆       ┆            ┆           ┆           │
│ 49       ┆ p_1   ┆ circle   ┆ Circle(O_3,       ┆ … ┆ 4     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{2})            ┆   ┆       ┆            ┆           ┆           │
│ 50       ┆ n_1   ┆ line     ┆ Line(O_{2},       ┆ … ┆ 0     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ F_{2})            ┆   ┆       ┆            ┆           ┆           │
│ 51       ┆ C     ┆ point    ┆ Intersect(p_1, l, ┆ … ┆ 2     ┆ true       ┆ true      ┆ false     │
│          ┆       ┆          ┆ 2)                ┆   ┆       ┆            ┆           ┆           │
│ 52       ┆ q_1   ┆ circle   ┆ Circle(A, F_{1})  ┆ … ┆ 2     ┆ true       ┆ false     ┆ false     │
│ 53       ┆ r_1   ┆ circle   ┆ Circle(A, F_{2})  ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│ 54       ┆ Q     ┆ point    ┆ Intersect(h_1,    ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ j_1)              ┆   ┆       ┆            ┆           ┆           │
│ 55       ┆ R     ┆ point    ┆ Intersect(h_1,    ┆ … ┆ 1     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ k_1)              ┆   ┆       ┆            ┆           ┆           │
│ 56       ┆ D     ┆ point    ┆ Point(p_1)        ┆ … ┆ 4     ┆ false      ┆ false     ┆ false     │
│ 57       ┆ t3    ┆ triangle ┆ Polygon(O_{2},    ┆ … ┆ 4     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{1}, D)         ┆   ┆       ┆            ┆           ┆           │
│ 58       ┆ d     ┆ segment  ┆ Segment(O_{2},    ┆ … ┆ 3     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ O_{1}, t3)        ┆   ┆       ┆            ┆           ┆           │
│ 59       ┆ o     ┆ segment  ┆ Segment(O_{1}, D, ┆ … ┆ 3     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ t3)               ┆   ┆       ┆            ┆           ┆           │
│ 60       ┆ l_2   ┆ segment  ┆ Segment(D, O_{2}, ┆ … ┆ 3     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ t3)               ┆   ┆       ┆            ┆           ┆           │
│ 61       ┆ α     ┆ angle    ┆ Angle(O_{2}, D,   ┆ … ┆ 4     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{1})            ┆   ┆       ┆            ┆           ┆           │
│ 62       ┆ O     ┆ point    ┆ Midpoint(F_{1},   ┆ … ┆ 5     ┆ true       ┆ true      ┆ false     │
│          ┆       ┆          ┆ F_{2})            ┆   ┆       ┆            ┆           ┆           │
│ 63       ┆ f     ┆ line     ┆ PerpendicularLine ┆ … ┆ 5     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ (O, l)            ┆   ┆       ┆            ┆           ┆           │
│ 64       ┆ i     ┆ segment  ┆ Segment(F_{1},    ┆ … ┆ 4     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ F_{2})            ┆   ┆       ┆            ┆           ┆           │
│ 65       ┆ t4    ┆ triangle ┆ Polygon(O_3, A,   ┆ … ┆ 5     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ C)                ┆   ┆       ┆            ┆           ┆           │
│ 66       ┆ c_3   ┆ segment  ┆ Segment(O_3, A,   ┆ … ┆ 5     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ t4)               ┆   ┆       ┆            ┆           ┆           │
│ 67       ┆ i_2   ┆ segment  ┆ Segment(A, C, t4) ┆ … ┆ 5     ┆ false      ┆ false     ┆ true      │
│ 68       ┆ a_2   ┆ segment  ┆ Segment(C, O_3,   ┆ … ┆ 5     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ t4)               ┆   ┆       ┆            ┆           ┆           │
│ 69       ┆ h     ┆ circle   ┆ Circle(C, F_{2})  ┆ … ┆ 2     ┆ true       ┆ false     ┆ false     │
│ 70       ┆ g     ┆ segment  ┆ Segment(A, Q)     ┆ … ┆ 7     ┆ false      ┆ true      ┆ false     │
│ 71       ┆ f_1   ┆ segment  ┆ Segment(A, G)     ┆ … ┆ 7     ┆ false      ┆ true      ┆ false     │
│ 72       ┆ s_1   ┆ segment  ┆ Segment(A, F_{2}) ┆ … ┆ 7     ┆ false      ┆ true      ┆ false     │
│ 73       ┆ d_1   ┆ segment  ┆ Segment(F_{2}, C) ┆ … ┆ 7     ┆ false      ┆ true      ┆ false     │
│ 74       ┆ e_1   ┆ line     ┆ PerpendicularLine ┆ … ┆ 2     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ (F_{2}, l)        ┆   ┆       ┆            ┆           ┆           │
│ 75       ┆ E     ┆ point    ┆ Intersect(p_1, t) ┆ … ┆ 4     ┆ false      ┆ true      ┆ false     │
│ 76       ┆ F     ┆ point    ┆ Intersect(p_1, t) ┆ … ┆ 4     ┆ false      ┆ true      ┆ true      │
│ 77       ┆ f_2   ┆ segment  ┆ Segment(E, O_{2}) ┆ … ┆ 4     ┆ false      ┆ false     ┆ false     │
│ 78       ┆ t5    ┆ triangle ┆ Polygon(O_3,      ┆ … ┆ 5     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{2}, E)         ┆   ┆       ┆            ┆           ┆           │
│ 79       ┆ e_2   ┆ segment  ┆ Segment(O_3,      ┆ … ┆ 6     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ O_{2}, t5)        ┆   ┆       ┆            ┆           ┆           │
│ 80       ┆ o_3   ┆ segment  ┆ Segment(O_{2}, E, ┆ … ┆ 5     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ t5)               ┆   ┆       ┆            ┆           ┆           │
│ 81       ┆ o_{2} ┆ segment  ┆ Segment(E, O_3,   ┆ … ┆ 5     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ t5)               ┆   ┆       ┆            ┆           ┆           │
│ 82       ┆ I     ┆ point    ┆ Intersect(c, k_1, ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ 1)                ┆   ┆       ┆            ┆           ┆           │
│ 83       ┆ t_1   ┆ circle   ┆ Circle(F_{2},     ┆ … ┆ 8     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ Distance(F_{1}, … ┆   ┆       ┆            ┆           ┆           │
│ 84       ┆ C'    ┆ point    ┆ Intersect(t_1, l, ┆ … ┆ 8     ┆ false      ┆ true      ┆ false     │
│          ┆       ┆          ┆ 2)                ┆   ┆       ┆            ┆           ┆           │
│ 85       ┆ b_1   ┆ line     ┆ Tangent(C', c)    ┆ … ┆ 8     ┆ false      ┆ false     ┆ false     │
│ 86       ┆ g_2   ┆ line     ┆ Tangent(C', c)    ┆ … ┆ 8     ┆ false      ┆ false     ┆ false     │
│ 87       ┆ O''   ┆ point    ┆ Midpoint(C',      ┆ … ┆ 8     ┆ false      ┆ true      ┆ false     │
│          ┆       ┆          ┆ O_{1})            ┆   ┆       ┆            ┆           ┆           │
│ 88       ┆ h_2   ┆ circle   ┆ Circle(O'', C')   ┆ … ┆ 8     ┆ false      ┆ false     ┆ false     │
│ 89       ┆ j_2   ┆ line     ┆ Line(C', O_{1})   ┆ … ┆ 8     ┆ false      ┆ false     ┆ false     │
│ 90       ┆ k_2   ┆ circle   ┆ Circle(O_{2},     ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ Radius(c) - Radi… ┆   ┆       ┆            ┆           ┆           │
│ 91       ┆ p_2   ┆ circle   ┆ Circle(O_{2},     ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ Radius(c) + Radi… ┆   ┆       ┆            ┆           ┆           │
│ 92       ┆ m_2   ┆ line     ┆ Tangent(O_{1},    ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ k_2)              ┆   ┆       ┆            ┆           ┆           │
│ 93       ┆ n_2   ┆ line     ┆ Tangent(O_{1},    ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ k_2)              ┆   ┆       ┆            ┆           ┆           │
│ 94       ┆ q_2   ┆ line     ┆ Tangent(O_{1},    ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ p_2)              ┆   ┆       ┆            ┆           ┆           │
│ 95       ┆ r_2   ┆ line     ┆ Tangent(O_{1},    ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ p_2)              ┆   ┆       ┆            ┆           ┆           │
│ 96       ┆ L     ┆ point    ┆ Intersect(k_2,    ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ m_2)              ┆   ┆       ┆            ┆           ┆           │
│ 97       ┆ M     ┆ point    ┆ Intersect(p_2,    ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ r_2)              ┆   ┆       ┆            ┆           ┆           │
│ 98       ┆ N     ┆ point    ┆ Intersect(p_2,    ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ q_2)              ┆   ┆       ┆            ┆           ┆           │
│ 99       ┆ S     ┆ point    ┆ Intersect(k_2,    ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ n_2)              ┆   ┆       ┆            ┆           ┆           │
│ 100      ┆ s_2   ┆ ray      ┆ Ray(O_{2}, L)     ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│ 101      ┆ t_2   ┆ ray      ┆ Ray(O_{2}, S)     ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│ 102      ┆ b_2   ┆ ray      ┆ Ray(O_{2}, M)     ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│ 103      ┆ d_2   ┆ ray      ┆ Ray(O_{2}, N)     ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│ 104      ┆ T     ┆ point    ┆ Intersect(c, d_2) ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│ 105      ┆ ι     ┆ angle    ┆ Angle(F_{2}, C,   ┆ … ┆ 8     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{2})            ┆   ┆       ┆            ┆           ┆           │
│ 106      ┆ κ     ┆ angle    ┆ Angle(I, C,       ┆ … ┆ 8     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{2})            ┆   ┆       ┆            ┆           ┆           │
│ 107      ┆ λ     ┆ angle    ┆ Angle(R, C,       ┆ … ┆ 8     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{1})            ┆   ┆       ┆            ┆           ┆           │
│ 108      ┆ μ     ┆ angle    ┆ Angle(F_{2}, C,   ┆ … ┆ 8     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{1})            ┆   ┆       ┆            ┆           ┆           │
│ 109      ┆ f_3   ┆ segment  ┆ Segment(O_{2}, C) ┆ … ┆ 2     ┆ true       ┆ false     ┆ false     │
│ 110      ┆ g_3   ┆ segment  ┆ Segment(O_{1}, C) ┆ … ┆ 2     ┆ true       ┆ false     ┆ false     │
└──────────┴───────┴──────────┴───────────────────┴───┴───────┴────────────┴───────────┴───────────┘

## ggblab_extra — construction tree parser

Use `ConstructionTreeParser` to build a graph of construction dependencies and perform graph analyses. The examples below show how to:

- Create the parser with `p = ConstructionTreeParser(df)`
- Build the full dependency graph with `g1 = p.parse()`
- Extract bounded subgraphs with `g2 = p.parse_subgraph(max_depth=3)`

These operations are for inspection and analysis; they help you visualize and trace construction dependency paths.

In [57]:
from ggblab_extra.construction_parser import ConstructionTreeParser

In [58]:
p = ConstructionTreeParser(df)

In [59]:
g1 = p.parse()

In [60]:
labels_map = {}
for n, t in p.df["Name", "Type"].rows():
    g1.nodes[n]["label"] = f"{n} ({t})"

In [61]:
nx.write_network_text(g1)

╟── O_{2} (point)
╎   ├─╼ B (point) ╾ A (point)
╎   │   ├─╼ c (circle) ╾ O_{2} (point)
╎   │   │   ├─╼ G (point) ╾ p (circle)
╎   │   │   │   ├─╼ β (angle) ╾ A (point), O_{2} (point)
╎   │   │   │   ├─╼ t1 (triangle) ╾ A (point), O_{2} (point)
╎   │   │   │   │   ├─╼ a (segment) ╾ A (point), G (point)
╎   │   │   │   │   ├─╼ c_1 (segment) ╾ G (point), O_{2} (point)
╎   │   │   │   │   └─╼ g_1 (segment) ╾ O_{2} (point), A (point)
╎   │   │   │   ├─╼ k (segment) ╾ A (point)
╎   │   │   │   ├─╼ δ (angle) ╾ O_{2} (point), A (point)
╎   │   │   │   ├─╼ f_1 (segment) ╾ A (point)
╎   │   │   │   └─╼  ...
╎   │   │   ├─╼ F_{2} (point) ╾ p (circle)
╎   │   │   │   ├─╼ γ (angle) ╾ A (point), O_{2} (point)
╎   │   │   │   ├─╼ t2 (triangle) ╾ A (point), O_{2} (point)
╎   │   │   │   │   ├─╼ a_1 (segment) ╾ A (point), F_{2} (point)
╎   │   │   │   │   ├─╼ c_2 (segment) ╾ F_{2} (point), O_{2} (point)
╎   │   │   │   │   └─╼ i_1 (segment) ╾ O_{2} (point), A (point)
╎   │   │   │   ├─╼ m (segment) ╾ A (point)
╎   │   │   │   ├─╼ ε (angle) ╾ O_{2} (point), A (point)
╎   │   │   │   ├─╼ n_1 (line) ╾ O_{2} (point)
╎   │   │   │   ├─╼ r_1 (circle) ╾ A (point)
╎   │   │   │   ├─╼ O (point) ╾ F_{1} (point)
╎   │   │   │   │   └─╼ f (line) ╾ l (line)
╎   │   │   │   ├─╼ i (segment) ╾ F_{1} (point)
╎   │   │   │   ├─╼ h (circle) ╾ C (point)
╎   │   │   │   ├─╼ s_1 (segment) ╾ A (point)
╎   │   │   │   ├─╼ d_1 (segment) ╾ C (point)
╎   │   │   │   ├─╼ e_1 (line) ╾ l (line)
╎   │   │   │   ├─╼ t_1 (circle) ╾ F_{1} (point), A (point)
╎   │   │   │   │   └─╼ C' (point) ╾ l (line)
╎   │   │   │   │       ├─╼ b_1 (line) ╾ c (circle)
╎   │   │   │   │       ├─╼ g_2 (line) ╾ c (circle)
╎   │   │   │   │       ├─╼ O'' (point) ╾ O_{1} (point)
╎   │   │   │   │       │   └─╼ h_2 (circle) ╾ C' (point)
╎   │   │   │   │       ├─╼ j_2 (line) ╾ O_{1} (point)
╎   │   │   │   │       └─╼  ...
╎   │   │   │   ├─╼ ι (angle) ╾ C (point), O_{2} (point)
╎   │   │   │   ├─╼ μ (angle) ╾ C (point), O_{1} (point)
╎   │   │   │   └─╼  ...
╎   │   │   ├─╼ j (line) ╾ A (point)
╎   │   │   │   ├─╼ q (line) ╾ l (line)
╎   │   │   │   ├─╼ r (line) ╾ l (line)
╎   │   │   │   │   ├─╼ A_{1} (point) ╾ e (circle)
╎   │   │   │   │   │   ├─╼ ζ (angle) ╾ A (point), K (point)
╎   │   │   │   │   │   └─╼ η (angle) ╾ A (point), C_{1} (point)
╎   │   │   │   │   └─╼ O_{1} (point)
╎   │   │   │   │       ├─╼ θ (angle) ╾ O_{2} (point), A (point)
╎   │   │   │   │       ├─╼ s (line) ╾ j (line)
╎   │   │   │   │       ├─╼ b (line) ╾ O_{2} (point)
╎   │   │   │   │       │   ├─╼ P' (point) ╾ j (line)
╎   │   │   │   │       │   │   ├─╼ j_1 (line) ╾ h_1 (circle)
╎   │   │   │   │       │   │   │   └─╼ Q (point) ╾ h_1 (circle)
╎   │   │   │   │       │   │   │       └─╼ g (segment) ╾ A (point)
╎   │   │   │   │       │   │   └─╼ k_1 (line) ╾ h_1 (circle)
╎   │   │   │   │       │   │       ├─╼ R (point) ╾ h_1 (circle)
╎   │   │   │   │       │   │       │   └─╼ λ (angle) ╾ C (point), O_{1} (point)
╎   │   │   │   │       │   │       └─╼ I (point) ╾ c (circle)
╎   │   │   │   │       │   │           └─╼ κ (angle) ╾ C (point), O_{2} (point)
╎   │   │   │   │       │   └─╼ P (point) ╾ l (line)
╎   │   │   │   │       │       ├─╼ l_1 (line) ╾ h_1 (circle)
╎   │   │   │   │       │       └─╼ m_1 (line) ╾ h_1 (circle)
╎   │   │   │   │       ├─╼ t (line) ╾ l (line)
╎   │   │   │   │       │   ├─╼ F_{1} (point) ╾ l (line)
╎   │   │   │   │       │   │   ├─╼ h_1 (circle) ╾ O_{1} (point)
╎   │   │   │   │       │   │   │   ├─╼ k_2 (circle) ╾ O_{2} (point), c (circle)
╎   │   │   │   │       │   │   │   │   ├─╼ m_2 (line) ╾ O_{1} (point)
╎   │   │   │   │       │   │   │   │   │   └─╼ L (point) ╾ k_2 (circle)
╎   │   │   │   │       │   │   │   │   │       └─╼ s_2 (ray) ╾ O_{2} (point)
╎   │   │   │   │       │   │   │   │   ├─╼ n_2 (line) ╾ O_{1} (point)
╎   │   │   │   │       │   │   │   │   │   └─╼ S (point) ╾ k_2 (circle)
╎   │   │   │   │       │   │   │   │   │       └─╼ t_2 (ray) ╾ O_{2} (point)
╎   │   │   │   │       │   │   │   │   └─╼  ...
╎   │   │   │   │       │   │   │   ├─╼ p_2 (circle) ╾ O_{2} (point), c (circle)
╎   │   │   │   │       │   │   │   │   ├─╼ q_2 (line) ╾ O_{1} (point)
╎   │   │   │   │       │   │   │   │   │   └─╼ N (point) ╾ p_2 (circle)
╎   │   │   │   │       │   │   │   │   │       └─╼ d_2 (ray) ╾ O_{2} (point)
╎   │   │   │   │       │   │   │   │   │           └─╼ T (point) ╾ c (circle)
╎   │   │   │   │       │   │   │   │   ├─╼ r_2 (line) ╾ O_{1} (point)
╎   │   │   │   │       │   │   │   │   │   └─╼ M (point) ╾ p_2 (circle)
╎   │   │   │   │       │   │   │   │   │       └─╼ b_2 (ray) ╾ O_{2} (point)
╎   │   │   │   │       │   │   │   │   └─╼  ...
╎   │   │   │   │       │   │   │   └─╼  ...
╎   │   │   │   │       │   │   ├─╼ q_1 (circle) ╾ A (point)
╎   │   │   │   │       │   │   └─╼  ...
╎   │   │   │   │       │   ├─╼ E (point) ╾ p_1 (circle)
╎   │   │   │   │       │   │   ├─╼ f_2 (segment) ╾ O_{2} (point)
╎   │   │   │   │       │   │   ├─╼ t5 (triangle) ╾ O_3 (point), O_{2} (point)
╎   │   │   │   │       │   │   │   ├─╼ e_2 (segment) ╾ O_3 (point), O_{2} (point)
╎   │   │   │   │       │   │   │   ├─╼ o_3 (segment) ╾ O_{2} (point), E (point)
╎   │   │   │   │       │   │   │   └─╼ o_{2} (segment) ╾ E (point), O_3 (point)
╎   │   │   │   │       │   │   └─╼  ...
╎   │   │   │   │       │   └─╼ F (point) ╾ p_1 (circle)
╎   │   │   │   │       ├─╼ O_3 (point) ╾ O_{2} (point)
╎   │   │   │   │       │   ├─╼ p_1 (circle) ╾ O_{2} (point)
╎   │   │   │   │       │   │   ├─╼ C (point) ╾ l (line)
╎   │   │   │   │       │   │   │   ├─╼ t4 (triangle) ╾ O_3 (point), A (point)
╎   │   │   │   │       │   │   │   │   ├─╼ c_3 (segment) ╾ O_3 (point), A (point)
╎   │   │   │   │       │   │   │   │   ├─╼ i_2 (segment) ╾ A (point), C (point)
╎   │   │   │   │       │   │   │   │   └─╼ a_2 (segment) ╾ C (point), O_3 (point)
╎   │   │   │   │       │   │   │   ├─╼ f_3 (segment) ╾ O_{2} (point)
╎   │   │   │   │       │   │   │   ├─╼ g_3 (segment) ╾ O_{1} (point)
╎   │   │   │   │       │   │   │   └─╼  ...
╎   │   │   │   │       │   │   ├─╼ D (point)
╎   │   │   │   │       │   │   │   ├─╼ t3 (triangle) ╾ O_{2} (point), O_{1} (point)
╎   │   │   │   │       │   │   │   │   ├─╼ d (segment) ╾ O_{2} (point), O_{1} (point)
╎   │   │   │   │       │   │   │   │   ├─╼ o (segment) ╾ O_{1} (point), D (point)
╎   │   │   │   │       │   │   │   │   └─╼ l_2 (segment) ╾ D (point), O_{2} (point)
╎   │   │   │   │       │   │   │   ├─╼ α (angle) ╾ O_{2} (point), O_{1} (point)
╎   │   │   │   │       │   │   │   └─╼  ...
╎   │   │   │   │       │   │   └─╼  ...
╎   │   │   │   │       │   └─╼  ...
╎   │   │   │   │       └─╼  ...
╎   │   │   │   ├─╼ C_{1} (point) ╾ e (circle)
╎   │   │   │   │   └─╼  ...
╎   │   │   │   ├─╼ H (point) ╾ e (circle)
╎   │   │   │   └─╼  ...
╎   │   │   ├─╼ l (line) ╾ A (point)
╎   │   │   │   ├─╼ J (point) ╾ e (circle)
╎   │   │   │   ├─╼ K (point) ╾ e (circle)
╎   │   │   │   │   └─╼  ...
╎   │   │   │   └─╼  ...
╎   │   │   └─╼  ...
╎   │   └─╼ e (circle) ╾ A (point)
╎   │       └─╼  ...
╎   ├─╼ n (line) ╾ A (point)
╎   ├─╼ O' (point) ╾ A (point)
╎   │   └─╼ p (circle) ╾ A (point)
╎   │       └─╼  ...
╎   └─╼  ...
╙── A (point)
    └─╼  ...

In [62]:
g2 = p.parse_subgraph(max_depth=3)

parse_subgraph: timeout exceeded during candidate evaluation (10.00s), falling back to parse_subgraph_legacy

In [63]:
nx.write_network_text(g2)

╟── O_{2}
╎   ├─╼ B ╾ A
╎   │   ├─╼ e
╎   │   └─╼ c
╎   │       ├─╼ l
╎   │       │   └─╼ r ╾ j
╎   │       │       └─╼ O_{1}
╎   │       │           ├─╼ t
╎   │       │           │   └─╼ F_{1}
╎   │       │           │       ├─╼ h_1
╎   │       │           │       │   ├─╼ p_2
╎   │       │           │       │   │   ├─╼ q_2
╎   │       │           │       │   │   │   └─╼ N
╎   │       │           │       │   │   └─╼ r_2
╎   │       │           │       │   ├─╼ k_2
╎   │       │           │       │   │   ├─╼ m_2
╎   │       │           │       │   │   └─╼ n_2
╎   │       │           │       │   ├─╼ k_1
╎   │       │           │       │   └─╼ j_1
╎   │       │           │       └─╼ t_1
╎   │       │           │           └─╼ C'
╎   │       │           ├─╼ b
╎   │       │           │   └─╼ P'
╎   │       │           └─╼ O_3
╎   │       │               └─╼ p_1
╎   │       │                   ├─╼ C
╎   │       │                   ├─╼ E
╎   │       │                   └─╼ D
╎   │       ├─╼ j
╎   │       │   └─╼  ...
╎   │       ├─╼ G ╾ p
╎   │       └─╼ F_{2} ╾ p
╎   └─╼ O' ╾ A
╎       └─╼ p
╎           └─╼  ...
╙── A
    └─╼  ...

In [64]:
p.df.filter(~pl.col("Auxiliary"))["Sequence", "Type", "Name", "Command", "Value", "Layer", "DependsOn"]

shape: (87, 7)
┌──────────┬──────────┬───────┬────────────────────┬───────────────────┬───────┬───────────────────┐
│ Sequence ┆ Type     ┆ Name  ┆ Command            ┆ Value             ┆ Layer ┆ DependsOn         │
│ ---      ┆ ---      ┆ ---   ┆ ---                ┆ ---               ┆ ---   ┆ ---               │
│ u32      ┆ str      ┆ str   ┆ str                ┆ str               ┆ u32   ┆ list[str]         │
╞══════════╪══════════╪═══════╪════════════════════╪═══════════════════╪═══════╪═══════════════════╡
│ 0        ┆ point    ┆ O_{2} ┆ null               ┆ O_{2} = (-2.1,    ┆ 9     ┆ []                │
│          ┆          ┆       ┆                    ┆ -0.1)             ┆       ┆                   │
│ 1        ┆ point    ┆ A     ┆ null               ┆ A = (10, 0)       ┆ 2     ┆ []                │
│ 2        ┆ point    ┆ B     ┆ Point(Line(O_{2},  ┆ B = (-9.6, -0.2)  ┆ 9     ┆ ["A", "O_{2}"]    │
│          ┆          ┆       ┆ A))                ┆                   ┆       ┆                   │
│ 3        ┆ circle   ┆ c     ┆ Circle(O_{2}, B)   ┆ c: (x + 2.1)² +   ┆ 9     ┆ ["A", "B",        │
│          ┆          ┆       ┆                    ┆ (y + 0.1)² = 5…   ┆       ┆ "O_{2}"]          │
│ 4        ┆ line     ┆ n     ┆ Line(O_{2}, A)     ┆ n: y = -0.1       ┆ 3     ┆ ["A", "O_{2}"]    │
│ 5        ┆ point    ┆ O'    ┆ Midpoint(O_{2}, A) ┆ O' = (3.9, 0)     ┆ 3     ┆ ["A", "O_{2}"]    │
│ 6        ┆ circle   ┆ p     ┆ Circle(O', A)      ┆ p: (x - 3.9)² +   ┆ 3     ┆ ["A", "O'",       │
│          ┆          ┆       ┆                    ┆ (y + 0)² = 36.…   ┆       ┆ "O_{2}"]          │
│ 7        ┆ point    ┆ G     ┆ Intersect(c, p)    ┆ G = (2.4, 5.8)    ┆ 1     ┆ ["A", "B", … "p"] │
│ 8        ┆ point    ┆ F_{2} ┆ Intersect(c, p)    ┆ F_{2} = (2.5,     ┆ 1     ┆ ["A", "B", … "p"] │
│          ┆          ┆       ┆                    ┆ -5.9)             ┆       ┆                   │
│ 9        ┆ line     ┆ j     ┆ Tangent(A, c)      ┆ j: -5.8x - 7.6y = ┆ 2     ┆ ["A", "B", … "c"] │
│          ┆          ┆       ┆                    ┆ -58.2             ┆       ┆                   │
│ 10       ┆ line     ┆ l     ┆ Tangent(A, c)      ┆ l: 5.9x - 7.5y =  ┆ 2     ┆ ["A", "B", … "c"] │
│          ┆          ┆       ┆                    ┆ 59.4              ┆       ┆                   │
│ 11       ┆ angle    ┆ β     ┆ Angle(A, G, O_{2}) ┆ β = 90°           ┆ 3     ┆ ["A", "B", … "p"] │
│ 12       ┆ angle    ┆ γ     ┆ Angle(A, F_{2},    ┆ γ = 90°           ┆ 3     ┆ ["A", "B", … "p"] │
│          ┆          ┆       ┆ O_{2})             ┆                   ┆       ┆                   │
│ 13       ┆ triangle ┆ t1    ┆ Polygon(A, G,      ┆ t1 = 35.7         ┆ 3     ┆ ["A", "B", … "p"] │
│          ┆          ┆       ┆ O_{2})             ┆                   ┆       ┆                   │
│ 17       ┆ triangle ┆ t2    ┆ Polygon(A, F_{2},  ┆ t2 = 35.7         ┆ 3     ┆ ["A", "B", … "p"] │
│          ┆          ┆       ┆ O_{2})             ┆                   ┆       ┆                   │
│ 21       ┆ segment  ┆ k     ┆ Segment(A, G)      ┆ k = 9.6           ┆ 3     ┆ ["A", "B", … "p"] │
│ 22       ┆ segment  ┆ m     ┆ Segment(A, F_{2})  ┆ m = 9.6           ┆ 3     ┆ ["A", "B", … "p"] │
│ 23       ┆ angle    ┆ δ     ┆ Angle(O_{2}, A, G) ┆ δ = 37.9°         ┆ 2     ┆ ["A", "B", … "p"] │
│ 24       ┆ angle    ┆ ε     ┆ Angle(O_{2}, A,    ┆ ε = 37.9°         ┆ 2     ┆ ["A", "B", … "p"] │
│          ┆          ┆       ┆ F_{2})             ┆                   ┆       ┆                   │
│ 25       ┆ line     ┆ q     ┆ AngleBisector(l,   ┆ q: 0x - 1y = 0.1  ┆ 2     ┆ ["A", "B", … "l"] │
│          ┆          ┆       ┆ j)                 ┆                   ┆       ┆                   │
│ 26       ┆ line     ┆ r     ┆ AngleBisector(l,   ┆ r: 1x = 10        ┆ 2     ┆ ["A", "B", … "l"] │
│          ┆          ┆       ┆ j)                 ┆                   ┆       ┆                   │
│ 33       ┆ angle    ┆ ζ     ┆ Angle(A_{1}, A, K) ┆ ζ = 52.1°         ┆ 2     ┆ ["A", "A_{1}", …  │
│          ┆          ┆       ┆                    ┆                   ┆       ┆ "r"]              │
│ 34       ┆ angle    ┆ η     ┆ Angle(A_{1}, A,    ┆ η = 52.1°         ┆ 2     ┆ ["A", "A_{1}", …  │
│          ┆          ┆       ┆ C_{1})             ┆                   ┆       ┆ "r"]              │
│ 35       ┆ point    ┆ O_{1} ┆ Point(r)           ┆ O_{1} = (10,      ┆ 9     ┆ ["A", "B", … "r"] │
│          ┆          ┆       ┆                    ┆ -4.8)             ┆       ┆                   │
│ 36       ┆ angle    ┆ θ     ┆ Angle(O_{2}, A,    ┆ θ = 90°           ┆ 2     ┆ ["A", "B", … "r"] │
│          ┆          ┆       ┆ O_{1})             ┆                   ┆       ┆                   │
│ 38       ┆ line     ┆ b     ┆ Line(O_{2}, O_{1}) ┆ b: y = -0.4x -    ┆ 4     ┆ ["A", "B", … "r"] │
│          ┆          ┆       ┆                    ┆ 0.9               ┆       ┆                   │
│ 39       ┆ point    ┆ P'    ┆ Intersect(b, j)    ┆ P' = (22.6, -9.7) ┆ 0     ┆ ["A", "B", … "r"] │
│ 40       ┆ point    ┆ P     ┆ Intersect(b, l)    ┆ P = (5.9, -3.2)   ┆ 0     ┆ ["A", "B", … "r"] │
│ 41       ┆ line     ┆ t     ┆ PerpendicularLine( ┆ t: 7.5x + 5.9y =  ┆ 2     ┆ ["A", "B", … "r"] │
│          ┆          ┆       ┆ O_{1}, l)          ┆ 46.7              ┆       ┆                   │
│ 42       ┆ point    ┆ F_{1} ┆ Intersect(t, l)    ┆ F_{1} = (7.7,     ┆ 2     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆                    ┆ -1.8)             ┆       ┆                   │
│ 43       ┆ circle   ┆ h_1   ┆ Circle(O_{1},      ┆ h_1: (x - 10)² +  ┆ 9     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆ F_{1})             ┆ (y + 4.8)² = …    ┆       ┆                   │
│ 44       ┆ line     ┆ j_1   ┆ Tangent(P', h_1)   ┆ j_1: -7.9x -      ┆ 0     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆                    ┆ 10.3y = -78.9     ┆       ┆                   │
│ 45       ┆ line     ┆ k_1   ┆ Tangent(P', h_1)   ┆ k_1: -1.1x -      ┆ 0     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆                    ┆ 12.9y = 100.3     ┆       ┆                   │
│ 46       ┆ line     ┆ l_1   ┆ Tangent(P, h_1)    ┆ l_1: 2.2x + 0.4y  ┆ 0     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆                    ┆ = 11.9            ┆       ┆                   │
│ 47       ┆ line     ┆ m_1   ┆ Tangent(P, h_1)    ┆ m_1: -1.4x + 1.7y ┆ 0     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆                    ┆ = -13.8           ┆       ┆                   │
│ 48       ┆ point    ┆ O_3   ┆ Midpoint(O_{2},    ┆ O_3 = (4, -2.5)   ┆ 4     ┆ ["A", "B", … "r"] │
│          ┆          ┆       ┆ O_{1})             ┆                   ┆       ┆                   │
│ 49       ┆ circle   ┆ p_1   ┆ Circle(O_3, O_{2}) ┆ p_1: (x - 4)² +   ┆ 4     ┆ ["A", "B", … "r"] │
│          ┆          ┆       ┆                    ┆ (y + 2.5)² = 4…   ┆       ┆                   │
│ 51       ┆ point    ┆ C     ┆ Intersect(p_1, l,  ┆ C = (0.2, -7.8)   ┆ 2     ┆ ["A", "B", … "r"] │
│          ┆          ┆       ┆ 2)                 ┆                   ┆       ┆                   │
│ 52       ┆ circle   ┆ q_1   ┆ Circle(A, F_{1})   ┆ q_1: (x - 10)² +  ┆ 2     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆                    ┆ y² = 8.8          ┆       ┆                   │
│ 53       ┆ circle   ┆ r_1   ┆ Circle(A, F_{2})   ┆ r_1: (x - 10)² +  ┆ 3     ┆ ["A", "B", … "p"] │
│          ┆          ┆       ┆                    ┆ y² = 91.6         ┆       ┆                   │
│ 54       ┆ point    ┆ Q     ┆ Intersect(h_1,     ┆ Q = (12.3, -1.8)  ┆ 1     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆ j_1)               ┆                   ┆       ┆                   │
│ 55       ┆ point    ┆ R     ┆ Intersect(h_1,     ┆ R = (9.7, -8.6)   ┆ 1     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆ k_1)               ┆                   ┆       ┆                   │
│ 56       ┆ point    ┆ D     ┆ Point(p_1)         ┆ D = (0.4, -7.9)   ┆ 4     ┆ ["A", "B", … "r"] │
│ 57       ┆ triangle ┆ t3    ┆ Polygon(O_{2},     ┆ t3 = 41.7         ┆ 4     ┆ ["A", "B", … "r"] │
│          ┆          ┆       ┆ O_{1}, D)          ┆                   ┆       ┆                   │
│ 61       ┆ angle    ┆ α     ┆ Angle(O_{2}, D,    ┆ α = 90°           ┆ 4     ┆ ["A", "B", … "r"] │
│          ┆          ┆       ┆ O_{1})             ┆                   ┆       ┆                   │
│ 62       ┆ point    ┆ O     ┆ Midpoint(F_{1},    ┆ O = (5.1, -3.9)   ┆ 5     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆ F_{2})             ┆                   ┆       ┆                   │
│ 63       ┆ line     ┆ f     ┆ PerpendicularLine( ┆ f: 7.5x + 5.9y =  ┆ 5     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆ O, l)              ┆ 15                ┆       ┆                   │
│ 64       ┆ segment  ┆ i     ┆ Segment(F_{1},     ┆ i = 6.6           ┆ 4     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆ F_{2})             ┆                   ┆       ┆                   │
│ 65       ┆ triangle ┆ t4    ┆ Polygon(O_3, A, C) ┆ t4 = 11.5         ┆ 5     ┆ ["A", "B", … "r"] │
│ 69       ┆ circle   ┆ h     ┆ Circle(C, F_{2})   ┆ h: (x - 0.2)² +   ┆ 2     ┆ ["A", "B", … "r"] │
│          ┆          ┆       ┆                    ┆ (y + 7.8)² = 8…   ┆       ┆                   │
│ 70       ┆ segment  ┆ g     ┆ Segment(A, Q)      ┆ g = 3             ┆ 7     ┆ ["A", "B", … "t"] │
│ 71       ┆ segment  ┆ f_1   ┆ Segment(A, G)      ┆ f_1 = 9.6         ┆ 7     ┆ ["A", "B", … "p"] │
│ 72       ┆ segment  ┆ s_1   ┆ Segment(A, F_{2})  ┆ s_1 = 9.6         ┆ 7     ┆ ["A", "B", … "p"] │
│ 73       ┆ segment  ┆ d_1   ┆ Segment(F_{2}, C)  ┆ d_1 = 3           ┆ 7     ┆ ["A", "B", … "r"] │
│ 74       ┆ line     ┆ e_1   ┆ PerpendicularLine( ┆ e_1: 7.5x + 5.9y  ┆ 2     ┆ ["A", "B", … "p"] │
│          ┆          ┆       ┆ F_{2}, l)          ┆ = -16.6           ┆       ┆                   │
│ 75       ┆ point    ┆ E     ┆ Intersect(p_1, t)  ┆ E = (3, 4)        ┆ 4     ┆ ["A", "B", … "t"] │
│ 77       ┆ segment  ┆ f_2   ┆ Segment(E, O_{2})  ┆ f_2 = 6.6         ┆ 4     ┆ ["A", "B", … "t"] │
│ 78       ┆ triangle ┆ t5    ┆ Polygon(O_3,       ┆ t5 = 18.6         ┆ 5     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆ O_{2}, E)          ┆                   ┆       ┆                   │
│ 82       ┆ point    ┆ I     ┆ Intersect(c, k_1,  ┆ I = (-2.8, -7.5)  ┆ 1     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆ 1)                 ┆                   ┆       ┆                   │
│ 83       ┆ circle   ┆ t_1   ┆ Circle(F_{2},      ┆ t_1: (x - 2.5)² + ┆ 8     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆ Distance(F_{1}, …  ┆ (y + 5.9)² =…     ┆       ┆                   │
│ 84       ┆ point    ┆ C'    ┆ Intersect(t_1, l,  ┆ C' = (0.2, -7.8)  ┆ 8     ┆ ["A", "B", …      │
│          ┆          ┆       ┆ 2)                 ┆                   ┆       ┆ "t_1"]            │
│ 85       ┆ line     ┆ b_1   ┆ Tangent(C', c)     ┆ b_1: -1.8x + 2.3y ┆ 8     ┆ ["A", "B", …      │
│          ┆          ┆       ┆                    ┆ = -18.4           ┆       ┆ "t_1"]            │
│ 86       ┆ line     ┆ g_2   ┆ Tangent(C', c)     ┆ g_2: -0.3x - 2.9y ┆ 8     ┆ ["A", "B", …      │
│          ┆          ┆       ┆                    ┆ = 22.9            ┆       ┆ "t_1"]            │
│ 87       ┆ point    ┆ O''   ┆ Midpoint(C',       ┆ O'' = (5.1, -6.3) ┆ 8     ┆ ["A", "B", …      │
│          ┆          ┆       ┆ O_{1})             ┆                   ┆       ┆ "t_1"]            │
│ 88       ┆ circle   ┆ h_2   ┆ Circle(O'', C')    ┆ h_2: (x - 5.1)² + ┆ 8     ┆ ["A", "B", …      │
│          ┆          ┆       ┆                    ┆ (y + 6.3)² =…     ┆       ┆ "t_1"]            │
│ 89       ┆ line     ┆ j_2   ┆ Line(C', O_{1})    ┆ j_2: y = 0.3x -   ┆ 8     ┆ ["A", "B", …      │
│          ┆          ┆       ┆                    ┆ 7.8               ┆       ┆ "t_1"]            │
│ 90       ┆ circle   ┆ k_2   ┆ Circle(O_{2},      ┆ k_2: (x + 2.1)² + ┆ 1     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆ Radius(c) - Radi…  ┆ (y + 0.1)² =…     ┆       ┆                   │
│ 91       ┆ circle   ┆ p_2   ┆ Circle(O_{2},      ┆ p_2: (x + 2.1)² + ┆ 1     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆ Radius(c) + Radi…  ┆ (y + 0.1)² =…     ┆       ┆                   │
│ 92       ┆ line     ┆ m_2   ┆ Tangent(O_{1},     ┆ m_2: -7.6x - 9.9y ┆ 1     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆ k_2)               ┆ = -28.7           ┆       ┆                   │
│ 93       ┆ line     ┆ n_2   ┆ Tangent(O_{1},     ┆ n_2: -1.1x -      ┆ 1     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆ k_2)               ┆ 12.5y = 49.4      ┆       ┆                   │
│ 94       ┆ line     ┆ q_2   ┆ Tangent(O_{1},     ┆ q_2: -6.5x - 1.1y ┆ 1     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆ p_2)               ┆ = -60.4           ┆       ┆                   │
│ 95       ┆ line     ┆ r_2   ┆ Tangent(O_{1},     ┆ r_2: 4.1x - 5.2y  ┆ 1     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆ p_2)               ┆ = 66.1            ┆       ┆                   │
│ 96       ┆ point    ┆ L     ┆ Intersect(k_2,     ┆ L = (0.1, 2.8)    ┆ 1     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆ m_2)               ┆                   ┆       ┆                   │
│ 97       ┆ point    ┆ M     ┆ Intersect(p_2,     ┆ M = (4.9, -8.9)   ┆ 1     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆ r_2)               ┆                   ┆       ┆                   │
│ 98       ┆ point    ┆ N     ┆ Intersect(p_2,     ┆ N = (9, 1.7)      ┆ 1     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆ q_2)               ┆                   ┆       ┆                   │
│ 99       ┆ point    ┆ S     ┆ Intersect(k_2,     ┆ S = (-2.4, -3.8)  ┆ 1     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆ n_2)               ┆                   ┆       ┆                   │
│ 100      ┆ ray      ┆ s_2   ┆ Ray(O_{2}, L)      ┆ s_2: y = 1.3x +   ┆ 1     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆                    ┆ 2.7               ┆       ┆                   │
│ 101      ┆ ray      ┆ t_2   ┆ Ray(O_{2}, S)      ┆ t_2: y = 11.8x +  ┆ 1     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆                    ┆ 25                ┆       ┆                   │
│ 102      ┆ ray      ┆ b_2   ┆ Ray(O_{2}, M)      ┆ b_2: y = -1.3x -  ┆ 1     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆                    ┆ 2.8               ┆       ┆                   │
│ 103      ┆ ray      ┆ d_2   ┆ Ray(O_{2}, N)      ┆ d_2: y = 0.2x +   ┆ 1     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆                    ┆ 0.2               ┆       ┆                   │
│ 104      ┆ point    ┆ T     ┆ Intersect(c, d_2)  ┆ T = (5.2, 1.1)    ┆ 1     ┆ ["A", "B", … "t"] │
│ 105      ┆ angle    ┆ ι     ┆ Angle(F_{2}, C,    ┆ ι = 68.4°         ┆ 8     ┆ ["A", "B", … "r"] │
│          ┆          ┆       ┆ O_{2})             ┆                   ┆       ┆                   │
│ 106      ┆ angle    ┆ κ     ┆ Angle(I, C, O_{2}) ┆ κ = 68.4°         ┆ 8     ┆ ["A", "B", … "t"] │
│ 107      ┆ angle    ┆ λ     ┆ Angle(R, C, O_{1}) ┆ λ = 21.6°         ┆ 8     ┆ ["A", "B", … "t"] │
│ 108      ┆ angle    ┆ μ     ┆ Angle(F_{2}, C,    ┆ μ = 21.6°         ┆ 8     ┆ ["A", "B", … "r"] │
│          ┆          ┆       ┆ O_{1})             ┆                   ┆       ┆                   │
│ 109      ┆ segment  ┆ f_3   ┆ Segment(O_{2}, C)  ┆ f_3 = 8           ┆ 2     ┆ ["A", "B", … "r"] │
│ 110      ┆ segment  ┆ g_3   ┆ Segment(O_{1}, C)  ┆ g_3 = 10.3        ┆ 2     ┆ ["A", "B", … "r"] │
└──────────┴──────────┴───────┴────────────────────┴───────────────────┴───────┴───────────────────┘

In [65]:
# find root
[node for node, degree in p.G.in_degree() if degree == 0]

['O_{2}', 'A']

In [67]:
p.roots, p.leaves

(['O_{2}', 'A'],
 ['n',
  'β',
  'γ',
  'a',
  'c_1',
  'g_1',
  'a_1',
  'c_2',
  'i_1',
  'k',
  'm',
  'δ',
  'ε',
  'q',
  'H',
  'J',
  'ζ',
  'η',
  'θ',
  's',
  'l_1',
  'm_1',
  'n_1',
  'q_1',
  'r_1',
  'd',
  'o',
  'l_2',
  'α',
  'f',
  'i',
  'c_3',
  'i_2',
  'a_2',
  'h',
  'g',
  'f_1',
  's_1',
  'd_1',
  'e_1',
  'F',
  'f_2',
  'e_2',
  'o_3',
  'o_{2}',
  'b_1',
  'g_2',
  'h_2',
  'j_2',
  's_2',
  't_2',
  'b_2',
  'T',
  'ι',
  'κ',
  'λ',
  'μ',
  'f_3',
  'g_3'])

## Utilities and analysis

These cells provide small utilities for working with constructions and snapshots produced by `ggblab` and `ggblab_extra`.

What these do:

- Save or export snapshots (base64 zip) to disk for later inspection.
- Decode base64 snapshots and inspect the embedded `.ggb` zip contents (including `geogebra.xml`).
- Provide graph-analysis helpers (e.g., longest-path, shortest-path length) to inspect construction dependency graphs built by `ConstructionTreeParser`.
- Offer lightweight helpers for exploring `ggb` applet internals (comm logs, pending messages, etc.).

Important: these cells focus on analysis and helper utilities — they do not perform automatic cleanup or remove application state.

In [24]:
def get_longest_path_to_node(G, target_node):
    roots = [node for node, degree in G.in_degree() if degree == 0]
    longest_path = []
    max_len = 0
    for root in roots:
        for path in nx.all_simple_paths(G, root, target_node):
            if len(path) > max_len:
                max_len = len(path)
                longest_path = path
    return longest_path

In [25]:
path = get_longest_path_to_node(p.G, 'I')
path

['O_{2}', 'B', 'c', 'j', 'r', 'O_{1}', 't', 'F_{1}', 'h_1', 'k_1', 'I']

In [26]:
depths = nx.shortest_path_length(p.G, source='A')
depths

{'A': 0,
 'B': 1,
 'n': 1,
 "O'": 1,
 'p': 1,
 'j': 1,
 'l': 1,
 'β': 1,
 'γ': 1,
 't1': 1,
 'a': 1,
 'g_1': 1,
 't2': 1,
 'a_1': 1,
 'i_1': 1,
 'k': 1,
 'm': 1,
 'δ': 1,
 'ε': 1,
 'e': 1,
 'ζ': 1,
 'η': 1,
 'θ': 1,
 'q_1': 1,
 'r_1': 1,
 't4': 1,
 'c_3': 1,
 'i_2': 1,
 'g': 1,
 'f_1': 1,
 's_1': 1,
 't_1': 1,
 'c': 2,
 'G': 2,
 'F_{2}': 2,
 'q': 2,
 'r': 2,
 'C_{1}': 2,
 'H': 2,
 's': 2,
 "P'": 2,
 'J': 2,
 'K': 2,
 'P': 2,
 't': 2,
 'F_{1}': 2,
 'C': 2,
 'f': 2,
 'e_1': 2,
 "C'": 2,
 'c_1': 2,
 'c_2': 2,
 'A_{1}': 2,
 'a_2': 2,
 'I': 3,
 'b_1': 3,
 'g_2': 3,
 'k_2': 3,
 'p_2': 3,
 'n_1': 3,
 'O': 3,
 'i': 3,
 'h': 3,
 'd_1': 3,
 'O_{1}': 3,
 'j_1': 3,
 'k_1': 3,
 'l_1': 3,
 'm_1': 3,
 'E': 3,
 'F': 3,
 'h_1': 3,
 'd_2': 3,
 "O''": 3,
 'h_2': 3,
 'j_2': 3,
 'm_2': 4,
 'n_2': 4,
 'q_2': 4,
 'r_2': 4,
 'b': 4,
 'O_3': 4,
 't3': 4,
 'd': 4,
 'o': 4,
 'α': 4,
 'Q': 4,
 'R': 4,
 'f_2': 4,
 't5': 4,
 'o_3': 4,
 'o_{2}': 4,
 'p_1': 5,
 'e_2': 5,
 'l_2': 5,
 'D': 6}

In [27]:
depths = nx.shortest_path_length(p.G2, source='A')
depths

{'A': 0,
 'B': 1,
 "O'": 1,
 'e': 2,
 'c': 2,
 'p': 2,
 'l': 3,
 'j': 3,
 'G': 3,
 'F_{2}': 3,
 'r': 4,
 'O_{1}': 5,
 't': 6,
 'b': 6,
 'O_3': 6,
 'F_{1}': 7,
 "P'": 7,
 'p_1': 7,
 'h_1': 8,
 't_1': 8,
 'C': 8,
 'E': 8,
 'D': 8,
 'j_1': 9,
 "C'": 9}

In [28]:
prev = set(list(zip(*(list(p.G.in_edges('R')) + list(p.G.in_edges('S')))))[0])
prev

{'h_1', 'k_1'}

In [29]:
[(n, depths[n]) for n in depths if n in prev]

[('h_1', 8)]

In [30]:
nx.write_network_text(p.roots_to_targets_with_containers('R'))

╟── A (point)
╎   ├─╼ B (point) ╾ O_{2} (point)
╎   │   └─╼ c (circle) ╾ O_{2} (point)
╎   │       ├─╼ j (line) ╾ A (point)
╎   │       │   ├─╼ r (line) ╾ l (line)
╎   │       │   │   └─╼ O_{1} (point)
╎   │       │   │       ├─╼ b (line) ╾ O_{2} (point)
╎   │       │   │       │   └─╼ P' (point) ╾ j (line)
╎   │       │   │       │       └─╼ k_1 (line) ╾ h_1 (circle)
╎   │       │   │       │           └─╼ R (point) ╾ h_1 (circle)
╎   │       │   │       ├─╼ t (line) ╾ l (line)
╎   │       │   │       │   └─╼ F_{1} (point) ╾ l (line)
╎   │       │   │       │       └─╼ h_1 (circle) ╾ O_{1} (point)
╎   │       │   │       │           └─╼  ...
╎   │       │   │       └─╼  ...
╎   │       │   └─╼  ...
╎   │       └─╼ l (line) ╾ A (point)
╎   │           └─╼  ...
╎   └─╼  ...
╙── O_{2} (point)
    └─╼  ...

## .

In [68]:
p.df.filter(pl.col("Layer").is_in([9]))["Sequence", "Type", "Name", "Command", "Value", "Layer", "DependsOn"]

shape: (5, 7)
┌──────────┬────────┬───────┬────────────────────┬────────────────────┬───────┬────────────────────┐
│ Sequence ┆ Type   ┆ Name  ┆ Command            ┆ Value              ┆ Layer ┆ DependsOn          │
│ ---      ┆ ---    ┆ ---   ┆ ---                ┆ ---                ┆ ---   ┆ ---                │
│ u32      ┆ str    ┆ str   ┆ str                ┆ str                ┆ u32   ┆ list[str]          │
╞══════════╪════════╪═══════╪════════════════════╪════════════════════╪═══════╪════════════════════╡
│ 0        ┆ point  ┆ O_{2} ┆ null               ┆ O_{2} = (-2.1,     ┆ 9     ┆ []                 │
│          ┆        ┆       ┆                    ┆ -0.1)              ┆       ┆                    │
│ 2        ┆ point  ┆ B     ┆ Point(Line(O_{2},  ┆ B = (-9.6, -0.2)   ┆ 9     ┆ ["A", "O_{2}"]     │
│          ┆        ┆       ┆ A))                ┆                    ┆       ┆                    │
│ 3        ┆ circle ┆ c     ┆ Circle(O_{2}, B)   ┆ c: (x + 2.1)² + (y ┆ 9     ┆ ["A", "B",         │
│          ┆        ┆       ┆                    ┆ + 0.1)² = 5…       ┆       ┆ "O_{2}"]           │
│ 35       ┆ point  ┆ O_{1} ┆ Point(r)           ┆ O_{1} = (10, -4.8) ┆ 9     ┆ ["A", "B", … "r"]  │
│ 43       ┆ circle ┆ h_1   ┆ Circle(O_{1},      ┆ h_1: (x - 10)² +   ┆ 9     ┆ ["A", "B", … "t"]  │
│          ┆        ┆       ┆ F_{1})             ┆ (y + 4.8)² = …     ┆       ┆                    │
└──────────┴────────┴───────┴────────────────────┴────────────────────┴───────┴────────────────────┘

In [197]:
's' in p.leaves

True

In [131]:
nx.descendants(p.G, 'j')

{'A_{1}',
 'C',
 "C'",
 'C_{1}',
 'D',
 'E',
 'F',
 'F_{1}',
 'H',
 'I',
 'L',
 'M',
 'N',
 'O',
 "O''",
 'O_3',
 'O_{1}',
 'P',
 "P'",
 'Q',
 'R',
 'S',
 'T',
 'a_2',
 'b',
 'b_1',
 'b_2',
 'c_3',
 'd',
 'd_1',
 'd_2',
 'e_2',
 'f',
 'f_2',
 'f_3',
 'g',
 'g_2',
 'g_3',
 'h',
 'h_1',
 'h_2',
 'i',
 'i_2',
 'j_1',
 'j_2',
 'k_1',
 'k_2',
 'l_1',
 'l_2',
 'm_1',
 'm_2',
 'n_2',
 'o',
 'o_3',
 'o_{2}',
 'p_1',
 'p_2',
 'q',
 'q_1',
 'q_2',
 'r',
 'r_2',
 's',
 's_2',
 't',
 't3',
 't4',
 't5',
 't_1',
 't_2',
 'α',
 'ζ',
 'η',
 'θ',
 'ι',
 'κ',
 'λ',
 'μ'}

In [33]:
await ggb.function("setVisible", ["C", True])

In [34]:
p.df["DependsOn"][42].to_list()

['A', 'B', 'O_{1}', 'O_{2}', 'c', 'j', 'l', 'r', 't']

In [35]:
await ggb.function("setVisible", list(zip_longest(_, [], fillvalue=True)))

[None, None, None, None, None, None, None, None, None]

## store

In [211]:
ggb.file.base64_buffer = await ggb.function("getBase64")
c.save(overwrite=True)

In [209]:
from itertools import zip_longest

l0 = range(10)
await ggb.function("setLayerVisible", list(zip_longest(list(l0), [], fillvalue=False)))
l0 = [9, 0, 2, 5]
await ggb.function("setLayerVisible", list(zip_longest(list(l0), [], fillvalue=True)))

[None, None, None, None]

In [73]:
for e in nx.ancestors(p.G, 'j_1'):
    print(e, p.ft[e])

l ['Tangent', 'A', 'c']
O_{1} ['Point', 'r']
P' ['Intersect', 'b', 'j']
c ['Circle', 'O_{2}', 'B']
B ['Point', 'Line', 'O_{2}', 'A']
b ['Line', 'O_{2}', 'O_{1}']
j ['Tangent', 'A', 'c']
F_{1} ['Intersect', 't', 'l']
A []
r ['AngleBisector', 'l', 'j']
t ['PerpendicularLine', 'O_{1}', 'l']
h_1 ['Circle', 'O_{1}', 'F_{1}']
O_{2} []

In [75]:
nx.write_network_text(p.G.subgraph(nx.ancestors(p.G, 'j_1') | {'j_1'}))

╟── A (point)
╎   ├─╼ B (point) ╾ O_{2} (point)
╎   │   └─╼ c (circle) ╾ O_{2} (point)
╎   │       ├─╼ j (line) ╾ A (point)
╎   │       │   ├─╼ r (line) ╾ l (line)
╎   │       │   │   └─╼ O_{1} (point)
╎   │       │   │       ├─╼ b (line) ╾ O_{2} (point)
╎   │       │   │       │   └─╼ P' (point) ╾ j (line)
╎   │       │   │       │       └─╼ j_1 (line) ╾ h_1 (circle)
╎   │       │   │       ├─╼ t (line) ╾ l (line)
╎   │       │   │       │   └─╼ F_{1} (point) ╾ l (line)
╎   │       │   │       │       └─╼ h_1 (circle) ╾ O_{1} (point)
╎   │       │   │       │           └─╼  ...
╎   │       │   │       └─╼  ...
╎   │       │   └─╼  ...
╎   │       └─╼ l (line) ╾ A (point)
╎   │           └─╼  ...
╎   └─╼  ...
╙── O_{2} (point)
    └─╼  ...

In [84]:
s = set()
for e in ['j_1', 'k_1', 'l_1', 'm_1']:
    s |= nx.ancestors(p.G, e) | {e}
s

{'A',
 'B',
 'F_{1}',
 'O_{1}',
 'O_{2}',
 'P',
 "P'",
 'b',
 'c',
 'h_1',
 'j',
 'j_1',
 'k_1',
 'l',
 'l_1',
 'm_1',
 'r',
 't'}

In [85]:
from itertools import zip_longest

l0 = range(10)
await ggb.function("setLayerVisible", list(zip_longest(list(l0), [], fillvalue=False)))
l1 = list(s) #['n', 'r', 'O_{1}', 'O_{2}', 'c', 'h_1', 'A', 'e_1', 'F_{1}', 'F_{2}', 't', 'j', 'l'] # 'C',  'k_1', "P'", 'l_1'
await ggb.function("setVisible", list(zip_longest(list(l1), [], fillvalue=True)))

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

In [100]:
for e in l1:
    print(e, p.ft[e])

n ['Line', 'O_{2}', 'A']
r ['AngleBisector', 'l', 'j']
O_{1} ['Point', 'r']
O_{2} []
c ['Circle', 'O_{2}', 'B']
h_1 ['Circle', 'O_{1}', 'F_{1}']
P' ['Intersect', 'b', 'j']
A []
C ['Intersect', 'p_1', 'l', '2']
F_{1} ['Intersect', 't', 'l']
F_{2} ['Intersect', 'c', 'p']
t ['PerpendicularLine', 'O_{1}', 'l']
j ['Tangent', 'A', 'c']
k_1 ['Tangent', "P'", 'h_1']
l ['Tangent', 'A', 'c']
l_1 ['Tangent', 'P', 'h_1']

In [106]:
nx.write_network_text(p.G.subgraph(l1))

╟── O_{2} (point)
╎   ├─╼ c (circle)
╎   │   ├─╼ F_{2} (point)
╎   │   │   └─╼ e_1 (line) ╾ l (line)
╎   │   ├─╼ j (line) ╾ A (point)
╎   │   │   └─╼ r (line) ╾ l (line)
╎   │   │       └─╼ O_{1} (point)
╎   │   │           ├─╼ t (line) ╾ l (line)
╎   │   │           │   └─╼ F_{1} (point) ╾ l (line)
╎   │   │           │       └─╼ h_1 (circle) ╾ O_{1} (point)
╎   │   │           │           └─╼ l_1 (line)
╎   │   │           └─╼  ...
╎   │   └─╼ l (line) ╾ A (point)
╎   │       ├─╼ C (point)
╎   │       └─╼  ...
╎   └─╼ n (line) ╾ A (point)
╙── A (point)
    └─╼  ...

In [36]:
p.ft['b']

['Line', 'O_{2}', 'O_{1}']

In [91]:
p.fbd('c')

{'A', 'B', 'O_{2}'}

In [110]:
await ggb.command("Circle(F_{2}, Distance(O_{1}, A))")

't_1'

In [112]:
await ggb.command("C' = Intersect[l, t_1, 2]")

"C'"

In [148]:
await ggb.command("Intersect(l_1, h_1)")

'U'

In [138]:
await ggb.command("O'' = Midpoint(C', O_{1})")

"O''"

In [146]:
await ggb.command("Line(C', O_{1})")

'j_2'

In [88]:
await ggb.command("Circle(V, Radius(h_1))")

'd_3'

In [149]:
await ggb.command("Circle(O_{2}, Radius(c) + Radius(h_1))")

'p_2'

In [150]:
await ggb.command("Tangent(O_{1}, k_2)")

'm_2,n_2'

In [151]:
await ggb.command("Tangent(O_{1}, p_2)")

'q_2,r_2'

In [40]:
await ggb.command("Intersect[k_2, n_2]")

'S'

In [87]:
await ggb.command("Intersect[c, b]")

'U,V'

In [151]:
await ggb.command("Angle[O_{1}, C, O_{2}]")

'ν'

In [150]:
await ggb.command("AngleBisector[k_1, m_1]")

'h_3,i_3'

In [97]:
nx.descendants(p.G, 'e')

{'A_{1}', 'C_{1}', 'H', 'J', 'K', 'ζ', 'η'}

In [98]:
p.ft['ζ']

['Angle', 'A_{1}', 'A', 'K']