# ggblab Examples

This notebook demonstrates basic usage of `ggblab`. It walks through loading a `.ggb` file, displaying it in the GeoGebra widget, and parsing the construction for inspection and manipulation.

Key points:

- Large constructions are handled using `getBase64` / `setBase64` (zip + base64).
- Run cells from top to bottom for the examples to work as intended.
- Cells that produce output (e.g., version checks, object lists) will display their results directly below the code cell.

In [1]:
# this magic for develop only
%load_ext autoreload
%autoreload 2

## Create and initialize GeoGebra

The next two cells import the `GeoGebra` controller and initialize the widget. The import cell does not print output; the initialization cell may open the widget and produce transient console output in the notebook UI.

## Create GeoGebra controller

Import and construct the `GeoGebra` controller; the next cell initializes the widget in the JupyterLab UI.

In [2]:
from ggblab import GeoGebra

## Initialize the GeoGebra widget

This cell runs `await GeoGebra().init()` to open the GeoGebra widget attached to the current kernel. Expect the widget to appear in the JupyterLab UI; the cell may print status messages or the kernel may emit frontend messages (these appear in the notebook output area).

In [3]:
# open GeoGebra Widget on left-side
ggb = await GeoGebra().init()

Using local cached file: xsd/common.xsd

## Version checks (package)

This cell prints the installed `ggblab` package version. Expect a short version string as the cell output.

In [4]:
# ggblab version
import ggblab
ggblab.__version__

'1.1.0'

## Version checks (applet)

This cell queries the GeoGebra applet with `getVersion()` and prints the applet version string. The output helps verify compatibility.

In [5]:
# GeoGebra Applet version
r = await ggb.function("getVersion")
r

'5.2.909.9'

## Load a .ggb file

Load a `.ggb` file from disk into the local `ggb.construction` object for inspection and sending to the applet.

In [6]:
# load from .ggb (zipped, and base64 encoded)
c = ggb.file.load('2025_06_08.ggb')

## Send construction to the applet

Use `setBase64` to send the loaded .ggb (zip+base64) to the GeoGebra view so it is rendered in the widget.

In [7]:
# sending loaded construction to GeoGebra view and draw
r = await ggb.function("setBase64", [ggb.construction.base64_buffer.decode('utf-8')])

## Parse the construction XML

Decode the construction XML into Python structures (dicts/lists) so you can inspect and modify element attributes programmatically.

In [ ]:
# parse loaded xml as python dict
o = c.ggb_schema.decode(c.geogebra_xml)

In [ ]:
# list of all object names
[e['@label'] for e in o['element']]

In [ ]:
[e['@label'] for e in o['element']].index('A')

In [ ]:
o['element'][1]

In [ ]:
# change visible state of object 'A'
o['element'][1]['show'][0]['@object'] = False

In [ ]:
import xmlschema

In [ ]:
# construct attributes from dict
x = xmlschema.etree_tostring(c.ggb_schema.encode(o['element'][1], 'element'))
print(x)

## Temporary updates with `preserve()`

The `preserve()` context manager snapshots the applet state (using a zip+base64 snapshot) and restores it automatically when the block exits.

Usage notes:

- The snapshot is taken with `getBase64` and restored with `setBase64` when available.
- The yielded `snap` object includes `base64_zip`, `xml` (optional), `timestamp`, `size_bytes`, and `sha1`.
- Call `await snap.restore()` to restore immediately; call `snap.release()` to drop the stored snapshot from memory.

In [ ]:
import asyncio

In [ ]:
# update the applet
async with ggb.preserve() as snap:
    r = await ggb.function("evalXML", [x])
    await asyncio.sleep(3)

## Advanced inspection

The following examples show how to decode the base64 snapshot, open the embedded zip, and inspect internal files (including the main construction XML). Expected outputs include a list of filenames inside the `.ggb` zip and the decoded XML string(s).

## Inspect base64 snapshot

Decode the base64 snapshot and inspect the zipped content (files inside the .ggb). This is useful when debugging or extracting the main construction XML.

In [ ]:
import base64
import zipfile
import io

In [ ]:
type(snap.base64_zip)

In [ ]:
with zipfile.ZipFile(io.BytesIO(base64.b64decode(snap.base64_zip))) as zf:
    for info in zf.infolist():
        if info.filename == 'geogebra.xml':
            with zf.open(info) as f:
                xml = f.read()

In [ ]:
type(xml.decode())

In [ ]:
# r = await ggb.function("setXML", [xml.decode()])

In [ ]:
await ggb.function("setBase64", [snap.base64_zip])

## draw step-by-step from new construction

In [ ]:
# draw step-by-step from new construction
r = await ggb.function("newConstruction")

names = [e['@label'] for e in o['element']]
for n in names:
    cmd = None
    ci, co = None, None
    for _c in o['command']:
        _ci = tuple(zip(*_c['input'].items()))[1]
        _co = tuple(zip(*_c['output'].items()))[1]
        if n in _co:
            cmd = _c
            ci = _ci
            co = _co
            break

    match names.index(n):
        case int(i):
            ei = o['element'][i]
            if cmd:
                if co.index(n) == 0:
                    x = xmlschema.etree_tostring(c.ggb_schema.encode(cmd, 'construction/command'))
                    r = await ggb.function("evalXML", [x])
                    # print(f"command: {n}")
            x = xmlschema.etree_tostring(c.ggb_schema.encode(ei, 'element'))
            r = await ggb.function("evalXML", [x])
            # print(f"element:{n}")

In [ ]:
ggb.comm.logs

In [ ]:
ggb.comm.recv_msgs

In [ ]:
ggb.comm.pending_futures

In [ ]:
ggb.comm.recv_events.queue

## ggblab_extra — construction protocol from the applet

These cells demonstrate how to extract a construction protocol (objects, commands, and dependency metadata) from a running GeoGebra applet using `ggblab_extra`.

They show how to initialize a structured `DataFrame` from the applet (`ConstructionIO.initialize_dataframe(ggb, use_applet=True)`) so you can analyze element attributes, sequences, and dependencies programmatically. These are analysis helpers and do not alter the stored applet state unless you explicitly call functions that modify the applet.

In [8]:
import polars as pl
import networkx as nx

In [69]:
from ggblab_extra.construction_io import ConstructionIO
df = await ConstructionIO.initialize_dataframe(ggb, use_applet=True)

In [70]:
df

shape: (89, 10)
┌──────────┬───────┬──────────┬───────────────────┬───┬───────┬────────────┬───────────┬───────────┐
│ Sequence ┆ Name  ┆ Type     ┆ Command           ┆ … ┆ Layer ┆ ShowObject ┆ ShowLabel ┆ Auxiliary │
│ ---      ┆ ---   ┆ ---      ┆ ---               ┆   ┆ ---   ┆ ---        ┆ ---       ┆ ---       │
│ u32      ┆ str   ┆ str      ┆ str               ┆   ┆ u32   ┆ bool       ┆ bool      ┆ bool      │
╞══════════╪═══════╪══════════╪═══════════════════╪═══╪═══════╪════════════╪═══════════╪═══════════╡
│ 0        ┆ O_{2} ┆ point    ┆ null              ┆ … ┆ 9     ┆ true       ┆ true      ┆ false     │
│ 1        ┆ A     ┆ point    ┆ null              ┆ … ┆ 2     ┆ true       ┆ true      ┆ false     │
│ 2        ┆ B     ┆ point    ┆ Point(Line(O_{2}, ┆ … ┆ 9     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ A))               ┆   ┆       ┆            ┆           ┆           │
│ 3        ┆ c     ┆ circle   ┆ Circle(O_{2}, B)  ┆ … ┆ 9     ┆ true       ┆ false     ┆ false     │
│ 4        ┆ n     ┆ line     ┆ Line(O_{2}, A)    ┆ … ┆ 4     ┆ false      ┆ false     ┆ false     │
│ 5        ┆ O'    ┆ point    ┆ Midpoint(O_{2},   ┆ … ┆ 4     ┆ false      ┆ true      ┆ false     │
│          ┆       ┆          ┆ A)                ┆   ┆       ┆            ┆           ┆           │
│ 6        ┆ p     ┆ circle   ┆ Circle(O', A)     ┆ … ┆ 4     ┆ false      ┆ false     ┆ false     │
│ 7        ┆ j     ┆ line     ┆ Tangent(A, c)     ┆ … ┆ 2     ┆ true       ┆ false     ┆ false     │
│ 8        ┆ l     ┆ line     ┆ Tangent(A, c)     ┆ … ┆ 2     ┆ true       ┆ false     ┆ false     │
│ 9        ┆ q     ┆ line     ┆ AngleBisector(l,  ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ j)                ┆   ┆       ┆            ┆           ┆           │
│ 10       ┆ r     ┆ line     ┆ AngleBisector(l,  ┆ … ┆ 3     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ j)                ┆   ┆       ┆            ┆           ┆           │
│ 11       ┆ O_{1} ┆ point    ┆ Point(r)          ┆ … ┆ 9     ┆ true       ┆ true      ┆ false     │
│ 12       ┆ t     ┆ line     ┆ PerpendicularLine ┆ … ┆ 2     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ (O_{1}, l)        ┆   ┆       ┆            ┆           ┆           │
│ 13       ┆ F_{1} ┆ point    ┆ Intersect(t, l)   ┆ … ┆ 2     ┆ true       ┆ true      ┆ false     │
│ 14       ┆ h_1   ┆ circle   ┆ Circle(O_{1},     ┆ … ┆ 9     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ F_{1})            ┆   ┆       ┆            ┆           ┆           │
│ 15       ┆ p_2   ┆ circle   ┆ Circle(O_{2},     ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ Radius(c) + Radi… ┆   ┆       ┆            ┆           ┆           │
│ 16       ┆ q_2   ┆ line     ┆ Tangent(O_{1},    ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ p_2)              ┆   ┆       ┆            ┆           ┆           │
│ 17       ┆ r_2   ┆ line     ┆ Tangent(O_{1},    ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ p_2)              ┆   ┆       ┆            ┆           ┆           │
│ 18       ┆ M     ┆ point    ┆ Intersect(p_2,    ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ r_2)              ┆   ┆       ┆            ┆           ┆           │
│ 19       ┆ b_2   ┆ ray      ┆ Ray(O_{2}, M)     ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│ 20       ┆ F_{2} ┆ point    ┆ Intersect(c, b_2, ┆ … ┆ 2     ┆ false      ┆ true      ┆ false     │
│          ┆       ┆          ┆ 1)                ┆   ┆       ┆            ┆           ┆           │
│ 21       ┆ γ     ┆ angle    ┆ Angle(A, F_{2},   ┆ … ┆ 4     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{2})            ┆   ┆       ┆            ┆           ┆           │
│ 22       ┆ t2    ┆ triangle ┆ Polygon(A, F_{2}, ┆ … ┆ 4     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{2})            ┆   ┆       ┆            ┆           ┆           │
│ 23       ┆ a_1   ┆ segment  ┆ Segment(A, F_{2}, ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ t2)               ┆   ┆       ┆            ┆           ┆           │
│ 24       ┆ c_2   ┆ segment  ┆ Segment(F_{2},    ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ O_{2}, t2)        ┆   ┆       ┆            ┆           ┆           │
│ 25       ┆ i_1   ┆ segment  ┆ Segment(O_{2}, A, ┆ … ┆ 4     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ t2)               ┆   ┆       ┆            ┆           ┆           │
│ 26       ┆ m     ┆ segment  ┆ Segment(A, F_{2}) ┆ … ┆ 4     ┆ false      ┆ false     ┆ false     │
│ 27       ┆ θ     ┆ angle    ┆ Angle(O_{2}, A,   ┆ … ┆ 6     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{1})            ┆   ┆       ┆            ┆           ┆           │
│ 28       ┆ b     ┆ line     ┆ Line(O_{2},       ┆ … ┆ 5     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{1})            ┆   ┆       ┆            ┆           ┆           │
│ 29       ┆ P'    ┆ point    ┆ Intersect(b, j)   ┆ … ┆ 0     ┆ true       ┆ true      ┆ false     │
│ 30       ┆ P     ┆ point    ┆ Intersect(b, l)   ┆ … ┆ 0     ┆ true       ┆ true      ┆ false     │
│ 31       ┆ j_1   ┆ line     ┆ Tangent(P', h_1)  ┆ … ┆ 0     ┆ true       ┆ false     ┆ false     │
│ 32       ┆ k_1   ┆ line     ┆ Tangent(P', h_1)  ┆ … ┆ 0     ┆ true       ┆ false     ┆ false     │
│ 33       ┆ l_1   ┆ line     ┆ Tangent(P, h_1)   ┆ … ┆ 0     ┆ true       ┆ false     ┆ false     │
│ 34       ┆ m_1   ┆ line     ┆ Tangent(P, h_1)   ┆ … ┆ 0     ┆ true       ┆ false     ┆ false     │
│ 35       ┆ O_3   ┆ point    ┆ Midpoint(O_{2},   ┆ … ┆ 5     ┆ false      ┆ true      ┆ false     │
│          ┆       ┆          ┆ O_{1})            ┆   ┆       ┆            ┆           ┆           │
│ 36       ┆ p_1   ┆ circle   ┆ Circle(O_3,       ┆ … ┆ 5     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{2})            ┆   ┆       ┆            ┆           ┆           │
│ 37       ┆ C     ┆ point    ┆ Intersect(p_1, l, ┆ … ┆ 2     ┆ false      ┆ true      ┆ false     │
│          ┆       ┆          ┆ 2)                ┆   ┆       ┆            ┆           ┆           │
│ 38       ┆ q_1   ┆ circle   ┆ Circle(A, F_{1})  ┆ … ┆ 2     ┆ true       ┆ false     ┆ false     │
│ 39       ┆ r_1   ┆ circle   ┆ Circle(A, F_{2})  ┆ … ┆ 4     ┆ false      ┆ false     ┆ false     │
│ 40       ┆ Q     ┆ point    ┆ Intersect(h_1,    ┆ … ┆ 2     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ j_1)              ┆   ┆       ┆            ┆           ┆           │
│ 41       ┆ R     ┆ point    ┆ Intersect(h_1,    ┆ … ┆ 2     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ k_1)              ┆   ┆       ┆            ┆           ┆           │
│ 42       ┆ D     ┆ point    ┆ Point(p_1)        ┆ … ┆ 6     ┆ false      ┆ false     ┆ false     │
│ 43       ┆ t3    ┆ triangle ┆ Polygon(O_{2},    ┆ … ┆ 6     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{1}, D)         ┆   ┆       ┆            ┆           ┆           │
│ 44       ┆ d     ┆ segment  ┆ Segment(O_{2},    ┆ … ┆ 6     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ O_{1}, t3)        ┆   ┆       ┆            ┆           ┆           │
│ 45       ┆ o     ┆ segment  ┆ Segment(O_{1}, D, ┆ … ┆ 6     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ t3)               ┆   ┆       ┆            ┆           ┆           │
│ 46       ┆ l_2   ┆ segment  ┆ Segment(D, O_{2}, ┆ … ┆ 6     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ t3)               ┆   ┆       ┆            ┆           ┆           │
│ 47       ┆ α     ┆ angle    ┆ Angle(O_{2}, D,   ┆ … ┆ 6     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{1})            ┆   ┆       ┆            ┆           ┆           │
│ 48       ┆ O     ┆ point    ┆ Midpoint(F_{1},   ┆ … ┆ 7     ┆ false      ┆ true      ┆ false     │
│          ┆       ┆          ┆ F_{2})            ┆   ┆       ┆            ┆           ┆           │
│ 49       ┆ f     ┆ line     ┆ PerpendicularLine ┆ … ┆ 7     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ (O, l)            ┆   ┆       ┆            ┆           ┆           │
│ 50       ┆ i     ┆ segment  ┆ Segment(F_{1},    ┆ … ┆ 7     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ F_{2})            ┆   ┆       ┆            ┆           ┆           │
│ 51       ┆ t4    ┆ triangle ┆ Polygon(O_3, A,   ┆ … ┆ 7     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ C)                ┆   ┆       ┆            ┆           ┆           │
│ 52       ┆ c_3   ┆ segment  ┆ Segment(O_3, A,   ┆ … ┆ 7     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ t4)               ┆   ┆       ┆            ┆           ┆           │
│ 53       ┆ i_2   ┆ segment  ┆ Segment(A, C, t4) ┆ … ┆ 7     ┆ false      ┆ false     ┆ true      │
│ 54       ┆ a_2   ┆ segment  ┆ Segment(C, O_3,   ┆ … ┆ 7     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ t4)               ┆   ┆       ┆            ┆           ┆           │
│ 55       ┆ h     ┆ circle   ┆ Circle(C, F_{2})  ┆ … ┆ 2     ┆ false      ┆ false     ┆ false     │
│ 56       ┆ g     ┆ segment  ┆ Segment(A, Q)     ┆ … ┆ 8     ┆ false      ┆ true      ┆ false     │
│ 57       ┆ s_1   ┆ segment  ┆ Segment(A, F_{2}) ┆ … ┆ 8     ┆ false      ┆ true      ┆ false     │
│ 58       ┆ d_1   ┆ segment  ┆ Segment(F_{2}, C) ┆ … ┆ 8     ┆ false      ┆ true      ┆ false     │
│ 59       ┆ e_1   ┆ line     ┆ PerpendicularLine ┆ … ┆ 2     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ (F_{2}, l)        ┆   ┆       ┆            ┆           ┆           │
│ 60       ┆ E     ┆ point    ┆ Intersect(p_1, t) ┆ … ┆ 6     ┆ false      ┆ true      ┆ false     │
│ 61       ┆ F     ┆ point    ┆ Intersect(p_1, t) ┆ … ┆ 6     ┆ false      ┆ false     ┆ true      │
│ 62       ┆ f_2   ┆ segment  ┆ Segment(E, O_{2}) ┆ … ┆ 7     ┆ false      ┆ false     ┆ false     │
│ 63       ┆ t5    ┆ triangle ┆ Polygon(O_3,      ┆ … ┆ 7     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{2}, E)         ┆   ┆       ┆            ┆           ┆           │
│ 64       ┆ e_2   ┆ segment  ┆ Segment(O_3,      ┆ … ┆ 7     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ O_{2}, t5)        ┆   ┆       ┆            ┆           ┆           │
│ 65       ┆ o_3   ┆ segment  ┆ Segment(O_{2}, E, ┆ … ┆ 7     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ t5)               ┆   ┆       ┆            ┆           ┆           │
│ 66       ┆ o_{2} ┆ segment  ┆ Segment(E, O_3,   ┆ … ┆ 7     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ t5)               ┆   ┆       ┆            ┆           ┆           │
│ 67       ┆ I     ┆ point    ┆ Intersect(c, k_1, ┆ … ┆ 2     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ 1)                ┆   ┆       ┆            ┆           ┆           │
│ 68       ┆ k_2   ┆ circle   ┆ Circle(O_{2},     ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ Radius(c) - Radi… ┆   ┆       ┆            ┆           ┆           │
│ 69       ┆ m_2   ┆ line     ┆ Tangent(O_{1},    ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ k_2)              ┆   ┆       ┆            ┆           ┆           │
│ 70       ┆ n_2   ┆ line     ┆ Tangent(O_{1},    ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ k_2)              ┆   ┆       ┆            ┆           ┆           │
│ 71       ┆ L     ┆ point    ┆ Intersect(k_2,    ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ m_2)              ┆   ┆       ┆            ┆           ┆           │
│ 72       ┆ N     ┆ point    ┆ Intersect(p_2,    ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ q_2)              ┆   ┆       ┆            ┆           ┆           │
│ 73       ┆ S     ┆ point    ┆ Intersect(k_2,    ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ n_2)              ┆   ┆       ┆            ┆           ┆           │
│ 74       ┆ s_2   ┆ ray      ┆ Ray(O_{2}, L)     ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│ 75       ┆ t_2   ┆ ray      ┆ Ray(O_{2}, S)     ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│ 76       ┆ d_2   ┆ ray      ┆ Ray(O_{2}, N)     ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│ 77       ┆ T     ┆ point    ┆ Intersect(c, d_2) ┆ … ┆ 2     ┆ true       ┆ false     ┆ false     │
│ 78       ┆ ι     ┆ angle    ┆ Angle(F_{2}, C,   ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{2})            ┆   ┆       ┆            ┆           ┆           │
│ 79       ┆ κ     ┆ angle    ┆ Angle(I, C,       ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{2})            ┆   ┆       ┆            ┆           ┆           │
│ 80       ┆ λ     ┆ angle    ┆ Angle(R, C,       ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{1})            ┆   ┆       ┆            ┆           ┆           │
│ 81       ┆ μ     ┆ angle    ┆ Angle(F_{2}, C,   ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{1})            ┆   ┆       ┆            ┆           ┆           │
│ 82       ┆ U     ┆ point    ┆ Intersect(h_1,    ┆ … ┆ 2     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ l_1)              ┆   ┆       ┆            ┆           ┆           │
│ 83       ┆ h_3   ┆ line     ┆ AngleBisector(k_1 ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ , m_1)            ┆   ┆       ┆            ┆           ┆           │
│ 84       ┆ i_3   ┆ line     ┆ AngleBisector(k_1 ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ , m_1)            ┆   ┆       ┆            ┆           ┆           │
│ 85       ┆ ν     ┆ angle    ┆ Angle(O_{1}, C,   ┆ … ┆ 6     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{2})            ┆   ┆       ┆            ┆           ┆           │
│ 86       ┆ η     ┆ angle    ┆ Angle(O_{1}, A,   ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ Q)                ┆   ┆       ┆            ┆           ┆           │
│ 87       ┆ ζ     ┆ angle    ┆ Angle(O_{1}, A,   ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ F_{1})            ┆   ┆       ┆            ┆           ┆           │
│ 88       ┆ ε     ┆ angle    ┆ Angle(O_{2}, A,   ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ F_{1})            ┆   ┆       ┆            ┆           ┆           │
└──────────┴───────┴──────────┴───────────────────┴───┴───────┴────────────┴───────────┴───────────┘

## ggblab_extra — construction tree parser

Use `ConstructionTreeParser` to build a graph of construction dependencies and perform graph analyses. The examples below show how to:

- Create the parser with `p = ConstructionTreeParser(df)`
- Build the full dependency graph with `g1 = p.parse()`
- Extract bounded subgraphs with `g2 = p.parse_subgraph(max_depth=3)`

These operations are for inspection and analysis; they help you visualize and trace construction dependency paths.

In [71]:
from ggblab_extra.construction_parser import ConstructionTreeParser

In [72]:
p = ConstructionTreeParser(df)

In [73]:
g1 = p.parse()

In [74]:
labels_map = {}
for n, t in p.df["Name", "Type"].rows():
    g1.nodes[n]["label"] = f"{n} ({t})"

In [75]:
nx.write_network_text(g1)

╟── O_{2} (point)
╎   ├─╼ B (point) ╾ A (point)
╎   │   └─╼ c (circle) ╾ O_{2} (point)
╎   │       ├─╼ j (line) ╾ A (point)
╎   │       │   ├─╼ q (line) ╾ l (line)
╎   │       │   ├─╼ r (line) ╾ l (line)
╎   │       │   │   └─╼ O_{1} (point)
╎   │       │   │       ├─╼ t (line) ╾ l (line)
╎   │       │   │       │   ├─╼ F_{1} (point) ╾ l (line)
╎   │       │   │       │   │   ├─╼ h_1 (circle) ╾ O_{1} (point)
╎   │       │   │       │   │   │   ├─╼ p_2 (circle) ╾ O_{2} (point), c (circle)
╎   │       │   │       │   │   │   │   ├─╼ q_2 (line) ╾ O_{1} (point)
╎   │       │   │       │   │   │   │   │   └─╼ N (point) ╾ p_2 (circle)
╎   │       │   │       │   │   │   │   │       └─╼ d_2 (ray) ╾ O_{2} (point)
╎   │       │   │       │   │   │   │   │           └─╼ T (point) ╾ c (circle)
╎   │       │   │       │   │   │   │   ├─╼ r_2 (line) ╾ O_{1} (point)
╎   │       │   │       │   │   │   │   │   └─╼ M (point) ╾ p_2 (circle)
╎   │       │   │       │   │   │   │   │       └─╼ b_2 (ray) ╾ O_{2} (point)
╎   │       │   │       │   │   │   │   │           └─╼ F_{2} (point) ╾ c (circle)
╎   │       │   │       │   │   │   │   │               ├─╼ γ (angle) ╾ A (point), O_{2} (point)
╎   │       │   │       │   │   │   │   │               ├─╼ t2 (triangle) ╾ A (point), O_{2} (point)
╎   │       │   │       │   │   │   │   │               │   ├─╼ a_1 (segment) ╾ A (point), F_{2} (point)
╎   │       │   │       │   │   │   │   │               │   ├─╼ c_2 (segment) ╾ F_{2} (point), O_{2} (point)
╎   │       │   │       │   │   │   │   │               │   └─╼ i_1 (segment) ╾ O_{2} (point), A (point)
╎   │       │   │       │   │   │   │   │               ├─╼ m (segment) ╾ A (point)
╎   │       │   │       │   │   │   │   │               ├─╼ r_1 (circle) ╾ A (point)
╎   │       │   │       │   │   │   │   │               ├─╼ O (point) ╾ F_{1} (point)
╎   │       │   │       │   │   │   │   │               │   └─╼ f (line) ╾ l (line)
╎   │       │   │       │   │   │   │   │               ├─╼ i (segment) ╾ F_{1} (point)
╎   │       │   │       │   │   │   │   │               ├─╼ h (circle) ╾ C (point)
╎   │       │   │       │   │   │   │   │               ├─╼ s_1 (segment) ╾ A (point)
╎   │       │   │       │   │   │   │   │               ├─╼ d_1 (segment) ╾ C (point)
╎   │       │   │       │   │   │   │   │               ├─╼ e_1 (line) ╾ l (line)
╎   │       │   │       │   │   │   │   │               ├─╼ ι (angle) ╾ C (point), O_{2} (point)
╎   │       │   │       │   │   │   │   │               ├─╼ μ (angle) ╾ C (point), O_{1} (point)
╎   │       │   │       │   │   │   │   │               └─╼  ...
╎   │       │   │       │   │   │   │   └─╼  ...
╎   │       │   │       │   │   │   ├─╼ j_1 (line) ╾ P' (point)
╎   │       │   │       │   │   │   │   └─╼ Q (point) ╾ h_1 (circle)
╎   │       │   │       │   │   │   │       ├─╼ g (segment) ╾ A (point)
╎   │       │   │       │   │   │   │       └─╼ η (angle) ╾ O_{1} (point), A (point)
╎   │       │   │       │   │   │   ├─╼ k_1 (line) ╾ P' (point)
╎   │       │   │       │   │   │   │   ├─╼ R (point) ╾ h_1 (circle)
╎   │       │   │       │   │   │   │   │   └─╼ λ (angle) ╾ C (point), O_{1} (point)
╎   │       │   │       │   │   │   │   ├─╼ I (point) ╾ c (circle)
╎   │       │   │       │   │   │   │   │   └─╼ κ (angle) ╾ C (point), O_{2} (point)
╎   │       │   │       │   │   │   │   ├─╼ h_3 (line) ╾ m_1 (line)
╎   │       │   │       │   │   │   │   └─╼ i_3 (line) ╾ m_1 (line)
╎   │       │   │       │   │   │   ├─╼ l_1 (line) ╾ P (point)
╎   │       │   │       │   │   │   │   └─╼ U (point) ╾ h_1 (circle)
╎   │       │   │       │   │   │   ├─╼ m_1 (line) ╾ P (point)
╎   │       │   │       │   │   │   │   └─╼  ...
╎   │       │   │       │   │   │   ├─╼ k_2 (circle) ╾ O_{2} (point), c (circle)
╎   │       │   │       │   │   │   │   ├─╼ m_2 (line) ╾ O_{1} (point)
╎   │       │   │       │   │   │   │   │   └─╼ L (point) ╾ k_2 (circle)
╎   │       │   │       │   │   │   │   │       └─╼ s_2 (ray) ╾ O_{2} (point)
╎   │       │   │       │   │   │   │   ├─╼ n_2 (line) ╾ O_{1} (point)
╎   │       │   │       │   │   │   │   │   └─╼ S (point) ╾ k_2 (circle)
╎   │       │   │       │   │   │   │   │       └─╼ t_2 (ray) ╾ O_{2} (point)
╎   │       │   │       │   │   │   │   └─╼  ...
╎   │       │   │       │   │   │   └─╼  ...
╎   │       │   │       │   │   ├─╼ q_1 (circle) ╾ A (point)
╎   │       │   │       │   │   ├─╼ ζ (angle) ╾ O_{1} (point), A (point)
╎   │       │   │       │   │   ├─╼ ε (angle) ╾ O_{2} (point), A (point)
╎   │       │   │       │   │   └─╼  ...
╎   │       │   │       │   ├─╼ E (point) ╾ p_1 (circle)
╎   │       │   │       │   │   ├─╼ f_2 (segment) ╾ O_{2} (point)
╎   │       │   │       │   │   ├─╼ t5 (triangle) ╾ O_3 (point), O_{2} (point)
╎   │       │   │       │   │   │   ├─╼ e_2 (segment) ╾ O_3 (point), O_{2} (point)
╎   │       │   │       │   │   │   ├─╼ o_3 (segment) ╾ O_{2} (point), E (point)
╎   │       │   │       │   │   │   └─╼ o_{2} (segment) ╾ E (point), O_3 (point)
╎   │       │   │       │   │   └─╼  ...
╎   │       │   │       │   └─╼ F (point) ╾ p_1 (circle)
╎   │       │   │       ├─╼ θ (angle) ╾ O_{2} (point), A (point)
╎   │       │   │       ├─╼ b (line) ╾ O_{2} (point)
╎   │       │   │       │   ├─╼ P' (point) ╾ j (line)
╎   │       │   │       │   │   └─╼  ...
╎   │       │   │       │   └─╼ P (point) ╾ l (line)
╎   │       │   │       │       └─╼  ...
╎   │       │   │       ├─╼ O_3 (point) ╾ O_{2} (point)
╎   │       │   │       │   ├─╼ p_1 (circle) ╾ O_{2} (point)
╎   │       │   │       │   │   ├─╼ C (point) ╾ l (line)
╎   │       │   │       │   │   │   ├─╼ t4 (triangle) ╾ O_3 (point), A (point)
╎   │       │   │       │   │   │   │   ├─╼ c_3 (segment) ╾ O_3 (point), A (point)
╎   │       │   │       │   │   │   │   ├─╼ i_2 (segment) ╾ A (point), C (point)
╎   │       │   │       │   │   │   │   └─╼ a_2 (segment) ╾ C (point), O_3 (point)
╎   │       │   │       │   │   │   ├─╼ ν (angle) ╾ O_{1} (point), O_{2} (point)
╎   │       │   │       │   │   │   └─╼  ...
╎   │       │   │       │   │   ├─╼ D (point)
╎   │       │   │       │   │   │   ├─╼ t3 (triangle) ╾ O_{2} (point), O_{1} (point)
╎   │       │   │       │   │   │   │   ├─╼ d (segment) ╾ O_{2} (point), O_{1} (point)
╎   │       │   │       │   │   │   │   ├─╼ o (segment) ╾ O_{1} (point), D (point)
╎   │       │   │       │   │   │   │   └─╼ l_2 (segment) ╾ D (point), O_{2} (point)
╎   │       │   │       │   │   │   ├─╼ α (angle) ╾ O_{2} (point), O_{1} (point)
╎   │       │   │       │   │   │   └─╼  ...
╎   │       │   │       │   │   └─╼  ...
╎   │       │   │       │   └─╼  ...
╎   │       │   │       └─╼  ...
╎   │       │   └─╼  ...
╎   │       ├─╼ l (line) ╾ A (point)
╎   │       │   └─╼  ...
╎   │       └─╼  ...
╎   ├─╼ n (line) ╾ A (point)
╎   ├─╼ O' (point) ╾ A (point)
╎   │   └─╼ p (circle) ╾ A (point)
╎   └─╼  ...
╙── A (point)
    └─╼  ...

In [16]:
g2 = p.parse_subgraph(max_depth=3)

parse_subgraph: timeout exceeded during candidate evaluation (10.00s), falling back to parse_subgraph_legacy

In [17]:
nx.write_network_text(g2)

╟── O_{2}
╎   ├─╼ B ╾ A
╎   │   └─╼ c
╎   │       ├─╼ l
╎   │       │   └─╼ r ╾ j
╎   │       │       └─╼ O_{1}
╎   │       │           ├─╼ t
╎   │       │           │   └─╼ F_{1}
╎   │       │           │       └─╼ h_1
╎   │       │           │           ├─╼ k_1
╎   │       │           │           ├─╼ p_2
╎   │       │           │           │   ├─╼ r_2
╎   │       │           │           │   └─╼ q_2
╎   │       │           │           │       └─╼ N
╎   │       │           │           ├─╼ j_1
╎   │       │           │           └─╼ k_2
╎   │       │           │               ├─╼ m_2
╎   │       │           │               └─╼ n_2
╎   │       │           ├─╼ O_3
╎   │       │           │   └─╼ p_1
╎   │       │           │       ├─╼ D
╎   │       │           │       ├─╼ E
╎   │       │           │       └─╼ C
╎   │       │           └─╼ b
╎   │       │               ├─╼ P'
╎   │       │               └─╼ P
╎   │       ├─╼ j
╎   │       │   └─╼  ...
╎   │       ├─╼ G ╾ p
╎   │       └─╼ F_{2} ╾ p
╎   └─╼ O' ╾ A
╎       └─╼ p
╎           └─╼  ...
╙── A
    └─╼  ...

In [18]:
p.df.filter(~pl.col("Auxiliary"))["Sequence", "Type", "Name", "Command", "Value", "Layer", "DependsOn"]

shape: (82, 7)
┌──────────┬──────────┬───────┬────────────────────┬───────────────────┬───────┬───────────────────┐
│ Sequence ┆ Type     ┆ Name  ┆ Command            ┆ Value             ┆ Layer ┆ DependsOn         │
│ ---      ┆ ---      ┆ ---   ┆ ---                ┆ ---               ┆ ---   ┆ ---               │
│ u32      ┆ str      ┆ str   ┆ str                ┆ str               ┆ u32   ┆ list[str]         │
╞══════════╪══════════╪═══════╪════════════════════╪═══════════════════╪═══════╪═══════════════════╡
│ 0        ┆ point    ┆ O_{2} ┆ null               ┆ O_{2} = (-2.1,    ┆ 9     ┆ []                │
│          ┆          ┆       ┆                    ┆ -0.1)             ┆       ┆                   │
│ 1        ┆ point    ┆ A     ┆ null               ┆ A = (10, 0)       ┆ 2     ┆ []                │
│ 2        ┆ point    ┆ B     ┆ Point(Line(O_{2},  ┆ B = (-9.6, -0.2)  ┆ 9     ┆ ["A", "O_{2}"]    │
│          ┆          ┆       ┆ A))                ┆                   ┆       ┆                   │
│ 3        ┆ circle   ┆ c     ┆ Circle(O_{2}, B)   ┆ c: (x + 2.1)² +   ┆ 9     ┆ ["A", "B",        │
│          ┆          ┆       ┆                    ┆ (y + 0.1)² = 5…   ┆       ┆ "O_{2}"]          │
│ 4        ┆ line     ┆ n     ┆ Line(O_{2}, A)     ┆ n: y = -0.1       ┆ 4     ┆ ["A", "O_{2}"]    │
│ 5        ┆ point    ┆ O'    ┆ Midpoint(O_{2}, A) ┆ O' = (3.9, 0)     ┆ 4     ┆ ["A", "O_{2}"]    │
│ 6        ┆ circle   ┆ p     ┆ Circle(O', A)      ┆ p: (x - 3.9)² +   ┆ 4     ┆ ["A", "O'",       │
│          ┆          ┆       ┆                    ┆ (y + 0)² = 36.…   ┆       ┆ "O_{2}"]          │
│ 7        ┆ point    ┆ G     ┆ Intersect(c, p)    ┆ G = (2.4, 5.8)    ┆ 2     ┆ ["A", "B", … "p"] │
│ 8        ┆ point    ┆ F_{2} ┆ Intersect(c, p)    ┆ F_{2} = (2.5,     ┆ 2     ┆ ["A", "B", … "p"] │
│          ┆          ┆       ┆                    ┆ -5.9)             ┆       ┆                   │
│ 9        ┆ line     ┆ j     ┆ Tangent(A, c)      ┆ j: -5.8x - 7.6y = ┆ 2     ┆ ["A", "B", … "c"] │
│          ┆          ┆       ┆                    ┆ -58.2             ┆       ┆                   │
│ 10       ┆ line     ┆ l     ┆ Tangent(A, c)      ┆ l: 5.9x - 7.5y =  ┆ 2     ┆ ["A", "B", … "c"] │
│          ┆          ┆       ┆                    ┆ 59.4              ┆       ┆                   │
│ 11       ┆ angle    ┆ β     ┆ Angle(A, G, O_{2}) ┆ β = 90°           ┆ 4     ┆ ["A", "B", … "p"] │
│ 12       ┆ angle    ┆ γ     ┆ Angle(A, F_{2},    ┆ γ = 90°           ┆ 4     ┆ ["A", "B", … "p"] │
│          ┆          ┆       ┆ O_{2})             ┆                   ┆       ┆                   │
│ 13       ┆ triangle ┆ t1    ┆ Polygon(A, G,      ┆ t1 = 35.7         ┆ 4     ┆ ["A", "B", … "p"] │
│          ┆          ┆       ┆ O_{2})             ┆                   ┆       ┆                   │
│ 17       ┆ triangle ┆ t2    ┆ Polygon(A, F_{2},  ┆ t2 = 35.7         ┆ 4     ┆ ["A", "B", … "p"] │
│          ┆          ┆       ┆ O_{2})             ┆                   ┆       ┆                   │
│ 21       ┆ segment  ┆ k     ┆ Segment(A, G)      ┆ k = 9.6           ┆ 4     ┆ ["A", "B", … "p"] │
│ 22       ┆ segment  ┆ m     ┆ Segment(A, F_{2})  ┆ m = 9.6           ┆ 4     ┆ ["A", "B", … "p"] │
│ 23       ┆ angle    ┆ δ     ┆ Angle(O_{2}, A, G) ┆ δ = 37.9°         ┆ 3     ┆ ["A", "B", … "p"] │
│ 24       ┆ line     ┆ q     ┆ AngleBisector(l,   ┆ q: 0x - 1y = 0.1  ┆ 3     ┆ ["A", "B", … "l"] │
│          ┆          ┆       ┆ j)                 ┆                   ┆       ┆                   │
│ 25       ┆ line     ┆ r     ┆ AngleBisector(l,   ┆ r: 1x = 10        ┆ 3     ┆ ["A", "B", … "l"] │
│          ┆          ┆       ┆ j)                 ┆                   ┆       ┆                   │
│ 26       ┆ point    ┆ O_{1} ┆ Point(r)           ┆ O_{1} = (10,      ┆ 9     ┆ ["A", "B", … "r"] │
│          ┆          ┆       ┆                    ┆ -4.7)             ┆       ┆                   │
│ 27       ┆ angle    ┆ θ     ┆ Angle(O_{2}, A,    ┆ θ = 90°           ┆ 6     ┆ ["A", "B", … "r"] │
│          ┆          ┆       ┆ O_{1})             ┆                   ┆       ┆                   │
│ 28       ┆ line     ┆ b     ┆ Line(O_{2}, O_{1}) ┆ b: y = -0.4x -    ┆ 5     ┆ ["A", "B", … "r"] │
│          ┆          ┆       ┆                    ┆ 0.9               ┆       ┆                   │
│ 29       ┆ point    ┆ P'    ┆ Intersect(b, j)    ┆ P' = (21.9, -9.1) ┆ 0     ┆ ["A", "B", … "r"] │
│ 30       ┆ point    ┆ P     ┆ Intersect(b, l)    ┆ P = (6, -3.2)     ┆ 0     ┆ ["A", "B", … "r"] │
│ 31       ┆ line     ┆ t     ┆ PerpendicularLine( ┆ t: 7.5x + 5.9y =  ┆ 2     ┆ ["A", "B", … "r"] │
│          ┆          ┆       ┆ O_{1}, l)          ┆ 47.5              ┆       ┆                   │
│ 32       ┆ point    ┆ F_{1} ┆ Intersect(t, l)    ┆ F_{1} = (7.7,     ┆ 2     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆                    ┆ -1.8)             ┆       ┆                   │
│ 33       ┆ circle   ┆ h_1   ┆ Circle(O_{1},      ┆ h_1: (x - 10)² +  ┆ 9     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆ F_{1})             ┆ (y + 4.7)² = …    ┆       ┆                   │
│ 34       ┆ line     ┆ j_1   ┆ Tangent(P', h_1)   ┆ j_1: -7.4x - 9.6y ┆ 0     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆                    ┆ = -74             ┆       ┆                   │
│ 35       ┆ line     ┆ k_1   ┆ Tangent(P', h_1)   ┆ k_1: -0.8x -      ┆ 0     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆                    ┆ 12.1y = 93.6      ┆       ┆                   │
│ 36       ┆ line     ┆ l_1   ┆ Tangent(P, h_1)    ┆ l_1: 2.2x + 0.4y  ┆ 0     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆                    ┆ = 11.8            ┆       ┆                   │
│ 37       ┆ line     ┆ m_1   ┆ Tangent(P, h_1)    ┆ m_1: -1.4x + 1.7y ┆ 0     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆                    ┆ = -13.8           ┆       ┆                   │
│ 38       ┆ point    ┆ O_3   ┆ Midpoint(O_{2},    ┆ O_3 = (4, -2.4)   ┆ 5     ┆ ["A", "B", … "r"] │
│          ┆          ┆       ┆ O_{1})             ┆                   ┆       ┆                   │
│ 39       ┆ circle   ┆ p_1   ┆ Circle(O_3, O_{2}) ┆ p_1: (x - 4)² +   ┆ 5     ┆ ["A", "B", … "r"] │
│          ┆          ┆       ┆                    ┆ (y + 2.4)² = 4…   ┆       ┆                   │
│ 40       ┆ point    ┆ C     ┆ Intersect(p_1, l,  ┆ C = (0.2, -7.7)   ┆ 2     ┆ ["A", "B", … "r"] │
│          ┆          ┆       ┆ 2)                 ┆                   ┆       ┆                   │
│ 41       ┆ circle   ┆ q_1   ┆ Circle(A, F_{1})   ┆ q_1: (x - 10)² +  ┆ 2     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆                    ┆ y² = 8.3          ┆       ┆                   │
│ 42       ┆ circle   ┆ r_1   ┆ Circle(A, F_{2})   ┆ r_1: (x - 10)² +  ┆ 4     ┆ ["A", "B", … "p"] │
│          ┆          ┆       ┆                    ┆ y² = 91.6         ┆       ┆                   │
│ 43       ┆ point    ┆ Q     ┆ Intersect(h_1,     ┆ Q = (12.3, -1.7)  ┆ 2     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆ j_1)               ┆                   ┆       ┆                   │
│ 44       ┆ point    ┆ R     ┆ Intersect(h_1,     ┆ R = (9.8, -8.4)   ┆ 2     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆ k_1)               ┆                   ┆       ┆                   │
│ 45       ┆ point    ┆ D     ┆ Point(p_1)         ┆ D = (-2.5, -2.6)  ┆ 6     ┆ ["A", "B", … "r"] │
│ 46       ┆ triangle ┆ t3    ┆ Polygon(O_{2},     ┆ t3 = 16.2         ┆ 6     ┆ ["A", "B", … "r"] │
│          ┆          ┆       ┆ O_{1}, D)          ┆                   ┆       ┆                   │
│ 50       ┆ angle    ┆ α     ┆ Angle(O_{2}, D,    ┆ α = 90°           ┆ 6     ┆ ["A", "B", … "r"] │
│          ┆          ┆       ┆ O_{1})             ┆                   ┆       ┆                   │
│ 51       ┆ point    ┆ O     ┆ Midpoint(F_{1},    ┆ O = (5.1, -3.9)   ┆ 7     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆ F_{2})             ┆                   ┆       ┆                   │
│ 52       ┆ line     ┆ f     ┆ PerpendicularLine( ┆ f: 7.5x + 5.9y =  ┆ 7     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆ O, l)              ┆ 15.4              ┆       ┆                   │
│ 53       ┆ segment  ┆ i     ┆ Segment(F_{1},     ┆ i = 6.7           ┆ 7     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆ F_{2})             ┆                   ┆       ┆                   │
│ 54       ┆ triangle ┆ t4    ┆ Polygon(O_3, A, C) ┆ t4 = 11.7         ┆ 7     ┆ ["A", "B", … "r"] │
│ 58       ┆ circle   ┆ h     ┆ Circle(C, F_{2})   ┆ h: (x - 0.2)² +   ┆ 2     ┆ ["A", "B", … "r"] │
│          ┆          ┆       ┆                    ┆ (y + 7.7)² = 8…   ┆       ┆                   │
│ 59       ┆ segment  ┆ g     ┆ Segment(A, Q)      ┆ g = 2.9           ┆ 8     ┆ ["A", "B", … "t"] │
│ 60       ┆ segment  ┆ f_1   ┆ Segment(A, G)      ┆ f_1 = 9.6         ┆ 8     ┆ ["A", "B", … "p"] │
│ 61       ┆ segment  ┆ s_1   ┆ Segment(A, F_{2})  ┆ s_1 = 9.6         ┆ 8     ┆ ["A", "B", … "p"] │
│ 62       ┆ segment  ┆ d_1   ┆ Segment(F_{2}, C)  ┆ d_1 = 2.9         ┆ 8     ┆ ["A", "B", … "r"] │
│ 63       ┆ line     ┆ e_1   ┆ PerpendicularLine( ┆ e_1: 7.5x + 5.9y  ┆ 2     ┆ ["A", "B", … "p"] │
│          ┆          ┆       ┆ F_{2}, l)          ┆ = -16.6           ┆       ┆                   │
│ 64       ┆ point    ┆ E     ┆ Intersect(p_1, t)  ┆ E = (3.1, 4.1)    ┆ 6     ┆ ["A", "B", … "t"] │
│ 66       ┆ segment  ┆ f_2   ┆ Segment(E, O_{2})  ┆ f_2 = 6.7         ┆ 7     ┆ ["A", "B", … "t"] │
│ 67       ┆ triangle ┆ t5    ┆ Polygon(O_3,       ┆ t5 = 18.7         ┆ 7     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆ O_{2}, E)          ┆                   ┆       ┆                   │
│ 71       ┆ point    ┆ I     ┆ Intersect(c, k_1,  ┆ I = (-2.6, -7.5)  ┆ 2     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆ 1)                 ┆                   ┆       ┆                   │
│ 72       ┆ circle   ┆ k_2   ┆ Circle(O_{2},      ┆ k_2: (x + 2.1)² + ┆ 1     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆ Radius(c) - Radi…  ┆ (y + 0.1)² =…     ┆       ┆                   │
│ 73       ┆ circle   ┆ p_2   ┆ Circle(O_{2},      ┆ p_2: (x + 2.1)² + ┆ 1     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆ Radius(c) + Radi…  ┆ (y + 0.1)² =…     ┆       ┆                   │
│ 74       ┆ line     ┆ m_2   ┆ Tangent(O_{1},     ┆ m_2: -7.6x - 9.9y ┆ 1     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆ k_2)               ┆ = -29.8           ┆       ┆                   │
│ 75       ┆ line     ┆ n_2   ┆ Tangent(O_{1},     ┆ n_2: -0.8x -      ┆ 1     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆ k_2)               ┆ 12.4y = 49.9      ┆       ┆                   │
│ 76       ┆ line     ┆ q_2   ┆ Tangent(O_{1},     ┆ q_2: -6.6x - 1.2y ┆ 1     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆ p_2)               ┆ = -60.5           ┆       ┆                   │
│ 77       ┆ line     ┆ r_2   ┆ Tangent(O_{1},     ┆ r_2: 4.2x - 5.2y  ┆ 1     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆ p_2)               ┆ = 66.3            ┆       ┆                   │
│ 78       ┆ point    ┆ L     ┆ Intersect(k_2,     ┆ L = (0.2, 2.9)    ┆ 1     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆ m_2)               ┆                   ┆       ┆                   │
│ 79       ┆ point    ┆ M     ┆ Intersect(p_2,     ┆ M = (4.8, -8.8)   ┆ 1     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆ r_2)               ┆                   ┆       ┆                   │
│ 80       ┆ point    ┆ N     ┆ Intersect(p_2,     ┆ N = (8.8, 1.9)    ┆ 1     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆ q_2)               ┆                   ┆       ┆                   │
│ 81       ┆ point    ┆ S     ┆ Intersect(k_2,     ┆ S = (-2.4, -3.9)  ┆ 1     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆ n_2)               ┆                   ┆       ┆                   │
│ 82       ┆ ray      ┆ s_2   ┆ Ray(O_{2}, L)      ┆ s_2: y = 1.3x +   ┆ 1     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆                    ┆ 2.7               ┆       ┆                   │
│ 83       ┆ ray      ┆ t_2   ┆ Ray(O_{2}, S)      ┆ t_2: y = 15.3x +  ┆ 1     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆                    ┆ 32.5              ┆       ┆                   │
│ 84       ┆ ray      ┆ b_2   ┆ Ray(O_{2}, M)      ┆ b_2: y = -1.3x -  ┆ 1     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆                    ┆ 2.8               ┆       ┆                   │
│ 85       ┆ ray      ┆ d_2   ┆ Ray(O_{2}, N)      ┆ d_2: y = 0.2x +   ┆ 1     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆                    ┆ 0.3               ┆       ┆                   │
│ 86       ┆ point    ┆ T     ┆ Intersect(c, d_2)  ┆ T = (5.2, 1.2)    ┆ 2     ┆ ["A", "B", … "t"] │
│ 87       ┆ angle    ┆ ι     ┆ Angle(F_{2}, C,    ┆ ι = 68.9°         ┆ 3     ┆ ["A", "B", … "r"] │
│          ┆          ┆       ┆ O_{2})             ┆                   ┆       ┆                   │
│ 88       ┆ angle    ┆ κ     ┆ Angle(I, C, O_{2}) ┆ κ = 68.9°         ┆ 3     ┆ ["A", "B", … "t"] │
│ 89       ┆ angle    ┆ λ     ┆ Angle(R, C, O_{1}) ┆ λ = 21.1°         ┆ 3     ┆ ["A", "B", … "t"] │
│ 90       ┆ angle    ┆ μ     ┆ Angle(F_{2}, C,    ┆ μ = 21.1°         ┆ 3     ┆ ["A", "B", … "r"] │
│          ┆          ┆       ┆ O_{1})             ┆                   ┆       ┆                   │
│ 91       ┆ point    ┆ U     ┆ Intersect(h_1,     ┆ U = (6.4, -5.3)   ┆ 2     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆ l_1)               ┆                   ┆       ┆                   │
│ 92       ┆ line     ┆ h_3   ┆ AngleBisector(k_1, ┆ h_3: -1x - 0.3y = ┆ 3     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆ m_1)               ┆ 2.1               ┆       ┆                   │
│ 93       ┆ line     ┆ i_3   ┆ AngleBisector(k_1, ┆ i_3: 0.3x - 1y =  ┆ 3     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆ m_1)               ┆ 7.5               ┆       ┆                   │
│ 94       ┆ angle    ┆ ν     ┆ Angle(O_{1}, C,    ┆ ν = 90°           ┆ 6     ┆ ["A", "B", … "r"] │
│          ┆          ┆       ┆ O_{2})             ┆                   ┆       ┆                   │
│ 95       ┆ angle    ┆ η     ┆ Angle(O_{1}, A, Q) ┆ η = 52.1°         ┆ 3     ┆ ["A", "B", … "t"] │
│ 96       ┆ angle    ┆ ζ     ┆ Angle(O_{1}, A,    ┆ ζ = 52.1°         ┆ 3     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆ F_{1})             ┆                   ┆       ┆                   │
│ 97       ┆ angle    ┆ ε     ┆ Angle(O_{2}, A,    ┆ ε = 37.9°         ┆ 3     ┆ ["A", "B", … "t"] │
│          ┆          ┆       ┆ F_{1})             ┆                   ┆       ┆                   │
└──────────┴──────────┴───────┴────────────────────┴───────────────────┴───────┴───────────────────┘

In [19]:
# find root
[node for node, degree in p.G.in_degree() if degree == 0]

['O_{2}', 'A']

In [20]:
p.roots, p.leaves

(['O_{2}', 'A'],
 ['n',
  'β',
  'γ',
  'a',
  'c_1',
  'g_1',
  'a_1',
  'c_2',
  'i_1',
  'k',
  'm',
  'δ',
  'q',
  'θ',
  'q_1',
  'r_1',
  'd',
  'o',
  'l_2',
  'α',
  'f',
  'i',
  'c_3',
  'i_2',
  'a_2',
  'h',
  'g',
  'f_1',
  's_1',
  'd_1',
  'e_1',
  'F',
  'f_2',
  'e_2',
  'o_3',
  'o_{2}',
  's_2',
  't_2',
  'b_2',
  'T',
  'ι',
  'κ',
  'λ',
  'μ',
  'U',
  'h_3',
  'i_3',
  'ν',
  'η',
  'ζ',
  'ε'])

## Utilities and analysis

These cells provide small utilities for working with constructions and snapshots produced by `ggblab` and `ggblab_extra`.

What these do:

- Save or export snapshots (base64 zip) to disk for later inspection.
- Decode base64 snapshots and inspect the embedded `.ggb` zip contents (including `geogebra.xml`).
- Provide graph-analysis helpers (e.g., longest-path, shortest-path length) to inspect construction dependency graphs built by `ConstructionTreeParser`.
- Offer lightweight helpers for exploring `ggb` applet internals (comm logs, pending messages, etc.).

Important: these cells focus on analysis and helper utilities — they do not perform automatic cleanup or remove application state.

In [21]:
def get_longest_path_to_node(G, target_node):
    roots = [node for node, degree in G.in_degree() if degree == 0]
    longest_path = []
    max_len = 0
    for root in roots:
        for path in nx.all_simple_paths(G, root, target_node):
            if len(path) > max_len:
                max_len = len(path)
                longest_path = path
    return longest_path

In [22]:
path = get_longest_path_to_node(p.G, 'I')
path

['O_{2}', 'B', 'c', 'j', 'r', 'O_{1}', 't', 'F_{1}', 'h_1', 'k_1', 'I']

In [23]:
depths = nx.shortest_path_length(p.G, source='A')
depths

{'A': 0,
 'B': 1,
 'n': 1,
 "O'": 1,
 'p': 1,
 'j': 1,
 'l': 1,
 'β': 1,
 'γ': 1,
 't1': 1,
 'a': 1,
 'g_1': 1,
 't2': 1,
 'a_1': 1,
 'i_1': 1,
 'k': 1,
 'm': 1,
 'δ': 1,
 'θ': 1,
 'q_1': 1,
 'r_1': 1,
 't4': 1,
 'c_3': 1,
 'i_2': 1,
 'g': 1,
 'f_1': 1,
 's_1': 1,
 'η': 1,
 'ζ': 1,
 'ε': 1,
 'c': 2,
 'G': 2,
 'F_{2}': 2,
 'q': 2,
 'r': 2,
 "P'": 2,
 'P': 2,
 't': 2,
 'F_{1}': 2,
 'C': 2,
 'f': 2,
 'e_1': 2,
 'c_1': 2,
 'c_2': 2,
 'a_2': 2,
 'I': 3,
 'k_2': 3,
 'p_2': 3,
 'T': 3,
 'O': 3,
 'i': 3,
 'h': 3,
 'd_1': 3,
 'ι': 3,
 'μ': 3,
 'O_{1}': 3,
 'j_1': 3,
 'k_1': 3,
 'l_1': 3,
 'm_1': 3,
 'E': 3,
 'F': 3,
 'h_1': 3,
 'κ': 3,
 'λ': 3,
 'ν': 3,
 'm_2': 4,
 'n_2': 4,
 'L': 4,
 'S': 4,
 'q_2': 4,
 'r_2': 4,
 'M': 4,
 'N': 4,
 'b': 4,
 'O_3': 4,
 't3': 4,
 'd': 4,
 'o': 4,
 'α': 4,
 'Q': 4,
 'R': 4,
 'h_3': 4,
 'i_3': 4,
 'U': 4,
 'f_2': 4,
 't5': 4,
 'o_3': 4,
 'o_{2}': 4,
 's_2': 5,
 't_2': 5,
 'b_2': 5,
 'd_2': 5,
 'p_1': 5,
 'e_2': 5,
 'l_2': 5,
 'D': 6}

In [24]:
depths = nx.shortest_path_length(p.G2, source='A')
depths

{'A': 0,
 'B': 1,
 "O'": 1,
 'c': 2,
 'p': 2,
 'l': 3,
 'j': 3,
 'G': 3,
 'F_{2}': 3,
 'r': 4,
 'O_{1}': 5,
 't': 6,
 'O_3': 6,
 'b': 6,
 'F_{1}': 7,
 'p_1': 7,
 "P'": 7,
 'P': 7,
 'h_1': 8,
 'D': 8,
 'E': 8,
 'C': 8,
 'k_1': 9,
 'p_2': 9,
 'j_1': 9,
 'k_2': 9,
 'r_2': 10,
 'q_2': 10,
 'm_2': 10,
 'n_2': 10,
 'N': 11}

In [25]:
prev = set(list(zip(*(list(p.G.in_edges('R')) + list(p.G.in_edges('S')))))[0])
prev

{'h_1', 'k_1', 'k_2', 'n_2'}

In [26]:
[(n, depths[n]) for n in depths if n in prev]

[('h_1', 8), ('k_1', 9), ('k_2', 9), ('n_2', 10)]

In [27]:
nx.write_network_text(p.roots_to_targets_with_containers('R'))

╟── O_{2} (point)
╎   ├─╼ B (point) ╾ A (point)
╎   │   └─╼ c (circle) ╾ O_{2} (point)
╎   │       ├─╼ j (line) ╾ A (point)
╎   │       │   ├─╼ r (line) ╾ l (line)
╎   │       │   │   └─╼ O_{1} (point)
╎   │       │   │       ├─╼ b (line) ╾ O_{2} (point)
╎   │       │   │       │   └─╼ P' (point) ╾ j (line)
╎   │       │   │       │       └─╼ k_1 (line) ╾ h_1 (circle)
╎   │       │   │       │           └─╼ R (point) ╾ h_1 (circle)
╎   │       │   │       ├─╼ t (line) ╾ l (line)
╎   │       │   │       │   └─╼ F_{1} (point) ╾ l (line)
╎   │       │   │       │       └─╼ h_1 (circle) ╾ O_{1} (point)
╎   │       │   │       │           └─╼  ...
╎   │       │   │       └─╼  ...
╎   │       │   └─╼  ...
╎   │       └─╼ l (line) ╾ A (point)
╎   │           └─╼  ...
╎   └─╼  ...
╙── A (point)
    └─╼  ...

## .

In [28]:
p.df.filter(pl.col("Layer").is_in([9]))["Sequence", "Type", "Name", "Command", "Value", "Layer", "DependsOn"]

shape: (5, 7)
┌──────────┬────────┬───────┬────────────────────┬────────────────────┬───────┬────────────────────┐
│ Sequence ┆ Type   ┆ Name  ┆ Command            ┆ Value              ┆ Layer ┆ DependsOn          │
│ ---      ┆ ---    ┆ ---   ┆ ---                ┆ ---                ┆ ---   ┆ ---                │
│ u32      ┆ str    ┆ str   ┆ str                ┆ str                ┆ u32   ┆ list[str]          │
╞══════════╪════════╪═══════╪════════════════════╪════════════════════╪═══════╪════════════════════╡
│ 0        ┆ point  ┆ O_{2} ┆ null               ┆ O_{2} = (-2.1,     ┆ 9     ┆ []                 │
│          ┆        ┆       ┆                    ┆ -0.1)              ┆       ┆                    │
│ 2        ┆ point  ┆ B     ┆ Point(Line(O_{2},  ┆ B = (-9.6, -0.2)   ┆ 9     ┆ ["A", "O_{2}"]     │
│          ┆        ┆       ┆ A))                ┆                    ┆       ┆                    │
│ 3        ┆ circle ┆ c     ┆ Circle(O_{2}, B)   ┆ c: (x + 2.1)² + (y ┆ 9     ┆ ["A", "B",         │
│          ┆        ┆       ┆                    ┆ + 0.1)² = 5…       ┆       ┆ "O_{2}"]           │
│ 26       ┆ point  ┆ O_{1} ┆ Point(r)           ┆ O_{1} = (10, -4.7) ┆ 9     ┆ ["A", "B", … "r"]  │
│ 33       ┆ circle ┆ h_1   ┆ Circle(O_{1},      ┆ h_1: (x - 10)² +   ┆ 9     ┆ ["A", "B", … "t"]  │
│          ┆        ┆       ┆ F_{1})             ┆ (y + 4.7)² = …     ┆       ┆                    │
└──────────┴────────┴───────┴────────────────────┴────────────────────┴───────┴────────────────────┘

## Geometric scenes

In [91]:
l1 = p.df.filter(pl.col("Layer").is_in([9, 0, 1, 2, 3]))["Name"].to_list()
l1

['O_{2}',
 'A',
 'B',
 'c',
 'j',
 'l',
 'q',
 'r',
 'O_{1}',
 't',
 'F_{1}',
 'h_1',
 'p_2',
 'q_2',
 'r_2',
 'M',
 'b_2',
 'F_{2}',
 "P'",
 'P',
 'j_1',
 'k_1',
 'l_1',
 'm_1',
 'C',
 'q_1',
 'Q',
 'R',
 'h',
 'e_1',
 'I',
 'k_2',
 'm_2',
 'n_2',
 'L',
 'N',
 'S',
 's_2',
 't_2',
 'd_2',
 'T',
 'ι',
 'κ',
 'λ',
 'μ',
 'U',
 'h_3',
 'i_3',
 'η',
 'ζ',
 'ε']

In [92]:
nx.write_network_text(p.G.subgraph(l1))

╟── O_{2} (point)
╎   ├─╼ B (point) ╾ A (point)
╎   │   └─╼ c (circle) ╾ O_{2} (point)
╎   │       ├─╼ j (line) ╾ A (point)
╎   │       │   ├─╼ q (line) ╾ l (line)
╎   │       │   ├─╼ r (line) ╾ l (line)
╎   │       │   │   └─╼ O_{1} (point)
╎   │       │   │       ├─╼ t (line) ╾ l (line)
╎   │       │   │       │   └─╼ F_{1} (point) ╾ l (line)
╎   │       │   │       │       ├─╼ h_1 (circle) ╾ O_{1} (point)
╎   │       │   │       │       │   ├─╼ p_2 (circle) ╾ O_{2} (point), c (circle)
╎   │       │   │       │       │   │   ├─╼ q_2 (line) ╾ O_{1} (point)
╎   │       │   │       │       │   │   │   └─╼ N (point) ╾ p_2 (circle)
╎   │       │   │       │       │   │   │       └─╼ d_2 (ray) ╾ O_{2} (point)
╎   │       │   │       │       │   │   │           └─╼ T (point) ╾ c (circle)
╎   │       │   │       │       │   │   ├─╼ r_2 (line) ╾ O_{1} (point)
╎   │       │   │       │       │   │   │   └─╼ M (point) ╾ p_2 (circle)
╎   │       │   │       │       │   │   │       └─╼ b_2 (ray) ╾ O_{2} (point)
╎   │       │   │       │       │   │   │           └─╼ F_{2} (point) ╾ c (circle)
╎   │       │   │       │       │   │   │               ├─╼ h (circle) ╾ C (point)
╎   │       │   │       │       │   │   │               ├─╼ e_1 (line) ╾ l (line)
╎   │       │   │       │       │   │   │               ├─╼ ι (angle) ╾ C (point), O_{2} (point)
╎   │       │   │       │       │   │   │               └─╼ μ (angle) ╾ C (point), O_{1} (point)
╎   │       │   │       │       │   │   └─╼  ...
╎   │       │   │       │       │   ├─╼ j_1 (line) ╾ P' (point)
╎   │       │   │       │       │   │   └─╼ Q (point) ╾ h_1 (circle)
╎   │       │   │       │       │   │       └─╼ η (angle) ╾ O_{1} (point), A (point)
╎   │       │   │       │       │   ├─╼ k_1 (line) ╾ P' (point)
╎   │       │   │       │       │   │   ├─╼ R (point) ╾ h_1 (circle)
╎   │       │   │       │       │   │   │   └─╼ λ (angle) ╾ C (point), O_{1} (point)
╎   │       │   │       │       │   │   ├─╼ I (point) ╾ c (circle)
╎   │       │   │       │       │   │   │   └─╼ κ (angle) ╾ C (point), O_{2} (point)
╎   │       │   │       │       │   │   ├─╼ h_3 (line) ╾ m_1 (line)
╎   │       │   │       │       │   │   └─╼ i_3 (line) ╾ m_1 (line)
╎   │       │   │       │       │   ├─╼ l_1 (line) ╾ P (point)
╎   │       │   │       │       │   │   └─╼ U (point) ╾ h_1 (circle)
╎   │       │   │       │       │   ├─╼ m_1 (line) ╾ P (point)
╎   │       │   │       │       │   │   └─╼  ...
╎   │       │   │       │       │   ├─╼ k_2 (circle) ╾ O_{2} (point), c (circle)
╎   │       │   │       │       │   │   ├─╼ m_2 (line) ╾ O_{1} (point)
╎   │       │   │       │       │   │   │   └─╼ L (point) ╾ k_2 (circle)
╎   │       │   │       │       │   │   │       └─╼ s_2 (ray) ╾ O_{2} (point)
╎   │       │   │       │       │   │   ├─╼ n_2 (line) ╾ O_{1} (point)
╎   │       │   │       │       │   │   │   └─╼ S (point) ╾ k_2 (circle)
╎   │       │   │       │       │   │   │       └─╼ t_2 (ray) ╾ O_{2} (point)
╎   │       │   │       │       │   │   └─╼  ...
╎   │       │   │       │       │   └─╼  ...
╎   │       │   │       │       ├─╼ q_1 (circle) ╾ A (point)
╎   │       │   │       │       ├─╼ ζ (angle) ╾ O_{1} (point), A (point)
╎   │       │   │       │       └─╼ ε (angle) ╾ O_{2} (point), A (point)
╎   │       │   │       └─╼  ...
╎   │       │   └─╼ P' (point)
╎   │       │       └─╼  ...
╎   │       ├─╼ l (line) ╾ A (point)
╎   │       │   ├─╼ P (point)
╎   │       │   │   └─╼  ...
╎   │       │   ├─╼ C (point)
╎   │       │   │   └─╼  ...
╎   │       │   └─╼  ...
╎   │       └─╼  ...
╎   └─╼  ...
╙── A (point)
    └─╼  ...

In [93]:
nx.ancestors(p.G, 'F_{2}')

{'A',
 'B',
 'F_{1}',
 'M',
 'O_{1}',
 'O_{2}',
 'b_2',
 'c',
 'h_1',
 'j',
 'l',
 'p_2',
 'r',
 'r_2',
 't'}

In [94]:
p.ft['F_{2}']

['Intersect', 'c', 'b_2', '1']

In [95]:
p.ft['p']

['Circle', "O'", 'A']

In [96]:
from itertools import zip_longest

In [97]:
l0 = range(10)
await ggb.function("setLayerVisible", list(zip_longest(list(l0), [], fillvalue=False)))
l0 = [9, 0, 1, 2, 3]
await ggb.function("setLayerVisible", list(zip_longest(list(l0), [], fillvalue=True)))

[None, None, None, None, None]

In [98]:
p.roots

['O_{2}', 'A']

In [99]:
p.G.subgraph(l1)

In [100]:
from collections import defaultdict
s0 = defaultdict(int)
for n, e in nx.dfs_edges(p.G.subgraph(l1), source='A'):
    # print(nx.ancestors(p.G, n), e)
    for n1 in nx.ancestors(p.G, n):
        if n1 not in s0:
            print(n1)
            s0[n1] += 1
    s0[n] += 1
    s0[e] += 1
s0

O_{2}
l
b
P'
P

defaultdict(int,
            {'A': 1,
             'B': 2,
             'O_{2}': 1,
             'c': 3,
             'j': 4,
             'q': 1,
             'r': 2,
             'l': 4,
             'O_{1}': 2,
             't': 2,
             'F_{1}': 5,
             'h_1': 7,
             'p_2': 3,
             'q_2': 2,
             'N': 2,
             'd_2': 2,
             'T': 1,
             'r_2': 2,
             'M': 2,
             'b_2': 2,
             'F_{2}': 5,
             'h': 1,
             'e_1': 1,
             'ι': 1,
             'μ': 1,
             'j_1': 2,
             'b': 1,
             "P'": 2,
             'Q': 2,
             'η': 1,
             'k_1': 5,
             'R': 2,
             'λ': 1,
             'I': 2,
             'κ': 1,
             'h_3': 1,
             'i_3': 1,
             'l_1': 2,
             'P': 2,
             'U': 1,
             'm_1': 1,
             'k_2': 3,
             'm_2': 2,
             'L': 2,
             's_2': 1,
             'n_2': 2,
             'S': 2,
             't_2': 1,
             'q_1': 1,
             'ζ': 1,
             'ε': 1,
             'C': 1})

In [101]:
from itertools import zip_longest

In [102]:
import asyncio

l0 = range(10)
await ggb.function("setLayerVisible", list(zip_longest(list(l0), [], fillvalue=False)))

l1 = list(s0.keys())

In [103]:
# for i in range(len(l1)):
#     l2 = list(zip_longest(l1, [True]*i, fillvalue=False))
#     # print(l2)
#     await ggb.function("setVisible", l2)
#     await asyncio.sleep(1)

In [104]:
%gui asyncio

In [105]:
# Helper function to create a future that waits for a widget change
# def wait_for_change(widget, value):
#     future = asyncio.Future()
#     def get_value(change):
#         future.set_result(change.new)
#         widget.unobserve(get_value, value)
#     widget.observe(get_value, value)
#     return future

# value = await wait_for_change(slider, 'value')

In [106]:
import ipywidgets as widgets
from IPython.display import display
import asyncio

# Your list of items
data_list = list(s0.keys())

# Create an IntSlider
# The min value is 0 (the first index)
# The max value is the last index (length of list - 1)
# The default value can be set to the starting index
slider = widgets.IntSlider(
    value=0,
    min=0,
    max=len(data_list) - 1,
    step=1,
    description='Select Index:',
    continuous_update=True # Update only when the slider is released
)

# Function to handle changes in the slider's value
async def on_slider_change(change):
    selected_index = change['new']
    selected_item = data_list[selected_index]
    l2 = list(zip_longest(l1, [True]*(selected_index+1), fillvalue=False))
    await(ggb.function("setVisible", l2))

def observe_wrapper(change):
    asyncio.ensure_future(on_slider_change(change))

slider.observe(observe_wrapper, names='value')

display(slider)
# Initial display (optional, can be called once to show the initial state)
await on_slider_change({'new': slider.value})

IntSlider(value=0, description='Select Index:', max=51)

## store

In [88]:
ggb.file.base64_buffer = await ggb.function("getBase64")
c.save(overwrite=True)