# ggblab Examples

This notebook demonstrates basic usage of `ggblab`. It walks through loading a `.ggb` file, displaying it in the GeoGebra widget, and parsing the construction for inspection and manipulation.

Key points:

- Large constructions are handled using `getBase64` / `setBase64` (zip + base64).
- Run cells from top to bottom for the examples to work as intended.
- Cells that produce output (e.g., version checks, object lists) will display their results directly below the code cell.

In [ ]:
# this magic for develop only
%load_ext autoreload
%autoreload 2

## Create and initialize GeoGebra

The next two cells import the `GeoGebra` controller and initialize the widget. The import cell does not print output; the initialization cell may open the widget and produce transient console output in the notebook UI.

## Create GeoGebra controller

Import and construct the `GeoGebra` controller; the next cell initializes the widget in the JupyterLab UI.

In [1]:
from ggblab import GeoGebra

## Initialize the GeoGebra widget

This cell runs `await GeoGebra().init()` to open the GeoGebra widget attached to the current kernel. Expect the widget to appear in the JupyterLab UI; the cell may print status messages or the kernel may emit frontend messages (these appear in the notebook output area).

In [2]:
# open GeoGebra Widget on left-side
ggb = await GeoGebra().init()

Using local cached file: xsd/common.xsd

## Version checks (package)

This cell prints the installed `ggblab` package version. Expect a short version string as the cell output.

In [3]:
# ggblab version
import ggblab
ggblab.__version__

'1.1.0'

## Version checks (applet)

This cell queries the GeoGebra applet with `getVersion()` and prints the applet version string. The output helps verify compatibility.

In [4]:
# GeoGebra Applet version
r = await ggb.function("getVersion")
r

'5.2.909.9'

## Load a .ggb file

Load a `.ggb` file from disk into the local `ggb.construction` object for inspection and sending to the applet.

In [5]:
# load from .ggb (zipped, and base64 encoded)
c = ggb.file.load('2025_06_08.ggb')

## Send construction to the applet

Use `setBase64` to send the loaded .ggb (zip+base64) to the GeoGebra view so it is rendered in the widget.

In [6]:
# sending loaded construction to GeoGebra view and draw
r = await ggb.function("setBase64", [ggb.construction.base64_buffer.decode('utf-8')])

## Parse the construction XML

Decode the construction XML into Python structures (dicts/lists) so you can inspect and modify element attributes programmatically.

In [7]:
# parse loaded xml as python dict
o = c.ggb_schema.decode(c.geogebra_xml)

In [8]:
# list of all object names
[e['@label'] for e in o['element']]

['O_{2}',
 'A',
 'B',
 'c',
 'n',
 "O'",
 'p',
 'G',
 'F_{2}',
 'j',
 'l',
 'β',
 'γ',
 't1',
 'a',
 'c_1',
 'g_1',
 't2',
 'a_1',
 'c_2',
 'i_1',
 'k',
 'm',
 'δ',
 'ε',
 'q',
 'r',
 'e',
 'A_{1}',
 'C_{1}',
 'H',
 'J',
 'K',
 'ζ',
 'η',
 'O_{1}',
 'θ',
 's',
 'b',
 'N',
 'P',
 't',
 'F_{1}',
 'h_1',
 'j_1',
 'k_1',
 'l_1',
 'm_1',
 'I',
 'p_1',
 'n_1',
 'C',
 'q_1',
 'r_1',
 'Q',
 'R',
 'S',
 'T',
 't_1',
 'b_1',
 'D',
 't3',
 'd',
 'o',
 'l_2',
 'α',
 'O',
 'f',
 'i',
 't4',
 'c_3',
 'i_2',
 'a_2',
 'h',
 'g',
 'f_1',
 's_1',
 'd_1',
 'e_1',
 'E',
 'F',
 'f_2',
 'd_2']

In [9]:
[e['@label'] for e in o['element']].index('A')

1

In [10]:
o['element'][1]

{'@type': 'point',
 '@label': 'A',
 'show': [{'@object': True, '@label': True, '@ev': 4}],
 'objColor': [{'@r': 176, '@g': 0, '@b': 32, '@alpha': 0.0}],
 'layer': [{'@val': 9}],
 'labelMode': [{'@val': 0}],
 'animation': [{'@step': '0.1', '@type': 1, '@playing': False}],
 'pointSize': [{'@val': 5.0}],
 'pointStyle': [{'@val': 0}],
 'coords': [{'@x': '10', '@y': '0', '@z': '1'}]}

In [11]:
# change visible state of object 'A'
o['element'][1]['show'][0]['@object'] = False

In [12]:
import xmlschema

In [13]:
# construct attributes from dict
x = xmlschema.etree_tostring(c.ggb_schema.encode(o['element'][1], 'element'))
print(x)

<element type="point" label="A">
    <show object="false" label="true" ev="4" />
    <objColor r="176" g="0" b="32" alpha="0.0" />
    <layer val="9" />
    <labelMode val="0" />
    <animation step="0.1" type="1" playing="false" />
    <pointSize val="5.0" />
    <pointStyle val="0" />
    <coords x="10" y="0" z="1" />
</element>

## Temporary updates with `preserve()`

The `preserve()` context manager snapshots the applet state (using a zip+base64 snapshot) and restores it automatically when the block exits.

Usage notes:

- The snapshot is taken with `getBase64` and restored with `setBase64` when available.
- The yielded `snap` object includes `base64_zip`, `xml` (optional), `timestamp`, `size_bytes`, and `sha1`.
- Call `await snap.restore()` to restore immediately; call `snap.release()` to drop the stored snapshot from memory.

In [14]:
import asyncio

In [15]:
# update the applet
async with ggb.preserve() as snap:
    r = await ggb.function("evalXML", [x])
    await asyncio.sleep(3)

## Advanced inspection

The following examples show how to decode the base64 snapshot, open the embedded zip, and inspect internal files (including the main construction XML). Expected outputs include a list of filenames inside the `.ggb` zip and the decoded XML string(s).

## Inspect base64 snapshot

Decode the base64 snapshot and inspect the zipped content (files inside the .ggb). This is useful when debugging or extracting the main construction XML.

In [16]:
import base64
import zipfile
import io

In [17]:
type(snap.base64_zip)

str

In [18]:
with zipfile.ZipFile(io.BytesIO(base64.b64decode(snap.base64_zip))) as zf:
    for info in zf.infolist():
        if info.filename == 'geogebra.xml':
            with zf.open(info) as f:
                xml = f.read()

In [19]:
type(xml.decode())

str

In [20]:
# r = await ggb.function("setXML", [xml.decode()])

In [21]:
await ggb.function("setBase64", [snap.base64_zip])

## draw step-by-step from new construction

In [22]:
# draw step-by-step from new construction
r = await ggb.function("newConstruction")

names = [e['@label'] for e in o['element']]
for n in names:
    cmd = None
    ci, co = None, None
    for _c in o['command']:
        _ci = tuple(zip(*_c['input'].items()))[1]
        _co = tuple(zip(*_c['output'].items()))[1]
        if n in _co:
            cmd = _c
            ci = _ci
            co = _co
            break

    match names.index(n):
        case int(i):
            ei = o['element'][i]
            if cmd:
                if co.index(n) == 0:
                    x = xmlschema.etree_tostring(c.ggb_schema.encode(cmd, 'construction/command'))
                    r = await ggb.function("evalXML", [x])
                    # print(f"command: {n}")
            x = xmlschema.etree_tostring(c.ggb_schema.encode(ei, 'element'))
            r = await ggb.function("evalXML", [x])
            # print(f"element:{n}")

In [23]:
ggb.comm.logs

['register_target_cb: <ipykernel.comm.comm.Comm object at 0x128454910>',
 'Clients connected: 1 (connects+=1, disconnects+=0)',
 'Clients connected: 1 (connects+=2, disconnects+=2)',
 'Clients connected: 1 (connects+=84, disconnects+=84)',
 'Clients connected: 1 (connects+=36, disconnects+=36)',
 'Clients connected: 1 (connects+=50, disconnects+=50)',
 'Clients connected: 1 (connects+=89, disconnects+=89)',
 'Clients connected: 1 (connects+=82, disconnects+=82)',
 'Clients connected: 1 (connects+=83, disconnects+=83)']

In [24]:
ggb.comm.recv_msgs

{}

In [25]:
ggb.comm.pending_futures

{}

In [26]:
ggb.comm.recv_events.queue

deque([{'type': 'start', 'payload': {}},
       {'type': 'add', 'payload': 'O_{2}'},
       {'type': 'add', 'payload': 'A'},
       {'type': 'add', 'payload': 'B'},
       {'type': 'add', 'payload': 'c'},
       {'type': 'add', 'payload': 'n'},
       {'type': 'add', 'payload': "O'"},
       {'type': 'add', 'payload': 'p'},
       {'type': 'add', 'payload': 'G'},
       {'type': 'add', 'payload': 'F_{2}'},
       {'type': 'add', 'payload': 'j'},
       {'type': 'add', 'payload': 'l'},
       {'type': 'add', 'payload': 'β'},
       {'type': 'add', 'payload': 'γ'},
       {'type': 'add', 'payload': 't1'},
       {'type': 'add', 'payload': 'a'},
       {'type': 'add', 'payload': 'c_1'},
       {'type': 'add', 'payload': 'g_1'},
       {'type': 'add', 'payload': 't2'},
       {'type': 'add', 'payload': 'a_1'},
       {'type': 'add', 'payload': 'c_2'},
       {'type': 'add', 'payload': 'i_1'},
       {'type': 'add', 'payload': 'k'},
       {'type': 'add', 'payload': 'm'},
       {'type': 'add', 'payload': 'δ'},
       {'type': 'add', 'payload': 'ε'},
       {'type': 'add', 'payload': 'q'},
       {'type': 'add', 'payload': 'r'},
       {'type': 'add', 'payload': 'e'},
       {'type': 'add', 'payload': 'A_{1}'},
       {'type': 'add', 'payload': 'C_{1}'},
       {'type': 'add', 'payload': 'H'},
       {'type': 'add', 'payload': 'J'},
       {'type': 'add', 'payload': 'K'},
       {'type': 'add', 'payload': 'ζ'},
       {'type': 'add', 'payload': 'η'},
       {'type': 'add', 'payload': 'O_{1}'},
       {'type': 'add', 'payload': 'θ'},
       {'type': 'add', 'payload': 's'},
       {'type': 'add', 'payload': 'b'},
       {'type': 'add', 'payload': 'N'},
       {'type': 'add', 'payload': 'P'},
       {'type': 'add', 'payload': 't'},
       {'type': 'add', 'payload': 'F_{1}'},
       {'type': 'add', 'payload': 'h_1'},
       {'type': 'add', 'payload': 'j_1'},
       {'type': 'add', 'payload': 'k_1'},
       {'type': 'add', 'payload': 'l_1'},
       {'type': 'add', 'payload': 'm_1'},
       {'type': 'add', 'payload': 'I'},
       {'type': 'add', 'payload': 'p_1'},
       {'type': 'add', 'payload': 'n_1'},
       {'type': 'add', 'payload': 'C'},
       {'type': 'add', 'payload': 'q_1'},
       {'type': 'add', 'payload': 'r_1'},
       {'type': 'add', 'payload': 'Q'},
       {'type': 'add', 'payload': 'R'},
       {'type': 'add', 'payload': 'S'},
       {'type': 'add', 'payload': 'T'},
       {'type': 'add', 'payload': 't_1'},
       {'type': 'add', 'payload': 'b_1'},
       {'type': 'add', 'payload': 'D'},
       {'type': 'add', 'payload': 't3'},
       {'type': 'add', 'payload': 'd'},
       {'type': 'add', 'payload': 'o'},
       {'type': 'add', 'payload': 'l_2'},
       {'type': 'add', 'payload': 'α'},
       {'type': 'add', 'payload': 'O'},
       {'type': 'add', 'payload': 'f'},
       {'type': 'add', 'payload': 'i'},
       {'type': 'add', 'payload': 't4'},
       {'type': 'add', 'payload': 'c_3'},
       {'type': 'add', 'payload': 'i_2'},
       {'type': 'add', 'payload': 'a_2'},
       {'type': 'add', 'payload': 'h'},
       {'type': 'add', 'payload': 'g'},
       {'type': 'add', 'payload': 'f_1'},
       {'type': 'add', 'payload': 's_1'},
       {'type': 'add', 'payload': 'd_1'},
       {'type': 'add', 'payload': 'e_1'},
       {'type': 'add', 'payload': 'E'},
       {'type': 'add', 'payload': 'F'},
       {'type': 'add', 'payload': 'f_2'},
       {'type': 'add', 'payload': 'd_2'},
       {'type': 'add', 'payload': 'O_{2}'},
       {'type': 'add', 'payload': 'A'},
       {'type': 'add', 'payload': 'B'},
       {'type': 'add', 'payload': 'c'},
       {'type': 'add', 'payload': 'n'},
       {'type': 'add', 'payload': "O'"},
       {'type': 'add', 'payload': 'p'},
       {'type': 'add', 'payload': 'G'},
       {'type': 'add', 'payload': 'F_{2}'},
       {'type': 'add', 'payload': 'j'},
       {'type': 'add', 'payload': 'l'},
       {'type': 'add', 'payload': 'β'},
       {'type': 'add', 'payload': 'γ'},
       {'type': 'add', 'payload': 't1'},
       {'type': 'add', 'payload': 'a'},
       {'type': 'add', 'payload': 'c_1'},
       {'type': 'add', 'payload': 'g_1'},
       {'type': 'add', 'payload': 't2'},
       {'type': 'add', 'payload': 'a_1'},
       {'type': 'add', 'payload': 'c_2'},
       {'type': 'add', 'payload': 'i_1'},
       {'type': 'add', 'payload': 'k'},
       {'type': 'add', 'payload': 'm'},
       {'type': 'add', 'payload': 'δ'},
       {'type': 'add', 'payload': 'ε'},
       {'type': 'add', 'payload': 'q'},
       {'type': 'add', 'payload': 'r'},
       {'type': 'add', 'payload': 'e'},
       {'type': 'add', 'payload': 'A_{1}'},
       {'type': 'add', 'payload': 'C_{1}'},
       {'type': 'add', 'payload': 'H'},
       {'type': 'add', 'payload': 'J'},
       {'type': 'add', 'payload': 'K'},
       {'type': 'add', 'payload': 'ζ'},
       {'type': 'add', 'payload': 'η'},
       {'type': 'add', 'payload': 'O_{1}'},
       {'type': 'add', 'payload': 'θ'},
       {'type': 'add', 'payload': 's'},
       {'type': 'add', 'payload': 'b'},
       {'type': 'add', 'payload': 'N'},
       {'type': 'add', 'payload': 'P'},
       {'type': 'add', 'payload': 't'},
       {'type': 'add', 'payload': 'F_{1}'},
       {'type': 'add', 'payload': 'h_1'},
       {'type': 'add', 'payload': 'j_1'},
       {'type': 'add', 'payload': 'k_1'},
       {'type': 'add', 'payload': 'l_1'},
       {'type': 'add', 'payload': 'm_1'},
       {'type': 'add', 'payload': 'I'},
       {'type': 'add', 'payload': 'p_1'},
       {'type': 'add', 'payload': 'n_1'},
       {'type': 'add', 'payload': 'C'},
       {'type': 'add', 'payload': 'q_1'},
       {'type': 'add', 'payload': 'r_1'},
       {'type': 'add', 'payload': 'Q'},
       {'type': 'add', 'payload': 'R'},
       {'type': 'add', 'payload': 'S'},
       {'type': 'add', 'payload': 'T'},
       {'type': 'add', 'payload': 't_1'},
       {'type': 'add', 'payload': 'b_1'},
       {'type': 'add', 'payload': 'D'},
       {'type': 'add', 'payload': 't3'},
       {'type': 'add', 'payload': 'd'},
       {'type': 'add', 'payload': 'o'},
       {'type': 'add', 'payload': 'l_2'},
       {'type': 'add', 'payload': 'α'},
       {'type': 'add', 'payload': 'O'},
       {'type': 'add', 'payload': 'f'},
       {'type': 'add', 'payload': 'i'},
       {'type': 'add', 'payload': 't4'},
       {'type': 'add', 'payload': 'c_3'},
       {'type': 'add', 'payload': 'i_2'},
       {'type': 'add', 'payload': 'a_2'},
       {'type': 'add', 'payload': 'h'},
       {'type': 'add', 'payload': 'g'},
       {'type': 'add', 'payload': 'f_1'},
       {'type': 'add', 'payload': 's_1'},
       {'type': 'add', 'payload': 'd_1'},
       {'type': 'add', 'payload': 'e_1'},
       {'type': 'add', 'payload': 'E'},
       {'type': 'add', 'payload': 'F'},
       {'type': 'add', 'payload': 'f_2'},
       {'type': 'add', 'payload': 'd_2'},
       {'type': 'add', 'payload': 'O_{2}'},
       {'type': 'add', 'payload': 'A'},
       {'type': 'add', 'payload': 'B'},
       {'type': 'add', 'payload': 'c'},
       {'type': 'add', 'payload': 'n'},
       {'type': 'add', 'payload': "O'"},
       {'type': 'add', 'payload': 'p'},
       {'type': 'add', 'payload': 'G'},
       {'type': 'add', 'payload': 'F_{2}'},
       {'type': 'add', 'payload': 'j'},
       {'type': 'add', 'payload': 'l'},
       {'type': 'add', 'payload': 'β'},
       {'type': 'add', 'payload': 'γ'},
       {'type': 'add', 'payload': 't1'},
       {'type': 'add', 'payload': 'a'},
       {'type': 'add', 'payload': 'c_1'},
       {'type': 'add', 'payload': 'g_1'},
       {'type': 'add', 'payload': 't2'},
       {'type': 'add', 'payload': 'a_1'},
       {'type': 'add', 'payload': 'c_2'},
       {'type': 'add', 'payload': 'i_1'},
       {'type': 'add', 'payload': 'k'},
       {'type': 'add', 'payload': 'm'},
       {'type': 'add', 'payload': 'δ'},
       {'type': 'add', 'payload': 'ε'},
       {'type': 'add', 'payload': 'q'},
       {'type': 'add', 'payload': 'r'},
       {'type': 'add', 'payload': 'e'},
       {'type': 'add', 'payload': 'A_{1}'},
       {'type': 'add', 'payload': 'C_{1}'},
       {'type': 'add', 'payload': 'H'},
       {'type': 'add', 'payload': 'J'},
       {'type': 'add', 'payload': 'K'},
       {'type': 'add', 'payload': 'ζ'},
       {'type': 'add', 'payload': 'η'},
       {'type': 'add', 'payload': 'O_{1}'},
       {'type': 'add', 'payload': 'θ'},
       {'type': 'add', 'payload': 's'},
       {'type': 'add', 'payload': 'b'},
       {'type': 'add', 'payload': 'N'},
       {'type': 'add', 'payload': 'P'},
       {'type': 'add', 'payload': 't'},
       {'type': 'add', 'payload': 'F_{1}'},
       {'type': 'add', 'payload': 'h_1'},
       {'type': 'add', 'payload': 'j_1'},
       {'type': 'add', 'payload': 'k_1'},
       {'type': 'add', 'payload': 'l_1'},
       {'type': 'add', 'payload': 'm_1'},
       {'type': 'add', 'payload': 'I'},
       {'type': 'add', 'payload': 'p_1'},
       {'type': 'add', 'payload': 'n_1'},
       {'type': 'add', 'payload': 'C'},
       {'type': 'add', 'payload': 'q_1'},
       {'type': 'add', 'payload': 'r_1'},
       {'type': 'add', 'payload': 'Q'},
       {'type': 'add', 'payload': 'R'},
       {'type': 'add', 'payload': 'S'},
       {'type': 'add', 'payload': 'T'},
       {'type': 'add', 'payload': 't_1'},
       {'type': 'add', 'payload': 'b_1'},
       {'type': 'add', 'payload': 'D'},
       {'type': 'add', 'payload': 't3'},
       {'type': 'add', 'payload': 'd'},
       {'type': 'add', 'payload': 'o'},
       {'type': 'add', 'payload': 'l_2'},
       {'type': 'add', 'payload': 'α'},
       {'type': 'add', 'payload': 'O'},
       {'type': 'add', 'payload': 'f'},
       {'type': 'add', 'payload': 'i'},
       {'type': 'add', 'payload': 't4'},
       {'type': 'add', 'payload': 'c_3'},
       {'type': 'add', 'payload': 'i_2'},
       {'type': 'add', 'payload': 'a_2'},
       {'type': 'add', 'payload': 'h'},
       {'type': 'add', 'payload': 'g'},
       {'type': 'add', 'payload': 'f_1'},
       {'type': 'add', 'payload': 's_1'},
       {'type': 'add', 'payload': 'd_1'},
       {'type': 'add', 'payload': 'e_1'},
       {'type': 'add', 'payload': 'E'},
       {'type': 'add', 'payload': 'F'},
       {'type': 'add', 'payload': 'f_2'},
       {'type': 'add', 'payload': 'd_2'},
       {'type': 'add', 'payload': 'O_{2}'},
       {'type': 'add', 'payload': 'A'},
       {'type': 'add', 'payload': 'B'},
       {'type': 'add', 'payload': 'c'},
       {'type': 'add', 'payload': 'n'},
       {'type': 'add', 'payload': "O'"},
       {'type': 'add', 'payload': 'p'},
       {'type': 'add', 'payload': 'G'},
       {'type': 'add', 'payload': 'F_{2}'},
       {'type': 'add', 'payload': 'j'},
       {'type': 'add', 'payload': 'l'},
       {'type': 'add', 'payload': 'β'},
       {'type': 'add', 'payload': 'γ'},
       {'type': 'add', 'payload': 't1'},
       {'type': 'add', 'payload': 'a'},
       {'type': 'add', 'payload': 'c_1'},
       {'type': 'add', 'payload': 'g_1'},
       {'type': 'add', 'payload': 't2'},
       {'type': 'add', 'payload': 'a_1'},
       {'type': 'add', 'payload': 'c_2'},
       {'type': 'add', 'payload': 'i_1'},
       {'type': 'add', 'payload': 'k'},
       {'type': 'add', 'payload': 'm'},
       {'type': 'add', 'payload': 'δ'},
       {'type': 'add', 'payload': 'ε'},
       {'type': 'add', 'payload': 'q'},
       {'type': 'add', 'payload': 'r'},
       {'type': 'add', 'payload': 'e'},
       {'type': 'add', 'payload': 'A_{1}'},
       {'type': 'add', 'payload': 'C_{1}'},
       {'type': 'add', 'payload': 'H'},
       {'type': 'add', 'payload': 'J'},
       {'type': 'add', 'payload': 'K'},
       {'type': 'add', 'payload': 'ζ'},
       {'type': 'add', 'payload': 'η'},
       {'type': 'add', 'payload': 'O_{1}'},
       {'type': 'add', 'payload': 'θ'},
       {'type': 'add', 'payload': 's'},
       {'type': 'add', 'payload': 'b'},
       {'type': 'add', 'payload': 'N'},
       {'type': 'add', 'payload': 'P'},
       {'type': 'add', 'payload': 't'},
       {'type': 'add', 'payload': 'F_{1}'},
       {'type': 'add', 'payload': 'h_1'},
       {'type': 'add', 'payload': 'j_1'},
       {'type': 'add', 'payload': 'k_1'},
       {'type': 'add', 'payload': 'l_1'},
       {'type': 'add', 'payload': 'm_1'},
       {'type': 'add', 'payload': 'I'},
       {'type': 'add', 'payload': 'p_1'},
       {'type': 'add', 'payload': 'n_1'},
       {'type': 'add', 'payload': 'C'},
       {'type': 'add', 'payload': 'q_1'},
       {'type': 'add', 'payload': 'r_1'},
       {'type': 'add', 'payload': 'Q'},
       {'type': 'add', 'payload': 'R'},
       {'type': 'add', 'payload': 'S'},
       {'type': 'add', 'payload': 'T'},
       {'type': 'add', 'payload': 't_1'},
       {'type': 'add', 'payload': 'b_1'},
       {'type': 'add', 'payload': 'D'},
       {'type': 'add', 'payload': 't3'},
       {'type': 'add', 'payload': 'd'},
       {'type': 'add', 'payload': 'o'},
       {'type': 'add', 'payload': 'l_2'},
       {'type': 'add', 'payload': 'α'},
       {'type': 'add', 'payload': 'O'},
       {'type': 'add', 'payload': 'f'},
       {'type': 'add', 'payload': 'i'},
       {'type': 'add', 'payload': 't4'},
       {'type': 'add', 'payload': 'c_3'},
       {'type': 'add', 'payload': 'i_2'},
       {'type': 'add', 'payload': 'a_2'},
       {'type': 'add', 'payload': 'h'},
       {'type': 'add', 'payload': 'g'},
       {'type': 'add', 'payload': 'f_1'},
       {'type': 'add', 'payload': 's_1'},
       {'type': 'add', 'payload': 'd_1'},
       {'type': 'add', 'payload': 'e_1'},
       {'type': 'add', 'payload': 'E'},
       {'type': 'add', 'payload': 'F'},
       {'type': 'add', 'payload': 'f_2'},
       {'type': 'add', 'payload': 'd_2'}])

## ggblab_extra — construction protocol from the applet

These cells demonstrate how to extract a construction protocol (objects, commands, and dependency metadata) from a running GeoGebra applet using `ggblab_extra`.

They show how to initialize a structured `DataFrame` from the applet (`ConstructionIO.initialize_dataframe(ggb, use_applet=True)`) so you can analyze element attributes, sequences, and dependencies programmatically. These are analysis helpers and do not alter the stored applet state unless you explicitly call functions that modify the applet.

In [27]:
import polars as pl
import networkx as nx

In [28]:
from ggblab_extra.construction_io import ConstructionIO
df = await ConstructionIO.initialize_dataframe(ggb, use_applet=True)

In [29]:
df

shape: (83, 10)
┌──────────┬───────┬──────────┬───────────────────┬───┬───────┬────────────┬───────────┬───────────┐
│ Sequence ┆ Name  ┆ Type     ┆ Command           ┆ … ┆ Layer ┆ ShowObject ┆ ShowLabel ┆ Auxiliary │
│ ---      ┆ ---   ┆ ---      ┆ ---               ┆   ┆ ---   ┆ ---        ┆ ---       ┆ ---       │
│ u32      ┆ str   ┆ str      ┆ str               ┆   ┆ u32   ┆ bool       ┆ bool      ┆ bool      │
╞══════════╪═══════╪══════════╪═══════════════════╪═══╪═══════╪════════════╪═══════════╪═══════════╡
│ 0        ┆ O_{2} ┆ point    ┆ null              ┆ … ┆ 9     ┆ true       ┆ true      ┆ false     │
│ 1        ┆ A     ┆ point    ┆ null              ┆ … ┆ 9     ┆ false      ┆ true      ┆ false     │
│ 2        ┆ B     ┆ point    ┆ Point(Line(O_{2}, ┆ … ┆ 9     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ A))               ┆   ┆       ┆            ┆           ┆           │
│ 3        ┆ c     ┆ circle   ┆ Circle(O_{2}, B)  ┆ … ┆ 9     ┆ true       ┆ false     ┆ false     │
│ 4        ┆ n     ┆ line     ┆ Line(O_{2}, A)    ┆ … ┆ 9     ┆ true       ┆ false     ┆ false     │
│ 5        ┆ O'    ┆ point    ┆ Midpoint(O_{2},   ┆ … ┆ 0     ┆ false      ┆ true      ┆ false     │
│          ┆       ┆          ┆ A)                ┆   ┆       ┆            ┆           ┆           │
│ 6        ┆ p     ┆ circle   ┆ Circle(O', A)     ┆ … ┆ 0     ┆ false      ┆ false     ┆ false     │
│ 7        ┆ G     ┆ point    ┆ Intersect(c, p)   ┆ … ┆ 0     ┆ true       ┆ false     ┆ false     │
│ 8        ┆ F_{2} ┆ point    ┆ Intersect(c, p)   ┆ … ┆ 0     ┆ true       ┆ true      ┆ false     │
│ 9        ┆ j     ┆ line     ┆ Tangent(A, c)     ┆ … ┆ 9     ┆ true       ┆ false     ┆ false     │
│ 10       ┆ l     ┆ line     ┆ Tangent(A, c)     ┆ … ┆ 9     ┆ true       ┆ false     ┆ false     │
│ 11       ┆ β     ┆ angle    ┆ Angle(A, G,       ┆ … ┆ 0     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{2})            ┆   ┆       ┆            ┆           ┆           │
│ 12       ┆ γ     ┆ angle    ┆ Angle(A, F_{2},   ┆ … ┆ 0     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{2})            ┆   ┆       ┆            ┆           ┆           │
│ 13       ┆ t1    ┆ triangle ┆ Polygon(A, G,     ┆ … ┆ 0     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{2})            ┆   ┆       ┆            ┆           ┆           │
│ 14       ┆ a     ┆ segment  ┆ Segment(A, G, t1) ┆ … ┆ 0     ┆ false      ┆ false     ┆ true      │
│ 15       ┆ c_1   ┆ segment  ┆ Segment(G, O_{2}, ┆ … ┆ 0     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ t1)               ┆   ┆       ┆            ┆           ┆           │
│ 16       ┆ g_1   ┆ segment  ┆ Segment(O_{2}, A, ┆ … ┆ 0     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ t1)               ┆   ┆       ┆            ┆           ┆           │
│ 17       ┆ t2    ┆ triangle ┆ Polygon(A, F_{2}, ┆ … ┆ 0     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{2})            ┆   ┆       ┆            ┆           ┆           │
│ 18       ┆ a_1   ┆ segment  ┆ Segment(A, F_{2}, ┆ … ┆ 0     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ t2)               ┆   ┆       ┆            ┆           ┆           │
│ 19       ┆ c_2   ┆ segment  ┆ Segment(F_{2},    ┆ … ┆ 0     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ O_{2}, t2)        ┆   ┆       ┆            ┆           ┆           │
│ 20       ┆ i_1   ┆ segment  ┆ Segment(O_{2}, A, ┆ … ┆ 0     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ t2)               ┆   ┆       ┆            ┆           ┆           │
│ 21       ┆ k     ┆ segment  ┆ Segment(A, G)     ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│ 22       ┆ m     ┆ segment  ┆ Segment(A, F_{2}) ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│ 23       ┆ δ     ┆ angle    ┆ Angle(O_{2}, A,   ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ G)                ┆   ┆       ┆            ┆           ┆           │
│ 24       ┆ ε     ┆ angle    ┆ Angle(O_{2}, A,   ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ F_{2})            ┆   ┆       ┆            ┆           ┆           │
│ 25       ┆ q     ┆ line     ┆ AngleBisector(l,  ┆ … ┆ 2     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ j)                ┆   ┆       ┆            ┆           ┆           │
│ 26       ┆ r     ┆ line     ┆ AngleBisector(l,  ┆ … ┆ 2     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ j)                ┆   ┆       ┆            ┆           ┆           │
│ 27       ┆ e     ┆ circle   ┆ Circle(A, B)      ┆ … ┆ 3     ┆ false      ┆ false     ┆ true      │
│ 28       ┆ A_{1} ┆ point    ┆ Intersect(e, r,   ┆ … ┆ 3     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ 2)                ┆   ┆       ┆            ┆           ┆           │
│ 29       ┆ C_{1} ┆ point    ┆ Intersect(e, j)   ┆ … ┆ 3     ┆ false      ┆ false     ┆ true      │
│ 30       ┆ H     ┆ point    ┆ Intersect(e, j)   ┆ … ┆ 3     ┆ false      ┆ false     ┆ true      │
│ 31       ┆ J     ┆ point    ┆ Intersect(e, l)   ┆ … ┆ 3     ┆ false      ┆ false     ┆ true      │
│ 32       ┆ K     ┆ point    ┆ Intersect(e, l)   ┆ … ┆ 3     ┆ false      ┆ false     ┆ true      │
│ 33       ┆ ζ     ┆ angle    ┆ Angle(A_{1}, A,   ┆ … ┆ 2     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ K)                ┆   ┆       ┆            ┆           ┆           │
│ 34       ┆ η     ┆ angle    ┆ Angle(A_{1}, A,   ┆ … ┆ 2     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ C_{1})            ┆   ┆       ┆            ┆           ┆           │
│ 35       ┆ O_{1} ┆ point    ┆ Point(r)          ┆ … ┆ 9     ┆ true       ┆ true      ┆ false     │
│ 36       ┆ θ     ┆ angle    ┆ Angle(O_{2}, A,   ┆ … ┆ 2     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{1})            ┆   ┆       ┆            ┆           ┆           │
│ 37       ┆ s     ┆ line     ┆ PerpendicularLine ┆ … ┆ 6     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ (O_{1}, j)        ┆   ┆       ┆            ┆           ┆           │
│ 38       ┆ b     ┆ line     ┆ Line(O_{2},       ┆ … ┆ 3     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{1})            ┆   ┆       ┆            ┆           ┆           │
│ 39       ┆ N     ┆ point    ┆ Intersect(b, j)   ┆ … ┆ 6     ┆ true       ┆ false     ┆ false     │
│ 40       ┆ P     ┆ point    ┆ Intersect(b, l)   ┆ … ┆ 6     ┆ true       ┆ false     ┆ false     │
│ 41       ┆ t     ┆ line     ┆ PerpendicularLine ┆ … ┆ 4     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ (O_{1}, l)        ┆   ┆       ┆            ┆           ┆           │
│ 42       ┆ F_{1} ┆ point    ┆ Intersect(t, l)   ┆ … ┆ 4     ┆ true       ┆ true      ┆ false     │
│ 43       ┆ h_1   ┆ circle   ┆ Circle(O_{1},     ┆ … ┆ 4     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ F_{1})            ┆   ┆       ┆            ┆           ┆           │
│ 44       ┆ j_1   ┆ line     ┆ Tangent(N, h_1)   ┆ … ┆ 6     ┆ true       ┆ false     ┆ false     │
│ 45       ┆ k_1   ┆ line     ┆ Tangent(N, h_1)   ┆ … ┆ 6     ┆ true       ┆ false     ┆ false     │
│ 46       ┆ l_1   ┆ line     ┆ Tangent(P, h_1)   ┆ … ┆ 6     ┆ true       ┆ false     ┆ false     │
│ 47       ┆ m_1   ┆ line     ┆ Tangent(P, h_1)   ┆ … ┆ 6     ┆ true       ┆ false     ┆ false     │
│ 48       ┆ I     ┆ point    ┆ Midpoint(O_{2},   ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{1})            ┆   ┆       ┆            ┆           ┆           │
│ 49       ┆ p_1   ┆ circle   ┆ Circle(I, O_{2})  ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│ 50       ┆ n_1   ┆ line     ┆ Line(O_{2},       ┆ … ┆ 0     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ F_{2})            ┆   ┆       ┆            ┆           ┆           │
│ 51       ┆ C     ┆ point    ┆ Intersect(p_1, l, ┆ … ┆ 3     ┆ true       ┆ true      ┆ false     │
│          ┆       ┆          ┆ 1)                ┆   ┆       ┆            ┆           ┆           │
│ 52       ┆ q_1   ┆ circle   ┆ Circle(A, F_{1})  ┆ … ┆ 5     ┆ true       ┆ false     ┆ false     │
│ 53       ┆ r_1   ┆ circle   ┆ Circle(A, F_{2})  ┆ … ┆ 1     ┆ true       ┆ false     ┆ false     │
│ 54       ┆ Q     ┆ point    ┆ Intersect(h_1,    ┆ … ┆ 4     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ j_1)              ┆   ┆       ┆            ┆           ┆           │
│ 55       ┆ R     ┆ point    ┆ Intersect(h_1,    ┆ … ┆ 7     ┆ true       ┆ false     ┆ false     │
│          ┆       ┆          ┆ k_1)              ┆   ┆       ┆            ┆           ┆           │
│ 56       ┆ S     ┆ point    ┆ Intersect(c, k_1) ┆ … ┆ 7     ┆ true       ┆ false     ┆ false     │
│ 57       ┆ T     ┆ point    ┆ Intersect(c, k_1) ┆ … ┆ 8     ┆ false      ┆ true      ┆ true      │
│ 58       ┆ t_1   ┆ segment  ┆ Segment(Q, R)     ┆ … ┆ 8     ┆ false      ┆ false     ┆ false     │
│ 59       ┆ b_1   ┆ segment  ┆ Segment(G, S)     ┆ … ┆ 8     ┆ false      ┆ false     ┆ false     │
│ 60       ┆ D     ┆ point    ┆ Point(p_1)        ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│ 61       ┆ t3    ┆ triangle ┆ Polygon(O_{2},    ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{1}, D)         ┆   ┆       ┆            ┆           ┆           │
│ 62       ┆ d     ┆ segment  ┆ Segment(O_{2},    ┆ … ┆ 3     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ O_{1}, t3)        ┆   ┆       ┆            ┆           ┆           │
│ 63       ┆ o     ┆ segment  ┆ Segment(O_{1}, D, ┆ … ┆ 3     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ t3)               ┆   ┆       ┆            ┆           ┆           │
│ 64       ┆ l_2   ┆ segment  ┆ Segment(D, O_{2}, ┆ … ┆ 3     ┆ false      ┆ false     ┆ true      │
│          ┆       ┆          ┆ t3)               ┆   ┆       ┆            ┆           ┆           │
│ 65       ┆ α     ┆ angle    ┆ Angle(O_{2}, D,   ┆ … ┆ 3     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ O_{1})            ┆   ┆       ┆            ┆           ┆           │
│ 66       ┆ O     ┆ point    ┆ Midpoint(F_{1},   ┆ … ┆ 5     ┆ true       ┆ true      ┆ false     │
│          ┆       ┆          ┆ F_{2})            ┆   ┆       ┆            ┆           ┆           │
│ 67       ┆ f     ┆ line     ┆ PerpendicularLine ┆ … ┆ 5     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ (O, l)            ┆   ┆       ┆            ┆           ┆           │
│ 68       ┆ i     ┆ segment  ┆ Segment(F_{1},    ┆ … ┆ 4     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ F_{2})            ┆   ┆       ┆            ┆           ┆           │
│ 69       ┆ t4    ┆ triangle ┆ Polygon(I, A, C)  ┆ … ┆ 5     ┆ false      ┆ false     ┆ false     │
│ 70       ┆ c_3   ┆ segment  ┆ Segment(I, A, t4) ┆ … ┆ 5     ┆ false      ┆ false     ┆ true      │
│ 71       ┆ i_2   ┆ segment  ┆ Segment(A, C, t4) ┆ … ┆ 5     ┆ false      ┆ false     ┆ true      │
│ 72       ┆ a_2   ┆ segment  ┆ Segment(C, I, t4) ┆ … ┆ 5     ┆ false      ┆ false     ┆ true      │
│ 73       ┆ h     ┆ circle   ┆ Circle(C, F_{2})  ┆ … ┆ 5     ┆ true       ┆ false     ┆ false     │
│ 74       ┆ g     ┆ segment  ┆ Segment(A, Q)     ┆ … ┆ 7     ┆ false      ┆ true      ┆ false     │
│ 75       ┆ f_1   ┆ segment  ┆ Segment(A, G)     ┆ … ┆ 7     ┆ false      ┆ true      ┆ false     │
│ 76       ┆ s_1   ┆ segment  ┆ Segment(A, F_{2}) ┆ … ┆ 7     ┆ false      ┆ true      ┆ false     │
│ 77       ┆ d_1   ┆ segment  ┆ Segment(F_{2}, C) ┆ … ┆ 7     ┆ false      ┆ true      ┆ false     │
│ 78       ┆ e_1   ┆ line     ┆ PerpendicularLine ┆ … ┆ 1     ┆ false      ┆ false     ┆ false     │
│          ┆       ┆          ┆ (F_{2}, l)        ┆   ┆       ┆            ┆           ┆           │
│ 79       ┆ E     ┆ point    ┆ Intersect(p_1, t) ┆ … ┆ 4     ┆ true       ┆ false     ┆ false     │
│ 80       ┆ F     ┆ point    ┆ Intersect(p_1, t) ┆ … ┆ 4     ┆ false      ┆ true      ┆ true      │
│ 81       ┆ f_2   ┆ segment  ┆ Segment(E, O_{2}) ┆ … ┆ 4     ┆ false      ┆ false     ┆ false     │
│ 82       ┆ d_2   ┆ circle   ┆ Circle(E, F_{1})  ┆ … ┆ 4     ┆ false      ┆ false     ┆ false     │
└──────────┴───────┴──────────┴───────────────────┴───┴───────┴────────────┴───────────┴───────────┘

## ggblab_extra — construction tree parser

Use `ConstructionTreeParser` to build a graph of construction dependencies and perform graph analyses. The examples below show how to:

- Create the parser with `p = ConstructionTreeParser(df)`
- Build the full dependency graph with `g1 = p.parse()`
- Extract bounded subgraphs with `g2 = p.parse_subgraph(max_depth=3)`

These operations are for inspection and analysis; they help you visualize and trace construction dependency paths.

In [30]:
from ggblab_extra.construction_parser import ConstructionTreeParser

In [31]:
p = ConstructionTreeParser(df)

In [32]:
g1 = p.parse()

In [33]:
labels_map = {}
for n, t in p.df["Name", "Type"].rows():
    g1.nodes[n]["label"] = f"{n} ({t})"

In [34]:
nx.write_network_text(g1)

╟── O_{2} (point)
╎   ├─╼ B (point) ╾ A (point)
╎   │   ├─╼ c (circle) ╾ O_{2} (point)
╎   │   │   ├─╼ G (point) ╾ p (circle)
╎   │   │   │   ├─╼ β (angle) ╾ A (point), O_{2} (point)
╎   │   │   │   ├─╼ t1 (triangle) ╾ A (point), O_{2} (point)
╎   │   │   │   │   ├─╼ a (segment) ╾ A (point), G (point)
╎   │   │   │   │   ├─╼ c_1 (segment) ╾ G (point), O_{2} (point)
╎   │   │   │   │   └─╼ g_1 (segment) ╾ O_{2} (point), A (point)
╎   │   │   │   ├─╼ k (segment) ╾ A (point)
╎   │   │   │   ├─╼ δ (angle) ╾ O_{2} (point), A (point)
╎   │   │   │   ├─╼ b_1 (segment) ╾ S (point)
╎   │   │   │   ├─╼ f_1 (segment) ╾ A (point)
╎   │   │   │   └─╼  ...
╎   │   │   ├─╼ F_{2} (point) ╾ p (circle)
╎   │   │   │   ├─╼ γ (angle) ╾ A (point), O_{2} (point)
╎   │   │   │   ├─╼ t2 (triangle) ╾ A (point), O_{2} (point)
╎   │   │   │   │   ├─╼ a_1 (segment) ╾ A (point), F_{2} (point)
╎   │   │   │   │   ├─╼ c_2 (segment) ╾ F_{2} (point), O_{2} (point)
╎   │   │   │   │   └─╼ i_1 (segment) ╾ O_{2} (point), A (point)
╎   │   │   │   ├─╼ m (segment) ╾ A (point)
╎   │   │   │   ├─╼ ε (angle) ╾ O_{2} (point), A (point)
╎   │   │   │   ├─╼ n_1 (line) ╾ O_{2} (point)
╎   │   │   │   ├─╼ r_1 (circle) ╾ A (point)
╎   │   │   │   ├─╼ O (point) ╾ F_{1} (point)
╎   │   │   │   │   └─╼ f (line) ╾ l (line)
╎   │   │   │   ├─╼ i (segment) ╾ F_{1} (point)
╎   │   │   │   ├─╼ h (circle) ╾ C (point)
╎   │   │   │   ├─╼ s_1 (segment) ╾ A (point)
╎   │   │   │   ├─╼ d_1 (segment) ╾ C (point)
╎   │   │   │   ├─╼ e_1 (line) ╾ l (line)
╎   │   │   │   └─╼  ...
╎   │   │   ├─╼ j (line) ╾ A (point)
╎   │   │   │   ├─╼ q (line) ╾ l (line)
╎   │   │   │   ├─╼ r (line) ╾ l (line)
╎   │   │   │   │   ├─╼ A_{1} (point) ╾ e (circle)
╎   │   │   │   │   │   ├─╼ ζ (angle) ╾ A (point), K (point)
╎   │   │   │   │   │   └─╼ η (angle) ╾ A (point), C_{1} (point)
╎   │   │   │   │   └─╼ O_{1} (point)
╎   │   │   │   │       ├─╼ θ (angle) ╾ O_{2} (point), A (point)
╎   │   │   │   │       ├─╼ s (line) ╾ j (line)
╎   │   │   │   │       ├─╼ b (line) ╾ O_{2} (point)
╎   │   │   │   │       │   ├─╼ N (point) ╾ j (line)
╎   │   │   │   │       │   │   ├─╼ j_1 (line) ╾ h_1 (circle)
╎   │   │   │   │       │   │   │   └─╼ Q (point) ╾ h_1 (circle)
╎   │   │   │   │       │   │   │       ├─╼ t_1 (segment) ╾ R (point)
╎   │   │   │   │       │   │   │       └─╼ g (segment) ╾ A (point)
╎   │   │   │   │       │   │   └─╼ k_1 (line) ╾ h_1 (circle)
╎   │   │   │   │       │   │       ├─╼ R (point) ╾ h_1 (circle)
╎   │   │   │   │       │   │       │   └─╼  ...
╎   │   │   │   │       │   │       ├─╼ S (point) ╾ c (circle)
╎   │   │   │   │       │   │       │   └─╼  ...
╎   │   │   │   │       │   │       └─╼ T (point) ╾ c (circle)
╎   │   │   │   │       │   └─╼ P (point) ╾ l (line)
╎   │   │   │   │       │       ├─╼ l_1 (line) ╾ h_1 (circle)
╎   │   │   │   │       │       └─╼ m_1 (line) ╾ h_1 (circle)
╎   │   │   │   │       ├─╼ t (line) ╾ l (line)
╎   │   │   │   │       │   ├─╼ F_{1} (point) ╾ l (line)
╎   │   │   │   │       │   │   ├─╼ h_1 (circle) ╾ O_{1} (point)
╎   │   │   │   │       │   │   │   └─╼  ...
╎   │   │   │   │       │   │   ├─╼ q_1 (circle) ╾ A (point)
╎   │   │   │   │       │   │   ├─╼ d_2 (circle) ╾ E (point)
╎   │   │   │   │       │   │   └─╼  ...
╎   │   │   │   │       │   ├─╼ E (point) ╾ p_1 (circle)
╎   │   │   │   │       │   │   ├─╼ f_2 (segment) ╾ O_{2} (point)
╎   │   │   │   │       │   │   └─╼  ...
╎   │   │   │   │       │   └─╼ F (point) ╾ p_1 (circle)
╎   │   │   │   │       ├─╼ I (point) ╾ O_{2} (point)
╎   │   │   │   │       │   ├─╼ p_1 (circle) ╾ O_{2} (point)
╎   │   │   │   │       │   │   ├─╼ C (point) ╾ l (line)
╎   │   │   │   │       │   │   │   ├─╼ t4 (triangle) ╾ I (point), A (point)
╎   │   │   │   │       │   │   │   │   ├─╼ c_3 (segment) ╾ I (point), A (point)
╎   │   │   │   │       │   │   │   │   ├─╼ i_2 (segment) ╾ A (point), C (point)
╎   │   │   │   │       │   │   │   │   └─╼ a_2 (segment) ╾ C (point), I (point)
╎   │   │   │   │       │   │   │   └─╼  ...
╎   │   │   │   │       │   │   ├─╼ D (point)
╎   │   │   │   │       │   │   │   ├─╼ t3 (triangle) ╾ O_{2} (point), O_{1} (point)
╎   │   │   │   │       │   │   │   │   ├─╼ d (segment) ╾ O_{2} (point), O_{1} (point)
╎   │   │   │   │       │   │   │   │   ├─╼ o (segment) ╾ O_{1} (point), D (point)
╎   │   │   │   │       │   │   │   │   └─╼ l_2 (segment) ╾ D (point), O_{2} (point)
╎   │   │   │   │       │   │   │   ├─╼ α (angle) ╾ O_{2} (point), O_{1} (point)
╎   │   │   │   │       │   │   │   └─╼  ...
╎   │   │   │   │       │   │   └─╼  ...
╎   │   │   │   │       │   └─╼  ...
╎   │   │   │   │       └─╼  ...
╎   │   │   │   ├─╼ C_{1} (point) ╾ e (circle)
╎   │   │   │   │   └─╼  ...
╎   │   │   │   ├─╼ H (point) ╾ e (circle)
╎   │   │   │   └─╼  ...
╎   │   │   ├─╼ l (line) ╾ A (point)
╎   │   │   │   ├─╼ J (point) ╾ e (circle)
╎   │   │   │   ├─╼ K (point) ╾ e (circle)
╎   │   │   │   │   └─╼  ...
╎   │   │   │   └─╼  ...
╎   │   │   └─╼  ...
╎   │   └─╼ e (circle) ╾ A (point)
╎   │       └─╼  ...
╎   ├─╼ n (line) ╾ A (point)
╎   ├─╼ O' (point) ╾ A (point)
╎   │   └─╼ p (circle) ╾ A (point)
╎   │       └─╼  ...
╎   └─╼  ...
╙── A (point)
    └─╼  ...

In [35]:
g2 = p.parse_subgraph(max_depth=3)

parse_subgraph: timeout exceeded during candidate evaluation (10.00s), falling back to parse_subgraph_legacy

In [36]:
nx.write_network_text(g2)

╟── A
╎   ├─╼ B ╾ O_{2}
╎   │   ├─╼ c
╎   │   │   ├─╼ j
╎   │   │   │   └─╼ r ╾ l
╎   │   │   │       └─╼ O_{1}
╎   │   │   │           ├─╼ t
╎   │   │   │           │   └─╼ F_{1}
╎   │   │   │           │       └─╼ h_1
╎   │   │   │           │           ├─╼ k_1
╎   │   │   │           │           └─╼ j_1
╎   │   │   │           ├─╼ b
╎   │   │   │           │   └─╼ N
╎   │   │   │           └─╼ I
╎   │   │   │               └─╼ p_1
╎   │   │   │                   ├─╼ C
╎   │   │   │                   └─╼ D
╎   │   │   ├─╼ l
╎   │   │   │   └─╼  ...
╎   │   │   ├─╼ G ╾ p
╎   │   │   └─╼ F_{2} ╾ p
╎   │   └─╼ e
╎   └─╼ O' ╾ O_{2}
╎       └─╼ p
╎           └─╼  ...
╙── O_{2}
    └─╼  ...

In [37]:
p.df.filter(~pl.col("Auxiliary"))["Sequence", "Type", "Name", "Command", "Value", "DependsOn"]

shape: (61, 6)
┌──────────┬──────────┬───────┬──────────────────────┬──────────────────────┬──────────────────────┐
│ Sequence ┆ Type     ┆ Name  ┆ Command              ┆ Value                ┆ DependsOn            │
│ ---      ┆ ---      ┆ ---   ┆ ---                  ┆ ---                  ┆ ---                  │
│ u32      ┆ str      ┆ str   ┆ str                  ┆ str                  ┆ list[str]            │
╞══════════╪══════════╪═══════╪══════════════════════╪══════════════════════╪══════════════════════╡
│ 0        ┆ point    ┆ O_{2} ┆ null                 ┆ O_{2} = (0, 0)       ┆ []                   │
│ 1        ┆ point    ┆ A     ┆ null                 ┆ A = (10, 0)          ┆ []                   │
│ 2        ┆ point    ┆ B     ┆ Point(Line(O_{2},    ┆ B = (-5.7, 0)        ┆ ["A", "O_{2}"]       │
│          ┆          ┆       ┆ A))                  ┆                      ┆                      │
│ 3        ┆ circle   ┆ c     ┆ Circle(O_{2}, B)     ┆ c: x² + y² = 32.7    ┆ ["A", "B", "O_{2}"]  │
│ 4        ┆ line     ┆ n     ┆ Line(O_{2}, A)       ┆ n: y = 0             ┆ ["A", "O_{2}"]       │
│ 5        ┆ point    ┆ O'    ┆ Midpoint(O_{2}, A)   ┆ O' = (5, 0)          ┆ ["A", "O_{2}"]       │
│ 6        ┆ circle   ┆ p     ┆ Circle(O', A)        ┆ p: (x - 5)² + y² =   ┆ ["A", "O'", "O_{2}"] │
│          ┆          ┆       ┆                      ┆ 25                   ┆                      │
│ 7        ┆ point    ┆ G     ┆ Intersect(c, p)      ┆ G = (3.3, 4.7)       ┆ ["A", "B", … "p"]    │
│ 8        ┆ point    ┆ F_{2} ┆ Intersect(c, p)      ┆ F_{2} = (3.3, -4.7)  ┆ ["A", "B", … "p"]    │
│ 9        ┆ line     ┆ j     ┆ Tangent(A, c)        ┆ j: -4.7x - 6.7y =    ┆ ["A", "B", … "c"]    │
│          ┆          ┆       ┆                      ┆ -46.9                ┆                      │
│ 10       ┆ line     ┆ l     ┆ Tangent(A, c)        ┆ l: 4.7x - 6.7y =     ┆ ["A", "B", … "c"]    │
│          ┆          ┆       ┆                      ┆ 46.9                 ┆                      │
│ 11       ┆ angle    ┆ β     ┆ Angle(A, G, O_{2})   ┆ β = 90°              ┆ ["A", "B", … "p"]    │
│ 12       ┆ angle    ┆ γ     ┆ Angle(A, F_{2},      ┆ γ = 90°              ┆ ["A", "B", … "p"]    │
│          ┆          ┆       ┆ O_{2})               ┆                      ┆                      │
│ 13       ┆ triangle ┆ t1    ┆ Polygon(A, G, O_{2}) ┆ t1 = 23.5            ┆ ["A", "B", … "p"]    │
│ 17       ┆ triangle ┆ t2    ┆ Polygon(A, F_{2},    ┆ t2 = 23.5            ┆ ["A", "B", … "p"]    │
│          ┆          ┆       ┆ O_{2})               ┆                      ┆                      │
│ 21       ┆ segment  ┆ k     ┆ Segment(A, G)        ┆ k = 8.2              ┆ ["A", "B", … "p"]    │
│ 22       ┆ segment  ┆ m     ┆ Segment(A, F_{2})    ┆ m = 8.2              ┆ ["A", "B", … "p"]    │
│ 23       ┆ angle    ┆ δ     ┆ Angle(O_{2}, A, G)   ┆ δ = 34.9°            ┆ ["A", "B", … "p"]    │
│ 24       ┆ angle    ┆ ε     ┆ Angle(O_{2}, A,      ┆ ε = 34.9°            ┆ ["A", "B", … "p"]    │
│          ┆          ┆       ┆ F_{2})               ┆                      ┆                      │
│ 25       ┆ line     ┆ q     ┆ AngleBisector(l, j)  ┆ q: y = 0             ┆ ["A", "B", … "l"]    │
│ 26       ┆ line     ┆ r     ┆ AngleBisector(l, j)  ┆ r: x = 10            ┆ ["A", "B", … "l"]    │
│ 33       ┆ angle    ┆ ζ     ┆ Angle(A_{1}, A, K)   ┆ ζ = 55.1°            ┆ ["A", "A_{1}", …     │
│          ┆          ┆       ┆                      ┆                      ┆ "r"]                 │
│ 34       ┆ angle    ┆ η     ┆ Angle(A_{1}, A,      ┆ η = 55.1°            ┆ ["A", "A_{1}", …     │
│          ┆          ┆       ┆ C_{1})               ┆                      ┆ "r"]                 │
│ 35       ┆ point    ┆ O_{1} ┆ Point(r)             ┆ O_{1} = (10, -3.4)   ┆ ["A", "B", … "r"]    │
│ 36       ┆ angle    ┆ θ     ┆ Angle(O_{2}, A,      ┆ θ = 90°              ┆ ["A", "B", … "r"]    │
│          ┆          ┆       ┆ O_{1})               ┆                      ┆                      │
│ 38       ┆ line     ┆ b     ┆ Line(O_{2}, O_{1})   ┆ b: y = -0.3x         ┆ ["A", "B", … "r"]    │
│ 39       ┆ point    ┆ N     ┆ Intersect(b, j)      ┆ N = (19.7, -6.8)     ┆ ["A", "B", … "r"]    │
│ 40       ┆ point    ┆ P     ┆ Intersect(b, l)      ┆ P = (6.7, -2.3)      ┆ ["A", "B", … "r"]    │
│ 41       ┆ line     ┆ t     ┆ PerpendicularLine(O_ ┆ t: 6.7x + 4.7y =     ┆ ["A", "B", … "r"]    │
│          ┆          ┆       ┆ {1}, l)              ┆ 51.2                 ┆                      │
│ 42       ┆ point    ┆ F_{1} ┆ Intersect(t, l)      ┆ F_{1} = (8.4, -1.1)  ┆ ["A", "B", … "t"]    │
│ 43       ┆ circle   ┆ h_1   ┆ Circle(O_{1}, F_{1}) ┆ h_1: (x - 10)² + (y  ┆ ["A", "B", … "t"]    │
│          ┆          ┆       ┆                      ┆ + 3.4)² = …          ┆                      │
│ 44       ┆ line     ┆ j_1   ┆ Tangent(N, h_1)      ┆ j_1: -5.6x - 8.1y =  ┆ ["A", "B", … "t"]    │
│          ┆          ┆       ┆                      ┆ -56.4                ┆                      │
│ 45       ┆ line     ┆ k_1   ┆ Tangent(N, h_1)      ┆ k_1: -0.5x - 9.8y =  ┆ ["A", "B", … "t"]    │
│          ┆          ┆       ┆                      ┆ 56.4                 ┆                      │
│ 46       ┆ line     ┆ l_1   ┆ Tangent(P, h_1)      ┆ l_1: 2x + 0.6y =     ┆ ["A", "B", … "t"]    │
│          ┆          ┆       ┆                      ┆ 11.8                 ┆                      │
│ 47       ┆ line     ┆ m_1   ┆ Tangent(P, h_1)      ┆ m_1: -1.2x + 1.7y =  ┆ ["A", "B", … "t"]    │
│          ┆          ┆       ┆                      ┆ -11.8                ┆                      │
│ 48       ┆ point    ┆ I     ┆ Midpoint(O_{2},      ┆ I = (5, -1.7)        ┆ ["A", "B", … "r"]    │
│          ┆          ┆       ┆ O_{1})               ┆                      ┆                      │
│ 49       ┆ circle   ┆ p_1   ┆ Circle(I, O_{2})     ┆ p_1: (x - 5)² + (y + ┆ ["A", "B", … "r"]    │
│          ┆          ┆       ┆                      ┆ 1.7)² = 2…           ┆                      │
│ 51       ┆ point    ┆ C     ┆ Intersect(p_1, l, 1) ┆ C = (1.7, -5.8)      ┆ ["A", "B", … "r"]    │
│ 52       ┆ circle   ┆ q_1   ┆ Circle(A, F_{1})     ┆ q_1: (x - 10)² + y²  ┆ ["A", "B", … "t"]    │
│          ┆          ┆       ┆                      ┆ = 3.8                ┆                      │
│ 53       ┆ circle   ┆ r_1   ┆ Circle(A, F_{2})     ┆ r_1: (x - 10)² + y²  ┆ ["A", "B", … "p"]    │
│          ┆          ┆       ┆                      ┆ = 67.3               ┆                      │
│ 54       ┆ point    ┆ Q     ┆ Intersect(h_1, j_1)  ┆ Q = (11.6, -1.1)     ┆ ["A", "B", … "t"]    │
│ 55       ┆ point    ┆ R     ┆ Intersect(h_1, k_1)  ┆ R = (9.9, -6.2)      ┆ ["A", "B", … "t"]    │
│ 56       ┆ point    ┆ S     ┆ Intersect(c, k_1)    ┆ S = (-0.3, -5.7)     ┆ ["A", "B", … "t"]    │
│ 58       ┆ segment  ┆ t_1   ┆ Segment(Q, R)        ┆ t_1 = 5.4            ┆ ["A", "B", … "t"]    │
│ 59       ┆ segment  ┆ b_1   ┆ Segment(G, S)        ┆ b_1 = 11             ┆ ["A", "B", … "t"]    │
│ 60       ┆ point    ┆ D     ┆ Point(p_1)           ┆ D = (5.1, 3.6)       ┆ ["A", "B", … "r"]    │
│ 61       ┆ triangle ┆ t3    ┆ Polygon(O_{2},       ┆ t3 = 26.6            ┆ ["A", "B", … "r"]    │
│          ┆          ┆       ┆ O_{1}, D)            ┆                      ┆                      │
│ 65       ┆ angle    ┆ α     ┆ Angle(O_{2}, D,      ┆ α = 90°              ┆ ["A", "B", … "r"]    │
│          ┆          ┆       ┆ O_{1})               ┆                      ┆                      │
│ 66       ┆ point    ┆ O     ┆ Midpoint(F_{1},      ┆ O = (5.8, -2.9)      ┆ ["A", "B", … "t"]    │
│          ┆          ┆       ┆ F_{2})               ┆                      ┆                      │
│ 67       ┆ line     ┆ f     ┆ PerpendicularLine(O, ┆ f: 6.7x + 4.7y =     ┆ ["A", "B", … "t"]    │
│          ┆          ┆       ┆ l)                   ┆ 25.6                 ┆                      │
│ 68       ┆ segment  ┆ i     ┆ Segment(F_{1},       ┆ i = 6.2              ┆ ["A", "B", … "t"]    │
│          ┆          ┆       ┆ F_{2})               ┆                      ┆                      │
│ 69       ┆ triangle ┆ t4    ┆ Polygon(I, A, C)     ┆ t4 = 7.4             ┆ ["A", "B", … "r"]    │
│ 73       ┆ circle   ┆ h     ┆ Circle(C, F_{2})     ┆ h: (x - 1.7)² + (y + ┆ ["A", "B", … "r"]    │
│          ┆          ┆       ┆                      ┆ 5.8)² = 3…           ┆                      │
│ 74       ┆ segment  ┆ g     ┆ Segment(A, Q)        ┆ g = 2                ┆ ["A", "B", … "t"]    │
│ 75       ┆ segment  ┆ f_1   ┆ Segment(A, G)        ┆ f_1 = 8.2            ┆ ["A", "B", … "p"]    │
│ 76       ┆ segment  ┆ s_1   ┆ Segment(A, F_{2})    ┆ s_1 = 8.2            ┆ ["A", "B", … "p"]    │
│ 77       ┆ segment  ┆ d_1   ┆ Segment(F_{2}, C)    ┆ d_1 = 2              ┆ ["A", "B", … "r"]    │
│ 78       ┆ line     ┆ e_1   ┆ PerpendicularLine(F_ ┆ e_1: 6.7x + 4.7y = 0 ┆ ["A", "B", … "p"]    │
│          ┆          ┆       ┆ {2}, l)              ┆                      ┆                      │
│ 79       ┆ point    ┆ E     ┆ Intersect(p_1, t)    ┆ E = (5.1, 3.6)       ┆ ["A", "B", … "t"]    │
│ 81       ┆ segment  ┆ f_2   ┆ Segment(E, O_{2})    ┆ f_2 = 6.2            ┆ ["A", "B", … "t"]    │
│ 82       ┆ circle   ┆ d_2   ┆ Circle(E, F_{1})     ┆ d_2: (x - 5.1)² + (y ┆ ["A", "B", … "t"]    │
│          ┆          ┆       ┆                      ┆ - 3.6)² =…           ┆                      │
└──────────┴──────────┴───────┴──────────────────────┴──────────────────────┴──────────────────────┘

In [38]:
# find root
[node for node, degree in p.G.in_degree() if degree == 0]

['O_{2}', 'A']

## Utilities and analysis

These cells provide small utilities for working with constructions and snapshots produced by `ggblab` and `ggblab_extra`.

What these do:

- Save or export snapshots (base64 zip) to disk for later inspection.
- Decode base64 snapshots and inspect the embedded `.ggb` zip contents (including `geogebra.xml`).
- Provide graph-analysis helpers (e.g., longest-path, shortest-path length) to inspect construction dependency graphs built by `ConstructionTreeParser`.
- Offer lightweight helpers for exploring `ggb` applet internals (comm logs, pending messages, etc.).

Important: these cells focus on analysis and helper utilities — they do not perform automatic cleanup or remove application state.

In [39]:
def get_longest_path_to_node(G, target_node):
    roots = [node for node, degree in G.in_degree() if degree == 0]
    longest_path = []
    max_len = 0
    for root in roots:
        for path in nx.all_simple_paths(G, root, target_node):
            if len(path) > max_len:
                max_len = len(path)
                longest_path = path
    return longest_path

In [40]:
path = get_longest_path_to_node(p.G, 'E')
path

['O_{2}', 'B', 'c', 'j', 'r', 'O_{1}', 'I', 'p_1', 'E']

In [42]:
depths = nx.shortest_path_length(p.G, source='A')
depths

{'A': 0,
 'B': 1,
 'n': 1,
 "O'": 1,
 'p': 1,
 'j': 1,
 'l': 1,
 'β': 1,
 'γ': 1,
 't1': 1,
 'a': 1,
 'g_1': 1,
 't2': 1,
 'a_1': 1,
 'i_1': 1,
 'k': 1,
 'm': 1,
 'δ': 1,
 'ε': 1,
 'e': 1,
 'ζ': 1,
 'η': 1,
 'θ': 1,
 'q_1': 1,
 'r_1': 1,
 't4': 1,
 'c_3': 1,
 'i_2': 1,
 'g': 1,
 'f_1': 1,
 's_1': 1,
 'c': 2,
 'G': 2,
 'F_{2}': 2,
 'q': 2,
 'r': 2,
 'C_{1}': 2,
 'H': 2,
 's': 2,
 'N': 2,
 'J': 2,
 'K': 2,
 'P': 2,
 't': 2,
 'F_{1}': 2,
 'C': 2,
 'f': 2,
 'e_1': 2,
 'c_1': 2,
 'c_2': 2,
 'A_{1}': 2,
 'a_2': 2,
 'S': 3,
 'T': 3,
 'b_1': 3,
 'n_1': 3,
 'O': 3,
 'i': 3,
 'h': 3,
 'd_1': 3,
 'O_{1}': 3,
 'j_1': 3,
 'k_1': 3,
 'l_1': 3,
 'm_1': 3,
 'E': 3,
 'F': 3,
 'h_1': 3,
 'd_2': 3,
 'b': 4,
 'I': 4,
 't3': 4,
 'd': 4,
 'o': 4,
 'α': 4,
 'Q': 4,
 'R': 4,
 'f_2': 4,
 'p_1': 5,
 'l_2': 5,
 't_1': 5,
 'D': 6}

In [43]:
depths = nx.shortest_path_length(p.G2, source='A')
depths

{'A': 0,
 'B': 1,
 "O'": 1,
 'c': 2,
 'e': 2,
 'p': 2,
 'j': 3,
 'l': 3,
 'G': 3,
 'F_{2}': 3,
 'r': 4,
 'O_{1}': 5,
 't': 6,
 'b': 6,
 'I': 6,
 'F_{1}': 7,
 'N': 7,
 'p_1': 7,
 'h_1': 8,
 'C': 8,
 'D': 8,
 'k_1': 9,
 'j_1': 9}

In [46]:
prev = set(list(zip(*(list(p.G.in_edges('α')) + list(p.G.in_edges('β')))))[0])
prev

{'A', 'D', 'G', 'O_{1}', 'O_{2}'}

In [47]:
[(n, depths[n]) for n in depths if n in prev]

[('A', 0), ('G', 3), ('O_{1}', 5), ('D', 8)]

In [48]:
nx.write_network_text(p.roots_to_targets_with_containers('D'))

╟── O_{2} (point)
╎   ├─╼ B (point) ╾ A (point)
╎   │   └─╼ c (circle) ╾ O_{2} (point)
╎   │       ├─╼ j (line) ╾ A (point)
╎   │       │   └─╼ r (line) ╾ l (line)
╎   │       │       └─╼ O_{1} (point)
╎   │       │           ├─╼ I (point) ╾ O_{2} (point)
╎   │       │           │   └─╼ p_1 (circle) ╾ O_{2} (point)
╎   │       │           │       └─╼ D (point)
╎   │       │           │           ├─╼ t3 (triangle) ╾ O_{2} (point), O_{1} (point)
╎   │       │           │           │   ├─╼ o (segment) ╾ D (point), O_{1} (point)
╎   │       │           │           │   └─╼ l_2 (segment) ╾ O_{2} (point), D (point)
╎   │       │           │           └─╼  ...
╎   │       │           └─╼  ...
╎   │       └─╼ l (line) ╾ A (point)
╎   │           └─╼  ...
╎   └─╼  ...
╙── A (point)
    └─╼  ...